#!/bin/bash
# Auto-generated by the runner-merge-claude-branches skill on 2026-05-30.
#
# AFTER the consolidation PR (merged-claude-models-2026-05-30) is merged into
# origin/main, run this script to advance each source claude/<task-id>
# branch tip to its cherry-picked commit. The branches will then sit on
# main and GitHub will show them as "merged" rather than the perpetual
# "1 commit ahead" that cherry-pick's SHA-rewrite causes.
#
# Usage:
#   bash post_merge_advance.sh             # dry-run (default; shows what would happen)
#   bash post_merge_advance.sh --apply     # actually force-push each branch
#
# Safety:
#   * Aborts (per branch) if the cherry-picked SHA is not yet on
#     origin/main (i.e. the consolidation PR hasn't merged yet).
#   * Uses --force-with-lease=<branch>:<original_sha> so a source
#     branch that was updated between cherry-pick time and now
#     (e.g. the runner re-dispatched the task) won't be silently
#     clobbered — the push fails and the operator can investigate.
#
# Exit codes:
#   0  applied (or dry-ran) all branches successfully
#   1  one or more branches not yet on main (PR not merged?)
#   2  one or more pushes rejected (branches moved since cherry-pick;
#      operator must inspect)
set -u
APPLY=0
[[ "${1:-}" == "--apply" ]] && APPLY=1
REPO_ABS=/home/bill/github/nlmixr2/nlmixr2lib
cd "$REPO_ABS"

git fetch origin --quiet
NOT_ON_MAIN=0
REJECTED=0
ADVANCED=0
SKIPPED=0

# Mapping: source branch <TAB> cherry-picked SHA on consolidation branch
# <TAB> original tip SHA on the source branch <TAB> "OK". Captured from
# /tmp/cherry_log.tsv at consolidation time (2026-05-30).
read_mapping() {
  cat <<'EOM'
claude/frompeople-1440-bender_2009_pharmaceutical_research	e678c7504e6d0b07578c904d3f5389e1eb44fa2c	d58a44278cfb904854ca93fecb082fc0ad2c38bb	OK
claude/frompeople-146-clewe_2017_journal_of_antimicrobial_chemo	567d41c064de7cf30040dae8d97a0a765faa18e7	64a37b6bc9c729cea94a7ab271d2016c6c689181	OK
claude/frompeople-1466-simpson_2013_plos_one	44af1da824c4ba694bd4cfc184d4043249d72459	35d8fa695560b9ebde07e39023876ff79a5d96bf	OK
claude/frompeople-1472-li_2015_1	007bcab1a9abfd56603a28aa057614de9c1deb76	f279b3df53c36194be89dedeba17801a8fe15a1f	OK
claude/frompeople-1482-garonzik_2016_plos_one	deef26124295c220cb3bac7e15981eff6a189f8c	28d18de26e385024d820c5478c1bb2c2ea785dca	OK
claude/frompeople-1484-li_2015_saudi_pharm_j_2015_jul_23_3	aa930b094cf979fd33a8a6fd1b38c041d89dd139	eb7599f5bdb8b56c66c1732c2e96a99b5ed5774a	OK
claude/frompeople-1486-renard_2011_respiratory_research	35db5eab216ba192358c06b43b0362c7d11c7c6e	8ee8616dc3078b6b9abf52688f967a0560c400af	OK
claude/frompeople-1493-long_boyle_2015_therapeutic_drug_monitoring	d3c6c05ade7500749384ce9b5d390c1962f61acc	93557e3d91dc4a6fde2b32bdc9e646c48aa57d34	OK
claude/frompeople-1506-rymut_2023_anti_tryptase	c24a3a1d3d2b1bf029f4a840dd9e34a65c698ec4	1c13e54edbcdbe4552a1447ed7d3884f6d7822a3	OK
claude/frompeople-190-kleideiter_2017_clinical_pharmacokinetics	5eb24b83a9ff7caaf4dcf2a8cd3d5d1085f89072	cb5c8680483bad0c60768b16c7c4457ec97cfdb4	OK
claude/frompeople-196-landersdorfer_2018_antimicrobial_agents_and_chemo	7385523ca382ccd3c37d68fa1b462c9a89a34201	2700f4cfa05060905ae016c9b8b4c8ccb5e7e8ff	OK
claude/frompeople-207-kleideiter_2018_clinical_pharmacokinetics	8f242cb3614f9cee2f0bf836963c76ed9e80aaa4	ab8ed4089ea8b918315a01e9c8bb8b6dab061b86	OK
claude/frompeople-261-hill_mcmanus_2017_british_journal_of_clinical_ph	e7019c47bcab55c4beeed4fde5e39a7453bf9ec5	d8e36c02d0f33f47655f9ca1d3d6efb23602cac1	OK
claude/frompeople-270-kim_2018_scientific_reports	5aaa40b1458d33969f0823101e6b9764ea9ed840	ff50e52f9c0f8181aed69dfe58bb5dd0da5e9eee	OK
claude/frompeople-274-ji_2017_acta_pharmacologica_sinica	802c77aa4005937ae73cda4c5ed323ded94e9ad6	3f1c465bba06a884c72df7dede19199ee10d7500	OK
claude/frompeople-278-wang_2017_acta_pharmacologica_sinica	73ec7fcf4332dbb63072fdeb77ec3ee410bd40db	461caf14aef512cc983560e96af196147ecead37	OK
claude/frompeople-280-denti_2018_antimicrobial_agents_and_chemo	6bd6572cb2d90395d64eaba68b8c11a0d17c6d82	55dc21cb16b940e9b9e7f95db563292ff95f6022	OK
claude/frompeople-282-boucher_2018_cpt_pharmacometrics_amp_sys	9b01176c887ecbf9d704c6b4828b396b94c406ca	2da1018efc0832530338c9e27d2bfff4ff442f5e	OK
claude/frompeople-288-rees_2018_antimicrobial_agents_and_chemo	bd83e6dd431f2283e958bc1b0bdcc289d991bc74	1e47bb3aa153090076dcd1345f49a4543a927cd7	OK
claude/frompeople-291-sharma_2017_the_journal_of_clinical_pharma	abd9ea2ef050c7c3b1008c43a0da282982e3eaab	311750a7499740c0f1057133c90cfc4a2fa777ef	OK
claude/frompeople-294-cardilin_2017_cpt_pharmacometrics_amp_sys	00330e4ee0252d66a484d1c3bf069aea04d56c77	7e32281e09a781249b3f6c3b37abb5987e2d01f4	OK
claude/frompeople-299-oniki_2018_cpt_pharmacometrics_amp_sys	57b2e8c69f8f4a12db5535523083186a4767def0	937695656a530e3170c9974ca8f934a3ba314ef5	OK
claude/frompeople-303-mulyukov_2018_cpt_pharmacometrics_amp_sys	a6db2be85ca231ffb7d16f5a76295a0c7ffb6cbc	aa7c94597b92e819981305592d8b717fda35b77e	OK
claude/frompeople-318-kawamura_2018_cancer_science	2b06558d0c15e93d6dead472a403f1efa04ae1b0	00f592d54dbc5029e6069b3c3b41f0c5ab492132	OK
claude/frompeople-330-smuszkiewicz_2017_journal_of_pharmacokinetics_an	978860421a08c0a96337715cceae0e31edd1a418	732009dd3df2649d16b30e0914dba949d88dc8be	OK
claude/frompeople-331-padari_2018_antimicrobial_agents_and_chemo	1f9c062c68d43296b5ca564f5b0e4e36c81a5077	d93e4eb867414222bff7044896ad58bbdff36a96	OK
claude/frompeople-345-alqahtani_2018_antimicrobial_agents_and_chemo	fd0fb2b56bbd09bbee3da80e3858554284274fba	81b4261ee90aa814cccd4e661f928f8ba24bc490	OK
claude/frompeople-347-struemper_2017_clinical_pharmacokinetics	7db5e0f2fecf208ba50c32f465255b89e4adba35	e71badf0cfb36ae17cb0e6defa29b0f0398d8c60	OK
claude/frompeople-351-zhang_2018_journal_of_pain_research	d52f2e165aaa01b332a551f5b8c575a90c94e799	f9a218472cf52808951b666a2777952b32a9f300	OK
claude/frompeople-355-tang_2019_antimicrobial_agents_and_chemo	bcc7de56b93f0fc09a838d1a36da9a79afc2f610	98eef2834421464b8fe0e0b8f7eee1c02c79f5c1	OK
claude/frompeople-357-zheng_2018_antimicrobial_agents_and_chemo	2adf5d5b1127c0565edaa9786b2024a8986c85e1	d0e37532a09f3b76e4d9343ea96167a13858a4b7	OK
claude/frompeople-358-shi_2018_antimicrobial_agents_and_chemo	4984ca19d67040e51faf9198bb4a6655f1415a05	665d596621396ee5820145a0624076e1c55c7787	OK
claude/frompeople-359-ku_2018_cpt_pharmacometrics_amp_sys	e1592e42f1de4a6667f2ddb3ada9ac71bf6c1782	f8a055fdac509dfbb0565f089e9649f0e17402fa	OK
claude/frompeople-360-zhi_2018_drug_design_development_and_t	f483c201421b9a563eb1fc6d45b80951e369ca93	959e49cf650ff7e18b2fb86105d17fe633f44ed7	OK
claude/frompeople-361-p_rez_guill_2018_anesthesia_amp_analgesia	a085842e45c080be9ee6baeecdcfd976b0626d6c	833c214b6b295548f403a8fd14650a7ab285596e	OK
claude/frompeople-362-takechi_2018_journal_of_clinical_pharmacolo	c27cb77f38a62a50b1bdd4b33aeef3418ae40266	196e36a8775fe06aa72111b00c489968a944e791	OK
claude/frompeople-369-taubert_2018_antimicrobial_agents_and_chemo	bb178353c45bf94d5c5543044e838a330de7641a	ce6171bdf84d6cbbea3aee1d46db1be189c7c520	OK
claude/frompeople-372-hanberg_2018_antimicrobial_agents_and_chemo	68ddb45972828eabf5aafc4e5440c344cc5990d2	04b3d588a38848807165f6ea99f2361b9d14d42e	OK
claude/frompeople-373-hoglund_2018_malaria_journal	c2072088a598d9f8e33111b5a06da17c7fe50512	cba0600056d789bc83784d27991163ba3c7b5764	OK
claude/frompeople-375-hao_2018_british_journal_of_clinical_ph	379a2546cd471dfdd4a1472d2d0b48df720b6d01	5457b5dd1d603832ba0ea7f32c302780011a8abf	OK
claude/frompeople-378-danielak_2017_european_journal_of_clinical_p	2d5076d7c8089fd6c1db9aede1d9bccbd136f720	b521020111eff1ded360894ca643a167efc690be	OK
claude/frompeople-380-li_2018_frontiers_in_pharmacology	82fdeeb3cce6ec42d7f1ff7affd37511136a3213	af2a3d95dfc1bbd6b3ac82142950be0555709b07	OK
claude/frompeople-382-lin_2018_british_journal_of_clinical_ph	cc5081f92d902a272950cd3836c65f421a0eecb4	bf730eb68cf9e78ae5bebc04162011d96f7eed56	OK
claude/frompeople-402-del_frari_2018_pharmacology_research_amp_pe	20b3eaa07fdb5a2411e72842ba5c03f1955db1ff	2250c179b707cf36e797a49828d0c1a4a13a7b7c	OK
claude/frompeople-410-xiang_2018_frontiers_in_pharmacology	b1a7c9c4034199813beb5ffe6fe2cf073f8cc28b	e396e15446c762bbbc0e34d1964af567cebdc978	OK
claude/frompeople-412-chelle_2019_journal_of_pharmacokinetics_an	e05d3a21910cb8e3d41bf3e38c36d2053dc6c90d	bb5302ded4ce47376a0cbb67f3d8f6e15e08f058	OK
claude/frompeople-433-tod_1998_antimicrobial_agents_and_chemo	11623a8cb6cb3603788500f0ee4056e348bad9c6	4353aed21426a72a530dd015580c8cb57c2bba3f	OK
claude/frompeople-434-moore_1999_antimicrobial_agents_and_chemo	90d8e9bdb6e9a0bc2e2eaf0e9a55db0dd10c0cbb	540cf4b42d20404f8fcaee07c6ad757662898cf4	OK
EOM
}

while IFS=$'\t' read -r BR NEW ORIG STATUS; do
  [[ -z "$BR" || "$STATUS" != "OK" ]] && continue
  echo "=== $BR ==="
  if ! git merge-base --is-ancestor "$NEW" origin/main 2>/dev/null; then
    echo "  SKIP: cherry-picked commit $NEW is not on origin/main yet."
    echo "        (consolidation PR not merged, or refs out of date — try git fetch)"
    NOT_ON_MAIN=$((NOT_ON_MAIN+1))
  elif (( APPLY )); then
    if git push --force-with-lease=$BR:$ORIG origin "$NEW:refs/heads/$BR" 2>&1 | sed 's/^/  /'; then
      ADVANCED=$((ADVANCED+1))
    else
      echo "  REJECTED: source branch moved since cherry-pick. Inspect manually."
      REJECTED=$((REJECTED+1))
    fi
  else
    cur_remote=$(git ls-remote origin "refs/heads/$BR" 2>/dev/null | cut -f1)
    if [[ "$cur_remote" != "$ORIG" ]]; then
      echo "  WARN: source branch moved since cherry-pick — push would be rejected."
      echo "        current remote tip: $cur_remote"
      echo "        expected original:  $ORIG"
      SKIPPED=$((SKIPPED+1))
    else
      echo "  DRY-RUN: would push --force-with-lease=$BR:$ORIG origin $NEW:refs/heads/$BR"
    fi
  fi
done < <(read_mapping)

echo
echo "=== Summary ==="
echo "  advanced:    $ADVANCED"
echo "  rejected:    $REJECTED   (source branch moved since cherry-pick; manual review)"
echo "  skipped:     $SKIPPED    (dry-run only; would have been rejected)"
echo "  not-on-main: $NOT_ON_MAIN"
if (( ! APPLY )); then
  echo
  echo "(dry-run — re-run with --apply to actually advance the branches.)"
fi
if (( NOT_ON_MAIN > 0 )); then exit 1; fi
if (( REJECTED > 0 )); then exit 2; fi
exit 0
