Anbari_2023_atezolizumab_cibisatamab_qsp <- function() {
  description <- paste(
    "QSP. Modular quantitative systems pharmacology platform for immuno-",
    "oncology in metastatic colorectal cancer, describing combination therapy",
    "with the anti-PD-L1 checkpoint inhibitor atezolizumab and the CEA-directed",
    "bispecific T cell engager cibisatamab (CEA-TCB, RO6958688). Four",
    "physiological compartments (central, peripheral, tumour, tumour-draining",
    "lymph node) plus APC endosomal / surface compartments and four",
    "immunological-synapse compartments. Covers naive and activated CD4+/CD8+ T",
    "cell trafficking and proliferation, logistic tumour growth with two cancer",
    "clones, antigen release, uptake, endosomal processing and MHC-I",
    "presentation for a self-antigen and a neo-antigen, TCR-mediated",
    "activation, PD-1/PD-L1/PD-L2 checkpoint binding with atezolizumab",
    "blockade, CEA-cibisatamab-CD3 trimer formation in the immunological",
    "synapse, MDSC recruitment with arginase-I and nitric oxide suppression,",
    "Th-to-Treg transdifferentiation, and TGF-beta / IFN-gamma / IL-2 / CCL2",
    "dynamics. 90 ODE states, 38 algebraic (repeated- and initial-assignment)",
    "rules and 192 parameters, translated from the SimBiology export in",
    "Supplementary Tables S2-S6. Deterministic mechanism model: the authors",
    "generated virtual patients by Latin hypercube sampling of the parameter",
    "distributions in Supplementary Table S7 rather than by fitting IIV or",
    "residual error, so no etas and no error model are encoded.",
    sep = " "
  )
  reference <- paste(
    "Anbari S, Wang H, Zhang Y, Wang J, Pilvankar M, Nickaeen M, Hansel S,",
    "Popel AS. Using quantitative systems pharmacology modeling to optimize",
    "combination therapy of anti-PD-L1 checkpoint inhibitor and T cell engager.",
    "Front Pharmacol. 2023;14:1163432. doi:10.3389/fphar.2023.1163432.",
    sep = " "
  )
  vignette <- "Anbari_2023_atezolizumab_cibisatamab_qsp"

  units <- list(
    time          = "day",
    dosing        = "nmol",
    concentration = "nmol/L"
  )

  covariateData <- list()

  population <- list(
    species     = "human (in silico virtual cohort)",
    n_subjects  = 500L,
    n_studies   = 3L,
    disease_state = "metastatic colorectal cancer",
    dose_range  = paste(
      "Cibisatamab 0-100 mg QW to Q3W and atezolizumab 1200 mg Q3W; the",
      "calibration scenarios are 60 mg cibisatamab QW as monotherapy, 1200 mg",
      "atezolizumab Q3W as monotherapy, and their concurrent combination.",
      sep = " "
    ),
    notes = paste(
      "Virtual cohort of 500 patients generated by Latin hypercube sampling of",
      "the 21 parameter distributions in Supplementary Table S7, screened on",
      "tumour diameter, blood T cell density and the Teff:Treg ratio. Calibrated",
      "against NCT02324257 (31 patients, cibisatamab monotherapy) and NCT02650713",
      "(25 patients, combination), with atezolizumab monotherapy calibrated to",
      "IMblaze370 / NCT02788279. Baseline tumour diameter is uniform on 0.5-5 cm.",
      sep = " "
    )
  )

  ini({
    vol_A_e <- fixed(1.5e-09); label("Capacity of compartment A_e [dm^2]")  # Table S2 (A_e = 15 micrometer^2)
    vol_A_s <- fixed(9e-08); label("Capacity of compartment A_s [dm^2]")  # Table S2 (A_s = 900 micrometer^2)
    vol_TCEsyn_T0_C1 <- fixed(7.56e-09); label("Capacity of compartment TCEsyn_T0_C1 [dm^2]")  # Table S2 (TCEsyn_T0_C1 = 75.6 micrometer^2)
    vol_TCEsyn_T1_C1 <- fixed(7.56e-09); label("Capacity of compartment TCEsyn_T1_C1 [dm^2]")  # Table S2 (TCEsyn_T1_C1 = 75.6 micrometer^2)
    vol_V_C <- fixed(5); label("Capacity of compartment V_C [L]")  # Table S2 (V_C = 5 liter)
    vol_V_LN <- fixed(0.001112647398); label("Capacity of compartment V_LN [L]")  # Table S2 (V_LN = 1112.6473981 millimeter^3)
    vol_V_P <- fixed(60); label("Capacity of compartment V_P [L]")  # Table S2 (V_P = 60 liter)
    vol_V_e <- fixed(4e-16); label("Capacity of compartment V_e [L]")  # Table S2 (V_e = 4e-16 litre)
    vol_syn_T_APC <- fixed(3.78e-09); label("Capacity of compartment syn_T_APC [dm^2]")  # Table S2 (syn_T_APC = 37.8 micrometer^2)
    vol_syn_T_C1 <- fixed(3.78e-09); label("Capacity of compartment syn_T_C1 [dm^2]")  # Table S2 (syn_T_C1 = 37.8 micrometer^2)

    NAVG_nmol <- fixed(6.0221409e14); label("Avogadro constant (molecule/nmol)")  # Table S4 N_avg

    # ---- Tumour, cell-clearance and unit-carrier parameters ----
    k_cell_clear <- fixed(0.1); label("Rate of dead cell clearance from tumour compartment (estimated) [1/day]")  # Table S4 (k_cell_clear = 0.1 1/day)
    cell <- fixed(1); label("unit parameter for calculation [cell]")  # Table S4 (cell = 1 cell)
    day <- fixed(1); label("unit parameter for calculation [day]")  # Table S4 (day = 1 day)
    vol_cell <- fixed(2.572440785e-12); label("Average volume of cancer cell Volume of a cancer cell calculated based on... [micrometer^3/cell]")  # Table S4 (vol_cell = 2572.440785 micrometer^3/cell)
    vol_Tcell <- fixed(1.750157098e-13); label("Average volume of T cells Volume of a T cell calculated based on the... [micrometer^3/cell]")  # Table S4 (vol_Tcell = 175.0157098 micrometer^3/cell)
    Ve_T <- fixed(0.37); label("Void fraction of the tumor (Finley 2012, PMID: 22547351) [dimensionless]")  # Table S4 (Ve_T = 0.37 dimensionless)
    k_C1_growth <- fixed(0.005); label("Cancer cell growth rate (Ryu 2014, PMID: 24895040; Desai, PMID: 16489089) [1/day]")  # Table S4 (k_C1_growth = 0.005 1/day)
    C_max <- fixed(8.628907822e+11); label("Cancer cell capacity derived [cell]")  # Table S4 (C_max = 8.628907822e+11 cell)
    k_C1_death <- fixed(1e-05); label("Cancer cell death rate from innate immune cells (Palsson 2013, PMID:... [1/day]")  # Table S4 (k_C1_death = 1e-05 1/day)
    k_C1_therapy <- fixed(0); label("Rate of C1 killing by therapy [1/day]")  # Table S4 (k_C1_therapy = 0 1/day)
    k_C2_growth <- fixed(0.005); label("Cancer cell growth rate (Ryu 2014, PMID: 24895040; Desai, PMID: 16489089) [1/day]")  # Table S4 (k_C2_growth = 0.005 1/day)
    k_C2_death <- fixed(1e-05); label("Cancer cell death rate from innate immune cells (Palsson 2013, PMID:... [1/day]")  # Table S4 (k_C2_death = 1e-05 1/day)
    k_C2_therapy <- fixed(0); label("Rate of C2 killing by therapy [1/day]")  # Table S4 (k_C2_therapy = 0 1/day)
    div_T0 <- fixed(1160000); label("T Cell Diversity (Robins 2009, PMID: 19706884) [dimensionless]")  # Table S4 (div_T0 = 1160000 dimensionless)

    # ---- Self-antigen-specific (Treg / T0) T cell module ----
    n_T0_clones <- fixed(63); label("Number of T cell clones (estimated) [dimensionless]")  # Table S4 (n_T0_clones = 63 dimensionless)
    q_nT0_LN_in <- fixed(0.1); label("Rate of naive T cell transport into the LN  calculated based on the... [1/day]")  # Table S4 (q_nT0_LN_in = 0.1 1/day)
    q_T0_LN_out <- fixed(24); label("Rate of activated T cell transport out of the LN (De Boer and Perelson... [1/day]")  # Table S4 (q_T0_LN_out = 24 1/day)
    q_nT0_LN_out <- fixed(2.88); label("Rate of naive T cell transport out of the LN (Mandl 2012, PMID: 23071319) [1/day]")  # Table S4 (q_nT0_LN_out = 2.88 1/day)
    k_T0_act <- fixed(5); label("T0 activation rate (De Boer and Perelson 1995, PMID: 7475092... [1/day]")  # Table S4 (k_T0_act = 5 1/day)
    k_T0_pro <- fixed(1); label("T0 proliferation rate (Marchingo 2014, PMID: 25430770) [1/day]")  # Table S4 (k_T0_pro = 1 1/day)
    k_T0_death <- fixed(0.01); label("T0 death rate (De Boer and Perelson 1995, PMID: 7475092) [1/day]")  # Table S4 (k_T0_death = 0.01 1/day)
    q_T0_P_in <- fixed(3507.84); label("rate of T0 transport into the peripheral compartment calculated based on T... [1/minute]")  # Table S4 (q_T0_P_in = 2.436 1/minute)
    q_T0_P_out <- fixed(24); label("rate of T0 transport out of the peripheral compartment (De Boer and... [1/day]")  # Table S4 (q_T0_P_out = 24 1/day)
    q_T0_T_in <- fixed(83.52); label("rate of T0 transport into the tumor compartment calculated based on T cell... [1/(centimeter^3*minute)]")  # Table S4 (q_T0_T_in = 5.8e-05 1/(centimeter^3*minute))
    q_nT0_P_in <- fixed(254.016); label("rate of nT0 transport into the peripheral compartment calculated based on T... [1/minute]")  # Table S4 (q_nT0_P_in = 0.1764 1/minute)
    q_nT0_P_out <- fixed(5.1); label("rate of nT0 transport out of the peripheral compartment  calculated based... [1/day]")  # Table S4 (q_nT0_P_out = 5.1 1/day)
    Q_nT0_thym <- fixed(70000000); label("Thymic output of nT0 (Bains 2009, PMID: 19179300; Yeh 2017, PMID: 28912973) [cell/day]")  # Table S4 (Q_nT0_thym = 70000000 cell/day)
    k_nT0_pro <- fixed(320000000); label("rate of nT0 proliferation (Braber 2012, PMID: 22365666) [cell/day]")  # Table S4 (k_nT0_pro = 320000000 cell/day)
    K_nT0_pro <- fixed(1000000000); label("half-maximal peripheral proliferation of of nT0 (Braber 2012, PMID:... [cell]")  # Table S4 (K_nT0_pro = 1000000000 cell)
    k_nT0_death <- fixed(0.002); label("rate of nT0 death (Braber 2012, PMID: 22365666) [1/day]")  # Table S4 (k_nT0_death = 0.002 1/day)
    k_IL2_deg <- fixed(288); label("rate of IL2 degradation (Lotze 1985, PMID: 3871099) [1/minute]")  # Table S4 (k_IL2_deg = 0.2 1/minute)
    k_IL2_cons <- fixed(0.000144); label("rate of IL2 consumption by T cells (Lotze 1985, PMID: 3871099) [nanomole/cell/h]")  # Table S4 (k_IL2_cons = 6e-06 nanomole/cell/h)
    k_IL2_sec <- fixed(0.00072); label("rate of IL2 secretion from T cells (Han 2012, PMID: 22160692; Thurley 2015... [nanomole/cell/h]")  # Table S4 (k_IL2_sec = 3e-05 nanomole/cell/h)
    IL2_50 <- fixed(0.32); label("T cell activation half-maximal IL2 concentration (Marchingo 2014, PMID:... [nanomolarity]")  # Table S4 (IL2_50 = 0.32 nanomolarity)
    IL2_50_Treg <- fixed(0.0032); label("Treg activation half-maximal IL2 concentration (Wang and Smith 1987, PMID:... [nanomolarity]")  # Table S4 (IL2_50_Treg = 0.0032 nanomolarity)
    N0 <- fixed(5); label("numer of activated T cell generation by TCR signaling only(Marchingo 2014... [dimensionless]")  # Table S4 (N0 = 5 dimensionless)
    N_IL2_CD8 <- fixed(11); label("maximum number of activated T cell generations due to IL2 (Marchingo 2014... [dimensionless]")  # Table S4 (N_IL2_CD8 = 11 dimensionless)
    N_IL2_CD4 <- fixed(8); label("maximum number of activated T cell generations due to IL2 (Marchingo 2014... [dimensionless]")  # Table S4 (N_IL2_CD4 = 8 dimensionless)
    k_Treg <- fixed(0.1); label("Rate of T cell death by Tregs (estimated) [1/day]")  # Table S4 (k_Treg = 0.1 1/day)
    k_Treg_TCE <- fixed(0.1); label("Rate of T cell death by TCE activated Tregs (estimated) [1/day]")  # Table S4 (k_Treg_TCE = 0.1 1/day)

    # ---- IL-2, generation-number and CD8 (T1) T cell module ----
    div_T1 <- fixed(1110000); label("T Cell Diversity (Robins 2009, PMID: 19706884) [dimensionless]")  # Table S4 (div_T1 = 1110000 dimensionless)
    n_T1_clones <- fixed(63); label("Number of T cell clones (Li 2016, PMID: 27240091) [dimensionless]")  # Table S4 (n_T1_clones = 63 dimensionless)
    q_nT1_LN_in <- fixed(0.076); label("Rate of naive T cell transport into the LN  calculated based on the... [1/day]")  # Table S4 (q_nT1_LN_in = 0.076 1/day)
    q_T1_LN_out <- fixed(24); label("Rate of activated T cell transport out of the LN (De Boer and Perelson... [1/day]")  # Table S4 (q_T1_LN_out = 24 1/day)
    q_nT1_LN_out <- fixed(1.8); label("Rate of naive T cell transport out of the LN (Mandl 2012, PMID: 23071319) [1/day]")  # Table S4 (q_nT1_LN_out = 1.8 1/day)
    k_T1_act <- fixed(23); label("T1 activation rate (De Boer and Perelson 1995, PMID: 7475092... [1/day]")  # Table S4 (k_T1_act = 23 1/day)
    k_T1_pro <- fixed(1); label("T1 proliferation rate (Marchingo 2014, PMID: 25430770) [1/day]")  # Table S4 (k_T1_pro = 1 1/day)
    k_T1_death <- fixed(0.01); label("T1 death rate (De Boer and Perelson 1995, PMID: 7475092) [1/day]")  # Table S4 (k_T1_death = 0.01 1/day)
    q_T1_P_in <- fixed(3507.84); label("rate of T1 transport into the peripheral compartment calculated based on T... [1/minute]")  # Table S4 (q_T1_P_in = 2.436 1/minute)
    q_T1_P_out <- fixed(24); label("rate of T1 transport out of the peripheral compartment (De Boer and... [1/day]")  # Table S4 (q_T1_P_out = 24 1/day)
    q_T1_T_in <- fixed(83.52); label("rate of T1 transport into the tumor compartment calculated based on T cell... [1/(centimeter^3*minute)]")  # Table S4 (q_T1_T_in = 5.8e-05 1/(centimeter^3*minute))
    q_nT1_P_in <- fixed(254.016); label("rate of nT1 transport into the peripheral compartment calculated based on T... [1/minute]")  # Table S4 (q_nT1_P_in = 0.1764 1/minute)
    q_nT1_P_out <- fixed(5.1); label("rate of nT1 transport out of the peripheral compartment  calculated based... [1/day]")  # Table S4 (q_nT1_P_out = 5.1 1/day)
    Q_nT1_thym <- fixed(35000000); label("Thymic output of nT1 (Bains 2009, PMID: 19179300; Ye 2002, PMID: 11994448) [cell/day]")  # Table S4 (Q_nT1_thym = 35000000 cell/day)
    k_nT1_pro <- fixed(320000000); label("rate of nT1 proliferation (Braber 2012, PMID: 22365666) [cell/day]")  # Table S4 (k_nT1_pro = 320000000 cell/day)
    K_nT1_pro <- fixed(1000000000); label("half-maximal peripheral proliferation of of nT1 (Braber 2012, PMID:... [cell]")  # Table S4 (K_nT1_pro = 1000000000 cell)
    k_nT1_death <- fixed(0.002); label("rate of nT1 death (Braber 2012, PMID: 22365666) [1/day]")  # Table S4 (k_nT1_death = 0.002 1/day)
    k_T1 <- fixed(0.1); label("Rate of T cell exhaustion by cancer cells (estimated) [1/day]")  # Table S4 (k_T1 = 0.1 1/day)
    k_C_T1 <- fixed(0.9); label("Rate of cancer cell death by T cells (Robertson-Tessi 2012, PMID: 22051568) [1/day]")  # Table S4 (k_C_T1 = 0.9 1/day)
    k_C_BTcell <- fixed(0.5); label("Rate of cancer cell death by TCE activated T cells (fitted) [1/day]")  # Table S4 (k_C_BTcell = 0.5 1/day)
    k_C_BTreg <- fixed(0); label("Rate of cancer cell death by TCE activated Tregs (fitted) [1/day]")  # Table S4 (k_C_BTreg = 0 1/day)

    # ---- Antigen-presenting cell and cytokine module ----
    k_APC_mat <- fixed(1.5); label("Maximum rate of APC maturation (Chen 2014, PMID: 25184733) [1/day]")  # Table S4 (k_APC_mat = 1.5 1/day)
    k_APC_mig <- fixed(4); label("Rate of APC migration (Russo Halin 2016, PMID: 26876174) [1/day]")  # Table S4 (k_APC_mig = 4 1/day)
    k_APC_death <- fixed(0.01); label("Rate of APC death (Marino and Kirschner 2004, PMID: 15038983) [1/day]")  # Table S4 (k_APC_death = 0.01 1/day)
    k_mAPC_death <- fixed(0.02); label("Rate of mAPC death(Marino and Kirschner 2004, PMID: 15038983) [1/day]")  # Table S4 (k_mAPC_death = 0.02 1/day)
    APC0_T <- fixed(400000000); label("Steady state density of CD103+ APCs in the tumor, calculated to fit basal... [cell/milliliter]")  # Table S4 (APC0_T = 400000 cell/milliliter)
    APC0_LN <- fixed(1200000000); label("Steady state density of all APC subtypes in the LN (Catron 2004, PMID:... [cell/milliliter]")  # Table S4 (APC0_LN = 1200000 cell/milliliter)
    k_c <- fixed(2); label("Cytokine rate constant (Chen 2014, PMID: 25184733) [1/day]")  # Table S4 (k_c = 2 1/day)
    c0 <- fixed(1); label("Baseline cytokine concentration (Chen 2014, PMID: 25184733) [molarity]")  # Table S4 (c0 = 1e-09 molarity)
    c50 <- fixed(1); label("Cytokine concentration for half-maximal APC maturation (Chen 2014, PMID:... [molarity]")  # Table S4 (c50 = 1e-09 molarity)
    DAMPs <- fixed(1.34e-05); label("Concentration of cytokines released per dying cancer cell (Milo 2013, PMID:... [mole/cell]")  # Table S4 (DAMPs = 1.34e-14 mole/cell)
    n_sites_APC <- fixed(10); label("Maxium number of T Cells an APC can interact with (De Boer and Perelson... [dimensionless]")  # Table S4 (n_sites_APC = 10 dimensionless)
    kin <- fixed(14.4); label("Rate of MHC internalization (Chen 2014, PMID: 25184733) [1/day]")  # Table S4 (kin = 14.4 1/day)
    kout <- fixed(28.8); label("Rate of MHC externalization (Chen 2014, PMID: 25184733) [1/day]")  # Table S4 (kout = 28.8 1/day)

    # ---- Antigen processing / MHC presentation (P0 self-antigen) ----
    k_P0_up <- fixed(14.4); label("Rate of antigen uptake by APCs (Chen 2014, PMID: 25184733) [1/day/cell]")  # Table S4 (k_P0_up = 14.4 1/day/cell)
    k_xP0_deg <- fixed(2); label("Rate of extracellular antigen degradation (Palsson 2013, PMID: 24074340) [1/day]")  # Table S4 (k_xP0_deg = 2 1/day)
    k_P0_deg <- fixed(17.28); label("Rate of endosomal antigen degradation (Chen 2014, PMID: 25184733) [1/day]")  # Table S4 (k_P0_deg = 17.28 1/day)
    k_p0_deg <- fixed(144); label("Rate of endosomal epitope degradation (Chen 2014, PMID: 25184733) [1/day]")  # Table S4 (k_p0_deg = 144 1/day)
    k_P0_on <- fixed(0.000144); label("Rate of antigen-MHC binding (Agrawal and Linderman 1996, PMID: 8944895) [1/day/molarity]")  # Table S4 (k_P0_on = 144000 1/day/molarity)
    k_P0_d1 <- fixed(100); label("Antigen-MHC kd (Stone 2015, PMID: 25618219) [molarity]")  # Table S4 (k_P0_d1 = 1e-07 molarity)
    p0_50 <- fixed(264550.2646); label("calculated based on the number of molecules for half-maximal T cell... [molecule/micrometer^2]")  # Table S4 (p0_50 = 2.645502646e-05 molecule/micrometer^2)
    P0_C1 <- fixed(0.00054); label("Concentration of P0 in C1 (estimated by 2.7e6 proteins/um^3 in a cancer... [mole/cell]")  # Table S4 (P0_C1 = 5.4e-13 mole/cell)
    P0_C2 <- fixed(0.00054); label("Concentration of P0 in C2 (estimated by 2.7e6 proteins/um^3 in a cancer... [mole/cell]")  # Table S4 (P0_C2 = 5.4e-13 mole/cell)
    A_Tcell <- fixed(1.513104119e-08); label("Surface area of the T cell calculated based on the average T cell diameter... [micrometer^2]")  # Table S4 (A_Tcell = 151.3104119 micrometer^2)
    A_cell <- fixed(9.079202769e-08); label("Surface area of the Cancer cell calculated based on the average cancer cell... [micrometer^2]")  # Table S4 (A_cell = 907.9202769 micrometer^2)
    A_APC <- fixed(9e-08); label("Surface area of the APC (Agrawal and Linderman 1996, PMID: 8944895) [micrometer^2]")  # Table S4 (A_APC = 900 micrometer^2)
    k_M1p0_TCR_on <- fixed(8.64e-06); label("Rate of TCR binding to MHC-peptide complex (Lever 2014, PMID: 25145757) [1/(second*molecule/micrometer^2)]")  # Table S4 (k_M1p0_TCR_on = 1 1/(second*molecule/micrometer^2))
    k_M1p0_TCR_off <- fixed(86400); label("Rate of TCR unbinding from MHC-peptide complex (Lever 2014, PMID: 25145757) [1/second]")  # Table S4 (k_M1p0_TCR_off = 1 1/second)
    k_M1p0_TCR_p <- fixed(86400); label("Rate of MHC-peptide-TCR complex modification (Lever 2014, PMID: 25145757) [1/second]")  # Table S4 (k_M1p0_TCR_p = 1 1/second)
    phi_M1p0_TCR <- fixed(7776); label("Rate of MHC-peptide-TCR complex with maximal modification that leads to... [1/second]")  # Table S4 (phi_M1p0_TCR = 0.09 1/second)
    N_M1p0_TCR <- fixed(10); label("Number of modifcation steps for MHC-peptide-TCR complex (Lever 2014, PMID:... [dimensionless]")  # Table S4 (N_M1p0_TCR = 10 dimensionless)
    TCR_p0_tot <- fixed(1.038130807e+12); label("Total number of TCR molecules per naive T cell calculated based on the... [molecule/micrometer^2]")  # Table S4 (TCR_p0_tot = 103.8130807 molecule/micrometer^2)

    # ---- Antigen processing / MHC presentation (P1 neo-antigen) ----
    k_P1_up <- fixed(14.4); label("Rate of antigen uptake by APCs (Chen 2014, PMID: 25184733) [1/day/cell]")  # Table S4 (k_P1_up = 14.4 1/day/cell)
    k_xP1_deg <- fixed(2); label("Rate of extracellular antigen degradation (Palsson 2013, PMID: 24074340) [1/day]")  # Table S4 (k_xP1_deg = 2 1/day)
    k_P1_deg <- fixed(17.28); label("Rate of endosomal antigen degradation (Chen 2014, PMID: 25184733) [1/day]")  # Table S4 (k_P1_deg = 17.28 1/day)
    k_p1_deg <- fixed(144); label("Rate of endosomal epitope degradation (Chen 2014, PMID: 25184733) [1/day]")  # Table S4 (k_p1_deg = 144 1/day)
    k_P1_on <- fixed(0.000144); label("Rate of antigen-MHC binding (Agrawal and Linderman 1996, PMID: 8944895) [1/day/molarity]")  # Table S4 (k_P1_on = 144000 1/day/molarity)
    k_P1_d1 <- fixed(10); label("Antigen-MHC kd (Stone 2015, PMID: 25618219) [molarity]")  # Table S4 (k_P1_d1 = 1e-08 molarity)
    p1_50 <- fixed(264550.2646); label("calculated based on the number of molecules for half-maximal T cell... [molecule/micrometer^2]")  # Table S4 (p1_50 = 2.645502646e-05 molecule/micrometer^2)
    P1_C1 <- fixed(0.00054); label("Concentration of P1 in C1 (estimated by 2.7e6 proteins/um^3 in a cancer... [mole/cell]")  # Table S4 (P1_C1 = 5.4e-13 mole/cell)
    P1_C2 <- fixed(0.00054); label("Concentration of P1 in C2 (estimated by 2.7e6 proteins/um^3 in a cancer... [mole/cell]")  # Table S4 (P1_C2 = 5.4e-13 mole/cell)
    k_M1p1_TCR_on <- fixed(8.64e-06); label("Rate of TCR binding to MHC-peptide complex (Lever 2014, PMID: 25145757) [1/(second*molecule/micrometer^2)]")  # Table S4 (k_M1p1_TCR_on = 1 1/(second*molecule/micrometer^2))
    k_M1p1_TCR_off <- fixed(86400); label("Rate of TCR unbinding from MHC-peptide complex (Lever 2014, PMID: 25145757) [1/second]")  # Table S4 (k_M1p1_TCR_off = 1 1/second)
    k_M1p1_TCR_p <- fixed(86400); label("Rate of MHC-peptide-TCR complex modification (Lever 2014, PMID: 25145757) [1/second]")  # Table S4 (k_M1p1_TCR_p = 1 1/second)
    phi_M1p1_TCR <- fixed(7776); label("Rate of MHC-peptide-TCR complex with maximal modification that leads to... [1/second]")  # Table S4 (phi_M1p1_TCR = 0.09 1/second)
    N_M1p1_TCR <- fixed(10); label("Number of modifcation steps for MHC-peptide-TCR complex (Lever 2014, PMID:... [dimensionless]")  # Table S4 (N_M1p1_TCR = 10 dimensionless)
    TCR_p1_tot <- fixed(1.038130807e+12); label("Total number of TCR molecules per naive T cell calculated based on the... [molecule/micrometer^2]")  # Table S4 (TCR_p1_tot = 103.8130807 molecule/micrometer^2)

    # ---- Immune checkpoint (PD-1 / PD-L1 / PD-L2) and atezolizumab ----
    kon_PD1_PDL1 <- fixed(504000000); label("kon of PD1-PDL1 binding kon for PD1-PDL1 (Cheng 2013, PMID: 23417675) [1/(micromolarity*nanometer*second)]")  # Table S4 (kon_PD1_PDL1 = 0.05833333333 1/(micromolarity*nanometer*second))
    q_P_atezo <- fixed(0.75168); label("Volumetric flow rate of atezo between central and peripheral compartment... [lits/second]")  # Table S4 (q_P_atezo = 8.7e-06 lits/second)
    q_T_atezo <- fixed(0.00736128); label("Volumetric flow rate of atezo between central and tumor compartment (Wang... [milliliter/second]")  # Table S4 (q_T_atezo = 8.52e-05 milliliter/second)
    q_LN_atezo <- fixed(0.0002808); label("Volumetric flow rate of atezo between central and TDLN compartment (Meijer... [milliliter/second]")  # Table S4 (q_LN_atezo = 3.25e-06 milliliter/second)
    q_LD_atezo <- fixed(2.16); label("Rate of lymphatic drainage of atezo from TDLN to central compartment (Zhu... [1/minute]")  # Table S4 (q_LD_atezo = 0.0015 1/minute)
    gamma_C_atezo <- fixed(0.61); label("Volume fraction of interstitial space available to atezo in central... [dimensionless]")  # Table S4 (gamma_C_atezo = 0.61 dimensionless)
    gamma_P_atezo <- fixed(0.068); label("Volume fraction of interstitial space available to atezo in peripheral... [dimensionless]")  # Table S4 (gamma_P_atezo = 0.068 dimensionless)
    gamma_T_atezo <- fixed(0.522); label("Volume fraction of interstitial space available to atezo in tumor... [dimensionless]")  # Table S4 (gamma_T_atezo = 0.522 dimensionless)
    gamma_LN_atezo <- fixed(0.2); label("Volume fraction of interstitial space available to atezo in TDLN... [dimensionless]")  # Table S4 (gamma_LN_atezo = 0.2 dimensionless)
    k_out_PDL1 <- fixed(50000); label("Expression rate of PDL1 on tumor cells (Mimura 2018, PMID: 29034543) [molecule/day]")  # Table S4 (k_out_PDL1 = 50000 molecule/day)
    k_in_PDL1 <- fixed(1); label("Degradation rate of PDL1 on tumor cells (Hsu 2018, PMID: 30442814) [1/day]")  # Table S4 (k_in_PDL1 = 1 1/day)
    r_PDL1_IFNg <- fixed(6); label("Number of folds increase of PDL1 expression by IFNg (Shin 2017, PMID:... [dimensionless]")  # Table S4 (r_PDL1_IFNg = 6 dimensionless)
    kon_PD1_PDL2 <- fixed(662400000); label("kon of PD1-PDL2 binding (Cheng 2013, PMID: 23417675) [1/(micromolarity*nanometer*second)]")  # Table S4 (kon_PD1_PDL2 = 0.07666666667 1/(micromolarity*nanometer*second))
    kon_PDL1_atezo <- fixed(37.152); label("kon of PDL1-atezolizumab binding (Wang 2014, PMID: 24872026) [1/(molarity*second)]")  # Table S4 (kon_PDL1_atezo = 430000 1/(molarity*second))
    koff_PD1_PDL1 <- fixed(123984); label("koff of PD1-PDL1 binding calculated based on the measured kd and kon (Cheng... [1/second]")  # Table S4 (koff_PD1_PDL1 = 1.435 1/second)
    koff_PD1_PDL2 <- fixed(45705.6); label("koff of PD1-PDL2 binding calculated based on the measured kd and kon (Cheng... [1/second]")  # Table S4 (koff_PD1_PDL2 = 0.529 1/second)
    koff_PDL1_atezo <- fixed(14.8608); label("koff of PDL1-atezolizumab binding calculated based on the measured kd and... [1/second]")  # Table S4 (koff_PDL1_atezo = 0.000172 1/second)
    Chi_PDL1_atezo <- fixed(3333333310); label("Antibody cross-arm binding efficiency that also includes the conversion of... [1/nanometer]")  # Table S4 (Chi_PDL1_atezo = 33.3333331 1/nanometer)
    PD1_50 <- fixed(2e+11); label("PD1/PDL1 concentration for half-maximal T cell inactivation (estimated) [molecule/micrometer^2]")  # Table S4 (PD1_50 = 20 molecule/micrometer^2)
    n_PD1 <- fixed(2); label("Hill coefficient for PD1/PDL1 half-maximal T cell inactivation (estimated) [dimensionless]")  # Table S4 (n_PD1 = 2 dimensionless)
    T_PD1_total <- fixed(62000); label("concentration of PD1 on T cells (Cheng 2014, PMID: 23417675) [molecule]")  # Table S4 (T_PD1_total = 62000 molecule)
    T_PDL1_total <- fixed(186000); label("concentration of PDL1 on T cells (Cheng 2014, PMID: 23417675; Mkrtichyan... [molecule]")  # Table S4 (T_PDL1_total = 186000 molecule)
    C1_PDL1_base <- fixed(180000); label("baseline number of PDL1 molecules per C1 cell (Cheng 2014, PMID: 23417675) [molecule]")  # Table S4 (C1_PDL1_base = 180000 molecule)
    r_PDL2C1 <- fixed(0.07); label("PDL2/PDL1 molecule ratio on C1cell (Cheng 2014, PMID: 23417675) [dimensionless]")  # Table S4 (r_PDL2C1 = 0.07 dimensionless)
    APC_PDL1_base <- fixed(266666.6667); label("baseline number of PDL1 molecules per APC cell (Cheng 2014, PMID: 23417675) [molecule]")  # Table S4 (APC_PDL1_base = 266666.6667 molecule)
    r_PDL2APC <- fixed(0.07); label("PDL2/PDL1 molecule ratio on APCcell (Cheng 2014, PMID: 23417675) [dimensionless]")  # Table S4 (r_PDL2APC = 0.07 dimensionless)

    # ---- Myeloid-derived suppressor cell (MDSC) module ----
    k_rec_MDSC <- fixed(1.2); label("Rate of MDSC recruitment into the tumor (Lai 2018, PMID: 29735668; Huang... [1/day]")  # Table S4 (k_rec_MDSC = 1.2 1/day)
    kd_MDSC <- fixed(0.015); label("Rate of MDSC death (Lai 2018, PMID: 29735668) [1/day]")  # Table S4 (kd_MDSC = 0.015 1/day)
    k_deg_CCL2 <- fixed(1.44); label("rate of CCL2 degradation (Tanimoto 2007, PMID: 18089573) [1/h]")  # Table S4 (k_deg_CCL2 = 0.06 1/h)
    k_deg_NO <- fixed(135); label("rate of NO degradation (Hakim 1996, PMID: 8953625) [1/day]")  # Table S4 (k_deg_NO = 135 1/day)
    k_deg_ArgI <- fixed(0.173); label("rate of ArgI degradation (Schimke 1964, PMID: 14257612) [1/day]")  # Table S4 (k_deg_ArgI = 0.173 1/day)
    k_sec_CCL2 <- fixed(1.5e-12); label("rate of CCL2 secretion (Huang 2007, PMID: 17257744; Dutta 2018, PMID:... [nanomole/cell/day]")  # Table S4 (k_sec_CCL2 = 1.5e-12 nanomole/cell/day)
    k_sec_NO <- fixed(4.8e-07); label("rate of NO secretion from MDSCs (Serafini 2008, PMID: 18593947) [nanomole/cell/day]")  # Table S4 (k_sec_NO = 4.8e-07 nanomole/cell/day)
    k_sec_ArgI <- fixed(1.4e-08); label("rate of ArgI secretion (Serafini 2008, PMID: 18593947) [(mU*microliter)/cell/day]")  # Table S4 (k_sec_ArgI = 0.014 (mU*microliter)/cell/day)
    IC50_ArgI_CTL <- fixed(61.7); label("rate of ArgI-induced T cell death (Serafini 2008, PMID: 18593947) [mU]")  # Table S4 (IC50_ArgI_CTL = 61.7 mU)
    IC50_NO_CTL <- fixed(0.75); label("rate of NO-induced T cell death (Serafini 2008, PMID: 18593947) [molarity]")  # Table S4 (IC50_NO_CTL = 7.5e-10 molarity)
    EC50_CCL2_rec <- fixed(0.5); label("Half-maximal CCL2 level of MDSC recruitment (Ernst 1994, PMID: 8144933) [molarity]")  # Table S4 (EC50_CCL2_rec = 5e-10 molarity)
    EC50_ArgI_Treg <- fixed(22.1); label("Half-maximal ArgI level of Treg expansion (estimated based on Serafini... [mU]")  # Table S4 (EC50_ArgI_Treg = 22.1 mU)
    MDSC_max <- fixed(163700000); label("Maximal MDSC density in the tumour (Diaz-Montero 2009, PMID: 18446337) [cell/milliliter]")  # Table S4 (MDSC_max = 163700 cell/milliliter)
    k_brec_MDSC <- fixed(0.0021); label("Baseline rate of MDSC migration into the tumor(Huang 2006, PMID: 17257744) [1/day]")  # Table S4 (k_brec_MDSC = 0.0021 1/day)

    # ---- T helper cell, TGF-beta and IFN-gamma module ----
    k_Th_act <- fixed(10); label("Rate of T helper cell activation (Robertson-Tessi 2012, PMID: 22051568) [1/day]")  # Table S4 (k_Th_act = 10 1/day)
    k_reg <- fixed(0.022); label("Th differentiation rate to Treg (Robertson-Tessi 2012, PMID: 22051568) [1/day]")  # Table S4 (k_reg = 0.022 1/day)
    k_TGF_Tsec <- fixed(1.2e-10); label("TGF secretion rate by Treg (Liyanage 2002, PMID: 12193750) [nanomole/cell/day]")  # Table S4 (k_TGF_Tsec = 1.2e-10 nanomole/cell/day)
    k_TGF_deg <- fixed(14.3); label("TGF degradtion rate (Robertson-Tessi 2012, PMID: 22051568) [1/day]")  # Table S4 (k_TGF_deg = 14.3 1/day)
    TGF_50_reg <- fixed(0.14); label("Half-Maximal TGFb level for differentiation of Th to Treg (Robertson-Tessi... [molarity]")  # Table S4 (TGF_50_reg = 1.4e-10 molarity)
    TGF_50_ctl <- fixed(0.28); label("Half-Maximal TGFb level for CD8 T cell inhibition (Robertson-Tessi 2012... [molarity]")  # Table S4 (TGF_50_ctl = 2.8e-10 molarity)
    Kc_rec <- fixed(20200000); label("Half-Maximal cancer cell number for T cell recruitment (Phillis 2006, PMID:... [cell^2]")  # Table S4 (Kc_rec = 20200000 cell^2)
    TGFbase <- fixed(0.02); label("Baseline TGFb level in tumor (Manuyakorn 2008, PMID: 19317336; Panis 2013... [molarity]")  # Table S4 (TGFbase = 2e-11 molarity)
    k_IFNg_sec <- fixed(4e-13); label("IFNg secretion rate by T helper cell (Borj 2017, doi:10.15171/ijbms.2017.05) [nanomole/cell/day]")  # Table S4 (k_IFNg_sec = 4e-13 nanomole/cell/day)
    k_IFNg_deg <- fixed(7.68); label("IFNg degradation rate (Hofstra 1998, PMID: 9806748) [1/day]")  # Table S4 (k_IFNg_deg = 7.68 1/day)
    IFNg_50_ind <- fixed(0.00296); label("Half-Maximal IFNg level for PD-L1 induction (Shin 2017, PMID: 27903500) [molarity]")  # Table S4 (IFNg_50_ind = 2.96e-12 molarity)

    # ---- Cibisatamab PK and TCE (CEA / CD3) binding module ----
    q_P_cibis <- fixed(2.38032e-05); label("Volumetric flow rate of cibis between central and peripheral compartment... [milliliter/second]")  # Table S4 (q_P_cibis = 2.755e-07 milliliter/second)
    q_T_cibis <- fixed(0.736128); label("Volumetric flow rate of cibis between central and tumor compartment (Wang... [1/second]")  # Table S4 (q_T_cibis = 8.52e-06 1/second)
    q_LN_cibis <- fixed(2.38032e-05); label("Volumetric flow rate of cibis between central and TDLN compartment (Padera... [milliliter/second]")  # Table S4 (q_LN_cibis = 2.755e-07 milliliter/second)
    q_LD_cibis <- fixed(2.16); label("Rate of lymphatic drainage of cibis from TDLN to central compartment (Zhu... [1/minute]")  # Table S4 (q_LD_cibis = 0.0015 1/minute)
    gamma_C_cibis <- fixed(0.46); label("Volume fraction of interstitial space available to cibis in central... [dimensionless]")  # Table S4 (gamma_C_cibis = 0.46 dimensionless)
    gamma_P_cibis <- fixed(0.067); label("Volume fraction of interstitial space available to cibis in peripheral... [dimensionless]")  # Table S4 (gamma_P_cibis = 0.067 dimensionless)
    gamma_T_cibis <- fixed(0.522); label("Volume fraction of interstitial space available to cibis in tumor... [dimensionless]")  # Table S4 (gamma_T_cibis = 0.522 dimensionless)
    gamma_LN_cibis <- fixed(0.2); label("Volume fraction of interstitial space available to cibis in TDLN... [dimensionless]")  # Table S4 (gamma_LN_cibis = 0.2 dimensionless)
    SA_Tcell <- fixed(1.513104119e-08); label("Surface area of the T cell calculated based on the average T cell diameter... [micrometer^2]")  # Table S4 (SA_Tcell = 151.3104119 micrometer^2)
    CEA_CD3_50 <- fixed(5000000000); label("CEA/CD3 concentration for half-maximal T cell inactivation (Jonathan 2016) [molecule/micrometer^2]")  # Table S4 (CEA_CD3_50 = 0.5 molecule/micrometer^2)
    n_CEA_CD3 <- fixed(1); label("Hill coefficient for CEA/CD3 half-maximal T cell inactivation (fitted to... [dimensionless]")  # Table S4 (n_CEA_CD3 = 1 dimensionless)
    T1_CD3_total <- fixed(50000); label("concentration of CD3 on T1 cells (Van De Vyver et. al 2021) [molecule]")  # Table S4 (T1_CD3_total = 50000 molecule)
    C1_CEA_total <- fixed(230000); label("number of CEA molecules per C1 cell (Van De Vyver et. al 2021) [molecule]")  # Table S4 (C1_CEA_total = 230000 molecule)
    T0_CD3_total <- fixed(50000); label("concentration of CD3 on T0 cells (estimated) [molecule]")  # Table S4 (T0_CD3_total = 50000 molecule)

    # ------------------------------------------------------------------
    # Symbols used by the Table S6 reaction rate laws that Table S4 does
    # not itself list. Six are exact renames of a Table S4 entry; two are
    # recovered from the on-disk upstream SimBiology export of Ma 2020b,
    # which Anbari 2023 states the TCE binding module is based on. See the
    # vignette Errata section.
    # ------------------------------------------------------------------
    SA_cell <- fixed(9.079202769e-08); label("Surface area of the cancer cell [micrometer^2]")
    # exact rename of SA_Ccell (Table S4, 907.92027688745 micrometer^2);
    #   used by Table S5 rules 43 and 46 for CEA density on the cancer
    #   cell
    k_cl_atezo <- fixed(0.324); label("Clearance of atezolizumab from the central compartment [liter/day]")
    # exact rename of CL_atezo (Table S4, 0.324 liter/day); Table S6 R97
    #   and Supplementary Eq 4 both give it as the central clearance
    k_cl_cibis <- fixed(3); label("Clearance of cibisatamab from the central compartment [liter/h]")
    # exact rename of CL_cibis (Table S4, 0.125 liter/h); Table S6 R150
    #   and Supplementary Eq 4
    kon_CEA_cibis <- fixed(1.728); label("kon of CEA-cibisatamab binding [1/(molarity*second)]")
    # exact rename of kon_CEA_TCE (Table S4, 20000 1/(molarity*second))
    koff_CEA_cibis <- fixed(86.4); label("koff of CEA-cibisatamab binding [1/second]")
    # exact rename of koff_CEA_TCE (Table S4, 0.001 1/second)
    kon_CD3_cibis <- fixed(0.864); label("kon of CD3-cibisatamab binding [1/(molarity*second)]")
    # exact rename of kon_CD3_TCE (Table S4, 10000 1/(molarity*second))
    koff_CD3_cibis <- fixed(86.4); label("koff of CD3-cibisatamab binding [1/second]")
    # exact rename of koff_CD3_TCE (Table S4, 0.001 1/second)
    kon_CD3_cibis2 <- fixed(28800000); label("Second-step 2D on-rate of CD3 binding to the CEA-cibisatamab dimer [1/(molarity*nanometer*second)]")
    # RECOVERED: second-step 2D on-rate, absent from Table S4. Ma 2020b
    #   SBML gives kon_CD3_cibis2 = 3333.333 = kon_CD3_cibis/3 and
    #   kon_CEA_cibis2 = 333.333 = kon_CEA_cibis/3, i.e. kon_X_cibis2 =
    #   kon_X_cibis / D_syn with D_syn = 3 nm. Applied to this papers
    #   kon_CD3_TCE: 10000/3 = 3333.333 1/(molarity*nanometer*second)
    kon_CEA_cibis2 <- fixed(57600000); label("Second-step 2D on-rate of CEA binding to the CD3-cibisatamab dimer [1/(molarity*nanometer*second)]")
    # RECOVERED: as kon_CD3_cibis2; 20000/3 = 6666.667
    #   1/(molarity*nanometer*second)
  })

  model({
    # ---------- parameter aliases ----------
    # rxode2 parses a bare (theta + theta) sub-expression as a mu-reference
    # block and refuses the model. These mechanistic rate laws legitimately
    # add two fixed constants, so each such parameter is copied to a local
    # first. Values and provenance are unchanged.
    a_k_C1_death <- k_C1_death
    a_k_C1_therapy <- k_C1_therapy
    a_k_C2_death <- k_C2_death
    a_k_C2_therapy <- k_C2_therapy
    a_k_M1p0_TCR_off <- k_M1p0_TCR_off
    a_k_M1p0_TCR_p <- k_M1p0_TCR_p
    a_k_M1p1_TCR_off <- k_M1p1_TCR_off
    a_k_M1p1_TCR_p <- k_M1p1_TCR_p
    a_k_T1_death <- k_T1_death
    a_phi_M1p0_TCR <- phi_M1p0_TCR
    a_phi_M1p1_TCR <- phi_M1p1_TCR

    # ---------- compartment capacities (Supplementary Table S2) ----------
    # Local copies of the ini() capacities. rxode2 reads a bare (theta+theta)
    # sub-expression as a mu-reference block, so every parameter that appears
    # in such a sum in a mechanistic rate law is aliased here first.
    m_V_C <- vol_V_C
    m_V_P <- vol_V_P
    m_V_LN <- vol_V_LN
    m_V_e <- vol_V_e
    m_A_e <- vol_A_e
    m_A_s <- vol_A_s
    m_syn_T_C1 <- vol_syn_T_C1
    m_syn_T_APC <- vol_syn_T_APC
    m_TCEsyn_T1_C1 <- vol_TCEsyn_T1_C1
    m_TCEsyn_T0_C1 <- vol_TCEsyn_T0_C1

    # ---------- species quantities (states are AMOUNTS; SimBiology-valued x_* derived) ----------
    x_V_C_nT0 <- q_V_C_nT0
    x_V_C_T0 <- q_V_C_T0
    x_V_C_nT1 <- q_V_C_nT1
    x_V_C_T1 <- q_V_C_T1
    x_V_C_atezo <- q_V_C_atezo/m_V_C
    x_V_C_Th <- q_V_C_Th
    x_V_C_cibis <- q_V_C_cibis/m_V_C
    x_V_P_nT0 <- q_V_P_nT0
    x_V_P_T0 <- q_V_P_T0
    x_V_P_nT1 <- q_V_P_nT1
    x_V_P_T1 <- q_V_P_T1
    x_V_P_atezo <- q_V_P_atezo/m_V_P
    x_V_P_Th <- q_V_P_Th
    x_V_P_cibis <- q_V_P_cibis/m_V_P
    x_V_LN_nT0 <- q_V_LN_nT0
    x_V_LN_aT0 <- q_V_LN_aT0
    x_V_LN_T0 <- q_V_LN_T0
    x_V_LN_IL2 <- q_V_LN_IL2/m_V_LN
    x_V_LN_nT1 <- q_V_LN_nT1
    x_V_LN_aT1 <- q_V_LN_aT1
    x_V_LN_T1 <- q_V_LN_T1
    x_V_LN_APC <- q_V_LN_APC
    x_V_LN_mAPC <- q_V_LN_mAPC
    x_V_LN_atezo <- q_V_LN_atezo/m_V_LN
    x_V_LN_aTh <- q_V_LN_aTh
    x_V_LN_Th <- q_V_LN_Th
    x_V_LN_cibis <- q_V_LN_cibis/m_V_LN
    x_V_e_P0 <- q_V_e_P0/m_V_e
    x_V_e_p0 <- q_V_e_p0/m_V_e
    x_V_e_P1 <- q_V_e_P1/m_V_e
    x_V_e_p1 <- q_V_e_p1/m_V_e
    x_A_e_M1 <- q_A_e_M1/m_A_e
    x_A_e_M1p0 <- q_A_e_M1p0/m_A_e
    x_A_e_M1p1 <- q_A_e_M1p1/m_A_e
    x_A_s_M1 <- q_A_s_M1/m_A_s
    x_A_s_M1p0 <- q_A_s_M1p0/m_A_s
    x_A_s_M1p1 <- q_A_s_M1p1/m_A_s
    x_syn_T_C1_PD1_PDL1 <- q_syn_T_C1_PD1_PDL1/m_syn_T_C1
    x_syn_T_C1_PD1_PDL2 <- q_syn_T_C1_PD1_PDL2/m_syn_T_C1
    x_syn_T_C1_PD1 <- q_syn_T_C1_PD1/m_syn_T_C1
    x_syn_T_C1_PDL1 <- q_syn_T_C1_PDL1/m_syn_T_C1
    x_syn_T_C1_PDL2 <- q_syn_T_C1_PDL2/m_syn_T_C1
    x_syn_T_C1_PDL1_atezo <- q_syn_T_C1_PDL1_atezo/m_syn_T_C1
    x_syn_T_C1_PDL1_atezo_PDL1 <- q_syn_T_C1_PDL1_atezo_PDL1/m_syn_T_C1
    x_syn_T_C1_TPDL1 <- q_syn_T_C1_TPDL1/m_syn_T_C1
    x_syn_T_C1_TPDL1_atezo <- q_syn_T_C1_TPDL1_atezo/m_syn_T_C1
    x_syn_T_C1_TPDL1_atezo_TPDL1 <- q_syn_T_C1_TPDL1_atezo_TPDL1/m_syn_T_C1
    x_syn_T_APC_PD1_PDL1 <- q_syn_T_APC_PD1_PDL1/m_syn_T_APC
    x_syn_T_APC_PD1_PDL2 <- q_syn_T_APC_PD1_PDL2/m_syn_T_APC
    x_syn_T_APC_PD1 <- q_syn_T_APC_PD1/m_syn_T_APC
    x_syn_T_APC_PDL1 <- q_syn_T_APC_PDL1/m_syn_T_APC
    x_syn_T_APC_PDL2 <- q_syn_T_APC_PDL2/m_syn_T_APC
    x_syn_T_APC_PDL1_atezo <- q_syn_T_APC_PDL1_atezo/m_syn_T_APC
    x_syn_T_APC_PDL1_atezo_PDL1 <- q_syn_T_APC_PDL1_atezo_PDL1/m_syn_T_APC
    x_syn_T_APC_TPDL1 <- q_syn_T_APC_TPDL1/m_syn_T_APC
    x_syn_T_APC_TPDL1_atezo <- q_syn_T_APC_TPDL1_atezo/m_syn_T_APC
    x_syn_T_APC_TPDL1_atezo_TPDL1 <- q_syn_T_APC_TPDL1_atezo_TPDL1/m_syn_T_APC
    x_TCEsyn_T1_C1_CEA_cibis_CEA_CD3 <- q_TCEsyn_T1_C1_CEA_cibis_CEA_CD3/m_TCEsyn_T1_C1
    x_TCEsyn_T1_C1_CEA_cibis_CEA <- q_TCEsyn_T1_C1_CEA_cibis_CEA/m_TCEsyn_T1_C1
    x_TCEsyn_T1_C1_CD3_cibis <- q_TCEsyn_T1_C1_CD3_cibis/m_TCEsyn_T1_C1
    x_TCEsyn_T1_C1_CEA <- q_TCEsyn_T1_C1_CEA/m_TCEsyn_T1_C1
    x_TCEsyn_T1_C1_CD3 <- q_TCEsyn_T1_C1_CD3/m_TCEsyn_T1_C1
    x_TCEsyn_T0_C1_CEA_cibis_CEA_CD3 <- q_TCEsyn_T0_C1_CEA_cibis_CEA_CD3/m_TCEsyn_T0_C1
    x_TCEsyn_T0_C1_CEA_cibis_CEA <- q_TCEsyn_T0_C1_CEA_cibis_CEA/m_TCEsyn_T0_C1
    x_TCEsyn_T0_C1_CD3_cibis <- q_TCEsyn_T0_C1_CD3_cibis/m_TCEsyn_T0_C1
    x_TCEsyn_T0_C1_CEA <- q_TCEsyn_T0_C1_CEA/m_TCEsyn_T0_C1
    x_TCEsyn_T0_C1_CD3 <- q_TCEsyn_T0_C1_CD3/m_TCEsyn_T0_C1

    # ---------- tumour volume: state-dependent repeated assignment (Table S5 rule 1) ----------
    x_V_T_C_x <- q_V_T_C_x
    x_V_T_T1_exh <- q_V_T_T1_exh
    x_V_T_Th_exh <- q_V_T_Th_exh
    x_V_T_C1 <- q_V_T_C1
    x_V_T_C2 <- q_V_T_C2
    x_V_T_nT0 <- q_V_T_nT0
    x_V_T_T0 <- q_V_T_T0
    x_V_T_nT1 <- q_V_T_nT1
    x_V_T_T1 <- q_V_T_T1
    x_V_T_APC <- q_V_T_APC
    x_V_T_mAPC <- q_V_T_mAPC
    x_V_T_MDSC <- q_V_T_MDSC
    x_V_T_Th <- q_V_T_Th
    C_total <- (((0*cell)+x_V_T_C1)+x_V_T_C2)   # Table S5 rule 2
    T_total <- ((((0*cell)+x_V_T_T0)+x_V_T_T1)+x_V_T_Th)   # Table S5 rule 3
    vol_V_T <- ((((((x_V_T_C_x+C_total)*vol_cell)+((((x_V_T_T1_exh+x_V_T_Th_exh)+T_total)+x_V_T_Th)*vol_Tcell))/Ve_T)+(vol_cell*x_V_T_C1))+(vol_cell*x_V_T_C2))   # Table S5 rule 1
    x_V_T_c <- q_V_T_c/vol_V_T
    x_V_T_P0 <- q_V_T_P0/vol_V_T
    x_V_T_P1 <- q_V_T_P1/vol_V_T
    x_V_T_atezo <- q_V_T_atezo/vol_V_T
    x_V_T_CCL2 <- q_V_T_CCL2/vol_V_T
    x_V_T_NO <- q_V_T_NO/vol_V_T
    x_V_T_ArgI <- q_V_T_ArgI/vol_V_T
    x_V_T_TGF <- q_V_T_TGF/vol_V_T
    x_V_T_IFNg <- q_V_T_IFNg/vol_V_T
    x_V_T_cibis <- q_V_T_cibis/vol_V_T

    # ---------- algebraic / repeated-assignment rules (Table S5) ----------
    T_total_LN <- ((((0*cell)+x_V_LN_T0)+x_V_LN_T1)+x_V_LN_Th)   # Table S5 rule 4
    Tregs_ <- x_V_T_T0   # Table S5 rule 6
    N_aT <- (N0+((N_IL2_CD8*x_V_LN_IL2)/(IL2_50+x_V_LN_IL2)))   # Table S5 rule 7
    N_aT0 <- (N0+((N_IL2_CD4*x_V_LN_IL2)/(IL2_50+x_V_LN_IL2)))   # Table S5 rule 8
    H_APC <- ((n_sites_APC*x_V_LN_mAPC)/(((n_sites_APC*x_V_LN_mAPC)+(x_V_LN_nT0*n_T0_clones))+cell))   # Table S5 rule 9
    H_mAPC <- ((n_sites_APC*x_V_LN_mAPC)/(((n_sites_APC*x_V_LN_mAPC)+(x_V_LN_nT1*n_T1_clones))+cell))   # Table S5 rule 10
    H_APCh <- ((n_sites_APC*x_V_LN_mAPC)/(((n_sites_APC*x_V_LN_mAPC)+(x_V_LN_nT0*n_T1_clones))+cell))   # Table S5 rule 11
    pTCR_p0_MHC_tot <- (((a_k_M1p0_TCR_off/(a_k_M1p0_TCR_off+a_phi_M1p0_TCR))*((a_k_M1p0_TCR_p/(a_k_M1p0_TCR_off+a_k_M1p0_TCR_p)))^(N_M1p0_TCR))*(0.5*((((x_A_s_M1p0/n_T0_clones)+TCR_p0_tot)+(a_k_M1p0_TCR_off/k_M1p0_TCR_on))-(TCR_p0_tot*sqrt(((((((x_A_s_M1p0/n_T0_clones)+TCR_p0_tot)+(a_k_M1p0_TCR_off/k_M1p0_TCR_on))/TCR_p0_tot))^(2)-(((4*x_A_s_M1p0)/n_T0_clones)/TCR_p0_tot)))))))   # Table S5 rule 12
    H_P0 <- (pTCR_p0_MHC_tot/(pTCR_p0_MHC_tot+p0_50))   # Table S5 rule 13
    pTCR_p1_MHC_tot <- (((a_k_M1p1_TCR_off/(a_k_M1p1_TCR_off+a_phi_M1p1_TCR))*((a_k_M1p1_TCR_p/(a_k_M1p1_TCR_off+a_k_M1p1_TCR_p)))^(N_M1p1_TCR))*(0.5*((((x_A_s_M1p1/n_T1_clones)+TCR_p1_tot)+(a_k_M1p1_TCR_off/k_M1p1_TCR_on))-(TCR_p1_tot*sqrt(((((((x_A_s_M1p1/n_T1_clones)+TCR_p1_tot)+(a_k_M1p1_TCR_off/k_M1p1_TCR_on))/TCR_p1_tot))^(2)-(((4*x_A_s_M1p1)/n_T1_clones)/TCR_p1_tot)))))))   # Table S5 rule 14
    H_P1 <- (pTCR_p1_MHC_tot/(pTCR_p1_MHC_tot+p1_50))   # Table S5 rule 15
    x_syn_T_C1_PDL1_total <- (((x_syn_T_C1_PDL1+x_syn_T_C1_PD1_PDL1)+x_syn_T_C1_PDL1_atezo)+(2*x_syn_T_C1_PDL1_atezo_PDL1))   # Table S5 rule 22
    x_syn_T_C1_PDL2_total <- (x_syn_T_C1_PD1_PDL2+x_syn_T_C1_PDL2)   # Table S5 rule 23
    H_PD1_C1 <- ((((x_syn_T_C1_PD1_PDL1+x_syn_T_C1_PD1_PDL2)/PD1_50))^(n_PD1)/((((x_syn_T_C1_PD1_PDL1+x_syn_T_C1_PD1_PDL2)/PD1_50))^(n_PD1)+1))   # Table S5 rule 26
    x_syn_T_APC_PDL1_total <- (((x_syn_T_APC_PDL1+x_syn_T_APC_PD1_PDL1)+x_syn_T_APC_PDL1_atezo)+(2*x_syn_T_APC_PDL1_atezo_PDL1))   # Table S5 rule 33
    x_syn_T_APC_PDL2_total <- (x_syn_T_APC_PD1_PDL2+x_syn_T_APC_PDL2)   # Table S5 rule 34
    H_MDSC_C1 <- (1-((IC50_NO_CTL/(IC50_NO_CTL+x_V_T_NO))*(1-(x_V_T_ArgI/(IC50_ArgI_CTL+x_V_T_ArgI)))))   # Table S5 rule 38
    H_TGF_reg <- (x_V_T_TGF/(x_V_T_TGF+TGF_50_reg))   # Table S5 rule 39
    H_TGF_CTL <- (x_V_T_TGF/(x_V_T_TGF+TGF_50_ctl))   # Table S5 rule 40
    N_aTh <- (N0+((N_IL2_CD4*x_V_LN_IL2)/(IL2_50+x_V_LN_IL2)))   # Table S5 rule 41
    H_CEA_C1_T1 <- (((x_TCEsyn_T1_C1_CEA_cibis_CEA_CD3/CEA_CD3_50))^(n_CEA_CD3)/(((x_TCEsyn_T1_C1_CEA_cibis_CEA_CD3/CEA_CD3_50))^(n_CEA_CD3)+1))   # Table S5 rule 44
    H_CEA_C1_T0 <- (((x_TCEsyn_T0_C1_CEA_cibis_CEA_CD3/CEA_CD3_50))^(n_CEA_CD3)/(((x_TCEsyn_T0_C1_CEA_cibis_CEA_CD3/CEA_CD3_50))^(n_CEA_CD3)+1))   # Table S5 rule 47
    R_Tcell <- ((((((((((0*cell)/day)+((a_k_T1_death+a_k_C1_therapy)*x_V_T_C1))+((((((((k_C_T1*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*(1-H_TGF_CTL))*(1-H_PD1_C1))*(1-H_MDSC_C1)))+((((((k_C_BTcell*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T1))+((((((k_C_BTreg*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T0))+((a_k_T1_death+a_k_C2_therapy)*x_V_T_C2))+((((((((k_C_T1*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*(1-H_TGF_CTL))*(1-H_PD1_C1))*(1-H_MDSC_C1)))+((((((k_C_BTcell*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T1))+((((((k_C_BTreg*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T0))   # Table S5 rule 5

    # ---------- reaction rates (Table S6) ----------
    v1 <- (k_cell_clear*x_V_T_C_x)   # R1 Clearance of dead cancer cells from tumor
    v2 <- (k_cell_clear*x_V_T_T1_exh)   # R2 Clearance of exhausted CD8 T cells from tumor
    v3 <- (k_cell_clear*x_V_T_Th_exh)   # R3 Clearance of exhausted CD4 T cells from tumor
    v4 <- ((k_C1_growth*x_V_T_C1)*(1-(C_total/C_max)))   # R4 Cancer cell growth (Logistic model based on Komarova and r
    v5 <- (a_k_C1_death*x_V_T_C1)   # R5 Cancer cell death
    v6 <- ((k_C2_growth*x_V_T_C2)*(1-(C_total/C_max)))   # R6 Cancer cell growth (Logistic model based on Komarova and r
    v7 <- (a_k_C2_death*x_V_T_C2)   # R7 Cancer cell death
    v8 <- (Q_nT0_thym/div_T0)   # R8 Thymic output of naive T cell to blood
    v9 <- (((k_nT0_pro/div_T0)*x_V_P_nT0)/((K_nT0_pro/div_T0)+x_V_P_nT0))   # R9 Naive T cell proliferation in the peripheral compartment
    v10 <- (((k_nT0_pro/div_T0)*x_V_LN_nT0)/((K_nT0_pro/div_T0)+x_V_LN_nT0))   # R10 Naive T cell proliferation in the TDLN compartment
    v11 <- (k_nT0_death*x_V_P_nT0)   # R11 Naive T cell death in the peripheral compartment
    v12 <- (k_nT0_death*x_V_C_nT0)   # R12 Naive T cell death in the central compartment
    v13 <- (k_nT0_death*x_V_LN_nT0)   # R13 Naive T cell death in the TDLN compartment
    v14 <- (k_nT0_death*x_V_T_nT0)   # R14 Naive T cell death in the tumor compartment
    v15 <- (q_nT0_P_in*x_V_C_nT0)   # R15 Naive T cell entry into the peripheral compartment
    v16 <- (q_nT0_P_out*x_V_P_nT0)   # R16 Naive T cell exit from the peripheral compartment
    v17 <- (q_nT0_LN_in*x_V_C_nT0)   # R17 Naive T cell entry into the lymph node
    v18 <- (q_nT0_LN_out*x_V_LN_nT0)   # R18 Naive T cell exit from the lymph node
    v19 <- (((k_T0_act*H_APC)*H_P0)*x_V_LN_nT0)   # R19 Naive T cell activation
    v20 <- ((((k_T0_act*H_APC)*H_P0)*x_V_LN_nT0)*n_T0_clones)   # R20 Naive T cell activation
    v21 <- ((k_T0_pro/N_aT0)*x_V_LN_aT0)   # R21 aT0 cell proliferation
    v22 <- (((k_T0_pro/N_aT0)*(2)^(N_aT0))*x_V_LN_aT0)   # R22 aT0 cell proliferation
    v23 <- (k_T0_death*x_V_C_T0)   # R23 T cell death in the central compartment
    v24 <- (k_T0_death*x_V_P_T0)   # R24 T cell death in the peripheral compartment
    v25 <- (k_T0_death*x_V_LN_T0)   # R25 T cell death in the lymph node compartment
    v26 <- (k_T0_death*x_V_T_T0)   # R26 T cell death in the tumor compartment
    v27 <- (q_T0_P_in*x_V_C_T0)   # R27 T cell transport into the peripheral compartment
    v28 <- (q_T0_P_out*x_V_P_T0)   # R28 T cell transport out of the peripheral compartment
    v29 <- (((q_T0_T_in*vol_V_T)*x_V_C_T0)*((C_total)^(2)/((C_total)^(2)+Kc_rec)))   # R29 T cell transport into the tumor compartment
    v30 <- (q_T0_LN_out*x_V_LN_T0)   # R30 T cell transport out of the lymph node compartment
    v31 <- ((k_IL2_deg*x_V_LN_IL2)*m_V_LN)   # R31 IL2 degradation
    v32 <- (((k_IL2_cons*x_V_LN_T1)*x_V_LN_IL2)/(IL2_50+x_V_LN_IL2))   # R32 IL2 consumption by T cells
    v33 <- (((k_IL2_cons*x_V_LN_T0)*x_V_LN_IL2)/(IL2_50_Treg+x_V_LN_IL2))   # R33 IL2 consumption by Tregs
    v34 <- (Q_nT1_thym/div_T1)   # R34 Thymic output of naive T cell to blood
    v35 <- (((k_nT1_pro/div_T1)*x_V_P_nT1)/((K_nT1_pro/div_T1)+x_V_P_nT1))   # R35 Naive T cell proliferation in the peripheral compartment
    v36 <- (((k_nT1_pro/div_T1)*x_V_LN_nT1)/((K_nT1_pro/div_T1)+x_V_LN_nT1))   # R36 Naive T cell proliferation in the TDLN compartment
    v37 <- (k_nT1_death*x_V_P_nT1)   # R37 Naive T cell death in the peripheral compartment
    v38 <- (k_nT1_death*x_V_C_nT1)   # R38 Naive T cell death in the central compartment
    v39 <- (k_nT1_death*x_V_LN_nT1)   # R39 Naive T cell death in the TDLN compartment
    v40 <- (k_nT1_death*x_V_T_nT1)   # R40 Naive T cell death in the tumor compartment
    v41 <- (q_nT1_P_in*x_V_C_nT1)   # R41 Naive T cell entry into the peripheral compartment
    v42 <- (q_nT1_P_out*x_V_P_nT1)   # R42 Naive T cell exit from the peripheral compartment
    v43 <- (q_nT1_LN_in*x_V_C_nT1)   # R43 Naive T cell entry into the lymph node
    v44 <- (q_nT1_LN_out*x_V_LN_nT1)   # R44 Naive T cell exit from the lymph node
    v45 <- (((k_T1_act*H_mAPC)*H_P1)*x_V_LN_nT1)   # R45 Naive T cell activation
    v46 <- ((((k_T1_act*H_mAPC)*H_P1)*x_V_LN_nT1)*n_T1_clones)   # R46 Naive T cell activation
    v47 <- ((k_T1_pro/N_aT)*x_V_LN_aT1)   # R47 aT1 cell proliferation
    v48 <- (((k_T1_pro/N_aT)*(2)^(N_aT))*x_V_LN_aT1)   # R48 aT1 cell proliferation
    v49 <- (a_k_T1_death*x_V_C_T1)   # R49 T cell death in the central compartment
    v50 <- (a_k_T1_death*x_V_P_T1)   # R50 T cell death in the peripheral compartment
    v51 <- (a_k_T1_death*x_V_LN_T1)   # R51 T cell death in the lymph node compartment
    v52 <- (a_k_T1_death*x_V_T_T1)   # R52 T cell death in the tumor compartment
    v53 <- (((k_Treg*x_V_T_T1)*Tregs_)/((x_V_T_T1+Tregs_)+cell))   # R53 T cell death from Tregs
    v54 <- ((((k_Treg_TCE*x_V_T_T1)*Tregs_)/((x_V_T_T1+Tregs_)+cell))*H_CEA_C1_T0)   # R54 T cell death from Tregs
    v55 <- ((((k_T1*x_V_T_T1)*C_total)/((C_total+x_V_T_T1)+cell))*H_PD1_C1)   # R55 T cell death from cancer
    v56 <- (q_T1_P_in*x_V_C_T1)   # R56 T cell transport into the peripheral compartment
    v57 <- (q_T1_P_out*x_V_P_T1)   # R57 T cell transport out of the peripheral compartment
    v58 <- (((q_T1_T_in*vol_V_T)*x_V_C_T1)*((C_total)^(2)/((C_total)^(2)+Kc_rec)))   # R58 T cell transport into the tumor compartment
    v59 <- (q_T1_LN_out*x_V_LN_T1)   # R59 T cell transport out of the lymph node compartment
    v60 <- (k_IL2_sec*x_V_LN_aT1)   # R60 IL2 secretion from activated T cells
    v61 <- (((((((((k_C_T1*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*(1-H_TGF_CTL))*(1-H_PD1_C1))+((((((k_C_BTcell*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T1))+(((((((k_C_BTreg*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T0)*(1-H_MDSC_C1)))   # R61 Cancer cell killing by T cells
    v62 <- (((((((((k_C_T1*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*(1-H_TGF_CTL))*(1-H_PD1_C1))+((((((k_C_BTcell*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T1))+(((((((k_C_BTreg*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T0)*(1-H_MDSC_C1)))   # R62 Cancer cell killing by T cells
    v63 <- (k_APC_death*((APC0_T*vol_V_T)-x_V_T_APC))   # R63 APC recruitment/death in the tumour
    v64 <- (k_APC_death*((APC0_LN*m_V_LN)-x_V_LN_APC))   # R64 APC recruitment/death in LN
    v65 <- (((k_APC_mat*x_V_T_c)/(x_V_T_c+c50))*x_V_T_APC)   # R65 APC maturation in the tumour
    v66 <- (k_APC_mig*x_V_T_mAPC)   # R66 APC migration to the lymph node
    v67 <- (k_mAPC_death*x_V_T_mAPC)   # R67 mAPC death in the tumour
    v68 <- (k_mAPC_death*x_V_LN_mAPC)   # R68 mAPC death in the lymph node
    v69 <- (k_c*(c0-x_V_T_c))   # R69 Baseline cytokine secretion/degradation
    v70 <- (R_Tcell*DAMPs)   # R70 Cytokine release in response to the tumour
    v71 <- (((kout*x_A_e_M1)*m_A_e)-((kin*x_A_s_M1)*m_A_s))   # R71 MHC translocation
    v72 <- (n_T0_clones*(((((((((P0_C1*(a_k_C1_death+a_k_C1_therapy))*x_V_T_C1)+((((((((P0_C1*k_C_T1)*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*(1-H_TGF_CTL))*(1-H_PD1_C1)))+(((((((P0_C1*k_C_BTcell)*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T1))+((((((((P0_C1*k_C_BTreg)*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T0)*(1-H_MDSC_C1)))+((P0_C2*(a_k_C2_death+a_k_C2_therapy))*x_V_T_C2))+((((((((P0_C2*k_C_T1)*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*(1-H_TGF_CTL))*(1-H_PD1_C1)))+(((((((P0_C2*k_C_BTcell)*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T1))+((((((((P0_C2*k_C_BTreg)*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T0)*(1-H_MDSC_C1))))   # R72 Antigen deposition from dying cancer cells
    v73 <- ((k_xP0_deg*x_V_T_P0)*vol_V_T)   # R73 Free antigen degradation
    v74 <- (((k_P0_up*x_V_T_APC)*x_V_T_P0)*vol_V_T)   # R74 Antigen uptake by mature antigen presenting cells
    v75 <- (((k_P0_up*cell)*x_V_T_P0)*m_V_e)   # R75 Antigen uptake by mature antigen presenting cells
    v76 <- ((k_P0_deg*x_V_e_P0)*m_V_e)   # R76 Antigen degradation in APC endosomes
    v77 <- ((k_p0_deg*x_V_e_p0)*m_V_e)   # R77 Epitope degradation in APC endosomes
    v78 <- (((k_P0_on*x_V_e_p0)*x_A_e_M1)*m_A_e)   # R78 Antigen-MHC binding in endosome
    v79 <- (((k_P0_d1*k_P0_on)*x_A_e_M1p0)*m_A_e)   # R79 Antigen-MHC unbinding in endosome
    v80 <- (((k_P0_d1*k_P0_on)*x_A_s_M1p0)*m_A_s)   # R80 Antigen-MHC unbinding on APC surface
    v81 <- ((kout*x_A_e_M1p0)*m_A_e)   # R81 Antigen-MHC translocation
    v81b <- ((kout*x_A_e_M1p1)*m_A_e)   # R81b Antigen-MHC translocation (P1 mirror of R81; omitted from 
    v82 <- (n_T1_clones*(((((((((P1_C1*(a_k_C1_death+a_k_C1_therapy))*x_V_T_C1)+((((((((P1_C1*k_C_T1)*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*(1-H_TGF_CTL))*(1-H_PD1_C1)))+(((((((P1_C1*k_C_BTcell)*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T1))+((((((((P1_C1*k_C_BTreg)*x_V_T_T1)*x_V_T_C1)/(((1.2*x_V_T_C1)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T0)*(1-H_MDSC_C1)))+((P1_C2*(a_k_C2_death+a_k_C2_therapy))*x_V_T_C2))+((((((((P1_C2*k_C_T1)*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*(1-H_TGF_CTL))*(1-H_PD1_C1)))+(((((((P1_C2*k_C_BTcell)*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T1))+((((((((P1_C2*k_C_BTreg)*x_V_T_T1)*x_V_T_C2)/(((1.2*x_V_T_C2)+x_V_T_T1)+cell))*x_V_T_T1)/((x_V_T_T1+(11*Tregs_))+cell))*H_CEA_C1_T0)*(1-H_MDSC_C1))))   # R82 Antigen deposition from dying cancer cells
    v83 <- ((k_xP1_deg*x_V_T_P1)*vol_V_T)   # R83 Free antigen degradation
    v84 <- (((k_P1_up*x_V_T_APC)*x_V_T_P1)*vol_V_T)   # R84 Antigen uptake by mature antigen presenting cells
    v85 <- (((k_P1_up*cell)*x_V_T_P1)*m_V_e)   # R85 Antigen uptake by mature antigen presenting cells
    v86 <- ((k_P1_deg*x_V_e_P1)*m_V_e)   # R86 Antigen degradation in APC endosomes
    v87 <- ((k_p1_deg*x_V_e_p1)*m_V_e)   # R87 Epitope degradation in APC endosomes
    v88 <- (((k_P1_on*x_V_e_p1)*x_A_e_M1)*m_A_e)   # R88 Antigen-MHC binding in endosome
    v89 <- (((k_P1_d1*k_P1_on)*x_A_e_M1p1)*m_A_e)   # R89 Antigen-MHC unbinding in endosome
    v90 <- (((k_P1_d1*k_P1_on)*x_A_s_M1p1)*m_A_s)   # R90 Antigen-MHC unbinding on APC surface
    v92 <- (q_P_atezo*((x_V_C_atezo/gamma_C_atezo)-(x_V_P_atezo/gamma_P_atezo)))   # R92 atezo diffusive transport to peripheral compartment
    v93 <- (q_T_atezo*((x_V_C_atezo/gamma_C_atezo)-(x_V_T_atezo/gamma_T_atezo)))   # R93 atezo diffusive transport to tumor compartment
    v94 <- (q_LN_atezo*((x_V_C_atezo/gamma_C_atezo)-(x_V_LN_atezo/gamma_LN_atezo)))   # R94 atezo diffusive transport to lymph node compartment
    v95 <- ((q_LD_atezo*x_V_T_atezo)/gamma_T_atezo)   # R95 atezo convective transport from tumor to lymph node
    v96 <- ((q_LD_atezo*x_V_LN_atezo)/gamma_LN_atezo)   # R96 atezo convective transport from lymph node to central
    v97 <- (k_cl_atezo*x_V_C_atezo)   # R97 Drug clearance from central compartment
    v98 <- (((k_out_PDL1*x_V_T_IFNg)/(x_V_T_IFNg+IFNg_50_ind))*(1-(x_syn_T_C1_PDL1_total/((C1_PDL1_base*r_PDL1_IFNg)/A_cell))))   # R98 Translocation of PDL1 between cell surface and cytoplasm
    v99 <- ((((k_out_PDL1*r_PDL2C1)*x_V_T_IFNg)/(x_V_T_IFNg+IFNg_50_ind))*(1-(x_syn_T_C1_PDL2_total/(((C1_PDL1_base*r_PDL1_IFNg)/A_cell)*r_PDL2C1))))   # R99 Translocation of PDL2 between cell surface and cytoplasm
    v100 <- (k_in_PDL1*((C1_PDL1_base/A_cell)-x_syn_T_C1_PDL1_total))   # R100 Translocation of PDL1 between cell surface and cytoplasm
    v101 <- (k_in_PDL1*(((C1_PDL1_base/A_cell)*r_PDL2C1)-x_syn_T_C1_PDL2_total))   # R101 Translocation of PDL2 between cell surface and cytoplasm
    v102 <- ((((kon_PD1_PDL1*x_syn_T_C1_PD1)*x_syn_T_C1_PDL1)/NAVG_nmol)-(koff_PD1_PDL1*x_syn_T_C1_PD1_PDL1))   # R102 binding and unbinding of PD1 PDL1 in synapse
    v103 <- ((((kon_PD1_PDL2*x_syn_T_C1_PD1)*x_syn_T_C1_PDL2)/NAVG_nmol)-(koff_PD1_PDL2*x_syn_T_C1_PD1_PDL2))   # R103 binding and unbinding of PD1 PDL2 in synapse
    v104 <- (((2*kon_PDL1_atezo)*((x_syn_T_C1_PDL1*x_V_T_atezo)/gamma_T_atezo))-(koff_PDL1_atezo*x_syn_T_C1_PDL1_atezo))   # R104 binding and unbinding of PDL1 to atezo on C1 surface in sy
    v105 <- ((((Chi_PDL1_atezo*kon_PDL1_atezo)*(x_syn_T_C1_PDL1*x_syn_T_C1_PDL1_atezo))/NAVG_nmol)-((2*koff_PDL1_atezo)*x_syn_T_C1_PDL1_atezo_PDL1))   # R105 binding and unbinding of PDL1 to PDL1-atezo on C1 surface 
    v106 <- (((2*kon_PDL1_atezo)*((x_syn_T_C1_TPDL1*x_V_T_atezo)/gamma_T_atezo))-(koff_PDL1_atezo*x_syn_T_C1_TPDL1_atezo))   # R106 binding and unbinding of PDL1 to atezo on C1 surface in sy
    v107 <- ((((Chi_PDL1_atezo*kon_PDL1_atezo)*(x_syn_T_C1_TPDL1*x_syn_T_C1_TPDL1_atezo))/NAVG_nmol)-((2*koff_PDL1_atezo)*x_syn_T_C1_TPDL1_atezo_TPDL1))   # R107 binding and unbinding of PDL1 to PDL1-atezo on C1 surface 
    v108 <- (((k_out_PDL1*x_V_T_IFNg)/(x_V_T_IFNg+IFNg_50_ind))*(1-(x_syn_T_APC_PDL1_total/((APC_PDL1_base*r_PDL1_IFNg)/A_cell))))   # R108 Translocation of PDL1 between cell surface and cytoplasm
    v109 <- ((((k_out_PDL1*r_PDL2APC)*x_V_T_IFNg)/(x_V_T_IFNg+IFNg_50_ind))*(1-(x_syn_T_APC_PDL2_total/(((APC_PDL1_base*r_PDL1_IFNg)/A_cell)*r_PDL2APC))))   # R109 Translocation of PDL2 between cell surface and cytoplasm
    v110 <- (k_in_PDL1*((APC_PDL1_base/A_cell)-x_syn_T_APC_PDL1_total))   # R110 Translocation of PDL1 between cell surface and cytoplasm
    v111 <- (k_in_PDL1*(((APC_PDL1_base/A_cell)*r_PDL2APC)-x_syn_T_APC_PDL2_total))   # R111 Translocation of PDL2 between cell surface and cytoplasm
    v112 <- ((((kon_PD1_PDL1*x_syn_T_APC_PD1)*x_syn_T_APC_PDL1)/NAVG_nmol)-(koff_PD1_PDL1*x_syn_T_APC_PD1_PDL1))   # R112 binding and unbinding of PD1 PDL1 in synapse
    v113 <- ((((kon_PD1_PDL2*x_syn_T_APC_PD1)*x_syn_T_APC_PDL2)/NAVG_nmol)-(koff_PD1_PDL2*x_syn_T_APC_PD1_PDL2))   # R113 binding and unbinding of PD1 PDL2 in synapse
    v114 <- (((2*kon_PDL1_atezo)*((x_syn_T_APC_PDL1*x_V_LN_atezo)/gamma_LN_atezo))-(koff_PDL1_atezo*x_syn_T_APC_PDL1_atezo))   # R114 binding and unbinding of PDL1 to atezo on APC surface in s
    v115 <- ((((Chi_PDL1_atezo*kon_PDL1_atezo)*(x_syn_T_APC_PDL1*x_syn_T_APC_PDL1_atezo))/NAVG_nmol)-((2*koff_PDL1_atezo)*x_syn_T_APC_PDL1_atezo_PDL1))   # R115 binding and unbinding of PDL1 to PDL1-atezo on APC surface
    v116 <- (((2*kon_PDL1_atezo)*((x_syn_T_APC_TPDL1*x_V_LN_atezo)/gamma_LN_atezo))-(koff_PDL1_atezo*x_syn_T_APC_TPDL1_atezo))   # R116 binding and unbinding of PDL1 to atezo on APC surface in s
    v117 <- ((((Chi_PDL1_atezo*kon_PDL1_atezo)*(x_syn_T_APC_TPDL1*x_syn_T_APC_TPDL1_atezo))/NAVG_nmol)-((2*koff_PDL1_atezo)*x_syn_T_APC_TPDL1_atezo_TPDL1))   # R117 binding and unbinding of PDL1 to PDL1-atezo on APC surface
    v118 <- ((k_rec_MDSC*((MDSC_max*vol_V_T)-x_V_T_MDSC))*(x_V_T_CCL2/(EC50_CCL2_rec+x_V_T_CCL2)))   # R118 MDSC recruitment into the tumor compartment
    v119 <- (k_brec_MDSC*((MDSC_max*vol_V_T)-x_V_T_MDSC))   # R119 Baseline MDSC Migration into the tumor compartment
    v120 <- (kd_MDSC*x_V_T_MDSC)   # R120 MDSC death in the tumor compartment
    v121 <- (k_deg_CCL2*x_V_T_CCL2)   # R121 CCL2 degradation
    v122 <- (k_deg_NO*x_V_T_NO)   # R122 NO degradation
    v123 <- (k_deg_ArgI*x_V_T_ArgI)   # R123 ArgI degradation
    v124 <- (k_sec_CCL2*C_total)   # R124 CCL2 secretion by MDSCs and cancer cells
    v125 <- (k_sec_NO*x_V_T_MDSC)   # R125 NO secretion from MDSC
    v126 <- (k_sec_ArgI*x_V_T_MDSC)   # R126 ArgI secretion from MDSC
    v127 <- (((k_Th_act*H_APCh)*H_P1)*x_V_LN_nT0)   # R127 Naive T cell activation
    v128 <- ((((k_Th_act*H_APCh)*H_P1)*x_V_LN_nT0)*n_T1_clones)   # R128 Naive T cell activation
    v129 <- ((k_T0_pro/N_aTh)*x_V_LN_aTh)   # R129 aTh cell proliferation
    v130 <- (((k_T0_pro/N_aTh)*(2)^(N_aTh))*x_V_LN_aTh)   # R130 aTh cell proliferation
    v131 <- ((((k_reg*x_V_T_Th)*x_V_T_ArgI)/(EC50_ArgI_Treg+x_V_T_ArgI))*H_TGF_reg)   # R131 Differentiation between Treg and Th Cells
    v132 <- (k_T0_death*x_V_C_Th)   # R132 T cell death in the central compartment
    v133 <- (k_T0_death*x_V_P_Th)   # R133 T cell death in the peripheral compartment
    v134 <- (k_T0_death*x_V_LN_Th)   # R134 T cell death in the lymph node compartment
    v135 <- (k_T0_death*x_V_T_Th)   # R135 T cell death in the tumor compartment
    v136 <- (q_T0_P_in*x_V_C_Th)   # R136 T cell transport into the peripheral compartment
    v137 <- (q_T0_P_out*x_V_P_Th)   # R137 T cell transport out of the peripheral compartment
    v138 <- (((q_T0_T_in*vol_V_T)*x_V_C_Th)*((C_total)^(2)/((C_total)^(2)+Kc_rec)))   # R138 T cell transport into the tumor compartment
    v139 <- (q_T0_LN_out*x_V_LN_Th)   # R139 T cell transport out of the lymph node compartment
    v140 <- (k_IL2_sec*x_V_LN_aTh)   # R140 IL2 secretion from activated T cells
    v141 <- ((k_TGF_deg*(TGFbase-x_V_T_TGF))*vol_V_T)   # R141 TGFb secretion by cancer cells
    v142 <- (k_TGF_Tsec*x_V_T_T0)   # R142 TGF secretion from activated T cells in tumor
    v143 <- (k_IFNg_sec*x_V_T_Th)   # R143 IFNg secretion from T helper cells in tumor
    v144 <- (k_IFNg_deg*x_V_T_IFNg)   # R144 IFNg degradtion in tumor
    v145 <- (q_P_cibis*((x_V_C_cibis/gamma_C_cibis)-(x_V_P_cibis/gamma_P_cibis)))   # R145 cibis diffusive transport to peripheral compartment
    v146 <- (q_T_cibis*((x_V_C_cibis/gamma_C_cibis)-(x_V_T_cibis/gamma_T_cibis)))   # R146 cibis diffusive transport to tumor compartment
    v147 <- (q_LN_cibis*((x_V_C_cibis/gamma_C_cibis)-(x_V_LN_cibis/gamma_LN_cibis)))   # R147 cibis diffusive transport to lymph node compartment
    v148 <- ((q_LD_cibis*x_V_T_cibis)/gamma_T_cibis)   # R148 cibis convective transport from tumor to lymph node
    v149 <- ((q_LD_cibis*x_V_LN_cibis)/gamma_LN_cibis)   # R149 cibis convective transport from lymph node to central
    v150 <- (k_cl_cibis*x_V_C_cibis)   # R150 Drug clearance from central compartment
    v151 <- ((kon_CEA_cibis*(x_TCEsyn_T1_C1_CEA*x_V_T_cibis))-(koff_CEA_cibis*x_TCEsyn_T1_C1_CEA_cibis_CEA))   # R151 binding and unbinding of CEA to cibis on surface in synaps
    v152 <- ((((kon_CD3_cibis2/1e4)*(x_TCEsyn_T1_C1_CD3*x_TCEsyn_T1_C1_CEA_cibis_CEA))/NAVG_nmol)-(koff_CD3_cibis*x_TCEsyn_T1_C1_CEA_cibis_CEA_CD3))   # R152 binding and unbinding of CD3 to CEA_cibis on in synapse
    v153 <- ((kon_CD3_cibis*(x_TCEsyn_T1_C1_CD3*x_V_T_cibis))-(koff_CD3_cibis*x_TCEsyn_T1_C1_CD3_cibis))   # R153 binding and unbinding of CD3 to cibis on surface in synaps
    v154 <- (((((kon_CEA_cibis2/1e4)*x_TCEsyn_T1_C1_CD3_cibis)*x_TCEsyn_T1_C1_CEA)/NAVG_nmol)-(koff_CEA_cibis*x_TCEsyn_T1_C1_CEA_cibis_CEA_CD3))   # R154 binding and unbinding of CEA to CD3_cibis on in synapse
    v155 <- ((kon_CEA_cibis*(x_TCEsyn_T0_C1_CEA*x_V_T_cibis))-(koff_CEA_cibis*x_TCEsyn_T0_C1_CEA_cibis_CEA))   # R155 binding and unbinding of CEA to cibis on surface in synaps
    v156 <- ((((kon_CD3_cibis2/1e4)*(x_TCEsyn_T0_C1_CD3*x_TCEsyn_T0_C1_CEA_cibis_CEA))/NAVG_nmol)-(koff_CD3_cibis*x_TCEsyn_T0_C1_CEA_cibis_CEA_CD3))   # R156 binding and unbinding of CD3 to CEA_cibis on in synapse
    v157 <- ((kon_CD3_cibis*(x_TCEsyn_T0_C1_CD3*x_V_T_cibis))-(koff_CD3_cibis*x_TCEsyn_T0_C1_CD3_cibis))   # R157 binding and unbinding of CD3 to cibis on surface in synaps
    v158 <- (((((kon_CEA_cibis2/1e4)*x_TCEsyn_T0_C1_CD3_cibis)*x_TCEsyn_T0_C1_CEA)/NAVG_nmol)-(koff_CEA_cibis*x_TCEsyn_T0_C1_CEA_cibis_CEA_CD3))   # R158 binding and unbinding of CEA to CD3_cibis on in synapse

    # ---------- initial conditions (Table S3 + initialAssignment rules of Table S5) ----------
    q_V_C_nT0(0) <- 3706.89655172   # Table S3
    q_V_C_nT1(0) <- 2274.77477477   # Table S3
    q_V_P_nT0(0) <- 185344.827586   # Table S3
    q_V_P_nT1(0) <- 185344.8276   # Table S3
    q_V_T_C1(0) <- 1   # Table S3
    q_V_T_P0(0) <- 4.20455436307e-12   # Table S3
    q_V_T_P1(0) <- 4.20455436307e-12   # Table S3
    q_V_LN_nT0(0) <- 155.689655172   # Table S3
    q_V_LN_IL2(0) <- 1.11264739815e-12   # Table S3
    q_V_LN_nT1(0) <- 113.738738739   # Table S3
    q_V_e_P0(0) <- 4e-25   # Table S3
    q_V_e_p0(0) <- 4e-25   # Table S3
    q_V_e_P1(0) <- 4e-25   # Table S3
    q_V_e_p1(0) <- 4e-25   # Table S3
    q_A_e_M1(0) <- 32786.8852459   # Table S3
    q_A_e_M1p0(0) <- 1.5e-05   # Table S3
    q_A_e_M1p1(0) <- 1.5e-05   # Table S3
    q_A_s_M1(0) <- 0.0009   # Table S3
    q_A_s_M1p0(0) <- 0.0009   # Table S3
    q_A_s_M1p1(0) <- 0.0009   # Table S3
    q_syn_T_C1_PD1(0) <- ((T_PD1_total/A_Tcell))*vol_syn_T_C1   # Table S5 rule 16
    q_syn_T_C1_PDL1(0) <- ((C1_PDL1_base/A_cell))*vol_syn_T_C1   # Table S5 rule 20
    q_syn_T_C1_PDL2(0) <- (((C1_PDL1_base*r_PDL2C1)/A_cell))*vol_syn_T_C1   # Table S5 rule 21
    q_syn_T_C1_TPDL1(0) <- ((T_PDL1_total/A_Tcell))*vol_syn_T_C1   # Table S5 rule 19
    q_syn_T_APC_PD1(0) <- ((T_PD1_total/A_Tcell))*vol_syn_T_APC   # Table S5 rule 27
    q_syn_T_APC_PDL1(0) <- ((APC_PDL1_base/A_APC))*vol_syn_T_APC   # Table S5 rule 31
    q_syn_T_APC_PDL2(0) <- (((APC_PDL1_base*r_PDL2APC)/A_APC))*vol_syn_T_APC   # Table S5 rule 32
    q_syn_T_APC_TPDL1(0) <- ((T_PDL1_total/A_Tcell))*vol_syn_T_APC   # Table S5 rule 30
    q_TCEsyn_T1_C1_CEA(0) <- ((C1_CEA_total/SA_cell))*vol_TCEsyn_T1_C1   # Table S5 rule 43
    q_TCEsyn_T1_C1_CD3(0) <- ((T1_CD3_total/SA_Tcell))*vol_TCEsyn_T1_C1   # Table S5 rule 42
    q_TCEsyn_T0_C1_CEA(0) <- ((C1_CEA_total/SA_cell))*vol_TCEsyn_T0_C1   # Table S5 rule 46
    q_TCEsyn_T0_C1_CD3(0) <- ((T0_CD3_total/SA_Tcell))*vol_TCEsyn_T0_C1   # Table S5 rule 45

    # ---------- ODEs (amounts) ----------
    d/dt(q_V_C_nT0) <- v8-v12-v15+v16-v17+v18
    d/dt(q_V_C_T0) <- -v23-v27+v28-v29+v30
    d/dt(q_V_C_nT1) <- v34-v38-v41+v42-v43+v44
    d/dt(q_V_C_T1) <- -v49-v56+v57-v58+v59
    d/dt(q_V_C_atezo) <- -v92-v93-v94+v96*vol_V_T-v97
    d/dt(q_V_C_Th) <- -v132-v136+v137-v138+v139
    d/dt(q_V_C_cibis) <- -v145-v146*vol_V_T-v147+v149*vol_V_T-v150
    d/dt(q_V_P_nT0) <- v9-v11+v15-v16
    d/dt(q_V_P_T0) <- -v24+v27-v28
    d/dt(q_V_P_nT1) <- v35-v37+v41-v42
    d/dt(q_V_P_T1) <- -v50+v56-v57
    d/dt(q_V_P_atezo) <- v92
    d/dt(q_V_P_Th) <- -v133+v136-v137
    d/dt(q_V_P_cibis) <- v145
    d/dt(q_V_T_C_x) <- -v1+v5+v7+v61+v62
    d/dt(q_V_T_T1_exh) <- -v2+v52+v53+v54+v55
    d/dt(q_V_T_Th_exh) <- -v3+v135
    d/dt(q_V_T_C1) <- v4-v5-v61
    d/dt(q_V_T_C2) <- v6-v7-v62
    d/dt(q_V_T_nT0) <- -v14
    d/dt(q_V_T_T0) <- -v26+v29+v131
    d/dt(q_V_T_nT1) <- -v40
    d/dt(q_V_T_T1) <- -v52-v53-v54-v55+v58
    d/dt(q_V_T_APC) <- v63-v65
    d/dt(q_V_T_mAPC) <- v65-v66-v67
    d/dt(q_V_T_c) <- v69*vol_V_T+v70
    d/dt(q_V_T_P0) <- v72-v73-v74
    d/dt(q_V_T_P1) <- v82-v83-v84
    d/dt(q_V_T_atezo) <- v93-v95*vol_V_T
    d/dt(q_V_T_MDSC) <- v118+v119-v120
    d/dt(q_V_T_CCL2) <- -v121*vol_V_T+v124
    d/dt(q_V_T_NO) <- -v122*vol_V_T+v125
    d/dt(q_V_T_ArgI) <- -v123*vol_V_T+v126
    d/dt(q_V_T_Th) <- -v131-v135+v138
    d/dt(q_V_T_TGF) <- v141+v142
    d/dt(q_V_T_IFNg) <- v143-v144*vol_V_T
    d/dt(q_V_T_cibis) <- v146*vol_V_T-v148*vol_V_T
    d/dt(q_V_LN_nT0) <- v10-v13+v17-v18-v19-v127
    d/dt(q_V_LN_aT0) <- v20-v21
    d/dt(q_V_LN_T0) <- v22-v25-v30
    d/dt(q_V_LN_IL2) <- -v31-v32-v33+v60+v140
    d/dt(q_V_LN_nT1) <- v36-v39+v43-v44-v45
    d/dt(q_V_LN_aT1) <- v46-v47
    d/dt(q_V_LN_T1) <- v48-v51-v59
    d/dt(q_V_LN_APC) <- v64
    d/dt(q_V_LN_mAPC) <- v66-v68
    d/dt(q_V_LN_atezo) <- v94+v95*vol_V_T-v96*vol_V_T
    d/dt(q_V_LN_aTh) <- v128-v129
    d/dt(q_V_LN_Th) <- v130-v134-v139
    d/dt(q_V_LN_cibis) <- v147+v148*vol_V_T-v149*vol_V_T
    d/dt(q_V_e_P0) <- v75-v76
    d/dt(q_V_e_p0) <- v76-v77-v78/NAVG_nmol+v79/NAVG_nmol
    d/dt(q_V_e_P1) <- v85-v86
    d/dt(q_V_e_p1) <- v86-v87-v88/NAVG_nmol+v89/NAVG_nmol
    d/dt(q_A_e_M1) <- -v71-v78+v79-v88+v89
    d/dt(q_A_e_M1p0) <- v78-v79-v81
    d/dt(q_A_e_M1p1) <- v88-v89-v81b
    d/dt(q_A_s_M1) <- v71+v80+v90
    d/dt(q_A_s_M1p0) <- -v80+v81
    d/dt(q_A_s_M1p1) <- -v90+v81b
    d/dt(q_syn_T_C1_PD1_PDL1) <- v102*m_syn_T_C1
    d/dt(q_syn_T_C1_PD1_PDL2) <- v103*m_syn_T_C1
    d/dt(q_syn_T_C1_PD1) <- -v102*m_syn_T_C1-v103*m_syn_T_C1
    d/dt(q_syn_T_C1_PDL1) <- v98+v100*m_syn_T_C1-v102*m_syn_T_C1-v104*m_syn_T_C1-v105*m_syn_T_C1
    d/dt(q_syn_T_C1_PDL2) <- v99+v101*m_syn_T_C1-v103*m_syn_T_C1
    d/dt(q_syn_T_C1_PDL1_atezo) <- v104*m_syn_T_C1-v105*m_syn_T_C1
    d/dt(q_syn_T_C1_PDL1_atezo_PDL1) <- v105*m_syn_T_C1
    d/dt(q_syn_T_C1_TPDL1) <- -v106*m_syn_T_C1-v107*m_syn_T_C1
    d/dt(q_syn_T_C1_TPDL1_atezo) <- v106*m_syn_T_C1-v107*m_syn_T_C1
    d/dt(q_syn_T_C1_TPDL1_atezo_TPDL1) <- v107*m_syn_T_C1
    d/dt(q_syn_T_APC_PD1_PDL1) <- v112*m_syn_T_APC
    d/dt(q_syn_T_APC_PD1_PDL2) <- v113*m_syn_T_APC
    d/dt(q_syn_T_APC_PD1) <- -v112*m_syn_T_APC-v113*m_syn_T_APC
    d/dt(q_syn_T_APC_PDL1) <- v108+v110*m_syn_T_APC-v112*m_syn_T_APC-v114*m_syn_T_APC-v115*m_syn_T_APC
    d/dt(q_syn_T_APC_PDL2) <- v109+v111*m_syn_T_APC-v113*m_syn_T_APC
    d/dt(q_syn_T_APC_PDL1_atezo) <- v114*m_syn_T_APC-v115*m_syn_T_APC
    d/dt(q_syn_T_APC_PDL1_atezo_PDL1) <- v115*m_syn_T_APC
    d/dt(q_syn_T_APC_TPDL1) <- -v116*m_syn_T_APC-v117*m_syn_T_APC
    d/dt(q_syn_T_APC_TPDL1_atezo) <- v116*m_syn_T_APC-v117*m_syn_T_APC
    d/dt(q_syn_T_APC_TPDL1_atezo_TPDL1) <- v117*m_syn_T_APC
    d/dt(q_TCEsyn_T1_C1_CEA_cibis_CEA_CD3) <- v152*m_TCEsyn_T1_C1+v154*m_TCEsyn_T1_C1
    d/dt(q_TCEsyn_T1_C1_CEA_cibis_CEA) <- v151*m_TCEsyn_T1_C1-v152*m_TCEsyn_T1_C1
    d/dt(q_TCEsyn_T1_C1_CD3_cibis) <- v153*m_TCEsyn_T1_C1-v154*m_TCEsyn_T1_C1
    d/dt(q_TCEsyn_T1_C1_CEA) <- -v151*m_TCEsyn_T1_C1-v154*m_TCEsyn_T1_C1
    d/dt(q_TCEsyn_T1_C1_CD3) <- -v152*m_TCEsyn_T1_C1-v153*m_TCEsyn_T1_C1
    d/dt(q_TCEsyn_T0_C1_CEA_cibis_CEA_CD3) <- v156*m_TCEsyn_T0_C1+v158*m_TCEsyn_T0_C1
    d/dt(q_TCEsyn_T0_C1_CEA_cibis_CEA) <- v155*m_TCEsyn_T0_C1-v156*m_TCEsyn_T0_C1
    d/dt(q_TCEsyn_T0_C1_CD3_cibis) <- v157*m_TCEsyn_T0_C1-v158*m_TCEsyn_T0_C1
    d/dt(q_TCEsyn_T0_C1_CEA) <- -v155*m_TCEsyn_T0_C1-v158*m_TCEsyn_T0_C1
    d/dt(q_TCEsyn_T0_C1_CD3) <- -v156*m_TCEsyn_T0_C1-v157*m_TCEsyn_T0_C1
  })
}
