Fuhr_2022_felodipine <- function() {
  description <- paste(
    "Direct-effect pharmacodynamic model of felodipine on diastolic blood",
    "pressure (DBP) and heart rate (HR) in healthy and hypertensive adults,",
    "the PD layer of the Fuhr 2022 parent-metabolite PBPK/PD model. Each",
    "endpoint rides a cosinor circadian baseline (DBP: 24 h + 12 h harmonics",
    "after Chae et al.; HR: one 24 h harmonic after Lott et al.), scaled",
    "multiplicatively by the 24 h mean, from which felodipine subtracts a",
    "hyperbolic Emax effect (DBP) or to which it adds a sigmoid Emax effect",
    "(HR), both driven directly by the felodipine plasma concentration with",
    "no effect delay. Only this PD layer is reproduced here: the PBPK layer is",
    "a PK-Sim / MoBi whole-body model whose organ volumes, blood flows,",
    "partition coefficients and CYP3A4 expression profile are platform",
    "database outputs the paper does not print, so the felodipine plasma",
    "concentration is supplied by the user as the canonical driver covariate",
    "CEFFECT (umol/L) rather than generated by a PK model in this file. The",
    "24 h means, circadian phases and amplitudes are the cross-study summary",
    "values of Table 3; the paper re-optimised the means and phases for every",
    "simulated study (supplementary Table S5). No inter-individual",
    "variability and no residual-error model are reported, so both are zero.",
    sep = " "
  )
  reference <- paste(
    "Fuhr LM, Marok FZ, Mees M, Mahfoud F, Selzer D, Lehr T. (2022).",
    "A Physiologically Based Pharmacokinetic and Pharmacodynamic Model of the",
    "CYP3A4 Substrate Felodipine for Drug-Drug Interaction Modeling.",
    "Pharmaceutics 14(7):1474. doi:10.3390/pharmaceutics14071474.",
    "Circadian baseline structure and amplitudes from Chae D, Kim Y, Park K",
    "(diastolic blood pressure) and Lott D et al. (heart rate), as cited by",
    "Fuhr 2022 (references 28 and 29).",
    sep = " "
  )
  vignette <- "Fuhr_2022_felodipine"
  units <- list(
    time = "h",
    dosing = "(not applicable; felodipine plasma concentration is supplied as the CEFFECT covariate, not as a dose record)",
    concentration = "umol/L (felodipine plasma concentration via CEFFECT; dbp is in mmHg and hr in beats/min)"
  )

  covariateData <- list(
    CEFFECT = list(
      description = "Felodipine plasma concentration (umol/L), supplied as the direct driver of both Emax effects",
      units = "umol/L",
      type = "continuous",
      reference_category = NULL,
      notes = paste(
        "Member of the canonical PD-driver family CEFFECT; here the biophase is",
        "plasma itself, because Fuhr 2022 links both effects directly to the",
        "felodipine plasma concentration with no effect compartment or lag",
        "('a direct-effect Emax model without lag time', Methods 2.4) and",
        "states that plasma rather than heart concentrations were used",
        "(Discussion). EC50 is reported in umol/L (Table 3), so CEFFECT must be",
        "in umol/L: convert from ng/mL by dividing by the felodipine molecular",
        "weight 384.25 g/mol (Table 2), and from nmol/L by dividing by 1000.",
        "In the source study CEFFECT is the plasma profile predicted by the",
        "authors' PK-Sim / MoBi whole-body PBPK model (CYP3A4 Km 2.81 umol/L,",
        "kcat 250.44 1/min, fu 0.36 %, predicted oral bioavailability 13-18 %;",
        "Table 2 and Results 3.1); that model is not reproduced in this file",
        "and cannot be reproduced from the publication. Users supply CEFFECT",
        "from their own felodipine PK model or from observed plasma",
        "concentrations; set it to 0 for placebo / drug-free records."
      ),
      source_name = "C (Fuhr 2022 Equation 1 / supplementary Equation S20)"
    ),
    DIS_HYPERT = list(
      description = "Hypertensive-individual indicator (1 = hypertensive patient, 0 = healthy volunteer)",
      units = "(binary)",
      type = "binary",
      reference_category = "0 (healthy volunteer)",
      notes = paste(
        "Selects the 24 h mean diastolic blood pressure and heart rate: Table 3",
        "reports BPmean 70.4 mmHg and HRmean 62.2 bpm as the mean of the",
        "individually optimised values for healthy individuals and 91.9 mmHg",
        "and 66.4 bpm 'used for hypertensive individuals' (footnote b). The",
        "paper reports no other hypertension effect on the PD layer (Emax,",
        "EC50, Hill coefficient, amplitudes and phases are shared). The",
        "32 % mean reduction in CYP3A4 kcat that the paper applied to",
        "hypertensive individuals acts on the PBPK layer only and therefore",
        "enters this model solely through the user-supplied CEFFECT."
      ),
      source_name = "HT (Fuhr 2022 figure panels; 'hypertensive individuals' in Table 1 and Table 3)"
    )
  )

  population <- list(
    species = "human",
    n_subjects = NA_integer_,
    n_studies = 17L,
    age_range = "healthy volunteers mostly 20-40 years (some elderly cohorts, 70-83 years); hypertensive patients older (per-study means in supplementary Table S1)",
    weight_range = "per-study means approximately 60-77 kg in healthy volunteers (supplementary Table S1)",
    sex_female_pct = NA_real_,
    disease_state = "healthy volunteers and patients with essential hypertension (many hypertensive patients also received other antihypertensives such as beta-blockers and diuretics; supplementary Table S1 footnote c)",
    dose_range = "felodipine 1-3 mg intravenous and 0.83-40 mg oral (solution, immediate-release tablet, extended-release tablet), single and multiple doses",
    regions = "not reported (studies digitised from the published literature)",
    notes = paste(
      "The PD layer was built from 30 diastolic-blood-pressure-time profiles",
      "and 22 heart-rate-time profiles taken from 17 published clinical",
      "studies (Results 3.2; Table 1: 18 DBP and 18 HR profiles in healthy",
      "individuals, 12 DBP and 4 HR profiles in hypertensive individuals).",
      "The whole PBPK/PD model used 49 studies and 94 plasma",
      "concentration-time profiles. Data are digitised literature means, not",
      "individual data, so the total number of individuals and the sex split",
      "of the PD subset are not reported (most healthy-volunteer cohorts in",
      "supplementary Table S1 were all-male). Per-study demographics are in",
      "supplementary Table S1; per-study circadian parameters in Table S5."
    )
  )

  ini({
    # ------------------------------------------------------------------
    # Fuhr 2022 supplementary Section 1.6, Equations S16-S22:
    #
    #   circBP(t) = amp24 * cos(2*pi/24 * (t - phase24))
    #             + amp12 * cos(2*pi/12 * (t - phase12))             (S16)
    #   circHR(t) = ampHR * cos(2*pi/24 * (t - phaseHR))             (S18)
    #   E(t)      = Emax * C(t)^h / (EC50^h + C(t)^h)                (S20)
    #   BP(t)     = BPmean * (1 + circBP(t)) - E(t)                  (S21)
    #   HR(t)     = HRmean * (1 + circHR(t)) + E(t)                  (S22)
    #
    # Parameter values are Table 3 of the main paper (repeated in
    # supplementary Table S6). No standard errors, IIV or residual error
    # are reported for any of them.
    # ------------------------------------------------------------------

    # Diastolic blood pressure -------------------------------------------
    lemax_dbp <- log(56.18)
    label("Maximum felodipine-induced decrease in diastolic blood pressure Emax (mmHg)")
    # Table 3, DBP model, 'Emax' = 56.18 mmHg (optimised; Table S6 '(opt)')

    lec50_dbp <- log(0.04)
    label("Felodipine plasma concentration for half-maximal DBP decrease EC50 (umol/L)")
    # Table 3, DBP model, 'EC50' = 0.04 umol/L (optimised); restated as
    # '40 nmol/L' in the Discussion. Table 3 lists no Hill coefficient for
    # the DBP model, so the DBP Emax function is hyperbolic (h = 1).

    amp24_dbp <- fixed(0.0214)
    label("Fractional amplitude of the 24 h DBP cosinor harmonic (fraction of the 24 h mean)")
    # Table 3, 'amp24' = 2.14 % (literature value from Chae et al.,
    # reference 28; Table S6 '(lit)'), hence fixed. Entered as the fraction
    # 0.0214 because Equation S17 multiplies BPmean by (1 + circBP).

    amp12_dbp <- fixed(0.0593)
    label("Fractional amplitude of the 12 h DBP cosinor harmonic (fraction of the 24 h mean)")
    # Table 3, 'amp12' = 5.93 % (literature value from Chae et al.,
    # reference 28), hence fixed.

    phase24_dbp <- 5.28
    label("Phase of the 24 h DBP cosinor harmonic (h of simulation time)")
    # Table 3, 'phase24' = 5.28 (SD 2.10) h, the mean of the per-study
    # optimised values listed in supplementary Table S5 (footnote a).

    phase12_dbp <- 0.16
    label("Phase of the 12 h DBP cosinor harmonic (h of simulation time)")
    # Table 3, 'phase12' = 0.16 (SD 2.10) h, mean of the per-study values
    # (footnote a). The 5.12 h interval to phase24 is the one identified by
    # Chae et al. and was held constant for every study (Section 1.6).

    le0_dbp <- log(70.4)
    label("24 h mean diastolic blood pressure BPmean in healthy individuals (mmHg)")
    # Table 3, 'BPmean' = 70.4 (SD 6.76) mmHg, mean of the per-study
    # optimised values for healthy individuals (footnote a).

    e_hypert_e0_dbp <- log(91.9 / 70.4)
    label("Log-ratio of the hypertensive to the healthy 24 h mean DBP (unitless)")
    # Table 3, 'BPmean' = 91.9 (SD 6.60) mmHg 'used for hypertensive
    # individuals' (footnote b) divided by the healthy 70.4 mmHg, so that
    # DIS_HYPERT = 1 reproduces 91.9 mmHg exactly.

    # Heart rate -----------------------------------------------------------
    lemax_hr <- log(39.71)
    label("Maximum felodipine-induced increase in heart rate Emax (beats/min)")
    # Table 3, HR model, 'Emax' = 39.71 bpm (optimised)

    lec50_hr <- log(0.05)
    label("Felodipine plasma concentration for half-maximal HR increase EC50 (umol/L)")
    # Table 3, HR model, 'EC50' = 0.05 umol/L (optimised)

    lhill_hr <- log(1.40)
    label("Hill coefficient of the HR Emax function (unitless)")
    # Table 3, HR model, 'h' = 1.40 (optimised)

    amp_hr <- fixed(0.063)
    label("Fractional amplitude of the 24 h HR cosinor harmonic (fraction of the 24 h mean)")
    # Table 3, HR 'amp' = 6.3 % (literature value from Lott et al.,
    # reference 29), hence fixed.

    phase_hr <- 11.8
    label("Phase of the 24 h HR cosinor harmonic (h of simulation time)")
    # Table 3, HR 'phase' = 11.8 (SD 5.13) h, mean of the per-study values
    # (footnote a); the literature value 9.2 h of Lott et al. was not used.

    le0_hr <- log(62.2)
    label("24 h mean heart rate HRmean in healthy individuals (beats/min)")
    # Table 3, 'HRmean' = 62.2 (SD 4.21) bpm, mean of the per-study values
    # for healthy individuals (footnote a).

    e_hypert_e0_hr <- log(66.4 / 62.2)
    label("Log-ratio of the hypertensive to the healthy 24 h mean HR (unitless)")
    # Table 3, 'HRmean' = 66.4 (SD 3.32) bpm 'used for hypertensive
    # individuals' (footnote b) divided by the healthy 62.2 bpm.

    # Residual error -------------------------------------------------------
    addSd_dbp <- fixed(0)
    label("Additive residual SD on diastolic blood pressure (mmHg; ZERO - no residual-error model is reported)")
    addSd_hr <- fixed(0)
    label("Additive residual SD on heart rate (beats/min; ZERO - no residual-error model is reported)")
  })

  model({
    # 1. Felodipine plasma concentration (umol/L) for this record, supplied
    #    through the CEFFECT covariate; the effect is direct (no effect
    #    compartment, no lag; Methods 2.4).
    conc <- CEFFECT

    # 2. Typical-value PD parameters (no IIV is reported). The 24 h means
    #    switch between the healthy and hypertensive Table 3 values.
    emax_dbp <- exp(lemax_dbp)
    ec50_dbp <- exp(lec50_dbp)
    e0_dbp <- exp(le0_dbp + e_hypert_e0_dbp * DIS_HYPERT)
    emax_hr <- exp(lemax_hr)
    ec50_hr <- exp(lec50_hr)
    hill_hr <- exp(lhill_hr)
    e0_hr <- exp(le0_hr + e_hypert_e0_hr * DIS_HYPERT)

    # 3. Circadian rhythms, supplementary Equations S16 and S18. `time` is
    #    the simulation clock in hours; Fuhr 2022 optimised the phases
    #    against each study's own simulation time, so the phases are
    #    relative to the simulation origin, not to midnight.
    circ_dbp <- amp24_dbp * cos(2 * pi / 24 * (time - phase24_dbp)) +
      amp12_dbp * cos(2 * pi / 12 * (time - phase12_dbp))
    circ_hr <- amp_hr * cos(2 * pi / 24 * (time - phase_hr))

    # 4. Direct Emax effects, supplementary Equation S20 (h = 1 for DBP,
    #    which has no Hill coefficient in Table 3).
    eff_dbp <- emax_dbp * conc / (ec50_dbp + conc)
    eff_hr <- emax_hr * conc^hill_hr / (ec50_hr^hill_hr + conc^hill_hr)

    # 5. Outputs, supplementary Equations S21 and S22.
    dbp <- e0_dbp * (1 + circ_dbp) - eff_dbp
    hr <- e0_hr * (1 + circ_hr) + eff_hr

    # 6. Observation. Residual SDs are fixed at zero because the source
    #    reports no residual-error model.
    dbp ~ add(addSd_dbp)
    hr ~ add(addSd_hr)
  })
}
