Gong_2023_pemigatinib_creatinine <- function() {
  description <- paste(
    "Exposure-response Emax model relating steady-state pemigatinib",
    "exposure to the percentage change from baseline in serum creatinine",
    "concentration, in 300 patients receiving pemigatinib monotherapy",
    "across FIGHT-101, FIGHT-102, and FIGHT-202 (Gong 2023). Pemigatinib",
    "inhibits the renal transporters OCT2 (IC50 0.075 uM) and MATE1",
    "(IC50 1.1 uM), which mediate active tubular secretion of creatinine;",
    "the resulting rise in serum creatinine is exposure-dependent and",
    "reversible rather than a marker of renal injury. The model is a",
    "direct-effect Emax function of the per-subject steady-state AUC over",
    "the 24 h dosing interval:",
    "pct change = Emax * AUC_PEMI / (EC50 + AUC_PEMI), with",
    "Emax = 43.4% and EC50 = 2595 h*nM. It carries no ODE state -- the",
    "exposure metric AUC_PEMI is supplied as a static covariate derived",
    "from the companion population PK model",
    "(see modellib('Gong_2023_pemigatinib')), mirroring the authors'",
    "workflow of simulating a dense steady-state post hoc profile in",
    "NONMEM, deriving AUCss noncompartmentally, and regressing the",
    "biomarker on it in SAS. Evaluating the model at the paper's own",
    "mean steady-state AUC of 2850 h*nM for 13.5 mg once daily, and",
    "dose-scaling that value, reproduces the four published predictions",
    "of 14.2%, 18.3%, 22.7%, and 26.9% at 6, 9, 13.5, and 20 mg to three",
    "significant figures.",
    sep = " "
  )
  reference <- paste(
    "Gong X, Akil A, Ndi A, Ji T, Liu X, Lovern M, Chen X. (2023).",
    "Population pharmacokinetic and exposure-response analyses of",
    "pemigatinib in patients with advanced solid tumors including",
    "cholangiocarcinoma.",
    "CPT Pharmacometrics Syst Pharmacol 12(11):1784-1794.",
    "doi:10.1002/psp4.13064.",
    "Parameter estimates are Table S2 of Appendix S1 (Supporting",
    "Information). Exposure covariate AUC_PEMI is generated by the",
    "companion population PK model; see",
    "modellib('Gong_2023_pemigatinib')."
  )
  vignette <- "Gong_2023_pemigatinib"
  # The single output is an algebraic percentage-change endpoint, not a drug
  # concentration and not an ODE state, so it has no canonical compartment
  # name. Declared here so checkModelConventions() treats it as a documented
  # paper-mechanistic output rather than a naming deviation.
  paper_specific_compartments <- c("creatPctChange")
  units    <- list(time = "h", dosing = "mg", concentration = "nM")

  covariateData <- list(
    AUC_PEMI = list(
      description        = "Per-subject steady-state pemigatinib AUC over the 24 h dosing interval",
      units              = "h*nM",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Static (time-fixed) drug-exposure covariate. Gong 2023 Methods",
        "'Exposure-response evaluation': NONMEM 7.5 was used to simulate a",
        "dense steady-state post hoc concentration-time profile for each",
        "patient using the updated population PK model, and AUCss was",
        "derived from it by noncompartmental methods; the exposure-response",
        "regressions were then run in SAS 9.4 on those per-subject AUCss",
        "values. Reference values from the paper: the mean AUCss at the",
        "13.5 mg once-daily dose is 2850 h*nM (Results, 'Exposure-response",
        "analysis of efficacy'); the observed AUCss quartile boundaries in",
        "the CCA efficacy population were 817, 1828, 2351, 3104, and",
        "8446 h*nM (Figure 3b). Set AUC_PEMI = 0 to recover the untreated",
        "condition, where the Emax term vanishes and the predicted change",
        "from baseline is zero."
      ),
      source_name        = "AUCss"
    )
  )

  population <- list(
    species       = "human",
    n_subjects    = 300,
    n_studies     = 3,
    disease_state = paste(
      "Patients with advanced malignancies receiving pemigatinib",
      "monotherapy, pooled across FIGHT-101, FIGHT-102, and FIGHT-202."
    ),
    dose_range    = "1-20 mg orally once daily (continuous and 2-weeks-on / 1-week-off regimens)",
    endpoint      = paste(
      "Percentage change from baseline in serum creatinine concentration.",
      "Serum creatinine was measured as part of a comprehensive serum",
      "chemistry assessment in FIGHT-101, FIGHT-102, and FIGHT-202",
      "(Gong 2023 Methods, 'Studies and end points')."
    ),
    notes         = paste(
      "The same 300-patient monotherapy pool was used for the companion",
      "serum-phosphate exposure-response analysis. Gong 2023 Discussion",
      "attributes the creatinine rise to reversible inhibition of the",
      "OCT2 / MATE renal secretion pathway rather than to a change in",
      "glomerular filtration."
    )
  )

  ini({
    # ---------------------------------------------------------------------
    # Gong 2023 Table S2 (Appendix S1), 'Serum creatinine concentration'
    # block. The paper describes a "three-parameter maximum-exposure
    # (Emax) nonlinear model" for the serum-chemistry endpoints; for
    # creatinine only two parameters are reported (Emax and EC50), the
    # third parameter in the phosphate model being a baseline-covariate
    # coefficient that has no creatinine counterpart in Table S2.
    # ---------------------------------------------------------------------
    lemax <- log(43.4) ; label("Maximum percentage change from baseline in serum creatinine (%)")                    # Gong 2023 Table S2: Emax 43.4 %, approximate SE 6.15, 95% CL 31.3-55.5
    lec50 <- log(2595) ; label("Steady-state pemigatinib AUC producing half-maximal creatinine change (h*nM)")       # Gong 2023 Table S2: EC50 2595 h*nM, approximate SE 793, 95% CL 1035-4154

    # ---------------------------------------------------------------------
    # Residual error. Gong 2023 Figure 4 plots simulated 5th and 95th
    # percentiles around the mean creatinine curve, so the fitted model
    # did carry a residual-variability term, but neither Table S2 nor the
    # main text reports its magnitude. Per the standing convention for
    # unreported variability with structural values present, it is
    # encoded as fixed(0) rather than invented, and the gap is recorded
    # in the vignette's Assumptions and deviations section. The model as
    # shipped is therefore a typical-value (deterministic) predictor.
    # ---------------------------------------------------------------------
    addSd_creatPctChange <- fixed(0) ; label("Additive residual SD on percentage creatinine change (%) -- not reported by the source")   # Gong 2023: magnitude not reported in Table S2 or main text; see vignette Errata
  })

  model({
    # -------------------------------------------------------------------
    # Direct-effect Emax on the static steady-state exposure metric
    # (Gong 2023 Methods, 'Exposure-response evaluation'). No ODE state:
    # the response is an algebraic function of AUC_PEMI, exactly as the
    # authors fitted it. Setting AUC_PEMI = 0 gives a predicted change of
    # zero (the untreated condition).
    # -------------------------------------------------------------------
    emax <- exp(lemax)
    ec50 <- exp(lec50)

    creatPctChange <- emax * AUC_PEMI / (ec50 + AUC_PEMI)

    creatPctChange ~ add(addSd_creatPctChange)
  })
}
