Kay_2018_dapivirine_pbpk <- function() {
  description <- paste(
    "PBPK (vaginal route, semi-physiological; original implementation in",
    "MATLAB SimBiology). Dapivirine (DPV) delivered vaginally as either a",
    "25 mg silicone intravaginal ring (Ring-004) or a 1.25 mg quick-dissolve",
    "film, from Kay et al. 2018. Thirteen mass-balance states: a dosage-form",
    "depot, the vaginal luminal fluid, vaginal epithelium and vaginal stroma",
    "tissue each carried as an un-ionised and an ionised species, the stromal",
    "blood pool, and a systemic circulation of venous blood, arterial blood,",
    "lungs, liver and a lumped rest-of-body. Un-ionised drug moves passively",
    "between lumen, epithelium, stroma and stromal blood; ionised drug moves",
    "only inward by active transport. Ionisation rates come from the",
    "Henderson-Hasselbalch equation at a luminal pH of 4.4 and a tissue pH of",
    "7.0 with a DPV pKa of 5.8, so the luminal fluid holds mostly un-ionised",
    "and the tissues mostly ionised drug. Elimination is hepatic only. Drug",
    "release is the one formulation-dependent part: the ring releases",
    "first-order at a rate that decays exponentially from the moment that",
    "particular ring is inserted, the film dissolves first-order with a 10 min",
    "half-life, and the luminal-fluid-to-epithelium rate constant is about",
    "50-fold larger for the film than for the ring. The binary covariate",
    "FORM_DPV_FILM selects between the two. STATE VARIABLES ARE",
    "CONCENTRATIONS (mg/L), not amounts, everywhere except the depot",
    "(mg) -- the source equations are written in concentration form and the",
    "partition-coefficient terms are only dimensionally coherent that way.",
    "Deterministic typical-value model (no IIV, no residual error):",
    "population variability was generated by Monte Carlo sampling of the",
    "coefficients of variation in Tables 1 and 2, not by estimated random",
    "effects."
  )
  reference <- paste(
    "Kay K, Shah DK, Rohan L, Bies R. (2018). Physiologically-based",
    "pharmacokinetic model of vaginally administered dapivirine ring and film",
    "formulations. Br J Clin Pharmacol 84(9):1950-1969.",
    "doi:10.1111/bcp.13625. PMCID PMC6089833.",
    "Structure from Supporting Information Equations S1-S19 (file",
    "BCP-84-1950-s004.docx) and main-text Equations 1-9; physiological",
    "parameters from Table 1; pharmacokinetic parameters from Table 2;",
    "reproduction targets from Tables 3-5 and Figure 4."
  )
  vignette <- "Kay_2018_dapivirine"

  units <- list(
    time = "h",
    dosing = "mg",
    concentration = "mg/L",
    amount = "mg"
  )

  # Non-canonical states. The vaginal luminal fluid, epithelium, stroma tissue
  # and stromal blood have no canonical compartment names -- this is the first
  # vaginal-route model in the library -- and neither does the un-ionised /
  # ionised species split, which the source carries as separate ODE states
  # because only the ionised species is actively transported inward. Declared
  # paper-specific rather than registered as canonicals; promoting the four
  # vaginal-anatomy names (alongside the registered route-specific mucosal
  # entries nasal_respiratory and buccal_submucosa) is the natural follow-up if
  # a second vaginal-route model arrives.
  paper_specific_compartments <- c(
    "vaginal_lumen",
    "ion_vaginal_lumen",
    "vaginal_epithelium",
    "ion_vaginal_epithelium",
    "vaginal_stroma",
    "ion_vaginal_stroma",
    "vaginal_stroma_blood"
  )

  covariateData <- list(
    FORM_DPV_FILM = list(
      description = paste(
        "1 = the dose record is a quick-dissolve vaginal film, 0 = the dose",
        "record is a Ring-004 intravaginal ring. Selects the drug-release law",
        "and the luminal-fluid-to-epithelium transfer rate constant."
      ),
      units = "(binary)",
      type = "binary",
      reference_category = "0 (Ring-004 intravaginal ring)",
      notes = paste(
        "Load-bearing on model structure, not only on parameter values: the",
        "ring releases at an exponentially decaying first-order rate keyed to",
        "its own insertion time while the film dissolves at a constant",
        "first-order rate, and k_lumen_epi differs about 50-fold between them",
        "(Kay 2018 section 'Film-dependent parameters'). Also gates the",
        "bioavailability term -- see lfdepot. Not a data column in the source:",
        "Kay 2018 ran the two formulations as separate SimBiology models."
      ),
      source_name = NA_character_
    )
  )

  compartmentData <- list(
    # The dosage form itself: the ring's undissolved silicone-matrix load or
    # the film's undissolved solid. Carried as an AMOUNT (mg), unlike every
    # other state.
    depot = list(analyte = "dapivirine", units = "mg", specimen = "administration site", verified = TRUE),
    # Cervicovaginal (luminal) fluid. The specimen vocabulary has no vaginal
    # fluid entry; "epithelial lining fluid" is the closest available term and
    # is literally what this matrix is -- the fluid lining the vaginal
    # epithelium, sampled in the source studies as a swab or lavage.
    vaginal_lumen = list(
      analyte = "dapivirine (un-ionised)",
      units = "mg/L",
      specimen = "epithelial lining fluid",
      verified = TRUE
    ),
    ion_vaginal_lumen = list(
      analyte = "dapivirine (ionised)",
      units = "mg/L",
      specimen = "epithelial lining fluid",
      verified = TRUE
    ),
    vaginal_epithelium = list(
      analyte = "dapivirine (un-ionised)",
      units = "mg/L",
      specimen = "tissue",
      verified = TRUE
    ),
    ion_vaginal_epithelium = list(
      analyte = "dapivirine (ionised)",
      units = "mg/L",
      specimen = "tissue",
      verified = TRUE
    ),
    vaginal_stroma = list(analyte = "dapivirine (un-ionised)", units = "mg/L", specimen = "tissue", verified = TRUE),
    ion_vaginal_stroma = list(analyte = "dapivirine (ionised)", units = "mg/L", specimen = "tissue", verified = TRUE),
    # The vascular pools are read as plasma: every partition coefficient in
    # Table 2 is a tissue-to-PLASMA ratio, and the source compares the venous
    # state directly against measured plasma concentrations.
    vaginal_stroma_blood = list(analyte = "dapivirine", units = "mg/L", specimen = "plasma", verified = TRUE),
    venous = list(analyte = "dapivirine", units = "mg/L", specimen = "plasma", verified = TRUE),
    arterial = list(analyte = "dapivirine", units = "mg/L", specimen = "plasma", verified = TRUE),
    lung = list(analyte = "dapivirine", units = "mg/L", specimen = "tissue", verified = TRUE),
    liver = list(analyte = "dapivirine", units = "mg/L", specimen = "tissue", verified = TRUE),
    other = list(analyte = "dapivirine", units = "mg/L", specimen = "tissue", verified = TRUE)
  )

  population <- list(
    species = "human",
    n_subjects = 79,
    n_studies = 3,
    sex_female_pct = 100,
    disease_state = "healthy, non-pregnant women (HIV pre-exposure prophylaxis)",
    dose_range = paste(
      "25 mg Ring-004 intravaginal ring worn 21-35 days per ring (one, two or",
      "three consecutive rings); 1.25 mg quick-dissolve vaginal film once daily"
    ),
    regions = "sub-Saharan Africa (ring studies), United States (film study)",
    notes = paste(
      "The model was not fitted to individual data -- it was built from",
      "literature physiology and calibrated against published summary",
      "profiles. Model-building ring data: Nel et al. [21], 48 women",
      "randomised to two multi-ring regimens (group A, two rings over 56 days;",
      "group B, three rings over 57 days). Film data: the FAME 02 phase I",
      "trial [30], 15 women given seven daily DPV films. External validation:",
      "Nel et al. [23], 16 women randomised 1:1 to a single active or placebo",
      "ring for 28 days. Physiological parameters describe a typical 70 kg",
      "woman at rest (Table 1); vaginal surface area is the 87.46 cm2 mean of",
      "62 vinyl polysiloxane vaginal casts, and vaginal stromal blood flow is",
      "derived from nine women with normal pregnancies, which the authors",
      "flag as likely an overestimate for non-pregnant women."
    )
  )

  ini({
    # ---- Compartment volumes (Table 1) -------------------------------------
    v_lumen <- fixed(0.0005); label("Volume of the vaginal luminal fluid (L)") # Table 1, Vlumen = 0.0005 (CV 71 percent)
    v_epithelium <- fixed(0.077); label("Volume of the vaginal epithelium (L)") # Table 1, VVE = 0.077, from cell diameter x surface area x layers
    v_stroma <- fixed(1.078); label("Volume of the vaginal stroma tissue (L)") # Table 1, VVS,t = 1.078 = 0.077 x 14 (stroma is ~14x thicker than epithelium)
    v_stroma_blood <- fixed(0.108); label("Volume of blood in the vaginal stroma (L)") # Table 1, VVS,b = 0.108 = 2 percent of 5.4 L total blood volume
    v_lung <- fixed(1.2); label("Volume of the lungs (L)") # Table 1, VL = 1.2
    v_liver <- fixed(1.7); label("Volume of the liver (L)") # Table 1, VH = 1.7
    v_other <- fixed(60.5); label("Volume of the lumped rest-of-body compartment (L)") # Table 1, VB = 60.5, inferred from 70 kg and the other volumes
    v_venous <- fixed(3.546); label("Volume of venous blood (L)") # Table 1, Vv = 3.546
    v_arterial <- fixed(1.746); label("Volume of arterial blood (L)") # Table 1, VA = 1.746

    # ---- Blood flow rates (Table 1) ----------------------------------------
    # The lungs sit in series and receive the whole cardiac output, so
    # q_cardiac = q_stroma + q_liver + q_other exactly (14.3 + 98.8 + 180.9).
    q_cardiac <- fixed(294.0); label("Total cardiac output (L/h)") # Table 1, QCO = 294.0 = 70 beats/min x 70 mL/beat (CV 30 percent)
    q_stroma <- fixed(14.3); label("Blood flow to the vaginal stroma (L/h)") # Table 1, QVS = 14.3, median of the uterine vein and artery flows of Issa et al. [45]
    q_liver <- fixed(98.8); label("Blood flow to the liver (L/h)") # Table 1, QH = 98.8
    q_other <- fixed(180.9); label("Blood flow to the lumped rest-of-body compartment (L/h)") # Table 1, QB = 180.9 = QCO - QH - QVS

    # ---- Drug release from the dosage form (Table 2) -----------------------
    # The ring rate constant already carries the 30 percent bioavailability
    # assumption: it is back-solved so that only 1.2 mg of the 25 mg load
    # leaves the ring over 28 days rather than the 4 mg observed in vitro.
    k_depot_lumen_ring <- fixed(7.32e-5); label("Initial ring-to-luminal-fluid release rate constant (1/h)") # Table 2, ka = -ln(23.8/25)/28/24 = 7.32e-5
    k_ring_decay <- fixed(1.2e-3); label("Exponential decay rate of the ring release rate constant (1/h)") # Table 2, ka_exp = 1.2e-3 (CV 10 percent); main-text Eq. 9
    k_depot_lumen_film <- fixed(4.16); label("Film-to-luminal-fluid release rate constant (1/h)") # Table 2, kF,L = 4.16 = ln(2)/(10/60), a 10 min film dissolution half-life [46]
    lfdepot <- fixed(log(0.30)); label("Bioavailability of vaginally administered dapivirine (fraction)") # Table 2, F = 30 percent (sampled U(25, 35) percent); applied to the FILM dose only -- see model()

    # ---- Drug movement through the vaginal tissues (Table 2) ---------------
    # Table 2 of the source transposes the Description labels of the next two
    # rows against their Abbreviation column ("Ring:" is printed beside
    # kL,E_film). The abbreviations are the correct reading: 0.058 is cited to
    # Nel et al. [23], the 12 h luminal half-life measured after RING removal
    # (ln(2)/12 = 0.0578), and 2.773 = ln(2)/0.25 is the ~50-fold larger FILM
    # value the text derives. See the vignette Errata.
    k_lumen_epi_ring <- fixed(0.058); label("Luminal fluid to epithelium transfer rate constant, ring (1/h)") # Table 2, kL,E_ring = 0.058 = ln(2)/12 h [23]
    k_lumen_epi_film <- fixed(2.773); label("Luminal fluid to epithelium transfer rate constant, film (1/h)") # Table 2, kL,E_film = 2.773 = ln(2)/0.25 h
    k_epi_lumen <- fixed(0); label("Epithelium to luminal fluid transfer rate constant (1/h)") # Table 2, kE,L = 0 (no back-transfer into the lumen)
    k_epi_stroma <- fixed(6.79e-3); label("Epithelium to stroma passive transfer rate constant (1/h)") # Table 2, kE,S = 6.79e-3, from Franz-cell epithelial permeability [46]
    k_epi_stroma_active <- fixed(0.5); label("Epithelium to stroma active transfer rate constant for ionised drug (1/h)") # Table 2, kE,S_active = 0.5
    k_stroma_epi <- fixed(0); label("Stroma to epithelium passive transfer rate constant (1/h)") # Table 2, kS,E = 0
    k_stroma_blood <- fixed(0.122); label("Stroma tissue to stromal blood passive transfer rate constant (1/h)") # Table 2, kST,SB = 0.122
    k_stroma_blood_active <- fixed(0.5); label("Stroma tissue to stromal blood active transfer rate constant for ionised drug (1/h)") # Table 2, kST,SB_active = 0.5
    k_blood_stroma <- fixed(0.01); label("Stromal blood to stroma tissue passive transfer rate constant (1/h)") # Table 2, kSB,ST = 0.01

    # ---- Ionisation (Table 2, Henderson-Hasselbalch) -----------------------
    # DPV pKa 5.8; luminal pH 4.4 gives a base:acid ratio of 0.04:1 and tissue
    # pH 7.0 gives 15.85:1.
    kion_lumen <- fixed(0.04); label("Ionisation rate constant in the luminal fluid (1/h)") # Table 2, ILumen = 0.04
    kion_epithelium <- fixed(15.85); label("Ionisation rate constant in the epithelium (1/h)") # Table 2, IVE = 15.85
    kion_stroma <- fixed(15.85); label("Ionisation rate constant in the stroma tissue (1/h)") # Table 2, IS = 15.85
    kunion <- fixed(1); label("Un-ionisation rate constant in every compartment (1/h)") # Table 2, UI = 1

    # ---- Tissue-to-plasma partition coefficients (Table 2) -----------------
    # Digitised from Figure 4b of Neves et al. [47], intravaginal DPV
    # nanoparticles in mice; the rest-of-body value was calibrated instead.
    lkp_stroma <- fixed(log(6)); label("Log vaginal-stroma-to-plasma partition coefficient (unitless)") # Table 2, PVS = 6
    lkp_liver <- fixed(log(4.1)); label("Log liver-to-plasma partition coefficient (unitless)") # Table 2, PH = 4.1
    lkp_lung <- fixed(log(0.18)); label("Log lung-to-plasma partition coefficient (unitless)") # Table 2, PL = 0.18, from an assumed below-limit-of-detection lung concentration
    lkp_other <- fixed(log(8)); label("Log rest-of-body-to-plasma partition coefficient (unitless)") # Table 2, PB = 8, calibrated to replicate the observed profiles

    # ---- Elimination (Table 2) ---------------------------------------------
    lcl <- fixed(log(4)); label("Log hepatic clearance of dapivirine (L/h)") # Table 2, CL = 4 (CV 10 percent), from a SimBiology parameter scan
  })

  model({
    # ---- 1. Derived terms --------------------------------------------------
    kp_stroma <- exp(lkp_stroma)
    kp_liver <- exp(lkp_liver)
    kp_lung <- exp(lkp_lung)
    kp_other <- exp(lkp_other)
    cl <- exp(lcl)

    # Formulation switch. The film's much larger release rate creates roughly a
    # 200-fold steeper lumen-to-epithelium concentration gradient than the
    # ring, which the source absorbs into a ~50-fold larger kL,E rather than
    # modelling the gradient explicitly.
    k_lumen_epi <- k_lumen_epi_ring * (1 - FORM_DPV_FILM) +
      k_lumen_epi_film * FORM_DPV_FILM

    # Release rate constant. Eq. 9: ka(t) = ka * exp(-ka_exp * t), where t runs
    # from the insertion of the CURRENT ring -- Eqs. S14-S18 restart the clock
    # for each ring in a multi-ring regimen, which tad(depot) reproduces
    # because every insertion is a dose record on the depot. Eq. 6 and Eq. S14
    # print this exponent without its minus sign; Eq. 9, the surrounding prose
    # ("decay exponentially") and the paper's own simulated exposures all
    # require the decaying form. See the vignette Errata.
    krel <- (1 - FORM_DPV_FILM) * k_depot_lumen_ring *
      exp(-k_ring_decay * tad(depot)) +
      FORM_DPV_FILM * k_depot_lumen_film
    rel <- krel * depot

    # ---- 2. ODE system -----------------------------------------------------
    # Eqs. S14-S19: drug leaving the dosage form. The depot holds an AMOUNT
    # (mg); every other state holds a CONCENTRATION (mg/L), so the release
    # flux is divided by the luminal volume on the way in.
    d/dt(depot) <- -rel

    # Eqs. S1, S2: vaginal luminal fluid.
    d/dt(vaginal_lumen) <-
      (rel -
        (k_lumen_epi * vaginal_lumen * v_lumen -
          k_epi_lumen * vaginal_epithelium * v_epithelium) -
        (kion_lumen * vaginal_lumen - kunion * ion_vaginal_lumen) * v_lumen) /
        v_lumen
    d/dt(ion_vaginal_lumen) <-
      kion_lumen * vaginal_lumen - kunion * ion_vaginal_lumen

    # Eqs. S3, S4: vaginal epithelium. Ionised drug leaves only by active
    # transport into the stroma.
    d/dt(vaginal_epithelium) <-
      ((k_lumen_epi * vaginal_lumen * v_lumen -
        k_epi_lumen * vaginal_epithelium * v_epithelium) -
        (k_epi_stroma * vaginal_epithelium * v_epithelium -
          k_stroma_epi * vaginal_stroma * v_stroma) -
        (kion_epithelium * vaginal_epithelium -
          kunion * ion_vaginal_epithelium) * v_epithelium) / v_epithelium
    d/dt(ion_vaginal_epithelium) <-
      (kion_epithelium * vaginal_epithelium -
        kunion * ion_vaginal_epithelium) -
        k_epi_stroma_active * ion_vaginal_epithelium

    # Eqs. S5, S6: vaginal stroma tissue.
    d/dt(vaginal_stroma) <-
      ((k_epi_stroma * vaginal_epithelium * v_epithelium -
        k_stroma_epi * vaginal_stroma * v_stroma) -
        (k_stroma_blood * vaginal_stroma -
          k_blood_stroma * kp_stroma * vaginal_stroma_blood) * v_stroma -
        (kion_stroma * vaginal_stroma - kunion * ion_vaginal_stroma) *
          v_stroma) / v_stroma
    d/dt(ion_vaginal_stroma) <-
      (kion_stroma * vaginal_stroma - kunion * ion_vaginal_stroma) +
        k_epi_stroma_active * ion_vaginal_epithelium * v_epithelium / v_stroma -
        k_stroma_blood_active * ion_vaginal_stroma

    # Eq. S7: blood perfusing the vaginal stroma; the only route by which
    # vaginally delivered drug reaches the systemic circulation.
    d/dt(vaginal_stroma_blood) <-
      ((k_stroma_blood * vaginal_stroma -
        k_blood_stroma * kp_stroma * vaginal_stroma_blood) * v_stroma -
        q_stroma * vaginal_stroma_blood + q_stroma * arterial +
        k_stroma_blood_active * ion_vaginal_stroma * v_stroma) / v_stroma_blood

    # Eqs. S8, S9: venous and arterial blood pools.
    d/dt(venous) <-
      (q_stroma * vaginal_stroma_blood - q_cardiac * venous +
        q_other * other / kp_other + q_liver * liver / kp_liver) / v_venous
    d/dt(arterial) <-
      (q_cardiac * lung / kp_lung - q_stroma * arterial -
        q_other * arterial - q_liver * arterial) / v_arterial

    # Eqs. S10-S12: perfusion-limited tissues. The lungs sit in series and see
    # the whole cardiac output; the liver carries the only elimination term
    # (Eq. S13).
    d/dt(lung) <- (q_cardiac * venous - q_cardiac * lung / kp_lung) / v_lung
    d/dt(liver) <-
      (q_liver * arterial - q_liver * liver / kp_liver -
        cl * liver / kp_liver) / v_liver
    d/dt(other) <- (q_other * arterial - q_other * other / kp_other) / v_other

    # ---- 3. Bioavailability ------------------------------------------------
    # The 30 percent bioavailability assumption enters the two formulations
    # differently in the source. For the ring it is already inside
    # k_depot_lumen_ring, which was back-solved on the reduced 1.2 mg release,
    # so the ring dose is the full 25 mg load and F is 1. For the film it is a
    # dose reduction: 1.25 mg x 0.30 = 0.375 mg available.
    f(depot) <- 1 - FORM_DPV_FILM * (1 - exp(lfdepot))

    # ---- 4. Observations ---------------------------------------------------
    # Every measured matrix is a TOTAL (un-ionised + ionised) concentration.
    Cc <- venous
    Cfluid <- vaginal_lumen + ion_vaginal_lumen
    Cepithelium <- vaginal_epithelium + ion_vaginal_epithelium
    Cstroma <- vaginal_stroma + ion_vaginal_stroma
    Cstromablood <- vaginal_stroma_blood
  })
}
