Knebel_2012_istradefylline_offtime <- function() {
  description <- paste0(
    "Population exposure-response model for the percentage of awake time ",
    "spent in the OFF state in adults with Parkinson disease on ",
    "levodopa/carbidopa with motor response complications, treated with ",
    "adjunctive oral istradefylline (KW-6002, a selective adenosine A2A ",
    "receptor antagonist). Knebel 2012 Table II 'Final Model' full ",
    "covariate model. Percentage OFF time is the sum of two additive ",
    "components: a disease-progression/placebo-response (DP-PR) term that ",
    "is an Emax function of time in the study proportional to the ",
    "individual baseline percentage OFF time E0, and an istradefylline ",
    "effect that is an Emax function of the individual predicted ",
    "istradefylline AUC at steady state. There is no PK layer in this ",
    "model: exposure enters as the time-fixed AUC_ISTRA data covariate ",
    "(ng*hr/mL), which the source paper generated from a companion ",
    "population PK model (Knebel 2012 reference 6). E0, the maximum DP-PR ",
    "effect and the maximum istradefylline effect each carry a power-model ",
    "covariate set (UPDRS subscale 2 score, time since onset of motor ",
    "complications, baseline OFF time, and four concomitant-medication ",
    "indicators). Between-subject variability is additive on the linear ",
    "scale of E0, EmaxP and EmaxI, with E0 and EmaxP correlated. Residual ",
    "error is combined exponential-plus-additive on the percentage scale. ",
    "Companion models from the same paper cover the dyskinesia, dizziness ",
    "and nausea adverse-event endpoints."
  )
  reference <- paste(
    "Knebel W, Rao N, Uchimura T, Mori A, Fisher J, Gastonguay MR, Chaikin P.",
    "Population pharmacokinetic-pharmacodynamic analysis of istradefylline",
    "in patients with Parkinson disease.",
    "J Clin Pharmacol. 2012;52(10):1468-1481.",
    "doi:10.1177/0091270011420566.",
    "The individual istradefylline AUC at steady state that drives this",
    "model was generated by the upstream population PK model of",
    "Knebel W, Rao N, Uchimura T, et al., Population pharmacokinetic",
    "analysis of istradefylline in healthy subjects and in patients with",
    "Parkinson's disease, J Clin Pharmacol (published online ahead of",
    "print 3 March 2010; Knebel 2012 reference 6). That PK model is not",
    "part of this file and is not currently in nlmixr2lib; AUC_ISTRA must",
    "be supplied as a data covariate.",
    sep = " "
  )
  vignette <- "Knebel_2012_istradefylline"

  # The source paper places the between-subject random effects ADDITIVELY on
  # the linear scale of E0, EmaxP and EmaxI (Knebel 2012 equations for E0i,
  # EmaxPi and EmaxIi each end in "+ etaE0", "+ etaEmaxP", "+ etaEmaxI"), and
  # the reported variances confirm it: omega^2_E0 = 98.1 gives SD 9.90 on a
  # parameter whose typical value is 39.5 percent, and omega^2_EmaxP = 0.118
  # gives SD 0.343 on a typical value of -0.147, i.e. the random effect is
  # large enough to flip the sign -- impossible under a log-normal. EmaxP and
  # EmaxI are negative, so they cannot be log-transformed at all. The
  # canonical eta + l<param> pairing therefore does not apply; declare the
  # eta names as paper-specific so checkModelConventions() accepts them.
  # Same shape as Lee_2011_parkinson_progression.R (etaslope / etasymeff).
  # See references/parameter-names.md "Paper-specific etas".
  #
  # NOTE the Methods text says "All interindividual error terms were
  # described by an exponential error model, or log-normal parameter
  # distribution, unless otherwise indicated." The printed equations ARE the
  # indication otherwise, and the reported variance magnitudes agree with
  # them; per skill policy a text-versus-printed-equation conflict is
  # resolved in favour of the equation.
  paper_specific_etas <- c("etae0", "etaemax_dppr", "etaemax_drug")

  units <- list(
    time          = "day",
    dosing        = "(none; istradefylline exposure enters as the AUC_ISTRA covariate in ng*hr/mL, not as dosing events)",
    concentration = "(percent of awake time spent in the OFF state; observation pctofftime)"
  )

  covariateData <- list(
    AUC_ISTRA = list(
      description        = "Individual predicted istradefylline area under the plasma concentration-time curve at steady state over one dosing interval (24 h; istradefylline is dosed once daily).",
      units              = "ng*hr/mL",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Required input; time-fixed per subject. Set to 0 for placebo-treated subjects, which reduces the model to the DP-PR component alone. In the source paper this column is the individual empirical-Bayes predicted AUCss from the companion istradefylline population PK model (a 2-compartment model with first-order absorption; Knebel 2012 reference 6), not an observed AUC. That PK model is not currently in nlmixr2lib, so AUC_ISTRA must be supplied by the user. Anchors reported in Knebel 2012 for the dose-to-exposure mapping: a median exposure of 1690 ng*hr/mL corresponds to a 5 mg/d dose (Discussion), and approximately 2500 ng*hr/mL is the approximate median exposure at 10 mg/d (Results, Figure 2); the per-dose distribution is shown graphically in Figure 4, bottom panel. Smoking decreases AUCss by 38 percent and CYP3A4 inhibitors increase it by 35 percent (Discussion), effects that live in the PK model rather than in this PD model.",
      source_name        = "AUC"
    ),
    SCORE_UPDRS_II = list(
      description        = "Unified Parkinson's Disease Rating Scale (UPDRS) subscale 2 score (activities of daily living).",
      units              = "(UPDRS subscale 2 units, score 0-52)",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Time-fixed per subject. Enters E0, EmaxP and EmaxI as the normalised power term (SCORE_UPDRS_II / 17)^exponent; 17 is the cohort median (Knebel 2012 Table I: mean 17.6, median 17, range 1-40). The Knebel 2012 Table II row labels write the normaliser as 'UPDS/17'.",
      source_name        = "UPDS"
    ),
    T_MOTORCOMPL = list(
      description        = "Time since the onset of levodopa-related motor response complications.",
      units              = "year",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Time-fixed per subject. Enters E0, EmaxP and EmaxI as the normalised power term (T_MOTORCOMPL / 2.8)^exponent; 2.8 is the rounded cohort median (Knebel 2012 Table I: mean 3.74, median 2.76, range 0.04-29.9 years). Knebel 2012 retained this covariate in preference to time since diagnosis of Parkinson disease (TPD) and time since start of levodopa therapy (LYRS), which were collinear with it (pairwise correlation at least 0.64) and gave similar estimates but a higher objective function; TPD and LYRS are recorded in covariatesDataExcluded.",
      source_name        = "TOMC"
    ),
    OFFTIME_BL = list(
      description        = "Baseline daily OFF time, i.e. the absolute number of awake hours per day spent in the OFF state before treatment.",
      units              = "hr",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Time-fixed per subject. Enters EmaxP and EmaxI (but NOT E0) as the normalised power term (OFFTIME_BL / 6.3)^exponent; 6.3 is the cohort median (Knebel 2012 Table I: mean 6.39, median 6.3, range 0.25-17.8 hr). Distinct from the model's endpoint, which is the PERCENTAGE of awake time spent OFF rather than an absolute number of hours; the two are related through each subject's awake-time denominator, which Knebel 2012 does not report. Knebel 2012 Table II writes the normaliser as 'BOFF/6.3'.",
      source_name        = "BOFF"
    ),
    CONMED_DOPA_AGONIST = list(
      description        = "Concomitant dopamine-agonist use. 1 = the subject is receiving a dopamine agonist; 0 = not.",
      units              = "(binary)",
      type               = "binary",
      reference_category = "0 (no concomitant dopamine agonist).",
      notes              = "Time-fixed per subject. Applied multiplicatively as e_conmed_dopa_agonist_<param>^CONMED_DOPA_AGONIST, so the level 0 carries a unit multiplier and the reported theta is the level-1 multiplier. The most prevalent concomitant medication in the cohort at 63 percent of patients (Knebel 2012 Results). Agents pooled under this indicator in Knebel 2012 Table III: ropinirole, pramipexole, pergolide, bromocriptine.",
      source_name        = "DOPA"
    ),
    CONMED_COMTI = list(
      description        = "Concomitant catechol-O-methyl transferase (COMT) inhibitor use. 1 = the subject is receiving a COMT inhibitor; 0 = not.",
      units              = "(binary)",
      type               = "binary",
      reference_category = "0 (no concomitant COMT inhibitor).",
      notes              = "Time-fixed per subject. Applied multiplicatively as e_conmed_comti_<param>^CONMED_COMTI. Present in 36 percent of the cohort (Knebel 2012 Results). Agents pooled under this indicator in Knebel 2012 Table III: entacapone, tolcapone. Knebel 2012 flags this effect as internally inconsistent -- the estimate increases EmaxI in istradefylline-treated patients while decreasing EmaxP in placebo-treated patients -- and both estimates carry wide bootstrap intervals; see the validation vignette's Assumptions and deviations section.",
      source_name        = "COMT"
    ),
    CONMED_SELEGILINE = list(
      description        = "Concomitant selegiline use. 1 = the subject is receiving selegiline; 0 = not.",
      units              = "(binary)",
      type               = "binary",
      reference_category = "0 (no concomitant selegiline).",
      notes              = "Time-fixed per subject. Applied multiplicatively as e_conmed_selegiline_<param>^CONMED_SELEGILINE. Present in 13 percent of the cohort (Knebel 2012 Results), the least prevalent of the four concomitant-medication indicators, and correspondingly the least precisely estimated (the EmaxP bootstrap interval runs from 8.60e-11 to 1.72).",
      source_name        = "SELG"
    ),
    CONMED_AMANTADINE = list(
      description        = "Concomitant amantadine use. 1 = the subject is receiving amantadine; 0 = not.",
      units              = "(binary)",
      type               = "binary",
      reference_category = "0 (no concomitant amantadine).",
      notes              = "Time-fixed per subject. Applied multiplicatively as e_conmed_amantadine_<param>^CONMED_AMANTADINE. Present in 26 percent of the cohort (Knebel 2012 Results).",
      source_name        = "AMAT"
    )
  )

  # Covariates that Knebel 2012 collected and screened graphically but did
  # NOT retain in the final percentage OFF time model, so they are documented
  # rather than referenced in model(). TPD and LYRS were dropped for
  # collinearity with T_MOTORCOMPL (Results: "Due to the correlations among
  # TPD, TOMC, and LYRS, these covariates were tested in separate full
  # models. With similar parameter estimates and precision, the minimum
  # objective function was used to select TOMC"). Hoehn and Yahr stage was
  # tabulated but never entered any model and was missing in 37 percent of
  # patients.
  covariatesDataExcluded <- list(
    T_DIAG_PD = list(
      description = "Time since diagnosis of Parkinson disease.",
      units       = "year",
      type        = "continuous",
      notes       = "Knebel 2012 Table I: mean 9.17, median 8.32, range 0.09-36.8 years. Screened in a separate full covariate model but not retained; collinear with T_MOTORCOMPL and with time since start of levodopa therapy (pairwise correlation at least 0.64), and T_MOTORCOMPL gave the lower objective function. No point estimate is reported for its effect, so it cannot be encoded.",
      source_name = "TPD"
    ),
    T_LEVODOPA = list(
      description = "Time since the start of levodopa therapy.",
      units       = "year",
      type        = "continuous",
      notes       = "Knebel 2012 Table I: mean 7.54, median 6.79, range 0.45-31.8 years. Screened in a separate full covariate model but not retained, for the same collinearity reason as T_DIAG_PD. No point estimate is reported.",
      source_name = "LYRS"
    ),
    HY_STAGE = list(
      description = "Hoehn and Yahr stage of Parkinson disease severity.",
      units       = "(stage, 1-5)",
      type        = "categorical",
      notes       = "Knebel 2012 Results reports the distribution only (missing 37 percent; stage 2 in 17 percent, stage 2.5 in 18 percent, stage 3 in 22 percent, stage 4 in 6 percent). Not listed among the covariates evaluated in Table III and never entered any reported model, so no effect estimate exists.",
      source_name = "HY"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 1760L,
    n_studies      = 6L,
    age_range      = "not reported in Knebel 2012 (Table I tabulates only the five continuous covariates used in the PD analysis; study design and demographics are reported in the companion population PK paper, Knebel 2012 reference 6)",
    weight_range   = "not reported in Knebel 2012",
    sex_female_pct = NA_real_,
    race_ethnicity = "not reported in Knebel 2012",
    disease_state  = "Parkinson disease with levodopa-related motor response complications, on levodopa/carbidopa therapy. Baseline OFF time mean 6.39 hr/day (median 6.3, range 0.25-17.8); UPDRS subscale 2 (activities of daily living) score mean 17.6 (median 17, range 1-40); time since diagnosis of Parkinson disease mean 9.17 years; time since onset of motor complications mean 3.74 years; time since start of levodopa therapy mean 7.54 years (Knebel 2012 Table I). Hoehn and Yahr stage was missing for 37 percent of patients; among those recorded, stage 2 in 17 percent, 2.5 in 18 percent, 3 in 22 percent and 4 in 6 percent.",
    dose_range     = "Istradefylline 5 to 60 mg once daily across the six phase 2/3 studies, plus placebo. Knebel 2012 additionally simulated an 80 mg/d dose by linear extrapolation from the 60 mg results.",
    regions        = "not reported in Knebel 2012",
    notes          = "Percentage OFF time database: 1760 patients contributing 9108 measurements, of whom 1181 received istradefylline and 579 received placebo (Knebel 2012 Results). Concomitant anti-Parkinson medications: dopamine agonists 63 percent, COMT inhibitors 36 percent, amantadine 26 percent, selegiline 13 percent. Approximately 90 percent of patients were receiving a concomitant dopaminergic therapy in addition to levodopa (Knebel 2012 Discussion). The safety/tolerability database is a slightly different, larger cohort (1198 istradefylline plus 591 placebo patients) and is described in the three companion adverse-event model files. Model fit in NONMEM VI level 1.1 with FOCE-INT; a full covariate model was estimated without stepwise hypothesis testing, and precision was assessed by a stratified nonparametric bootstrap of 1000 replicates."
  )

  ini({
    # ================================================================
    # All values are Knebel 2012 Table II, "Final Model / Fixed effect
    # Parameter estimate" column (the full covariate model, which is the
    # paper's final percentage OFF time model). The base-model column of
    # the same table is NOT used here; per skill policy a
    # base-plus-final model-development paper contributes the final model
    # only. The base-model values (E0 37.9, EmaxP -0.152, ET50 19.3 d,
    # EmaxI -5.79, EC50 1690 ng*hr/mL) are the ones quoted in the
    # abstract and used for the paper's integrated dose-response
    # simulations in Table VI and Figures 5-6; the validation vignette
    # reproduces both sets.
    #
    # Sign conventions. E0 is a positive percentage. EmaxP and EmaxI are
    # both NEGATIVE because both effects reduce percentage OFF time: the
    # DP-PR term enters as E0 * (1 + EmaxP * time/(ET50 + time)), so a
    # negative EmaxP is a fractional REDUCTION of the individual
    # baseline, and the istradefylline term is added to it, so a negative
    # EmaxI is an absolute reduction in percentage points.
    # ================================================================

    # ---- Baseline percentage OFF time (E0 = theta1) -----------------
    # Kept on the LINEAR scale rather than log-transformed, even though
    # E0 is strictly positive, because the source paper's random effect
    # on it is additive on the linear scale (see the paper_specific_etas
    # note above). Writing `le0 <- log(39.5)` and then adding `etae0` to
    # `exp(le0)` would pair a log-transformed parameter with a
    # linear-scale eta, which the canonical eta + l<param> naming rule
    # cannot express without asserting something false about the
    # variability. Same reasoning and same resolution as
    # Lee_2011_parkinson_progression.R, whose beta / gamma parameters are
    # likewise left untransformed for this reason. `e0` is the registered
    # canonical bare PD-baseline parameter name.
    e0 <- 39.5
    label("Typical baseline percentage of awake time spent in the OFF state (percent)")
    # Table II Final Model: E0 = theta1 = 39.5 (2% SE), bootstrap 95% CI 38.3-40.7.

    e_score_updrs_ii_e0 <- 0.0998
    label("Power exponent on (SCORE_UPDRS_II / 17) for E0 (unitless)")
    # Table II Final Model: *(UPDS/17)^theta6 = 0.0998 (20% SE), bootstrap 95% CI 0.0583-0.140.

    e_t_motorcompl_e0 <- -0.0388
    label("Power exponent on (T_MOTORCOMPL / 2.8) for E0 (unitless)")
    # Table II Final Model: *(TOMC/2.8)^theta7 = -0.0388 (-23% SE), bootstrap 95% CI -0.0550 to -0.0226.

    e_conmed_dopa_agonist_e0 <- 0.974
    label("Multiplier on E0 for concomitant dopamine-agonist use (unitless)")
    # Table II Final Model: *theta8 DOPA[dopamine agonists yes] = 0.974 (2% SE), bootstrap 95% CI 0.941-1.01.

    e_conmed_comti_e0 <- 0.960
    label("Multiplier on E0 for concomitant COMT-inhibitor use (unitless)")
    # Table II Final Model: *theta9 COMT[COMT inhibitors yes] = 0.960 (2% SE), bootstrap 95% CI 0.929-0.993.

    e_conmed_selegiline_e0 <- 0.976
    label("Multiplier on E0 for concomitant selegiline use (unitless)")
    # Table II Final Model: *theta10 SELG[selegiline yes] = 0.976 (2% SE), bootstrap 95% CI 0.933-1.03.

    e_conmed_amantadine_e0 <- 0.967
    label("Multiplier on E0 for concomitant amantadine use (unitless)")
    # Table II Final Model: *theta11 AMAT[amantadine yes] = 0.967 (2% SE), bootstrap 95% CI 0.929-1.01.

    # ---- Maximum DP-PR effect (EmaxP = theta2) ----------------------
    # Fractional, relative to the individual E0. Negative: percentage OFF
    # time falls over study time in both arms. Knebel 2012 Results: "the
    # estimated population typical maximum decrease in percentage OFF
    # time due to DP-PR was estimated to be 15.2% of a patient's E0"
    # (that 0.152 is the base-model value; the final model gives 0.147).
    emax_dppr <- -0.147
    label("Maximum fractional disease-progression/placebo-response decrease in percentage OFF time, relative to E0 (fraction)")
    # Table II Final Model: EmaxP = theta2 = -0.147 (-20% SE), bootstrap 95% CI -0.204 to -0.0881.

    e_score_updrs_ii_emax_dppr <- 0.227
    label("Power exponent on (SCORE_UPDRS_II / 17) for EmaxP (unitless)")
    # Table II Final Model: *(UPDS/17)^theta12 = 0.227 (91% SE), bootstrap 95% CI -0.226 to 0.663.

    e_offtime_bl_emax_dppr <- -0.494
    label("Power exponent on (OFFTIME_BL / 6.3) for EmaxP (unitless)")
    # Table II Final Model: *(BOFF/6.3)^theta13 = -0.494 (-35% SE), bootstrap 95% CI -1.25 to -0.251.

    e_t_motorcompl_emax_dppr <- -0.0672
    label("Power exponent on (T_MOTORCOMPL / 2.8) for EmaxP (unitless)")
    # Table II Final Model: *(TOMC/2.8)^theta14 = -0.0672 (-197% SE), bootstrap 95% CI -0.277 to 0.241.

    e_conmed_dopa_agonist_emax_dppr <- 1.33
    label("Multiplier on EmaxP for concomitant dopamine-agonist use (unitless)")
    # Table II Final Model: *theta15 DOPA[dopamine agonists yes] = 1.33 (24% SE), bootstrap 95% CI 0.642-2.14.

    e_conmed_comti_emax_dppr <- 0.569
    label("Multiplier on EmaxP for concomitant COMT-inhibitor use (unitless)")
    # Table II Final Model: *theta16 COMT[COMT inhibitors yes] = 0.569 (31% SE), bootstrap 95% CI 0.237-1.11.

    e_conmed_selegiline_emax_dppr <- 0.961
    label("Multiplier on EmaxP for concomitant selegiline use (unitless)")
    # Table II Final Model: *theta17 SELG[selegiline yes] = 0.961 (36% SE), bootstrap 95% CI 8.60e-11 to 1.72.

    e_conmed_amantadine_emax_dppr <- 0.865
    label("Multiplier on EmaxP for concomitant amantadine use (unitless)")
    # Table II Final Model: *theta18 AMAT[amantadine yes] = 0.865 (26% SE), bootstrap 95% CI 0.408-1.33.

    # ---- Time to half the maximum DP-PR effect (ET50 = theta3) ------
    # No covariates and no IIV were placed on ET50 (Knebel 2012 prints
    # "ET50i = theta3ET50" with no covariate terms and no eta).
    let50 <- log(17.8)
    label("Time in the study reaching half of the maximum DP-PR effect (day)")
    # Table II Final Model: ET50(days) = theta3 = 17.8 (31% SE), bootstrap 95% CI 10.6-33.4.

    # ---- Maximum istradefylline effect (EmaxI = theta4) -------------
    # Absolute, in percentage points of OFF time, ADDED to the DP-PR
    # component. Negative: istradefylline reduces percentage OFF time.
    emax_drug <- -3.57
    label("Maximum absolute decrease in percentage OFF time due to istradefylline exposure (percentage points)")
    # Table II Final Model: EmaxI = theta4 = -3.57 (-24% SE), bootstrap 95% CI -5.37 to -1.41.

    e_score_updrs_ii_emax_drug <- -0.0767
    label("Power exponent on (SCORE_UPDRS_II / 17) for EmaxI (unitless)")
    # Table II Final Model: *(UPDS/17)^theta19 = -0.0767 (-255% SE), bootstrap 95% CI -0.500 to 0.361.

    e_offtime_bl_emax_drug <- -0.134
    label("Power exponent on (OFFTIME_BL / 6.3) for EmaxI (unitless)")
    # Table II Final Model: *(BOFF/6.3)^theta20 = -0.134 (-157% SE), bootstrap 95% CI -0.529 to 0.46.

    e_t_motorcompl_emax_drug <- 0.163
    label("Power exponent on (T_MOTORCOMPL / 2.8) for EmaxI (unitless)")
    # Table II Final Model: *(TOMC/2.8)^theta21 = 0.163 (87% SE), bootstrap 95% CI -0.108 to 0.521.

    e_conmed_dopa_agonist_emax_drug <- 1.24
    label("Multiplier on EmaxI for concomitant dopamine-agonist use (unitless)")
    # Table II Final Model: *theta22 DOPA[dopamine agonists yes] = 1.24 (26% SE), bootstrap 95% CI 0.792-4.23.

    e_conmed_comti_emax_drug <- 1.88
    label("Multiplier on EmaxI for concomitant COMT-inhibitor use (unitless)")
    # Table II Final Model: *theta23 COMT[COMT inhibitors yes] = 1.88 (27% SE), bootstrap 95% CI 1.06-3.61.

    e_conmed_selegiline_emax_drug <- 1.07
    label("Multiplier on EmaxI for concomitant selegiline use (unitless)")
    # Table II Final Model: *theta24 SELG[selegiline yes] = 1.07 (28% SE), bootstrap 95% CI 0.498-2.21.

    e_conmed_amantadine_emax_drug <- 1.11
    label("Multiplier on EmaxI for concomitant amantadine use (unitless)")
    # Table II Final Model: *theta25 AMAT[amantadine yes] = 1.11 (21% SE), bootstrap 95% CI 0.665-1.70.

    # ---- Exposure producing half the maximum istradefylline effect --
    # No covariates and no IIV (Knebel 2012 prints "EC50i = theta5EC50").
    lec50 <- log(1860)
    label("Istradefylline steady-state AUC producing half of the maximum istradefylline effect (ng*hr/mL)")
    # Table II Final Model: EC50(ng*hr/mL) = theta5 = 1860 (44% SE), bootstrap 95% CI 640-4670. The least precisely estimated structural parameter in both the base and the final model.

    # ================================================================
    # Between-subject variability. ADDITIVE on the linear scale of E0,
    # EmaxP and EmaxI (see the paper_specific_etas note above). Table II
    # reports each entry as a VARIANCE and helpfully prints the implied
    # SD alongside, which confirms the reading:
    #   omega^2_E0    = 98.1  -> SD = sqrt(98.1)  = 9.905  (Table: 9.90)
    #   omega^2_EmaxP = 0.118 -> SD = sqrt(0.118) = 0.3435 (Table: 0.343)
    #   omega^2_EmaxI = 14.2  -> SD = sqrt(14.2)  = 3.768  (Table: 3.77)
    # The E0-EmaxP covariance is reported as a CORRELATION r = 0.0120, so
    # the covariance element nlmixr2 needs is
    #   cov = r * SD_E0 * SD_EmaxP = 0.0120 * 9.905 * 0.3435 = 0.04083.
    # Knebel 2012 notes the bootstrap 95% CI for this correlation spans
    # zero (-0.545 to 0.405), i.e. the correlation is not distinguishable
    # from independence. EmaxI carries no covariance term with the other
    # two, so it is a separate diagonal entry; its own variance is also
    # imprecise (118% SE, bootstrap 95% CI 3.34e-09 to 48.9).
    # ================================================================
    etae0 + etaemax_dppr ~ c(
      98.1,
      0.04083, 0.118
    )
    # Table II Final Model Interindividual Variance: omega^2_E0 = 98.1 (7% SE) SD = 9.90, bootstrap 95% CI 83.9-111; COV_E0-EmaxP (463% SE) r = 0.0120, bootstrap 95% CI -0.545 to 0.405; omega^2_EmaxP = 0.118 (13% SE) SD = 0.343, bootstrap 95% CI 0.0921-0.160.

    etaemax_drug ~ 14.2
    # Table II Final Model Interindividual Variance: omega^2_EmaxI = 14.2 (118% SE) SD = 3.77, bootstrap 95% CI 3.34e-09 to 48.9.

    # ================================================================
    # Residual error. Knebel 2012 prints
    #   POFF = POFFi * exp(eps1) + eps2
    # i.e. a combined exponential-plus-additive model. Table II reports
    # both terms as VARIANCES and prints the back-transformed summary:
    #   sigma^2_exp = 0.0215 -> CV% = sqrt(0.0215) = 0.1466 (Table: 14.7)
    #   sigma^2_add = 51.8   -> SD  = sqrt(51.8)   = 7.197  (Table: 7.20)
    # nlmixr2 has no combined lnorm-plus-additive error model, so the
    # exponential term is encoded as the proportional term of a combined
    # add+prop model. This is the standard small-sigma mapping,
    # exp(eps) = 1 + eps + O(eps^2), and it is exactly how the source
    # paper itself summarises the term -- Table II reports it as a CV%,
    # not as a log-scale SD. At CV 14.7% the approximation error in the
    # residual SD is about 1%. Recorded in the vignette's Assumptions and
    # deviations section.
    # ================================================================
    propSd <- sqrt(0.0215)
    label("Proportional (exponential) residual error on percentage OFF time (fraction)")
    # Table II Final Model Residual Variance: sigma^2_exp = 0.0215 (22% SE) CV% = 14.7, bootstrap 95% CI 0.0128-0.0301.

    addSd <- sqrt(51.8)
    label("Additive residual error on percentage OFF time (percentage points)")
    # Table II Final Model Residual Variance: sigma^2_add = 51.8 (9% SE) SD = 7.20, bootstrap 95% CI 43.1-61.3.
  })

  model({
    # ================================================================
    # Knebel 2012 individual-parameter equations. Continuous covariates
    # enter as normalised power terms and binary covariates as
    # multiplicative factors raised to the 0/1 indicator, so the
    # reference (indicator = 0) level carries a multiplier of exactly 1
    # and the tabulated theta is the level-1 multiplier. The random
    # effect is added LAST, on the linear scale, exactly as printed.
    # ================================================================

    # E0i = theta1 * (UPDS/17)^theta6 * (TOMC/2.8)^theta7
    #        * theta8^DOPA * theta9^COMT * theta10^SELG * theta11^AMAT
    #        + etaE0
    # Note E0 carries NO baseline-OFF-time covariate: Knebel 2012 found
    # the strongest graphical signal to be between the E0 random effect
    # and baseline OFF time, but OFFTIME_BL was entered on EmaxP and
    # EmaxI only.
    e0_i <- e0 *
      (SCORE_UPDRS_II / 17)^e_score_updrs_ii_e0 *
      (T_MOTORCOMPL / 2.8)^e_t_motorcompl_e0 *
      e_conmed_dopa_agonist_e0^CONMED_DOPA_AGONIST *
      e_conmed_comti_e0^CONMED_COMTI *
      e_conmed_selegiline_e0^CONMED_SELEGILINE *
      e_conmed_amantadine_e0^CONMED_AMANTADINE +
      etae0

    # EmaxPi = theta2 * (UPDS/17)^theta12 * (BOFF/6.3)^theta13
    #           * (TOMC/2.8)^theta14 * theta15^DOPA * theta16^COMT
    #           * theta17^SELG * theta18^AMAT + etaEmaxP
    emax_dppr_i <- emax_dppr *
      (SCORE_UPDRS_II / 17)^e_score_updrs_ii_emax_dppr *
      (OFFTIME_BL / 6.3)^e_offtime_bl_emax_dppr *
      (T_MOTORCOMPL / 2.8)^e_t_motorcompl_emax_dppr *
      e_conmed_dopa_agonist_emax_dppr^CONMED_DOPA_AGONIST *
      e_conmed_comti_emax_dppr^CONMED_COMTI *
      e_conmed_selegiline_emax_dppr^CONMED_SELEGILINE *
      e_conmed_amantadine_emax_dppr^CONMED_AMANTADINE +
      etaemax_dppr

    # ET50i = theta3 (no covariates, no IIV)
    et50_i <- exp(let50)

    # EmaxIi = theta4 * (UPDS/17)^theta19 * (BOFF/6.3)^theta20
    #           * (TOMC/2.8)^theta21 * theta22^DOPA * theta23^COMT
    #           * theta24^SELG * theta25^AMAT + etaEmaxI
    emax_drug_i <- emax_drug *
      (SCORE_UPDRS_II / 17)^e_score_updrs_ii_emax_drug *
      (OFFTIME_BL / 6.3)^e_offtime_bl_emax_drug *
      (T_MOTORCOMPL / 2.8)^e_t_motorcompl_emax_drug *
      e_conmed_dopa_agonist_emax_drug^CONMED_DOPA_AGONIST *
      e_conmed_comti_emax_drug^CONMED_COMTI *
      e_conmed_selegiline_emax_drug^CONMED_SELEGILINE *
      e_conmed_amantadine_emax_drug^CONMED_AMANTADINE +
      etaemax_drug

    # EC50i = theta5 (no covariates, no IIV)
    ec50_i <- exp(lec50)

    # ================================================================
    # Structural model. Knebel 2012:
    #   PDDPEi = E0i * [1 + EmaxPi * Timei / (ET50i + Timei)]
    #   IEi    = EmaxIi * AUCi / (EC50i + AUCi)
    #   POFFi  = PDDPEi + IEi
    # `time` is days since the first dose (Knebel 2012 Results: "the time
    # after the first placebo dose was used to model these changes in
    # percentage OFF time"), so at time = 0 the DP-PR term contributes
    # nothing and pctofftime = E0i + IEi.
    #
    # The istradefylline term is an ordinary (not sigmoid) Emax function
    # of steady-state exposure and is ADDITIVE to the DP-PR term. Knebel
    # 2012 tested and rejected both alternatives: "An additional time
    # component affecting the IE or the use of a sigmoid Emax model did
    # not improve the fit of the model to the data." Because IE has no
    # time dependence, istradefylline's full effect is present from
    # time = 0 in this model.
    # ================================================================
    pddpe <- e0_i * (1 + emax_dppr_i * time / (et50_i + time))
    ie    <- emax_drug_i * AUC_ISTRA / (ec50_i + AUC_ISTRA)

    pctofftime <- pddpe + ie

    pctofftime ~ prop(propSd) + add(addSd)
  })
}
