Knebel_2012_istradefylline_dyskinesia <- function() {
  description <- paste0(
    "Population exposure-response logistic-regression model for the ",
    "probability of reporting aggravation of dyskinesia as a ",
    "treatment-emergent adverse event in adults with Parkinson disease on ",
    "levodopa/carbidopa treated with adjunctive oral istradefylline ",
    "(KW-6002, a selective adenosine A2A receptor antagonist). Knebel 2012 ",
    "Table IV. The log-odds of dyskinesia is a baseline intercept plus a ",
    "sigmoid Emax function of the individual predicted istradefylline AUC ",
    "at steady state. There is no PK layer and no time dependence: ",
    "exposure enters as the time-fixed AUC_ISTRA data covariate ",
    "(ng*hr/mL), which the source paper generated from a companion ",
    "population PK model (Knebel 2012 reference 6), and the endpoint is a ",
    "single per-subject binary outcome (dyskinesia reported at any point ",
    "during the study, yes/no). The source fit is a naive-pooled logistic ",
    "regression with no between-subject random effects and no covariates ",
    "retained. Companion models from the same paper cover the dizziness ",
    "and nausea adverse-event endpoints and the percentage OFF time ",
    "efficacy endpoint."
  )
  reference <- paste(
    "Knebel W, Rao N, Uchimura T, Mori A, Fisher J, Gastonguay MR, Chaikin P.",
    "Population pharmacokinetic-pharmacodynamic analysis of istradefylline",
    "in patients with Parkinson disease.",
    "J Clin Pharmacol. 2012;52(10):1468-1481.",
    "doi:10.1177/0091270011420566.",
    "The individual istradefylline AUC at steady state that drives this",
    "model was generated by the upstream population PK model of",
    "Knebel W, Rao N, Uchimura T, et al., Population pharmacokinetic",
    "analysis of istradefylline in healthy subjects and in patients with",
    "Parkinson's disease, J Clin Pharmacol (published online ahead of",
    "print 3 March 2010; Knebel 2012 reference 6). That PK model is not",
    "part of this file and is not currently in nlmixr2lib; AUC_ISTRA must",
    "be supplied as a data covariate.",
    sep = " "
  )
  vignette <- "Knebel_2012_istradefylline"

  units <- list(
    time          = "day",
    dosing        = "(none; istradefylline exposure enters as the AUC_ISTRA covariate in ng*hr/mL, not as dosing events)",
    concentration = "(probability, 0-1; the observation prob_dyskinesia is the probability of reporting a dyskinesia adverse event at any point during the study, not a drug concentration)"
  )

  covariateData <- list(
    AUC_ISTRA = list(
      description        = "Individual predicted istradefylline area under the plasma concentration-time curve at steady state over one dosing interval (24 h; istradefylline is dosed once daily).",
      units              = "ng*hr/mL",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Required input; time-fixed per subject. Set to 0 for placebo-treated subjects, which reduces the model to the intercept alone and yields the baseline dyskinesia probability expit(logite0) = 15.4 percent (Knebel 2012 Table V, placebo row). In the source paper this column is the individual empirical-Bayes predicted AUCss from the companion istradefylline population PK model (Knebel 2012 reference 6), not an observed AUC; that PK model is not currently in nlmixr2lib, so AUC_ISTRA must be supplied by the user. Anchors reported in Knebel 2012 for the dose-to-exposure mapping: a median exposure of 1690 ng*hr/mL corresponds to a 5 mg/d dose (Discussion), and approximately 2500 ng*hr/mL is the approximate median exposure at 10 mg/d (Results, Figure 2); the per-dose distribution is shown graphically in Figure 4, bottom panel.",
      source_name        = "AUC"
    )
  )

  # Knebel 2012 built full covariate models for every adverse-event endpoint
  # using the same prespecified covariate list as the efficacy model
  # (Table III), but retained none of them: "However, the precision of the
  # estimates in the full covariate models was very poor, limiting the
  # information that could be extracted from the model. The base models were
  # therefore considered the final models for each AE." No covariate point
  # estimates are reported for the adverse-event models, so none can be
  # encoded; they are documented here instead.
  covariatesDataExcluded <- list(
    SCORE_UPDRS_II = list(
      description = "UPDRS subscale 2 score (activities of daily living).",
      units       = "(UPDRS subscale 2 units, score 0-52)",
      type        = "continuous",
      notes       = "Knebel 2012 Table III lists this covariate as evaluated in the safety/tolerability models as a measure of disease severity. Screened in the full covariate model but not retained (poor precision); no point estimate reported.",
      source_name = "UPDS"
    ),
    CONMED_DOPA_AGONIST = list(
      description = "Concomitant dopamine-agonist use (ropinirole, pramipexole, pergolide, bromocriptine).",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models for a possible increase in the incidence of side effects. Screened but not retained; no point estimate reported.",
      source_name = "DOPA"
    ),
    CONMED_COMTI = list(
      description = "Concomitant COMT-inhibitor use (entacapone, tolcapone).",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models. Screened but not retained; no point estimate reported.",
      source_name = "COMT"
    ),
    CONMED_SELEGILINE = list(
      description = "Concomitant selegiline use.",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models. Screened but not retained; no point estimate reported.",
      source_name = "SELG"
    ),
    CONMED_AMANTADINE = list(
      description = "Concomitant amantadine use.",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models. Screened but not retained; no point estimate reported.",
      source_name = "AMAT"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 1789L,
    n_studies      = 6L,
    age_range      = "not reported in Knebel 2012 (study design and demographics are reported in the companion population PK paper, Knebel 2012 reference 6)",
    weight_range   = "not reported in Knebel 2012",
    sex_female_pct = NA_real_,
    race_ethnicity = "not reported in Knebel 2012",
    disease_state  = "Parkinson disease with levodopa-related motor response complications, on levodopa/carbidopa therapy. Baseline characteristics are tabulated for the percentage OFF time cohort in Knebel 2012 Table I; the adverse-event cohort is a slightly larger overlapping set from the same six studies.",
    dose_range     = "Istradefylline 5 to 60 mg once daily across the six phase 2/3 studies, plus placebo. Knebel 2012 additionally simulated an 80 mg/d dose by linear extrapolation from the 60 mg results.",
    regions        = "not reported in Knebel 2012",
    notes          = "Adverse-event database: 1198 patients treated with istradefylline and 591 treated with placebo from the six phase 2/3 studies (Knebel 2012 Results, AE Analysis), i.e. 1789 patients. The abstract instead states 1798 patients for the safety/tolerability analysis; the two figures disagree by 9 and Knebel 2012 does not reconcile them, so this file records the Results-section sum of the two stated arms. All patients supplied only one observation each, from the parallel fixed-dose response studies, except 73 patients in study 6002-US-001 who supplied 174 observations in total (that study randomised patients to the dose sequences 5, 10, 20 mg or 10, 20, 40 mg). Because the endpoint is essentially one binary record per subject, the source model is a naive-pooled logistic regression with no between-subject random effects. Only endpoints with an incidence at least 2 percent higher than placebo and judged clinically relevant were modelled; dyskinesia, dizziness and nausea met that bar. Model fit in NONMEM VI level 1.1 with FOCE-INT; precision assessed by a stratified nonparametric bootstrap of 1000 replicates."
  )

  ini({
    # ================================================================
    # All values are Knebel 2012 Table IV, "Dyskinesia" block. The model
    # form is given in Knebel 2012 Supplemental Table S2, which is not on
    # disk; the form encoded here is the one the paper's own text
    # specifies ("The relationship between istradefylline AUCss and the
    # probability of experiencing dyskinesia as an AE was best described
    # by a sigmoid Emax model. The logit model is described in
    # Supplemental Table S2.") and it is confirmed numerically by the
    # paper's reported anchors -- see the source-trace note below.
    #
    # SOURCE-TRACE CONFIRMATION of the additive-on-logit sigmoid Emax
    # form. With the Table IV point estimates:
    #   at AUC = 0     logit = -1.7            -> p = 15.45 percent
    #   as AUC -> inf  logit = -1.7 + 0.57     -> p = 24.43 percent
    # Knebel 2012 Table V reports 15.4 percent for placebo and Results
    # reports "a maximum dyskinesia probability of 24.3% (95% CI =
    # 21.3%-28.1%)"; Table V reports 24.4 percent at the extrapolated
    # 80 mg dose. Both anchors are reproduced to within 0.15 percentage
    # points, which pins EmaxPD as an increment on the LOGIT scale (not
    # on the probability scale) and pins BD0 as the logit-scale
    # intercept. The residual sub-0.15-point differences arise because
    # Table V was computed from the bootstrap parameter distribution
    # rather than from these point estimates (Knebel 2012 Methods,
    # Integration of PK and PD Results).
    #
    # No between-subject variability and no residual-error model are
    # reported: Table IV lists fixed effects only, and the endpoint is
    # one binary record per subject. Encoded faithfully -- no invented
    # etas.
    # ================================================================

    logite0 <- -1.7
    label("Logit of the dyskinesia probability at zero istradefylline exposure (unitless)")
    # Table IV Dyskinesia: BD0 = theta4 = -1.7 (6% SE). Table footnote: "BD0, baseline dyskinesia probability". expit(-1.7) = 0.1545, matching the 15.4 percent placebo row of Table V.

    emax <- 0.57
    label("Maximum increase in the dyskinesia log-odds attributable to istradefylline (logit units)")
    # Table IV Dyskinesia: EmaxPD = theta1 = 0.57 (28% SE). Table footnote: "EmaxPD, maximum dyskinesia probability". expit(-1.7 + 0.57) = 0.2443, matching the 24.3 percent maximum reported in Results.

    lec50 <- log(2380)
    label("Istradefylline steady-state AUC producing half of the maximum dyskinesia effect (ng*hr/mL)")
    # Table IV Dyskinesia: EC50D = theta2 = 2380 (44% SE). Results: "an EC50D (AUC resulting in 50% of EmaxD) of 2380 ng x hr/mL (95% CI = 327-4430 ng x hr/mL)". Poorly estimated, per Results.

    lhill <- log(2.94)
    label("Hill coefficient of the sigmoid istradefylline effect on the dyskinesia log-odds (unitless)")
    # Table IV Dyskinesia: Gamma = theta3 = 2.94 (75% SE). Table footnote: "gamma, Hill coefficient". Results notes the Hill coefficient and EC50D were the only structural parameters NOT estimated with good precision.

    # The source fits this model with a binary (Bernoulli) logistic
    # likelihood on a 0/1 adverse-event indicator, so there is no
    # observation-error model to translate. This placeholder additive
    # residual is attached to the probability output so the nlmixr2
    # likelihood machinery accepts the model for forward simulation. It
    # is NOT from the source -- see the vignette's Assumptions and
    # deviations section. Same device as
    # Garcia_2025_garadacimab_hae_attack.R.
    addSd <- 0.001
    label("Placeholder additive residual error on the probability output prob_dyskinesia (unitless); not from the source")
  })

  model({
    ec50 <- exp(lec50)
    hill <- exp(lhill)

    # Sigmoid Emax in steady-state exposure, additive on the logit scale:
    #   logit(p) = BD0 + EmaxPD * AUC^gamma / (EC50D^gamma + AUC^gamma)
    # Written in the algebraically identical relative-exposure form
    #   f = r^gamma / (1 + r^gamma),  r = AUC / EC50D
    # purely for numerical safety. Evaluating AUC^2.94 directly is fine
    # here, but the companion dizziness model shares this structure with
    # a Hill coefficient of 10, where AUC^10 reaches 1e40 for realistic
    # exposures; keeping one form across both files avoids a form that is
    # safe in one and marginal in the other. At AUC = 0 the ratio form
    # gives f = 0 exactly, so the intercept is recovered.
    auc_rel <- AUC_ISTRA / ec50
    edrug   <- emax * auc_rel^hill / (1 + auc_rel^hill)

    prob_dyskinesia <- expit(logite0 + edrug)

    prob_dyskinesia ~ add(addSd)
  })
}
