Knebel_2012_istradefylline_nausea <- function() {
  description <- paste0(
    "Population exposure-response logistic-regression model for the ",
    "probability of reporting nausea as a treatment-emergent adverse event ",
    "in adults with Parkinson disease on levodopa/carbidopa treated with ",
    "adjunctive oral istradefylline (KW-6002, a selective adenosine A2A ",
    "receptor antagonist). Knebel 2012 Table IV. Unlike the companion ",
    "dyskinesia and dizziness models, which are sigmoid Emax and therefore ",
    "plateau, the nausea log-odds is a baseline intercept plus an ",
    "UNBOUNDED power function of the individual predicted istradefylline ",
    "AUC at steady state; this is the paper's reported finding that the ",
    "probability of nausea continues to rise with every dose increase ",
    "rather than plateauing at 40 mg/d. There is no PK layer and no time ",
    "dependence: exposure enters as the time-fixed AUC_ISTRA data ",
    "covariate (ng*hr/mL), which the source paper generated from a ",
    "companion population PK model (Knebel 2012 reference 6), and the ",
    "endpoint is a single per-subject binary outcome (nausea reported at ",
    "any point during the study, yes/no). The source fit is a ",
    "naive-pooled logistic regression with no between-subject random ",
    "effects and no covariates retained. Companion models from the same ",
    "paper cover the dyskinesia and dizziness adverse-event endpoints and ",
    "the percentage OFF time efficacy endpoint."
  )
  reference <- paste(
    "Knebel W, Rao N, Uchimura T, Mori A, Fisher J, Gastonguay MR, Chaikin P.",
    "Population pharmacokinetic-pharmacodynamic analysis of istradefylline",
    "in patients with Parkinson disease.",
    "J Clin Pharmacol. 2012;52(10):1468-1481.",
    "doi:10.1177/0091270011420566.",
    "The individual istradefylline AUC at steady state that drives this",
    "model was generated by the upstream population PK model of",
    "Knebel W, Rao N, Uchimura T, et al., Population pharmacokinetic",
    "analysis of istradefylline in healthy subjects and in patients with",
    "Parkinson's disease, J Clin Pharmacol (published online ahead of",
    "print 3 March 2010; Knebel 2012 reference 6). That PK model is not",
    "part of this file and is not currently in nlmixr2lib; AUC_ISTRA must",
    "be supplied as a data covariate.",
    sep = " "
  )
  vignette <- "Knebel_2012_istradefylline"

  units <- list(
    time          = "day",
    dosing        = "(none; istradefylline exposure enters as the AUC_ISTRA covariate in ng*hr/mL, not as dosing events)",
    concentration = "(probability, 0-1; the observation prob_nausea is the probability of reporting a nausea adverse event at any point during the study, not a drug concentration)"
  )

  covariateData <- list(
    AUC_ISTRA = list(
      description        = "Individual predicted istradefylline area under the plasma concentration-time curve at steady state over one dosing interval (24 h; istradefylline is dosed once daily).",
      units              = "ng*hr/mL",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Required input; time-fixed per subject. Set to 0 for placebo-treated subjects, which reduces the model to the intercept alone and yields the baseline nausea probability expit(logite0) = 6.79 percent (Knebel 2012 Table V reports 6.75 percent for the placebo row). In the source paper this column is the individual empirical-Bayes predicted AUCss from the companion istradefylline population PK model (Knebel 2012 reference 6), not an observed AUC; that PK model is not currently in nlmixr2lib, so AUC_ISTRA must be supplied by the user. Anchors reported in Knebel 2012 for the dose-to-exposure mapping: a median exposure of 1690 ng*hr/mL corresponds to a 5 mg/d dose (Discussion), and approximately 2500 ng*hr/mL is the approximate median exposure at 10 mg/d (Results, Figure 2); the per-dose distribution is shown graphically in Figure 4, bottom panel. Because the exposure term is an unbounded power function, extrapolating AUC_ISTRA far beyond the 5-60 mg/d range studied will drive the predicted probability toward 1 with no mechanistic ceiling; the paper's own 80 mg/d row in Table V and Table VI was obtained by linear extrapolation from 60 mg rather than by evaluating the model at a higher exposure.",
      source_name        = "AUC"
    )
  )

  # Knebel 2012 built full covariate models for every adverse-event endpoint
  # using the same prespecified covariate list as the efficacy model
  # (Table III), but retained none of them: "However, the precision of the
  # estimates in the full covariate models was very poor, limiting the
  # information that could be extracted from the model. The base models were
  # therefore considered the final models for each AE." No covariate point
  # estimates are reported for the adverse-event models, so none can be
  # encoded; they are documented here instead.
  covariatesDataExcluded <- list(
    SCORE_UPDRS_II = list(
      description = "UPDRS subscale 2 score (activities of daily living).",
      units       = "(UPDRS subscale 2 units, score 0-52)",
      type        = "continuous",
      notes       = "Knebel 2012 Table III lists this covariate as evaluated in the safety/tolerability models as a measure of disease severity. Screened in the full covariate model but not retained (poor precision); no point estimate reported.",
      source_name = "UPDS"
    ),
    CONMED_DOPA_AGONIST = list(
      description = "Concomitant dopamine-agonist use (ropinirole, pramipexole, pergolide, bromocriptine).",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models for a possible increase in the incidence of side effects. Screened but not retained; no point estimate reported.",
      source_name = "DOPA"
    ),
    CONMED_COMTI = list(
      description = "Concomitant COMT-inhibitor use (entacapone, tolcapone).",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models. Screened but not retained; no point estimate reported.",
      source_name = "COMT"
    ),
    CONMED_SELEGILINE = list(
      description = "Concomitant selegiline use.",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models. Screened but not retained; no point estimate reported.",
      source_name = "SELG"
    ),
    CONMED_AMANTADINE = list(
      description = "Concomitant amantadine use.",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models. Screened but not retained; no point estimate reported.",
      source_name = "AMAT"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 1789L,
    n_studies      = 6L,
    age_range      = "not reported in Knebel 2012 (study design and demographics are reported in the companion population PK paper, Knebel 2012 reference 6)",
    weight_range   = "not reported in Knebel 2012",
    sex_female_pct = NA_real_,
    race_ethnicity = "not reported in Knebel 2012",
    disease_state  = "Parkinson disease with levodopa-related motor response complications, on levodopa/carbidopa therapy. Baseline characteristics are tabulated for the percentage OFF time cohort in Knebel 2012 Table I; the adverse-event cohort is a slightly larger overlapping set from the same six studies.",
    dose_range     = "Istradefylline 5 to 60 mg once daily across the six phase 2/3 studies, plus placebo. Knebel 2012 additionally simulated an 80 mg/d dose by linear extrapolation from the 60 mg results.",
    regions        = "not reported in Knebel 2012",
    notes          = "Adverse-event database: 1198 patients treated with istradefylline and 591 treated with placebo from the six phase 2/3 studies (Knebel 2012 Results, AE Analysis), i.e. 1789 patients. The abstract instead states 1798 patients for the safety/tolerability analysis; the two figures disagree by 9 and Knebel 2012 does not reconcile them, so this file records the Results-section sum of the two stated arms. All patients supplied only one observation each, from the parallel fixed-dose response studies, except 73 patients in study 6002-US-001 who supplied 174 observations in total (that study randomised patients to the dose sequences 5, 10, 20 mg or 10, 20, 40 mg). Because the endpoint is essentially one binary record per subject, the source model is a naive-pooled logistic regression with no between-subject random effects. Only endpoints with an incidence at least 2 percent higher than placebo and judged clinically relevant were modelled; dyskinesia, dizziness and nausea met that bar. Model fit in NONMEM VI level 1.1 with FOCE-INT; precision assessed by a stratified nonparametric bootstrap of 1000 replicates."
  )

  ini({
    # ================================================================
    # All values are Knebel 2012 Table IV, "Nausea" block. The model form
    # is given in Knebel 2012 Supplemental Table S2, which is not on
    # disk; the form encoded here is the one the paper's own text
    # specifies ("The relationship between istradefylline AUCss and the
    # probability of experiencing nausea as an AE was best described by a
    # power model. The power model was characterized by a baseline
    # probability for the occurrence of nausea, a slope for the effect of
    # istradefylline, and the power term.") -- three parameters, matching
    # the three rows of the Table IV Nausea block exactly.
    #
    # SOURCE-TRACE CONFIRMATION at zero exposure: expit(-2.62) = 6.79
    # percent, against 6.75 percent for the placebo row of Knebel 2012
    # Table V. The residual difference arises because Table V was
    # computed from the bootstrap parameter distribution rather than from
    # these point estimates (Knebel 2012 Methods, Integration of PK and
    # PD Results).
    #
    # PRECISION WARNING. Knebel 2012 Results: "All the structural model
    # parameters, with the exception of the baseline probability, were
    # poorly estimated." The slope carries a 403 percent standard error
    # and the power term 68 percent, so only the intercept is well
    # determined. The slope and power are also strongly aliased with each
    # other -- a power model of this form trades slope against exponent
    # along a ridge -- so the two values must be used together and
    # neither is interpretable alone.
    #
    # No between-subject variability and no residual-error model are
    # reported: Table IV lists fixed effects only, and the endpoint is
    # one binary record per subject. Encoded faithfully -- no invented
    # etas.
    # ================================================================

    logite0 <- -2.62
    label("Logit of the nausea probability at zero istradefylline exposure (unitless)")
    # Table IV Nausea: BNS0 = theta3 = -2.62 (6% SE). Table footnote: "BNS0, baseline nausea probability". expit(-2.62) = 0.0679, against the 6.75 percent placebo row of Table V. The only well-estimated parameter of this model per Results.

    slope <- 0.00218
    label("Slope of the istradefylline effect on the nausea log-odds, per (ng*hr/mL) raised to the power term (logit units)")
    # Table IV Nausea: SLOP = theta1 = 0.00218 (403% SE). Table footnote: "SLOP, slope of nausea probability". Very poorly estimated; strongly aliased with the power term below.

    e_auc_istra_slope <- 0.635
    label("Power exponent applied to AUC_ISTRA inside the nausea slope term (unitless)")
    # Table IV Nausea: Power = theta2 = 0.635 (68% SE). Table footnote: "power, power term". Because the exponent is below 1 the effect is concave in exposure, but it is unbounded -- unlike the sigmoid Emax used for dyskinesia and dizziness, it has no asymptote, which is the structural reason Knebel 2012 concludes "the probability of nausea is expected to continually rise as the dose is increased".

    # The source fits this model with a binary (Bernoulli) logistic
    # likelihood on a 0/1 adverse-event indicator, so there is no
    # observation-error model to translate. This placeholder additive
    # residual is attached to the probability output so the nlmixr2
    # likelihood machinery accepts the model for forward simulation. It
    # is NOT from the source -- see the vignette's Assumptions and
    # deviations section. Same device as
    # Garcia_2025_garadacimab_hae_attack.R.
    addSd <- 0.001
    label("Placeholder additive residual error on the probability output prob_nausea (unitless); not from the source")
  })

  model({
    # Power model, additive on the logit scale:
    #   logit(p) = BNS0 + SLOP * AUC^power
    # At AUC = 0 the exposure term is 0^0.635 = 0, so the intercept is
    # recovered exactly and the placebo probability is expit(BNS0).
    edrug <- slope * AUC_ISTRA^e_auc_istra_slope

    prob_nausea <- expit(logite0 + edrug)

    prob_nausea ~ add(addSd)
  })
}
