Knebel_2012_istradefylline_dizziness <- function() {
  description <- paste0(
    "Population exposure-response logistic-regression model for the ",
    "probability of reporting dizziness (predominantly lightheadedness) as ",
    "a treatment-emergent adverse event in adults with Parkinson disease on ",
    "levodopa/carbidopa treated with adjunctive oral istradefylline ",
    "(KW-6002, a selective adenosine A2A receptor antagonist). Knebel 2012 ",
    "Table IV. The log-odds of dizziness is a baseline intercept plus a ",
    "sigmoid Emax function of the individual predicted istradefylline AUC ",
    "at steady state; the estimated Hill coefficient of 10 makes the ",
    "exposure-response curve nearly a step change, which is the paper's ",
    "reported finding that most of the increase in dizziness risk occurs ",
    "between the 10 and 20 mg/d doses. There is no PK layer and no time ",
    "dependence: exposure enters as the time-fixed AUC_ISTRA data ",
    "covariate (ng*hr/mL), which the source paper generated from a ",
    "companion population PK model (Knebel 2012 reference 6), and the ",
    "endpoint is a single per-subject binary outcome (dizziness reported ",
    "at any point during the study, yes/no). The source fit is a ",
    "naive-pooled logistic regression with no between-subject random ",
    "effects and no covariates retained. Companion models from the same ",
    "paper cover the dyskinesia and nausea adverse-event endpoints and the ",
    "percentage OFF time efficacy endpoint."
  )
  reference <- paste(
    "Knebel W, Rao N, Uchimura T, Mori A, Fisher J, Gastonguay MR, Chaikin P.",
    "Population pharmacokinetic-pharmacodynamic analysis of istradefylline",
    "in patients with Parkinson disease.",
    "J Clin Pharmacol. 2012;52(10):1468-1481.",
    "doi:10.1177/0091270011420566.",
    "The individual istradefylline AUC at steady state that drives this",
    "model was generated by the upstream population PK model of",
    "Knebel W, Rao N, Uchimura T, et al., Population pharmacokinetic",
    "analysis of istradefylline in healthy subjects and in patients with",
    "Parkinson's disease, J Clin Pharmacol (published online ahead of",
    "print 3 March 2010; Knebel 2012 reference 6). That PK model is not",
    "part of this file and is not currently in nlmixr2lib; AUC_ISTRA must",
    "be supplied as a data covariate.",
    sep = " "
  )
  vignette <- "Knebel_2012_istradefylline"

  units <- list(
    time          = "day",
    dosing        = "(none; istradefylline exposure enters as the AUC_ISTRA covariate in ng*hr/mL, not as dosing events)",
    concentration = "(probability, 0-1; the observation prob_dizziness is the probability of reporting a dizziness adverse event at any point during the study, not a drug concentration)"
  )

  covariateData <- list(
    AUC_ISTRA = list(
      description        = "Individual predicted istradefylline area under the plasma concentration-time curve at steady state over one dosing interval (24 h; istradefylline is dosed once daily).",
      units              = "ng*hr/mL",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Required input; time-fixed per subject. Set to 0 for placebo-treated subjects, which reduces the model to the intercept alone and yields the baseline dizziness probability expit(logite0) = 6.23 percent (Knebel 2012 Table V reports 6.21 percent for the placebo row). In the source paper this column is the individual empirical-Bayes predicted AUCss from the companion istradefylline population PK model (Knebel 2012 reference 6), not an observed AUC; that PK model is not currently in nlmixr2lib, so AUC_ISTRA must be supplied by the user. Anchors reported in Knebel 2012 for the dose-to-exposure mapping: a median exposure of 1690 ng*hr/mL corresponds to a 5 mg/d dose (Discussion), and approximately 2500 ng*hr/mL is the approximate median exposure at 10 mg/d (Results, Figure 2); the per-dose distribution is shown graphically in Figure 4, bottom panel. Because the fitted Hill coefficient is 10, this model is extremely sensitive to AUC_ISTRA in a narrow band around the 2770 ng*hr/mL EC50 and almost flat elsewhere.",
      source_name        = "AUC"
    )
  )

  # Knebel 2012 built full covariate models for every adverse-event endpoint
  # using the same prespecified covariate list as the efficacy model
  # (Table III), but retained none of them: "However, the precision of the
  # estimates in the full covariate models was very poor, limiting the
  # information that could be extracted from the model. The base models were
  # therefore considered the final models for each AE." No covariate point
  # estimates are reported for the adverse-event models, so none can be
  # encoded; they are documented here instead.
  covariatesDataExcluded <- list(
    SCORE_UPDRS_II = list(
      description = "UPDRS subscale 2 score (activities of daily living).",
      units       = "(UPDRS subscale 2 units, score 0-52)",
      type        = "continuous",
      notes       = "Knebel 2012 Table III lists this covariate as evaluated in the safety/tolerability models as a measure of disease severity. Screened in the full covariate model but not retained (poor precision); no point estimate reported.",
      source_name = "UPDS"
    ),
    CONMED_DOPA_AGONIST = list(
      description = "Concomitant dopamine-agonist use (ropinirole, pramipexole, pergolide, bromocriptine).",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models for a possible increase in the incidence of side effects. Screened but not retained; no point estimate reported.",
      source_name = "DOPA"
    ),
    CONMED_COMTI = list(
      description = "Concomitant COMT-inhibitor use (entacapone, tolcapone).",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models. Screened but not retained; no point estimate reported.",
      source_name = "COMT"
    ),
    CONMED_SELEGILINE = list(
      description = "Concomitant selegiline use.",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models. Screened but not retained; no point estimate reported.",
      source_name = "SELG"
    ),
    CONMED_AMANTADINE = list(
      description = "Concomitant amantadine use.",
      units       = "(binary)",
      type        = "binary",
      notes       = "Knebel 2012 Table III, evaluated in the safety/tolerability models. Screened but not retained; no point estimate reported.",
      source_name = "AMAT"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 1789L,
    n_studies      = 6L,
    age_range      = "not reported in Knebel 2012 (study design and demographics are reported in the companion population PK paper, Knebel 2012 reference 6)",
    weight_range   = "not reported in Knebel 2012",
    sex_female_pct = NA_real_,
    race_ethnicity = "not reported in Knebel 2012",
    disease_state  = "Parkinson disease with levodopa-related motor response complications, on levodopa/carbidopa therapy. Baseline characteristics are tabulated for the percentage OFF time cohort in Knebel 2012 Table I; the adverse-event cohort is a slightly larger overlapping set from the same six studies.",
    dose_range     = "Istradefylline 5 to 60 mg once daily across the six phase 2/3 studies, plus placebo. Knebel 2012 additionally simulated an 80 mg/d dose by linear extrapolation from the 60 mg results.",
    regions        = "not reported in Knebel 2012",
    notes          = "Adverse-event database: 1198 patients treated with istradefylline and 591 treated with placebo from the six phase 2/3 studies (Knebel 2012 Results, AE Analysis), i.e. 1789 patients. The abstract instead states 1798 patients for the safety/tolerability analysis; the two figures disagree by 9 and Knebel 2012 does not reconcile them, so this file records the Results-section sum of the two stated arms. All patients supplied only one observation each, from the parallel fixed-dose response studies, except 73 patients in study 6002-US-001 who supplied 174 observations in total (that study randomised patients to the dose sequences 5, 10, 20 mg or 10, 20, 40 mg). Because the endpoint is essentially one binary record per subject, the source model is a naive-pooled logistic regression with no between-subject random effects. Only endpoints with an incidence at least 2 percent higher than placebo and judged clinically relevant were modelled; dyskinesia, dizziness and nausea met that bar. Model fit in NONMEM VI level 1.1 with FOCE-INT; precision assessed by a stratified nonparametric bootstrap of 1000 replicates."
  )

  ini({
    # ================================================================
    # All values are Knebel 2012 Table IV, "Dizziness" block. The model
    # form is given in Knebel 2012 Supplemental Table S2, which is not on
    # disk; the form encoded here is the one the paper's own text
    # specifies ("The relationship between istradefylline AUCss and the
    # probability of experiencing dizziness as an AE was best described
    # by a sigmoid Emax model. The logit model is described in
    # Supplemental Table S2.") and is the same structure as the companion
    # dyskinesia model, where the paper's reported anchors confirm the
    # additive-on-logit sigmoid Emax reading to within 0.15 percentage
    # points.
    #
    # SOURCE-TRACE CONFIRMATION at zero exposure: expit(-2.71) = 6.23
    # percent, against 6.21 percent for the placebo row of Knebel 2012
    # Table V.
    #
    # KNOWN DISCREPANCY at the upper asymptote. The Table IV point
    # estimates give a maximum of expit(-2.71 + 0.538) = 10.23 percent,
    # whereas Results and Table V report 10.9 percent at 60 mg/d (and
    # 11.0 percent at the extrapolated 80 mg dose), i.e. ABOVE the
    # asymptote this parameterisation can reach. The published Table V
    # values were not computed from these point estimates: Knebel 2012
    # Methods states "The population PK-PD parameters from the bootstrap
    # analysis and the median observed AUC at each dose were used to
    # simulate ... the probability of dizziness, dyskinesia, and nausea".
    # A bootstrap-median-of-predictions summary is not constrained to lie
    # below the point-estimate asymptote, and EmaxPDZ carries a 35
    # percent standard error, so the 0.7-percentage-point excess is
    # consistent with that route. Nothing here has been tuned to close
    # the gap; the discrepancy is recorded in the validation vignette's
    # Assumptions and deviations section.
    #
    # No between-subject variability and no residual-error model are
    # reported: Table IV lists fixed effects only, and the endpoint is
    # one binary record per subject. Encoded faithfully -- no invented
    # etas.
    # ================================================================

    logite0 <- -2.71
    label("Logit of the dizziness probability at zero istradefylline exposure (unitless)")
    # Table IV Dizziness: BDZ0 = theta4 = -2.71 (5% SE). Table footnote: "BDZ0, baseline dizziness probability". expit(-2.71) = 0.0623, against the 6.21 percent placebo row of Table V.

    emax <- 0.538
    label("Maximum increase in the dizziness log-odds attributable to istradefylline (logit units)")
    # Table IV Dizziness: EmaxPDZ = theta1 = 0.538 (35% SE). Results: "The model predicted maximum probability of dizziness (EmaxPDZ) was 10.9% (95% CI = 8.6%-14.1%)". See the upper-asymptote note above.

    lec50 <- log(2770)
    label("Istradefylline steady-state AUC producing half of the maximum dizziness effect (ng*hr/mL)")
    # Table IV Dizziness: EC50DZ = theta2 = 2770 (29% SE). Results: "an EC50DZ (AUC resulting in 50% of EmaxDYS) of 2770 ng x hr/mL (95% CI = 1200-4340 ng x hr/mL)".

    lhill <- log(10)
    label("Hill coefficient of the sigmoid istradefylline effect on the dizziness log-odds (unitless)")
    # Table IV Dizziness: Gamma = theta3 = 10 (227% SE). Table footnote: "gamma, Hill coefficient". Results: the Hill coefficient was the only structural parameter NOT estimated with good precision. A value of 10 with a 227 percent standard error makes the exposure-response effectively a step at the EC50; it is reported as exactly 10, which is very likely an upper bound the estimation ran into rather than an identified value, so simulations should not read mechanistic meaning into the steepness.

    # The source fits this model with a binary (Bernoulli) logistic
    # likelihood on a 0/1 adverse-event indicator, so there is no
    # observation-error model to translate. This placeholder additive
    # residual is attached to the probability output so the nlmixr2
    # likelihood machinery accepts the model for forward simulation. It
    # is NOT from the source -- see the vignette's Assumptions and
    # deviations section. Same device as
    # Garcia_2025_garadacimab_hae_attack.R.
    addSd <- 0.001
    label("Placeholder additive residual error on the probability output prob_dizziness (unitless); not from the source")
  })

  model({
    ec50 <- exp(lec50)
    hill <- exp(lhill)

    # Sigmoid Emax in steady-state exposure, additive on the logit scale:
    #   logit(p) = BDZ0 + EmaxPDZ * AUC^gamma / (EC50DZ^gamma + AUC^gamma)
    # Written in the algebraically identical relative-exposure form
    #   f = r^gamma / (1 + r^gamma),  r = AUC / EC50DZ
    # because the direct form is numerically hazardous at this Hill
    # coefficient: with gamma = 10, AUC^10 is about 1e40 at a realistic
    # 10 000 ng*hr/mL exposure and about 1e34 at the EC50, so the direct
    # form divides two enormous numbers where the ratio form divides two
    # numbers of order 1. At AUC = 0 the ratio form gives f = 0 exactly,
    # so the intercept is recovered.
    auc_rel <- AUC_ISTRA / ec50
    edrug   <- emax * auc_rel^hill / (1 + auc_rel^hill)

    prob_dizziness <- expit(logite0 + edrug)

    prob_dizziness ~ add(addSd)
  })
}
