Marier_2011_cenicriviroc_mcp1 <- function() {
  description <- paste(
    "Static exposure-response Emax model relating average steady-state plasma",
    "cenicriviroc concentration to the change from baseline in plasma",
    "monocyte chemotactic protein 1 (MCP-1 / CCL2), in HIV-1-infected,",
    "antiretroviral treatment-experienced, CCR5-antagonist-naive adults given",
    "10 days of once-daily oral monotherapy (Marier 2011). The drug is",
    "identified throughout the source only by its Tobira Therapeutics",
    "development code TBR-652 (also TAK-652); the INN cenicriviroc was",
    "assigned later, and this file uses the INN per the nlmixr2lib naming",
    "policy. The model is:",
    "dmcp1 = emax * CSS_CVC / (ic50 + CSS_CVC),",
    "with emax = +2.63 log10 pg/mL and ic50 = 29.8 ng/mL. MCP-1 is the",
    "endogenous ligand of CCR2, and the effect is an INCREASE: cenicriviroc is",
    "a dual CCR5 / CCR2 antagonist, so blocking CCR2 prevents receptor-mediated",
    "clearance of MCP-1 and circulating MCP-1 accumulates. This is a",
    "target-engagement biomarker for the CCR2 arm of the molecule, not an",
    "efficacy endpoint, and the authors present it as exploratory. Like its",
    "companion, it is a SIMPLE (hyperbolic, non-sigmoidal) Emax model with NO",
    "baseline intercept -- the fitted curve in the source's Figure 4 passes",
    "through the origin -- and it has NO structural pharmacokinetic",
    "component, so the driving exposure is supplied as the covariate CSS_CVC",
    "(an NCA-derived per-subject average steady-state concentration) rather",
    "than generated by dose events. The source reports no inter-individual",
    "variability and no residual error, only standard errors on the two",
    "parameters (0.233 log10 pg/mL on Emax and 9.45 ng/mL on IC50), so the",
    "model returns the deterministic curve. Companion model file",
    "Marier_2011_cenicriviroc_hiv1rna.R carries the paper's primary,",
    "independently fitted Emax model, for HIV-1 RNA.",
    sep = " "
  )

  reference <- paste(
    "Marier JF, Trinh M, Pheng LH, Palleja SM, Martin DE.",
    "Pharmacokinetics and pharmacodynamics of TBR-652, a novel CCR5",
    "antagonist, in HIV-1-infected, antiretroviral treatment-experienced,",
    "CCR5 antagonist-naive patients.",
    "Antimicrob Agents Chemother. 2011;55(6):2768-2774.",
    "doi:10.1128/AAC.00713-10. PMCID PMC3101382.",
    "The MCP-1 sampling day is in Methods 'Pharmacodynamics' (p. 2770) and",
    "the model form in Methods 'Pharmacokinetic/pharmacodynamic modeling'",
    "(p. 2770); the parameter estimates and their standard errors are in",
    "Results (pp. 2772-2773); the fitted curve and the individual data it was",
    "fit to are Figure 4 (p. 2773).",
    "Companion model file from the same paper:",
    "modellib('Marier_2011_cenicriviroc_hiv1rna').",
    sep = " "
  )

  vignette <- "Marier_2011_cenicriviroc"

  units <- list(
    time          = "h",
    dosing        = "not applicable (static exposure-response model; cenicriviroc exposure enters through the covariate CSS_CVC rather than through rxode2 dose events)",
    concentration = "log10 pg/mL (the modelled observation dmcp1 is the CHANGE FROM BASELINE in plasma MCP-1 on the log10 scale, NOT a drug concentration; the driving covariate CSS_CVC is the average steady-state cenicriviroc plasma concentration in ng/mL)"
  )

  covariateData <- list(
    CSS_CVC = list(
      description        = "Individual average steady-state plasma concentration (Css) of cenicriviroc (TBR-652) on day 10 of once-daily oral dosing, carried as the per-subject exposure metric that drives the Emax term.",
      units              = "ng/mL",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Identical column, identical derivation and identical caveats as in the companion model Marier_2011_cenicriviroc_hiv1rna.R; see that file's covariateData notes for the full detail. In brief: Css is a noncompartmental quantity, AUC0-24 / 24 h from the day-10 intensive profile (Methods 'Pharmacokinetics', p. 2769), with cohort mean values of 15.92, 51.89, 79.82, 110.8 and 303.0 ng/mL at 25, 50, 75, 100 and 150 mg QD (Table 2, p. 2772). There is no PK model in this paper to generate the column with.",
        "One timing mismatch is worth being explicit about, because it is a real limitation of pairing these two quantities rather than a transcription question. MCP-1 was measured on DAY 10 (Methods 'Pharmacodynamics', p. 2770: 'Determination of the change from baseline in the inflammatory marker monocyte chemotactic protein 1 (MCP-1) was performed based on data collected on day 10'), which is the same day as the PK profile that yields Css -- so exposure and response are contemporaneous here. The companion HIV-1 RNA model instead pairs the day-10 Css with the day-11 viral load, one day later. Both pairings are the authors' own.",
        "PLACEBO subjects carry CSS_CVC = 0 and are plotted on the y-axis of Figure 4; the model returns exactly 0 there because it has no intercept term. Set CSS_CVC = 0 to simulate placebo.",
        "Individual Css values span roughly 0 to 490 ng/mL across Figure 4, the same range as Figure 3. Total, not unbound concentration."
      ),
      source_name        = "Css (average concentration under steady-state conditions)"
    )
  )

  # Baseline characteristics tabulated for the study population (Table 1,
  # p. 2770) but not used by this model. Marier 2011 reports no covariate
  # screen on either Emax fit. Documentation only.
  covariatesDataExcluded <- list(
    WT = list(
      description        = "Body weight at baseline.",
      units              = "kg",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Table 1: overall mean 79.81 kg (SD 17.08); cohort means 69.50-93.87 kg. Not used in the PK/PD model.",
      source_name        = "Mean wt (kg) (SD)"
    ),
    AGE = list(
      description        = "Age at baseline.",
      units              = "years",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Table 1: overall mean 38.9 years (SD 7.95); inclusion range 18-65 years. Not used in the PK/PD model.",
      source_name        = "Mean age (yr) (SD)"
    ),
    SEXF = list(
      description        = "Female sex indicator (0 = male, 1 = female).",
      units              = "(binary)",
      type               = "binary",
      reference_category = "0 (male)",
      notes              = "Table 1: 7 of 54 (13%) female. Not used in the PK/PD model.",
      source_name        = "Females"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = NA_integer_,
    n_studies      = 1L,
    age_range      = "18-65 years by protocol; cohort means 33.9-41.0 years, overall mean 38.9 years (SD 7.95)",
    weight_range   = "cohort mean weights 69.50-93.87 kg; overall mean 79.81 kg (SD 17.08)",
    height_range   = "cohort mean heights 171.33-179.14 cm; overall mean 176.71 cm (SD 9.685)",
    sex_female_pct = 13,
    race_ethnicity = c(Caucasian = 55.6, `African-American` = 25.9, Hispanic = 13.0, Other = 3.7, Asian = 1.9),
    disease_state  = "HIV-1 infection, antiretroviral treatment-experienced but off all antiretroviral therapy for at least 6 weeks (range 6 weeks to 3 years), CCR5-antagonist-naive, CCR5-tropic virus by the enhanced-sensitivity Trofile assay, screening plasma HIV-1 RNA at least 5,000 copies/mL and CD4+ count at least 250 cells/mm^3",
    dose_range     = "Cenicriviroc (TBR-652) 25, 50, 75, 100 or 150 mg orally once daily for 10 days as monotherapy, or matching placebo, randomised 4:1 within each dose cohort. The 25, 50, 75 and 150 mg doses were given as multiples of a 25 mg tablet (formulation F1); the 100 mg dose used a single 100 mg tablet of a different formulation (F2).",
    regions        = "10 sites: 9 in the United States (52 of 54 patients) and 1 in Argentina (2 patients, both in the 100 mg cohort)",
    endpoint       = "Change from baseline in plasma MCP-1 (CCL2) concentration on day 10, on the log10 scale, in log10 pg/mL.",
    notes          = paste(
      "n_subjects is NA deliberately. Marier 2011 states neither an analysis-set size nor a per-cohort n for the MCP-1 exposure-response, and the only per-cohort n values in the paper are the PK set (Table 2) and the HIV-1 RNA set (Table 3), neither of which the paper says applies here. Counting points off Figure 4 would be a guess, so no number is asserted. 54 patients were screened and entered study 652-2-201 and are the population of Table 1; the demographic percentages above are that 54-patient denominator.",
      "The MCP-1 analysis is explicitly EXPLORATORY: Methods 'Pharmacokinetic/pharmacodynamic modeling' (p. 2770) introduces it as 'An exploratory analysis was performed by assessing the relationship between drug exposure and change from baseline in the inflammatory marker MCP-1', and the Results close with 'Additional studies will be required to assess the longer-term effect of TBR-652 on MCP-1' (p. 2773). Treat the parameters accordingly.",
      "No baseline MCP-1 concentration is reported anywhere in the paper, so the model can only return the change from baseline and cannot be converted to an absolute MCP-1 concentration without an external baseline. This is recorded in the vignette's Assumptions and deviations.",
      "Interpretation the authors give (Results p. 2773 and Discussion p. 2773): MCP-1 rises steeply with dose and plateaus at the exposures associated with the 150 mg cohort, which they read as 'a strong CCR2 blockade at the higher dose levels'. Supporting in-vitro potency from the Introduction (p. 2768): cenicriviroc inhibits CCR2 with an IC50 of 5.9 nM."
    )
  )

  ini({
    # =========================================================================
    # Simple Emax exposure-response model, the same form the paper fitted to
    # HIV-1 RNA but estimated independently on the MCP-1 data. Marier 2011
    # Results p. 2772: "The relationship between the exposure of TBR-652 and
    # MCP-1 plasma concentrations was described using a simple Emax model.
    # Results obtained with the Emax model for MCP-1 are presented in Fig. 4."
    #
    #   dmcp1 = emax * Css / (ic50 + Css)
    #
    # No intercept term: Figure 4's fitted curve rises from the origin, where
    # the placebo subjects (Css = 0) are plotted.
    # =========================================================================

    emax <- 2.63
    label("Maximum change from baseline in log10 plasma MCP-1 at saturating cenicriviroc exposure (log10 pg/mL)")
    # Marier 2011 Results pp. 2772-2773: "The Emax and IC50 of TBR-652 were
    # 2.63 log10 and 29.8 ng/ml, respectively." SE = 0.233 log10 pg/mL
    # (Results p. 2773), i.e. RSE 8.9% and a Wald 95% CI of (2.17, 3.09).
    #
    # POSITIVE, unlike the HIV-1 RNA companion. Three independent checks on
    # the sign, because an unsigned number quoted next to a signed sibling is
    # exactly where a dropped minus sign hides:
    #   (1) The raw PDF text layer renders minus signs as Symbol-font glyphs
    #       and does so on every occurrence of the -1.43 HIV-1 RNA Emax; no
    #       such glyph precedes 2.63.
    #   (2) Figure 4's y-axis runs 0.0 to 3.0 with no negative region, and its
    #       fitted curve rises to an asymptote just under 2.5. Evaluating this
    #       model at the plot's right-hand edge gives
    #       2.63 * 490 / (29.8 + 490) = 2.48, which is that asymptote.
    #   (3) The mechanism requires it: blocking CCR2 blocks the receptor that
    #       clears MCP-1, so MCP-1 accumulates. The paper says so directly --
    #       "MCP-1 concentrations increase rapidly with higher dose levels".
    #
    # Encoded on the LINEAR scale rather than as log(emax), matching the
    # companion file, where the negative value forces it. Keeping the pair
    # parallel makes the sign contrast between the two endpoints legible at
    # the ini() line rather than only in prose.

    lic50 <- log(29.8)
    label("Log of the average steady-state cenicriviroc concentration producing half of the MCP-1 Emax (ng/mL)")
    # Marier 2011 Results pp. 2772-2773: IC50 = 29.8 ng/mL. SE = 9.45 ng/mL
    # (Results p. 2773), i.e. RSE 31.7% and a Wald 95% CI of
    # (11.3, 48.3) ng/mL -- imprecise, but comfortably bounded away from
    # zero, and better determined than the 13.1 ng/mL IC50 of the HIV-1 RNA
    # companion (RSE 49.8%). This IC50 is 2.3-fold HIGHER than the antiviral
    # one, i.e. more cenicriviroc exposure is needed for half-maximal CCR2
    # blockade than for half-maximal CCR5-mediated viral suppression, which
    # is consistent with the in-vitro potency ordering the paper reports in
    # its Introduction. The vignette asserts the ratio.

    # =========================================================================
    # No inter-individual variability and no residual error are reported.
    # As with the companion model, Marier 2011 fitted this curve in Phoenix
    # WinNonlin 6.1 to pooled individual (Css, delta-log MCP-1) pairs and
    # publishes only the two point estimates and their standard errors.
    # Figure 4 shows substantial residual scatter (roughly +/- 0.5 log10
    # pg/mL about the curve, wider at low exposures) but no estimate of it is
    # given, so nothing is invented here. Per the standing policy on
    # unreported residual error, addSd is FIXED at 0 and the model returns
    # the deterministic curve.
    # =========================================================================
    addSd <- fixed(0)
    label("Additive residual error on the change from baseline in log10 plasma MCP-1 (ZERO - not reported in source)")
  })

  model({
    ic50 <- exp(lic50)

    # -------------------------------------------------------------------------
    # Marier 2011 simple Emax model for MCP-1, Results p. 2772, drawn as
    # Figure 4 (p. 2773):
    #
    #   dmcp1 = emax * Css / (ic50 + Css)
    #
    # emax is positive, so the returned change from baseline is positive
    # (MCP-1 accumulates) and bounded above by emax. At CSS_CVC = ic50 the
    # model returns emax / 2 = 1.315 log10 pg/mL, the definition of the
    # reported IC50, asserted in the vignette. At CSS_CVC = 0 (placebo) it
    # returns exactly 0.
    #
    # Units: CSS_CVC and ic50 are both ng/mL, so the quotient is
    # dimensionless and the product carries emax's units of log10 pg/mL.
    # dmcp1 is a CHANGE FROM BASELINE on the log10 scale, so it is a
    # log10 FOLD-CHANGE: an absolute day-10 MCP-1 concentration is
    # baseline_pg_per_mL * 10^dmcp1. The paper reports no baseline MCP-1
    # concentration, so this model cannot produce absolute concentrations on
    # its own.
    # -------------------------------------------------------------------------
    dmcp1 <- emax * CSS_CVC / (ic50 + CSS_CVC)

    dmcp1 ~ add(addSd)
  })
}
