Marques_2025_salbutamol <- function() {
  description <- paste(
    "Two-compartment population PK model for oral salbutamol (4 mg",
    "immediate-release tablet, every 6 h) with transit-compartment",
    "first-order absorption and linear elimination, fitted in Monolix to a",
    "fully in silico cohort: 838 plasma concentrations from 40 VIRTUAL",
    "patients generated by a GastroPlus PBPK model, not from clinical",
    "measurements. Encodes Marques 2025 Table 6 (the published final-model",
    "parameter table) VERBATIM. IMPORTANT: the Table 6 estimates as printed",
    "do not reproduce the paper's own published summaries of the same",
    "model -- simulating them gives a steady-state peak at 3.9 h into a 6 h",
    "interval with a peak/trough ratio of 1.3, against the Figure 5 VPC's",
    "peak near 1 h and ratio near 3, and underpredicts the Table S3 Cmax",
    "roughly 6-fold and AUC roughly 4-fold. Table 7 reports EBE geometric",
    "means for the same parameters that differ by 32-45x (Mtt) and about",
    "2x (Cl) and 3x (V1). These are documented as errata in the validation",
    "vignette, which reports the discrepancies rather than concealing them;",
    "the packaged model is the published table, not a corrected refit. No",
    "covariate effects are encoded: the paper's headline claim is a",
    "covariate model, but no coefficient, functional form, reference value",
    "or centering constant is published for any covariate anywhere in the",
    "article or its supplement (see covariatesDataExcluded)."
  )
  reference <- paste(
    "Marques L, Vale N. Improving Individualized Salbutamol Treatment: A",
    "Population Pharmacokinetic Model for Oral Salbutamol in Virtual",
    "Patients. Pharmaceutics. 2025;17(1):39.",
    "doi:10.3390/pharmaceutics17010039. Parameters from Table 6",
    "('Parameter estimates for the final model'), transcribed as printed."
  )
  vignette <- "Marques_2025_salbutamol"
  # Dose is in mg (4 mg tablet) and volumes are in L, so central / vc is
  # mg/L = ug/mL, which is the unit the paper tabulates concentrations in
  # throughout (Table 4, Table S3, Figures 3-5). No value is converted.
  units <- list(time = "h", dosing = "mg", concentration = "ug/mL")

  compartmentData <- list(
    depot = list(
      analyte = "salbutamol", units = "mg",
      specimen = "administration site", verified = TRUE
    ),
    central = list(
      analyte = "salbutamol", units = "mg",
      specimen = "plasma", verified = TRUE
    ),
    peripheral1 = list(
      analyte = "salbutamol", units = "mg",
      specimen = "tissue", verified = TRUE
    )
  )

  # No covariate enters model(). Section 2.4 screened eight covariates and
  # Section 3.3.2 reports that gender acts on Mtt and Cl, weight and BSA on
  # V1 and Cl, and health status on Cl -- but Table 6 (the final-model table)
  # contains no covariate rows, and no coefficient, functional form,
  # reference value or centering constant for any covariate appears in the
  # article or in Supplementary Tables S1-S5. Supplementary Table S5 is a
  # correlation / p-value screen only, and it CONTRADICTS the Section 3.3.2
  # text at three places (noted per entry below). The screened covariates are
  # recorded here so the paper's headline claim is not lost.
  covariatesDataExcluded <- list(
    AGE = list(
      description        = "Age",
      units              = "years",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Screened as a continuous covariate (Section 2.4) and not retained.",
        "Table S5 reports no significant correlation with any PK parameter",
        "(smallest p = 0.128, on V1). The Discussion states 'the results",
        "indicate that age does not affect the PK parameters of orally",
        "administered salbutamol'. Cohort range 5-65 years (Section 2.2),",
        "mean 39.5 (SD 18.4) years (Table 5)."
      ),
      source_name        = "Age"
    ),
    WT = list(
      description        = "Body weight",
      units              = "kg",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Section 3.3.2 reports 'a significant impact of weight on V1 and",
        "Cl'; no coefficient is published. Table S5 SUPPORTS only the V1",
        "effect (r = 0.516, p < 0.001) and CONTRADICTS the Cl effect",
        "(r = -0.058, p = 0.724). Table 7 stratifies EBE V1 and Cl at",
        "26.4-75.0 vs 75.0-109 kg, but those are descriptive subgroup",
        "geometric means, not covariate coefficients. Cohort mean 60.2",
        "(SD 19.8) kg, range 26-109 kg (Table 5; Discussion)."
      ),
      source_name        = "Weight"
    ),
    BSA = list(
      description        = "Body surface area",
      units              = "m^2",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Section 3.3.2 reports 'BSA effects on V1 and Cl'; no coefficient is",
        "published. Table S5 SUPPORTS only the V1 effect (r = 0.510,",
        "p < 0.001) and CONTRADICTS the Cl effect (r = -0.075, p = 0.646).",
        "Table 7 stratifies EBE V1 and Cl at 0.94-1.60 vs 1.60-2.37 m^2",
        "(descriptive only). Cohort mean 1.64 (SD 0.330) m^2, range",
        "0.94-2.37 m^2 (Table 5; Discussion)."
      ),
      source_name        = "BSA"
    ),
    SEXF = list(
      description        = "Female sex indicator (1 = female, 0 = male)",
      units              = "(binary)",
      type               = "binary",
      reference_category = "0 = male",
      notes              = paste(
        "Section 3.3.2 reports 'potential gender effects on Mtt and Cl'; no",
        "coefficient is published. This is the one covariate Table S5",
        "supports on both parameters (ANOVA F = 4.378, p = 0.043 on Mtt;",
        "F = 4.828, p = 0.034 on Cl). Table 7 gives EBE geometric-mean Mtt",
        "of 0.21 h (female) and 0.30 h (male) -- descriptive subgroup",
        "summaries, and both 32-45x below Table 6's population Mtt of",
        "9.50 h (see the vignette Errata). The source reports a two-level",
        "'Female' / 'Male' categorical; SEXF is the canonical encoding.",
        "Cohort 16 female (40%), 24 male (60%) (Table 5)."
      ),
      source_name        = "Gender"
    ),
    RACE_ASIAN = list(
      description        = paste(
        "Asian (non-Chinese) heritage indicator (1 = Asian, 0 = American or",
        "Chinese)"
      ),
      units              = "(binary)",
      type               = "binary",
      reference_category = "0 = American (the modal group, 50% of the cohort)",
      notes              = paste(
        "Race was screened (Section 2.4) and explicitly NOT retained: the",
        "Discussion states 'Race was not included as a covariate in the",
        "model, as no significant statistical correlations with PK",
        "parameters were found', consistent with Table S5 (smallest",
        "p = 0.071, on Mtt). The GastroPlus virtual cohort has three race",
        "levels -- American 20 (50%), Asian 10 (25%), Chinese 10 (25%)",
        "(Table 5) -- so two indicators are needed to span it; this is the",
        "Asian one, paired with RACE_CHINESE, against an American",
        "reference. Note that Figure S4's caption asserts 'Race has a",
        "significant impact on kel', which contradicts both the Discussion",
        "and Table S5."
      ),
      source_name        = "Race"
    ),
    RACE_CHINESE = list(
      description        = paste(
        "Chinese heritage indicator (1 = Chinese, 0 = American or Asian)"
      ),
      units              = "(binary)",
      type               = "binary",
      reference_category = "0 = American (the modal group, 50% of the cohort)",
      notes              = paste(
        "Second of the two indicators spanning the three-level race",
        "covariate (American / Asian / Chinese; Table 5). Screened and not",
        "retained -- see the RACE_ASIAN entry for the full rationale and the",
        "Figure S4 caption conflict."
      ),
      source_name        = "Race"
    ),
    CYP2D6 = list(
      description        = "CYP2D6 relative expression level",
      units              = "% (GastroPlus relative expression)",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Screened as a continuous covariate (Section 2.4) and not retained;",
        "Table S5 reports no significant correlation with any PK parameter",
        "(smallest p = 0.211, on V1). The Discussion notes that CYP2D6 is a",
        "salbutamol-metabolizing enzyme and that higher female activity was",
        "a candidate explanation for the gender effect on Cl, but that",
        "'CYP2D6 expression, as well as CYP2C19 expression, were examined as",
        "covariates, showing no influence on the PK parameters'. The value",
        "is a GastroPlus-assigned relative expression percentage, not a",
        "probe-substrate clearance or an activity score: cohort mean 1.90",
        "(SD 1.60) % (Table 5). Orientation: higher = higher CYP2D6",
        "activity."
      ),
      source_name        = "CYP2D6 expression"
    ),
    CYP2C19 = list(
      description        = "CYP2C19 relative expression level",
      units              = "% (GastroPlus relative expression)",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Screened as a continuous covariate (Section 2.4) and not retained;",
        "Table S5 reports no significant correlation with any PK parameter",
        "(smallest p = 0.219, on V1). The value is a GastroPlus-assigned",
        "relative expression percentage, not a probe-substrate metabolic",
        "ratio: cohort mean 1.30 (SD 1.50) % (Table 5). Orientation: higher",
        "= higher CYP2C19 activity (the expression-level form, not the",
        "inverted S/R-mephenytoin-ratio form)."
      ),
      source_name        = "CYP2C19 expression"
    ),
    HEPIMP_MILD = list(
      description        = paste(
        "Mild hepatic impairment indicator (1 = Child-Pugh A cirrhosis,",
        "0 = healthy or obese)"
      ),
      units              = "(binary)",
      type               = "binary",
      reference_category = "0 = healthy (non-obese, no comorbidity)",
      notes              = paste(
        "Section 3.3.2 reports 'a significant impact of health status on",
        "Cl'; no coefficient is published, and Table S5 CONTRADICTS the",
        "claim (ANOVA F = 0.492, p = 0.615 on Cl; no p < 0.05 on any",
        "parameter). Health status is a three-level categorical in the",
        "source -- healthy 26 (65%), obese 4 (10%), cirrhosis Child-Pugh A",
        "10 (25%) (Table 5) -- so two indicators would be needed to span",
        "it. Only the cirrhosis level maps onto a registered canonical:",
        "Child-Pugh A is an explicit source alias of HEPIMP_MILD. The obese",
        "level (BMI >= 30 per Section 2.2) has no registered canonical --",
        "DIS_OBESE_MORBID is a morbid-obesity (BMI >= 40) indicator and is",
        "the wrong severity -- so that level is recorded here in prose",
        "rather than under an unregistered column name. Because nothing",
        "enters model(), the incomplete decomposition costs nothing; a",
        "future model that actually estimates a health-status effect on this",
        "cohort would need a non-morbid obesity canonical registered first."
      ),
      source_name        = "Health status"
    )
  )

  population <- list(
    species        = "human (virtual; GastroPlus PBPK-generated, not measured)",
    n_subjects     = 40,
    n_studies      = 0,
    n_observations = 838,
    age_range      = "5-65 years (Section 2.2)",
    age_median     = "39.5 years (mean, SD 18.4; Table 5)",
    weight_range   = "26-109 kg (Discussion)",
    weight_median  = "60.2 kg (mean, SD 19.8; Table 5)",
    bsa_range      = "0.94-2.37 m^2 (Discussion)",
    bsa_median     = "1.64 m^2 (mean, SD 0.330; Table 5)",
    sex_female_pct = 40,
    race_ethnicity = c(American = 50, Asian = 25, Chinese = 25),
    disease_state  = paste(
      "Mixed virtual cohort: healthy 26 (65%), obese 4 (10%), cirrhosis",
      "Child-Pugh A 10 (25%) (Table 5). Intended indication is asthma, but",
      "no asthma severity or lung-function covariate was simulated."
    ),
    dose_range     = paste(
      "4 mg oral salbutamol as an immediate-release tablet every 6 h for",
      "24 h (Section 2.2 and Table S3). Section 3.1 instead states the",
      "regimen was 'adjusted to 4 mg every 4 h'; Table S3's Tmax of",
      "18.8-19.2 h and the Figure 5 VPC x-axis of 0-6 h both pin the",
      "interval at 6 h, so q6h is the regimen encoded and validated."
    ),
    regions        = NA_character_,
    notes          = paste(
      "FULLY IN SILICO. There are no clinical observations in this dataset.",
      "A GastroPlus 9.9 PBPK model of oral salbutamol (drug parameters from",
      "ADMET Predictor 12.0, Table 1 / Table 3; tissue Kp from Table 2) was",
      "first checked against literature single-dose reference values",
      "(Table 4: observed Cmax 0.00725 ug/mL, Tmax 2.35 h, AUCinf 0.0318",
      "ug*h/mL vs predicted 0.00919, 1.28, 0.0553 -- all within 2-fold),",
      "then run through the GastroPlus Population Simulator (PEAR",
      "age-related physiologies) to generate 40 virtual patients in four",
      "groups by ethnicity and health status. The resulting 838",
      "concentration-time points over 24 h were treated as the observed",
      "data for the Monolix 2024R1 SAEM fit. Bioavailability was not",
      "estimated by the popPK model, so Cl, V1, Q and V2 are apparent",
      "(CL/F etc.); for reference the PBPK cohort's own F was 39.6-46.0%",
      "and fraction absorbed 78.3-83.6% (Table S3). Detailed per-group",
      "demographics are in Supplementary Table S2. NCA was performed in",
      "PKAnalix 2024R1 (linear-trapezoidal-linear)."
    )
  )

  ini({
    # ---------------------------------------------------------------------
    # Structural parameters -- Marques 2025 Table 6, "Parameter estimates
    # for the final model", Fixed effects block, transcribed exactly as
    # printed. Bioavailability was not estimated (Monolix F = 1 against the
    # full 4 mg nominal dose), so Cl, V1, Q and V2 are apparent.
    #
    # READ THE VIGNETTE ERRATA BEFORE SIMULATING. Table 6's Mtt, Cl and V1
    # are each contradicted by the paper's own Table 7 EBE geometric means,
    # by its Table S3 NCA summary and by its Figure 5 VPC. They are shipped
    # as printed on the operator's ruling; the vignette quantifies every
    # discrepancy.
    # ---------------------------------------------------------------------
    lmtt <- log(9.50);  label("Mean transit time Mtt (h)")                            # Table 6 Fixed effects: Mtt = 9.50 h (RSE 7.14%)
    lktr <- log(0.15);  label("Transit rate constant Ktr (1/h)")                      # Table 6 Fixed effects: Ktr = 0.15 1/h (RSE 9.21%)
    lka  <- log(2.91);  label("Absorption rate constant ka (1/h)")                    # Table 6 Fixed effects: ka = 2.91 1/h (RSE 6.80%)
    lcl  <- log(140);   label("Apparent clearance CL/F (L/h)")                        # Table 6 Fixed effects: Cl = 140 L/h (RSE 223%) -- the paper's own Section 3.3.2 flags this RSE as failing its < 30% acceptance criterion
    lvc  <- log(77.5);  label("Apparent central volume of distribution V1/F (L)")     # Table 6 Fixed effects: V1 = 77.5 L (RSE 97.2%) -- likewise flagged by the authors as failing the < 30% criterion
    lq   <- log(48.9);  label("Apparent intercompartmental clearance Q/F (L/h)")      # Table 6 Fixed effects: Q = 48.9 L/h (RSE 24.9%)
    lvp  <- log(130);   label("Apparent peripheral volume of distribution V2/F (L)")  # Table 6 Fixed effects: V2 = 130 L (RSE 21.4%)

    # ---------------------------------------------------------------------
    # IIV -- Marques 2025 Table 6, Random effects block.
    #
    # Monolix reports random effects as omega, the STANDARD DEVIATION of the
    # random effect on the transformed (log) scale; nlmixr2's ini() takes
    # VARIANCES, so each value below is the published omega squared.
    #
    # Section 3.3.1 states "A normal distribution was used to describe IIV",
    # which would make these SDs of untransformed parameters. That reading
    # is not sustainable: Table 7's SD column for the same parameters is
    # dimensionless and greater than 1 throughout (1.37-3.89), i.e. those
    # are GEOMETRIC SDs, and they line up with exponentiated Table 6 omegas
    # (exp(0.32) = 1.38 against Mtt male SD 1.37; exp(0.36) = 1.43 against
    # V1 SDs 1.54-1.84; exp(0.38) = 1.46 against Cl SDs 1.45-2.28). The
    # omegas are therefore log-scale SDs and IIV is log-normal, which is
    # also the Monolix default for positive PK parameters. Documented in the
    # vignette Errata.
    #
    # Section 3.3.2: "No significant correlations were found between PK
    # parameters", so all seven random effects are diagonal.
    # ---------------------------------------------------------------------
    etalmtt ~ 0.1849   # Table 6 Random effects: IIV(Mtt) = 0.43 (RSE 13.0%); 0.43^2 = 0.1849
    etalktr ~ 0.1024   # Table 6 Random effects: IIV(Ktr) = 0.32 (RSE 13.8%); 0.32^2 = 0.1024
    etalka  ~ 0.1681   # Table 6 Random effects: IIV(ka)  = 0.41 (RSE 15.4%); 0.41^2 = 0.1681
    etalcl  ~ 0.1444   # Table 6 Random effects: IIV(Cl)  = 0.38 (RSE 13.0%); 0.38^2 = 0.1444
    etalvc  ~ 0.1296   # Table 6 Random effects: IIV(V1)  = 0.36 (RSE 12.3%); 0.36^2 = 0.1296
    etalq   ~ 0.8464   # Table 6 Random effects: IIV(Q)   = 0.92 (RSE 14.9%); 0.92^2 = 0.8464
    etalvp  ~ 0.7569   # Table 6 Random effects: IIV(V2)  = 0.87 (RSE 27.4%); 0.87^2 = 0.7569

    # ---------------------------------------------------------------------
    # Residual error -- Marques 2025 Table 6, "Error model parameters".
    # Section 3.3.1 gives the combined model as Y = F + (a + b*F)*eps, i.e.
    # the SDs add LINEARLY (Monolix "combined1"), not in quadrature, so the
    # observation line below carries combined1(). Concentrations are ug/mL,
    # so a is in ug/mL and b is a dimensionless fraction.
    # ---------------------------------------------------------------------
    addSd  <- 1.9e-5; label("Additive residual standard deviation (ug/mL)")           # Table 6 Error model parameters: a = 0.19 x 10^-4 = 1.9e-5 ug/mL (RSE 20.2%)
    propSd <- 1.5e-3; label("Proportional residual standard deviation (fraction)")    # Table 6 Error model parameters: b = 0.15 x 10^-2 = 1.5e-3 (RSE 37.2%)
  })

  model({
    # 1. Individual PK parameters (log-normal; see the ini() note on the IIV
    #    distribution).
    mtt <- exp(lmtt + etalmtt)
    ktr <- exp(lktr + etalktr)
    ka  <- exp(lka  + etalka)
    cl  <- exp(lcl  + etalcl)
    vc  <- exp(lvc  + etalvc)
    q   <- exp(lq   + etalq)
    vp  <- exp(lvp  + etalvp)

    # 2. Transit-chain length. Monolix's transit-absorption parameterisation
    #    estimates Mtt and Ktr as two independent parameters and derives the
    #    (continuous) number of transit compartments as n = Mtt * Ktr - 1.
    #    Table 6's printed pair is self-consistent under this relation:
    #    9.50 * 0.15 - 1 = 0.425, and rxode2's transit(n, mtt) internally
    #    uses ktr = (n + 1) / mtt = 1.425 / 9.50 = 0.15 1/h exactly, so both
    #    printed numbers are reproduced by this encoding.
    #
    #    Because Table 6 puts IIV on BOTH Mtt and Ktr, n varies between
    #    individuals and is negative whenever Mtt * Ktr < 1 -- which the
    #    published omegas make true for roughly a quarter of the population.
    #    A negative transit-chain length is not physically interpretable.
    #    rxode2 evaluates the gamma-form input flux without error for n > -1
    #    (n + 1 > 0 always holds here), so the model still solves, but this
    #    is a further internal inconsistency in Table 6 and is quantified in
    #    the vignette Errata.
    nn <- mtt * ktr - 1

    # 3. Micro-constants.
    kel <- cl / vc
    k12 <- q  / vc
    k21 <- q  / vp

    # 4. ODE system: transit-chain absorption into a depot that empties into
    #    central at first-order rate ka, two-compartment disposition, linear
    #    elimination (Section 3.3.1). rxode2's transit() returns the
    #    closed-form (gamma-density) input rate to depot from the most recent
    #    dose; f(depot) <- 0 suppresses the ordinary bolus so the analytical
    #    chain is the only input pathway, while transit() still reads the raw
    #    dose amount via podo(). Doses are given to depot.
    d/dt(depot)       <- transit(nn, mtt) - ka * depot
    d/dt(central)     <- ka * depot - kel * central - k12 * central + k21 * peripheral1
    d/dt(peripheral1) <-                              k12 * central - k21 * peripheral1

    f(depot) <- 0  # suppress the bolus into depot; transit() drives the input rate

    # 5. Observation. Dose in mg / volume in L gives mg/L = ug/mL, the unit
    #    the paper tabulates. combined1() makes the additive and
    #    proportional SDs add linearly, per the Section 3.3.1 error equation.
    Cc <- central / vc
    Cc ~ add(addSd) + prop(propSd) + combined1()
  })
}
