OrtizZacarias_2018_fosfomycin_iv <- function() {
  description <- "Two-compartment intravenous population PK model for fosfomycin disodium in adults, assembled by Ortiz Zacarias 2018 from previously published literature parameter estimates (Kjellsson 2009) rather than fitted to new data, and used to simulate multiple-dose regimens for systemic infections. Clearance is a mean-centered linear function of creatinine clearance. Companion of the oral model OrtizZacarias_2018_fosfomycin_oral, which extends this disposition with a gastrointestinal / transit absorption chain and an additional apparent biliary elimination route."
  reference <- "Ortiz Zacarias NV, Dijkmans AC, Burggraaf J, Mouton JW, Wilms EB, van Nieuwkoop C, Touw DJ, Kamerling IMC, Stevens J. Fosfomycin as a potential therapy for the treatment of systemic infections: a population pharmacokinetic model to simulate multiple dosing regimens. Pharmacol Res Perspect. 2018;6(1):e00378. doi:10.1002/prp2.378"
  vignette <- "OrtizZacarias_2018_fosfomycin"
  units <- list(time = "h", dosing = "mg", concentration = "mg/L")

  compartmentData <- list(
    central = list(analyte = "fosfomycin", units = "mg", specimen = "serum", verified = TRUE),
    peripheral1 = list(analyte = "fosfomycin", units = "mg", specimen = "serum", verified = TRUE)
  )

  covariateData <- list(
    CRCL = list(
      description = "Creatinine clearance (raw, NOT BSA-normalized)",
      units = "mL/min",
      type = "continuous",
      reference_category = NULL,
      notes = "Source column CLCR. Ortiz Zacarias 2018 Sect. 2.2 Covariates: 'A mean-centered linear relationship between creatinine clearance (CLCR) and clearance (CL) was reported, and incorporated as such in the simulated clearance for the ith individual', Equation 5: CLi = [CLTV + 0.0141 * (CLCR,i - 103)] * exp(gi). The centering constant 103 mL/min and the simulated CLCR distribution (mean 103, SD 41 mL/min, truncated at the minimum and maximum reported values) were taken from Sauermann et al. (reference 32 of the source paper), NOT from the cohort the PK parameters came from. The estimating equation for CLCR is not named in the source paper; the values are raw mL/min with no BSA normalization, which is within scope of the canonical CRCL column per inst/references/covariate-columns.md. Because the effect is additive and mean-centered, exp(lcl) is the typical CL at CLCR = 103 mL/min, not a renal-function-free intercept.",
      source_name = "CLCR"
    )
  )

  population <- list(
    species = "human",
    n_subjects = 12L,
    n_studies = 1L,
    age_range = "Adults; not further specified by Ortiz Zacarias 2018",
    disease_state = "Patients scheduled for abscess drainage (Ortiz Zacarias 2018 Sect. 2.1: 'a previously reported two-compartment population PK model of fosfomycin, developed on 12 patients scheduled for abscess drainage'). The creatinine-clearance covariate distribution used for simulation comes from a separate published cohort (Sauermann et al.), not from these 12 patients.",
    dose_range = "Simulated regimens: 3, 4, 6 and 8 g fosfomycin disodium every 8 h, and 4 and 6 g every 6 h, given as 30-minute intravenous infusions (Sect. 3.2 and Table 2). Validation scenarios: 8 doses of 500 mg every 6 h; 500 mg over a 5-minute infusion; 50 mg/kg bolus (Sect. 2.4).",
    regions = "Not reported",
    renal_function = "Simulated CLCR mean 103 mL/min, SD 41 mL/min, truncated between the minimum and maximum values reported by Sauermann et al. (Sect. 2.2)",
    notes = "Ortiz Zacarias 2018 fitted NO data of its own. It is a simulation study: the structural model and every parameter value were taken from previously published analyses, and 1000 virtual individuals were generated by sampling both the parameter-uncertainty distribution and the inter-individual-variability distribution (Sect. 2.3). The intravenous disposition parameters (CL, Vc, Vp, Q and their IIV and uncertainty) all come from Kjellsson et al., reference 25 of the source paper, via Table 1. n_subjects = 12 records the size of that upstream cohort, which is the number of real subjects this model's parameters rest on; it is not a cohort studied by Ortiz Zacarias 2018."
  )

  ini({
    # All values from Ortiz Zacarias 2018 Table 1, 'Mean estimate (90% CI or
    # SD)' column, rows sourced to Kjellsson et al. (reference 25). Table 1
    # footnote b marks CL and Q as 'Value converted to match units' -- the
    # upstream model was parameterized by an elimination rate constant ke and
    # Ortiz Zacarias 2018 converted it to a clearance.
    #
    # The 'Uncertainty (variance)' column of Table 1 (1.4841 for CL, 8.2329
    # for Vc, 6.2120 for Vp, 14.3892 for Q) describes the PARAMETER-UNCERTAINTY
    # distribution that the source paper resampled over in its Monte Carlo
    # simulations (Equations 2-4). That is a layer above the model itself and
    # is not part of ini(); it is reproduced in the validation vignette.

    lcl <- log(5.808); label("Clearance CL at CLCR = 103 mL/min (L/h)") # Table 1 CL = 5.808 L/h (90% CI 3.792-7.80)
    lvc <- log(10.1); label("Central volume of distribution Vc (L)") # Table 1 Vc = 10.1 L (90% CI 5.36-14.8)
    lvp <- log(9.80); label("Peripheral volume of distribution Vp (L)") # Table 1 Vp = 9.80 L (90% CI 5.70-13.9)
    lq <- log(15.36); label("Intercompartmental clearance Q (L/h)") # Table 1 Q = 15.36 L/h (90% CI 9.12-21.6)

    # Covariate effect. Equation 5 is additive and mean-centered at
    # 103 mL/min, so the slope carries units of L/h per mL/min.
    e_crcl_cl <- 0.0141
    label("Slope of the mean-centered linear CLCR effect on CL (L/h per mL/min)") # Table 1 row 'COV CLCR-CL' = 0.0141; Equation 5

    # Inter-individual variability. Sect. 2.1: 'IIV was reported to be
    # log-normally distributed for CL, Vc, and Vp, and incorporated as such
    # in the model; g is assumed to be normally distributed around 0 with its
    # reported variance x2.' The Table 1 'IIV' column therefore holds
    # VARIANCES on the exponential eta, not SDs or CVs.
    etalcl ~ 0.238 # Table 1 CL row, 'IIV' column = 0.238 variance -> CV = sqrt(exp(0.238) - 1) = 51.9%
    etalvc ~ 0.238 * 1.64 # Table 1 Vc row, 'IIV' column printed literally as '0.238 * 1.64' = 0.39032 variance -> CV = 69.9%
    etalvp ~ 0.197 # Table 1 Vp row, 'IIV' column = 0.197 variance -> CV = 46.8%
    # No eta on Q: Table 1 Q row, 'IIV' column = 'NI' (not identified).

    # Residual error. Ortiz Zacarias 2018 estimated nothing and reports no
    # residual-error model anywhere; its 90% prediction intervals (Figures 2
    # and 3) are built from parameter uncertainty and IIV alone. Encoded as
    # fixed(0) rather than invented, per the library's unreported-RUV policy.
    addSd <- fixed(0)
    label("Additive residual SD on Cc (mg/L); no residual-error model is reported by the source") # Sect. 2.3-2.4: simulation only, no estimation step
  })

  model({
    # Individual clearance follows Equation 5 exactly: the mean-centered
    # additive CLCR term is added to the typical clearance BEFORE the
    # multiplicative log-normal eta is applied.
    cl <- (exp(lcl) + e_crcl_cl * (CRCL - 103)) * exp(etalcl)
    vc <- exp(lvc + etalvc)
    vp <- exp(lvp + etalvp)
    q <- exp(lq)

    # Two-compartment disposition micro-constants (Figure 1, CMT 3 <-> CMT 4).
    kel <- cl / vc
    k12 <- q / vc
    k21 <- q / vp

    # Intravenous doses are administered into `central` via the event table,
    # as a 30-minute infusion for the Table 2 regimens (Sect. 3.2). Figure 1
    # parameterizes the infusion by Qinf and tinf; no value is given for
    # either, so the infusion is supplied through the data rather than fitted.
    d/dt(central) <- -kel * central - k12 * central + k21 * peripheral1
    d/dt(peripheral1) <- k12 * central - k21 * peripheral1

    # Serum fosfomycin concentration in mg/L (dose in mg, volumes in L).
    Cc <- central / vc
    Cc ~ add(addSd)
  })
}
