OrtizZacarias_2018_fosfomycin_oral <- function() {
  description <- "Oral population PK model for fosfomycin tromethamine in adults, assembled by Ortiz Zacarias 2018 from previously published literature parameter estimates (Kjellsson 2009 disposition, Segre 1987 absorption) rather than fitted to new data, and used to simulate multiple-dose regimens for systemic infections. A gastrointestinal depot drains by two competing first-order routes -- absorption into a transit compartment and a loss that accounts for incomplete oral bioavailability -- and the two-compartment disposition carries an additional apparent biliary elimination rate constant. Clearance is a mean-centered linear function of creatinine clearance. Companion of the intravenous model OrtizZacarias_2018_fosfomycin_iv."
  reference <- "Ortiz Zacarias NV, Dijkmans AC, Burggraaf J, Mouton JW, Wilms EB, van Nieuwkoop C, Touw DJ, Kamerling IMC, Stevens J. Fosfomycin as a potential therapy for the treatment of systemic infections: a population pharmacokinetic model to simulate multiple dosing regimens. Pharmacol Res Perspect. 2018;6(1):e00378. doi:10.1002/prp2.378"
  vignette <- "OrtizZacarias_2018_fosfomycin"
  units <- list(time = "h", dosing = "mg", concentration = "mg/L")

  compartmentData <- list(
    depot = list(analyte = "fosfomycin", units = "mg", specimen = "administration site", verified = TRUE),
    transit1 = list(analyte = "fosfomycin", units = "mg", specimen = "administration site", verified = TRUE),
    central = list(analyte = "fosfomycin", units = "mg", specimen = "serum", verified = TRUE),
    peripheral1 = list(analyte = "fosfomycin", units = "mg", specimen = "serum", verified = TRUE)
  )

  covariateData <- list(
    CRCL = list(
      description = "Creatinine clearance (raw, NOT BSA-normalized)",
      units = "mL/min",
      type = "continuous",
      reference_category = NULL,
      notes = "Source column CLCR. Ortiz Zacarias 2018 Sect. 2.2 Covariates: 'A mean-centered linear relationship between creatinine clearance (CLCR) and clearance (CL) was reported, and incorporated as such in the simulated clearance for the ith individual', Equation 5: CLi = [CLTV + 0.0141 * (CLCR,i - 103)] * exp(gi). The centering constant 103 mL/min and the simulated CLCR distribution (mean 103, SD 41 mL/min, truncated at the minimum and maximum reported values) were taken from Sauermann et al. (reference 32 of the source paper), NOT from either cohort the PK parameters came from. The estimating equation for CLCR is not named in the source paper; the values are raw mL/min with no BSA normalization, which is within scope of the canonical CRCL column per inst/references/covariate-columns.md. Because the effect is additive and mean-centered, exp(lcl) is the typical CL at CLCR = 103 mL/min, not a renal-function-free intercept. The covariate acts only on CL; the additional biliary rate constant kbile carries no covariate.",
      source_name = "CLCR"
    )
  )

  population <- list(
    species = "human",
    n_subjects = 17L,
    n_studies = 2L,
    age_range = "Adults; not further specified by Ortiz Zacarias 2018",
    disease_state = "Two upstream cohorts pooled at the parameter level rather than at the data level: 12 patients scheduled for abscess drainage (Kjellsson et al., source of CL, Vc, Vp and Q) and 5 healthy volunteers who received oral and intravenous fosfomycin (Segre et al., source of k10, k12, k23 and kb).",
    dose_range = "Simulated oral regimens of fosfomycin tromethamine: 2-15 g per dose every 8 h, and 3 and 6 g every 12 or 24 h (Table 3); the paper's headline recommendation is 6-12 g per day divided into three doses. Validation scenarios: single oral doses of 50 mg/kg, 2 g and 5 g (Sect. 2.4).",
    regions = "Not reported",
    renal_function = "Simulated CLCR mean 103 mL/min, SD 41 mL/min, truncated between the minimum and maximum values reported by Sauermann et al. (Sect. 2.2)",
    notes = "Ortiz Zacarias 2018 fitted NO data of its own. It is a simulation study: the structural model and every parameter value were taken from previously published analyses, and 1000 virtual individuals were generated by sampling both the parameter-uncertainty distribution and the inter-individual-variability distribution (Sect. 2.3). n_subjects = 17 is the sum of the two upstream cohorts (12 + 5), which is the number of real subjects this model's parameters rest on; it is not a cohort studied by Ortiz Zacarias 2018. Enterohepatic recirculation (Figure 1, gray: CMT 5 biliary tract -> CMT 6 transit -> CMT 1 GI, via k56 and k61) was tested and EXCLUDED from the final model (Sect. 3.1: 'the median concentrations and 90% PI did not differ substantially ... it was decided to exclude this PK property from the model'), so k56 and k61 are deliberately absent here and kb is a terminal elimination route."
  )

  ini({
    # Disposition parameters from Ortiz Zacarias 2018 Table 1, rows sourced to
    # Kjellsson et al. (reference 25); absorption and biliary parameters from
    # the same table, rows sourced to Segre et al. (reference 24). Table 1
    # footnote b marks CL and Q as 'Value converted to match units'.
    #
    # The 'Uncertainty (variance)' column of Table 1 describes the
    # PARAMETER-UNCERTAINTY distribution the source paper resampled over in its
    # Monte Carlo simulations (Equations 2-4). That is a layer above the model
    # itself and is not part of ini(); it is reproduced in the vignette.
    #
    # Symbol map from Figure 1 to the canonical names used here:
    #   CMT 1 'GI'        -> depot            CMT 2 'TRANS' -> transit1
    #   CMT 3 'Central'   -> central          CMT 4 'Peripheral' -> peripheral1
    #   k12 (CMT 1 -> 2)  -> ka      (absorptive route out of the GI depot)
    #   k10 (out of CMT 1)-> kfec    (competing loss that sets bioavailability)
    #   k23 (CMT 2 -> 3)  -> ktr     (transit compartment into central)
    #   kb  (out of CMT 3)-> kbile   (apparent biliary elimination)
    # Note that the canonical k12 / k21 used inside model() below are the
    # central <-> peripheral1 micro-constants and are NOT the paper's k12.

    lcl <- log(5.808); label("Clearance CL at CLCR = 103 mL/min (L/h)") # Table 1 CL = 5.808 L/h (90% CI 3.792-7.80)
    lvc <- log(10.1); label("Central volume of distribution Vc (L)") # Table 1 Vc = 10.1 L (90% CI 5.36-14.8)
    lvp <- log(9.80); label("Peripheral volume of distribution Vp (L)") # Table 1 Vp = 9.80 L (90% CI 5.70-13.9)
    lq <- log(15.36); label("Intercompartmental clearance Q (L/h)") # Table 1 Q = 15.36 L/h (90% CI 9.12-21.6)

    lka <- log(1.69); label("Absorption rate constant out of the GI depot, paper k12 (1/h)") # Table 1 k12 = 1.69 +/- 0.62 1/h (Segre et al.)
    lkfec <- log(1.24)
    label("Competing first-order loss of unabsorbed drug out of the GI depot, paper k10 (1/h)") # Table 1 k10 = 1.24 +/- 0.55 1/h (Segre et al.)
    lktr <- log(0.34); label("Transit rate constant from the transit compartment into central, paper k23 (1/h)") # Table 1 k23 = 0.34 +/- 0.10 1/h (Segre et al.)
    lkbile <- log(0.50); label("Apparent biliary elimination rate constant out of central, paper kb (1/h)") # Table 1 kb = 0.50 +/- 0.18 1/h (Segre et al.)

    # Covariate effect. Equation 5 is additive and mean-centered at
    # 103 mL/min, so the slope carries units of L/h per mL/min.
    e_crcl_cl <- 0.0141
    label("Slope of the mean-centered linear CLCR effect on CL (L/h per mL/min)") # Table 1 row 'COV CLCR-CL' = 0.0141; Equation 5

    # Inter-individual variability. Sect. 2.1: 'IIV was reported to be
    # log-normally distributed for CL, Vc, and Vp, and incorporated as such
    # in the model; g is assumed to be normally distributed around 0 with its
    # reported variance x2.' The Table 1 'IIV' column therefore holds
    # VARIANCES on the exponential eta, not SDs or CVs.
    etalcl ~ 0.238 # Table 1 CL row, 'IIV' column = 0.238 variance -> CV = sqrt(exp(0.238) - 1) = 51.9%
    etalvc ~ 0.238 * 1.64 # Table 1 Vc row, 'IIV' column printed literally as '0.238 * 1.64' = 0.39032 variance -> CV = 69.9%
    etalvp ~ 0.197 # Table 1 Vp row, 'IIV' column = 0.197 variance -> CV = 46.8%
    # No eta on Q ('NI', not identified) and none on the four Segre rate
    # constants ('ND', no data available) -- Table 1 'IIV' column.

    # Residual error. Ortiz Zacarias 2018 estimated nothing and reports no
    # residual-error model anywhere; its 90% prediction intervals (Figures 2
    # and 3) are built from parameter uncertainty and IIV alone. Encoded as
    # fixed(0) rather than invented, per the library's unreported-RUV policy.
    addSd <- fixed(0)
    label("Additive residual SD on Cc (mg/L); no residual-error model is reported by the source") # Sect. 2.3-2.4: simulation only, no estimation step
  })

  model({
    # Individual clearance follows Equation 5 exactly: the mean-centered
    # additive CLCR term is added to the typical clearance BEFORE the
    # multiplicative log-normal eta is applied.
    cl <- (exp(lcl) + e_crcl_cl * (CRCL - 103)) * exp(etalcl)
    vc <- exp(lvc + etalvc)
    vp <- exp(lvp + etalvp)
    q <- exp(lq)
    ka <- exp(lka)
    kfec <- exp(lkfec)
    ktr <- exp(lktr)
    kbile <- exp(lkbile)

    # Two-compartment disposition micro-constants (Figure 1, CMT 3 <-> CMT 4).
    kel <- cl / vc
    k12 <- q / vc
    k21 <- q / vp

    # Oral doses of fosfomycin tromethamine are administered into `depot`
    # (Figure 1 'CMT 1 GI') via the event table. No absorption rate governs
    # the dose input itself -- the dose lands in the depot and the depot then
    # drains by the two competing routes ka and kfec, so the bioavailable
    # fraction is ka / (ka + kfec) = 1.69 / 2.93 = 0.577.
    d/dt(depot) <- -(ka + kfec) * depot
    d/dt(transit1) <- ka * depot - ktr * transit1
    d/dt(central) <- ktr * transit1 - kel * central - kbile * central -
      k12 * central + k21 * peripheral1
    d/dt(peripheral1) <- k12 * central - k21 * peripheral1

    # Serum fosfomycin concentration in mg/L (dose in mg, volumes in L).
    Cc <- central / vc
    Cc ~ add(addSd)
  })
}
