Rohatagi_2008_apricoxib <- function() {
  description <- paste(
    "Joint pain-relief / rescue-medication / onset-time exposure-response",
    "model for the selective cyclooxygenase-2 (COX-2) inhibitor apricoxib",
    "(development code CS-706) in adults with acute postoperative dental",
    "pain after third-molar extraction. Four coupled sub-models, the terms",
    "of the paper's equations 1 to 3. (1) A proportional-odds categorical",
    "response model for the five-point pain relief (PR) score 0 to 4, whose",
    "shared linear predictor is the sum of a first-order placebo response",
    "Ep * (1 - exp(-Kp * t)), an Emax drug effect Emax * Cp / (Cp + EC50)",
    "on the model-predicted apricoxib plasma concentration, and one",
    "additive subject-level random effect on the logit. (2) A rescue",
    "medication (discontinuation) hazard h = h0 * lambda^PR that declines",
    "five-fold per unit increase in pain relief score; it is integrated",
    "here as a cumulative-hazard state driven by the expectation of",
    "lambda^PR over the categorical score distribution, so the",
    "probability of having required rescue medication by time t is",
    "1 - exp(-cumhaz). (3) A saturable dose-response for the probability",
    "of meaningful pain relief (MPR) in patients who required rescue",
    "medication, mixed with the dose-independent 98.2 percent MPR",
    "probability in patients who did not. (4) Log-normal onset time of",
    "meaningful pain relief (TMPR), reported as an absolute time in",
    "patients who required no rescue medication and as a fraction of the",
    "individual rescue time in patients who did. The apricoxib plasma",
    "concentration driving the Emax term is generated by the two-",
    "compartment first-order-absorption population PK model of",
    "Kastrissios 2006, reproduced in full here so the file is",
    "self-contained; see modellib('Kastrissios_2006_apricoxib')."
  )
  reference <- paste(
    "Rohatagi S, Kastrissios H, Sasahara K, Truitt K, Moberly JB, Wada R,",
    "Salazar DE. (2008). Pain relief model for a COX-2 inhibitor in",
    "patients with postoperative dental pain.",
    "British Journal of Clinical Pharmacology 66(1):60-70.",
    "doi:10.1111/j.1365-2125.2008.03175.x.",
    "The pharmacokinetic layer is the paper's reference 1, Kastrissios H,",
    "Rohatagi S, Moberly J, Truitt K, Gao Y, Wada R, Takahashi M,",
    "Kawabata K, Salazar D. (2006). Development of a predictive",
    "pharmacokinetic model for a novel COX-2 inhibitor.",
    "Journal of Clinical Pharmacology 46(5):537-548.",
    "doi:10.1177/0091270006287122; see",
    "modellib('Kastrissios_2006_apricoxib').",
    "Both papers name the compound only by its Sankyo development code",
    "CS-706; the INN subsequently assigned to that molecule is apricoxib,",
    "which this file uses per the library's",
    "generic-name-over-development-code convention.",
    sep = " "
  )
  vignette <- "Rohatagi_2008_apricoxib"
  units <- list(
    time          = "h",
    dosing        = "mg",
    concentration = "ng/mL"
  )

  compartmentData <- list(
    depot       = list(analyte = "apricoxib", units = "mg", specimen = "administration site", verified = TRUE),
    central     = list(analyte = "apricoxib", units = "mg", specimen = "plasma", verified = TRUE),
    peripheral1 = list(analyte = "apricoxib", units = "mg", specimen = "plasma", verified = TRUE),
    cumhaz      = list(analyte = "rescue-medication hazard", units = NA_character_, specimen = "not applicable", verified = TRUE)
  )

  covariateData <- list(
    DOSE_APRICOXIB_MG = list(
      description        = paste(
        "Administered single oral apricoxib (CS-706) dose in mg, 0 for a",
        "placebo subject. Time-fixed per subject: the phase 2a dental-pain",
        "study gave one dose of placebo or 10, 50, 100 or 200 mg."
      ),
      units              = "mg",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Rohatagi 2008 equations 13, 14 and 15 use 'Dose_i, the patient's",
        "dose' as a subject-level regressor in the meaningful-pain-relief",
        "sub-models: P(MPR) = P0 + (Pmax - P0) * Dose / (Dose + D50PMPR),",
        "log(TMPR/TRescue) = LTR0 + LTRmax * Dose / (Dose + D50LTR), and",
        "log(TMPR) = LT0 + LTslope * Dose. It is carried as a covariate",
        "column rather than read from the dose record because a placebo",
        "subject has no dose record at all (Dose = 0 must still select",
        "P(MPR) = P0 = 16 percent and TMPR = exp(LT0) = 1.6 h), and",
        "because rxode2's generic DOSE column is consumed by etTrans()",
        "and is not visible inside model(). Populate it with the same",
        "amount that the depot dose record carries; the two are used for",
        "different purposes (the dose record drives the PK, this column",
        "drives the algebraic MPR and TMPR dose-response equations).",
        "The apricoxib PK layer's own dose nonlinearities read the dose",
        "record directly via podo(depot) and DOSE_HIGH, and do NOT use",
        "this column."
      ),
      source_name        = "Dose"
    ),
    WT = list(
      description        = paste(
        "Body weight. Enters the apparent central volume of the",
        "Kastrissios 2006 apricoxib PK layer as a power term normalised",
        "to 73.3 kg, that paper's development-cohort median weight."
      ),
      units              = "kg",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Kastrissios 2006 equation 8, Vc/F = (Vc/F)_Typ *",
        "(Weight / 73.3)^K_Vc/F-WT, which prints the 73.3 kg normalising",
        "value literally. Rohatagi 2008 restates the same relationship in",
        "prose ('The typical apparent volume of the central compartment",
        "(Vc/F) in a 73-kg subject was 166 l and was increased",
        "approximately 8% per 10% increase in body weight'); the 73 kg",
        "there is the rounded form of Kastrissios 2006's 73.3 kg and the",
        "unrounded value is used here. Body weight has no effect on any",
        "pharmacodynamic parameter: Rohatagi 2007 (the paper's reference",
        "2, summarised in Rohatagi 2008's Methods) reports that 'None of",
        "the tested covariates, including age, gender, race, weight,",
        "height and body mass index, influenced the pharmacodynamics of",
        "CS-706'. Weight matters to pain relief only indirectly, through",
        "Vc/F and therefore through the concentration that drives the",
        "Emax term. Dental-pain-cohort weights: median 68.2 kg, range",
        "39.1 to 134 kg (Rohatagi 2008 Table 2)."
      ),
      source_name        = "Weight"
    ),
    SEXF = list(
      description        = paste(
        "Biological sex, 1 = female, 0 = male. Acts on apparent oral",
        "clearance in the Kastrissios 2006 PK layer. That paper uses the",
        "opposite orientation: its equation 7 indicator 'Gender' is 1 for",
        "MALE, so the canonical column is the value inversion",
        "SEXF = 1 - Gender."
      ),
      units              = "(binary)",
      type               = "binary",
      reference_category = 0,
      notes              = paste(
        "VALUE INVERSION. The published coefficient K_CL/F-SEX = +0.325",
        "multiplies Kastrissios 2006's MALE indicator, so it is applied",
        "here to (1 - SEXF) and the typical value lcl = log(34.1) is the",
        "FEMALE apparent oral clearance; males are exp(0.325) = 1.384-fold",
        "higher, 47.2 L/h, which is the value Rohatagi 2008's Methods",
        "quotes ('Apparent oral clearance (CL/F) was 47.2 l h-1 in the",
        "dose range 2-200 mg'). Rohatagi 2008 repeats Kastrissios 2006's",
        "prose mis-statement of the direction of this effect ('reduced ...",
        "by 38% in women compared to men'): 38.4% is exp(0.325) - 1, the",
        "amount by which MALES exceed females, whereas the model-implied",
        "female-versus-male reduction is 1 - exp(-0.325) = 27.7%. This",
        "file encodes the estimate, not the prose; the orientation is",
        "pinned by the independent 47.2 L/h anchor. See the sibling",
        "model file Kastrissios_2006_apricoxib.R, whose SEXF notes carry",
        "the full argument, and the vignette Assumptions and deviations",
        "section. Sex has no effect on any pharmacodynamic parameter",
        "(Rohatagi 2008 Methods, quoting the paper's reference 2).",
        "Dental-pain cohort: 193 of 304 patients female, 63.5 percent",
        "(Table 2)."
      ),
      source_name        = "Gender"
    ),
    CYP2D6_PM_IM = list(
      description        = paste(
        "Pooled CYP2D6 poor-or-intermediate-metabolizer phenotype",
        "indicator: 1 = poor OR intermediate metabolizer, 0 = extensive",
        "OR ultrafast metabolizer. Acts on apparent oral clearance in the",
        "Kastrissios 2006 PK layer."
      ),
      units              = "(binary)",
      type               = "binary",
      reference_category = 0,
      notes              = paste(
        "Kastrissios 2006 equation 7 indicator 'CYPD', defined there as",
        "'0 for subjects with the extensive/ultrafast CYP 2D6 phenotype",
        "and the value 1 for subjects with the poor/intermediate",
        "phenotype'. Rohatagi 2008 quotes the resulting effect size in",
        "its Methods ('reduced ... by 64% in subjects expressing poor and",
        "intermediate cytochrome P450 (CYP) 2D6 phenotypes');",
        "1 - exp(-1.01) = 63.6 percent. Rohatagi 2008 Table 1 gives the",
        "phenotype frequencies used in its Japanese-versus-Western dose",
        "bridging simulations: extensive / poor-or-intermediate = 0.98 /",
        "0.02 in Japanese and 0.91 / 0.09 in Western populations. See the",
        "sibling model file Kastrissios_2006_apricoxib.R for the full",
        "derivation of the pooling."
      ),
      source_name        = "CYPD"
    ),
    CYP2C9_RH = list(
      description        = paste(
        "CYP2C9 reduced-hydroxylator phenotype indicator: 1 = reduced",
        "hydroxylator, 0 = intermediate metabolizer OR normal",
        "hydroxylator. Acts on apparent oral clearance in the",
        "Kastrissios 2006 PK layer."
      ),
      units              = "(binary)",
      type               = "binary",
      reference_category = 0,
      notes              = paste(
        "Kastrissios 2006 equation 7 indicator 'CYPC', defined there as",
        "'0 for subjects with the intermediate/normal hydroxylator CYP 2C9",
        "phenotype and the value 1 for those with the reduced hydroxylator",
        "phenotype'. Rohatagi 2008 quotes the effect size in its Methods",
        "('reduced ... by 15% in subjects expressing the CYP 2C9 reduced",
        "hydroxylator phenotype'); 1 - exp(-0.163) = 15.0 percent. Note",
        "that the REFERENCE group contains the paper's 'intermediate",
        "metabolizer' subjects, which is why the registered CYP2C9_PM_IM",
        "canonical must NOT be substituted here. Rohatagi 2008 Table 1",
        "gives the frequencies used in the bridging simulations: normal-",
        "or-extensive / reduced hydroxylator = 0.96 / 0.04 in Japanese and",
        "0.85 / 0.15 in Western populations."
      ),
      source_name        = "CYPC"
    ),
    DOSE_HIGH = list(
      description        = paste(
        "Supratherapeutic-dose-cohort indicator: 1 = the subject received",
        "a 400 mg or 800 mg dose of apricoxib, 0 = the subject received a",
        "dose in the 2 to 200 mg range. Selects between the two typical",
        "apparent oral clearance values of the Kastrissios 2006 PK layer."
      ),
      units              = "(binary)",
      type               = "binary",
      reference_category = 0,
      notes              = paste(
        "Kastrissios 2006 equation 7 indicator 'D_hi'. Rohatagi 2008",
        "quotes the effect in its Methods ('Apparent oral clearance (CL/F)",
        "was 47.2 l h-1 in the dose range 2-200 mg and was reduced by 43%",
        "at higher doses (>200 mg)'); 1 - 19.5/34.1 = 42.8 percent. In the",
        "Rohatagi 2008 dental-pain study this indicator is 0 for every",
        "patient, because the studied CS-706 doses were 10, 50, 100 and",
        "200 mg (Table 2) and the >200 mg levels were only ever given in",
        "the Kastrissios 2006 phase 1 programme. It is retained so that",
        "the PK layer reproduces the published model over its full dose",
        "range. Carried as its own indicator column rather than derived as",
        "an inequality on the dose amount, per the register's DOSE_LOW",
        "rule: the authors defined the group by the studied dose levels",
        "(400, 800) and not by a threshold. Distinct from the saturable",
        "relative-bioavailability nonlinearity, which is a smooth function",
        "of the actual dose amount read from the event record via",
        "podo(depot), and distinct from DOSE_APRICOXIB_MG, which drives",
        "the pharmacodynamic dose-response equations 13 to 15."
      ),
      source_name        = "Dhi"
    )
  )

  # Screened by the authors and NOT retained in the final model, so these are
  # documented for provenance only and are deliberately absent from model().
  covariatesDataExcluded <- list(
    PAIN = list(
      description        = paste(
        "Baseline postoperative pain intensity, recorded on both a",
        "four-point categorical scale and a visual analogue scale at the",
        "time of dosing."
      ),
      units              = "(categorical: 2 = moderate, 3 = severe)",
      type               = "categorical",
      reference_category = 2,
      notes              = paste(
        "Rohatagi 2008 Methods 'Data': 'Pain intensity (PI; categorical",
        "and visual analogue scales) was assessed at the time of dosing'.",
        "Explicitly screened as a covariate on the pharmacodynamic",
        "parameters -- 'Baseline pain intensity was examined as a possible",
        "covariate to explain variability in response. It was introduced",
        "in the model as follows: theta_i = theta_T * exp(Cov_i * Kcov_i)",
        "... where Cov_i is a derived binary variable with values of 0 or",
        "1' (equation 9) -- and NOT retained: Table 3, the final pain",
        "relief parameter table, contains no covariate coefficient of any",
        "kind, and its three parameter groups are the categorical",
        "intercepts, the placebo response and the CS-706 response only. No",
        "point estimate is reported, so no effect can be encoded. Only",
        "patients with moderate or severe baseline pain were enrolled;",
        "Table 2 gives the 2/3 split as 121/183 across all 304 patients",
        "(20/32 placebo, 80/121 CS-706-treated). NOTE the scale: the",
        "canonical PAIN register entry is a 0-100 mm VAS, whereas the",
        "column screened here is the four-point categorical pain-intensity",
        "score dichotomised to a 0/1 indicator per equation 9. Documented",
        "under the same canonical because the paper collected both scales",
        "and reports neither a VAS summary nor a retained coefficient."
      ),
      source_name        = "PI"
    ),
    AGE = list(
      description        = "Age.",
      units              = "years",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Not retained on any pharmacodynamic parameter. Rohatagi 2008",
        "Methods, summarising the paper's reference 2: 'None of the tested",
        "covariates, including age, gender, race, weight, height and body",
        "mass index, influenced the pharmacodynamics of CS-706.' No point",
        "estimate is reported. Table 2 dental-pain cohort: median 22",
        "years, range 18 to 36."
      ),
      source_name        = "Age"
    ),
    HT = list(
      description        = "Height.",
      units              = "cm",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Screened and not retained on any pharmacodynamic parameter",
        "(Rohatagi 2008 Methods, quoting the paper's reference 2); no",
        "point estimate reported. Table 2 dental-pain cohort: median 166",
        "cm, range 125 to 193."
      ),
      source_name        = "Height"
    ),
    BMI = list(
      description        = "Body mass index.",
      units              = "kg/m^2",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Screened and not retained on any pharmacodynamic parameter",
        "(Rohatagi 2008 Methods, quoting the paper's reference 2); no",
        "point estimate reported and no cohort summary given."
      ),
      source_name        = "BMI"
    ),
    RACE_WHITE = list(
      description        = "White race indicator.",
      units              = "(binary)",
      type               = "binary",
      reference_category = 0,
      notes              = paste(
        "Screened and not retained on any pharmacodynamic parameter, and",
        "not retained on any pharmacokinetic parameter either (Kastrissios",
        "2006). Table 2 dental-pain cohort ethnicity counts",
        "White/Black/Asian/Hispanic/Other = 181/14/9/95/5 of 304. Race",
        "nonetheless matters to the paper's conclusion indirectly, through",
        "the CYP phenotype and body-weight distributions used in the",
        "Japanese-versus-Western bridging simulation (Table 1), not",
        "through a direct effect on any model parameter. No point estimate",
        "is reported."
      ),
      source_name        = "Race"
    ),
    COX2_ACT = list(
      description        = paste(
        "Whole-blood cyclooxygenase-2 activity, measured as the",
        "prostaglandin E2 concentration in heparinized plasma after",
        "incubation of whole blood with lipopolysaccharide."
      ),
      units              = "(percent of baseline COX-2 activity)",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Tested as the explanatory variable of the drug-effect term in",
        "place of plasma concentration and REJECTED: 'For treated",
        "patients, CS-706 plasma concentrations and whole blood COX-2",
        "activity ... were evaluated as possible explanatory variables'",
        "and 'Utilizing COX-2 data instead of plasma concentration as the",
        "explanatory variable for pain relief did not improve the model",
        "fit' (Rohatagi 2008 Methods, Drug effect model). The final",
        "drug-effect term of equation 7 is therefore driven by Cp, the",
        "population-PK-model-predicted plasma concentration, and the",
        "COX-2 pathway does not appear in model(). The COX-2 inhibition",
        "relationship itself lives in the paper's reference 2 (Rohatagi",
        "2007), which reports an Emax model with EC50 = 20 ng/mL for",
        "COX-2 and 397 ng/mL for COX-1 and a maximum possible inhibition",
        "of 100 percent for both; that PK/PD biomarker model is a separate",
        "publication and is not encoded here."
      ),
      source_name        = "COX-2 activity"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 304L,
    n_studies      = 1L,
    age_range      = "18-36 years",
    age_median     = "22 years",
    weight_range   = "39.1-134 kg",
    weight_median  = "68.2 kg",
    height_range   = "125-193 cm",
    height_median  = "166 cm",
    sex_female_pct = 63.5,
    race_ethnicity = c(White = 59.5, Black = 4.6, Asian = 3.0, Hispanic = 31.3, Other = 1.6),
    disease_state  = paste(
      "Acute moderate-to-severe postoperative dental pain, assessed within",
      "6 h of surgical removal of two or more third molars"
    ),
    dose_range     = paste(
      "Single oral dose of one of six randomised treatments in approximately",
      "equal proportions (about 50 patients per treatment): placebo, 10, 50,",
      "100 or 200 mg apricoxib (CS-706), or 400 mg celecoxib as an active",
      "comparator. Pain intensity and pain relief were scored at 0.25, 0.5,",
      "0.75, 1, 1.5, 2, 3, 4, 5, 6, 7, 8, 12 and 24 h postdose."
    ),
    regions        = "United States (two sites)",
    notes          = paste(
      "Baseline characteristics from Rohatagi 2008 Table 2, 'All' column.",
      "n_subjects = 304 is the whole randomised study population; Table 2",
      "breaks it down as 52 placebo, 201 apricoxib (10, 50, 100 and 200 mg)",
      "and, by difference, 51 celecoxib. The pain relief model of equation 4",
      "carries a placebo term and an apricoxib-concentration term only, so",
      "the celecoxib comparator arm is not described by it and the paper",
      "reports no celecoxib parameters. The paper does not print the exact",
      "number of subjects or observations entering each fit; the closest",
      "figure it gives is the per-pain-relief-score observation counts in",
      "Figure 5 (N = 98, 202, 729, 455 at PR scores 0, 1, 2, 3 with 31, 32,",
      "25 and 2 rescue events respectively). Two protocol rules shape the",
      "analysis data set: patients requiring rescue medication within 90 min",
      "of dosing were excluded from the primary efficacy analysis, and",
      "patients who received rescue medication before the end of the 24 h",
      "evaluation period were analysed with last observation carried",
      "forward. Estimation of the pain relief model used the Laplacian",
      "method in NONMEM version V; the rescue-medication and",
      "meaningful-pain-relief models were fitted in S-PLUS 6.1. Model-based",
      "shrinkage on the pain relief post hoc estimates was 10 percent. The",
      "PK layer reproduced here was fitted to a different population, the",
      "104 healthy adult volunteers of Kastrissios 2006; see",
      "modellib('Kastrissios_2006_apricoxib')."
    )
  )

  ini({
    # ==================================================================
    # PHARMACOKINETIC LAYER -- Kastrissios 2006 Table IV, "Final
    # Pharmacokinetic Parameter Estimates" (a FOCE fit in NONMEM v5).
    # Rohatagi 2008 does not re-estimate the PK; its Methods state that
    # the concentrations driving equation 7 "were the individual (post
    # hoc) estimates from population PK and PK/PD models developed
    # previously" and summarise that model in prose. Every value below
    # is transcribed from Kastrissios 2006 Table IV, which Rohatagi
    # 2008 cites as its reference 1, and each is cross-checked against
    # the summary Rohatagi 2008 prints in its own Methods. Nothing in
    # Kastrissios 2006 Table IV is flagged FIX -- every row carries a
    # CV% and a 95% confidence interval -- so no PK parameter is
    # wrapped in fixed(). The one genuinely fixed quantity there is
    # absolute oral bioavailability F, which "was not uniquely
    # estimable and therefore was assumed to be equal to the product of
    # 1 and Frel"; that unit constant appears in model() as the
    # implicit multiplier of frel, not as an ini() entry, so every
    # clearance and volume below is APPARENT.
    # ==================================================================
    lvc <- log(166)
    label("Apparent central volume Vc/F at the 73.3 kg reference weight (L)")
    # Kastrissios 2006 Table IV: Vc/F = 166 L, CV 8%, 95% CI (141, 191).
    # Rohatagi 2008 Methods: "The typical apparent volume of the central
    # compartment (Vc/F) in a 73-kg subject was 166 l".

    lvp <- log(483)
    label("Apparent peripheral volume Vp/F (L)")
    # Kastrissios 2006 Table IV: Vp/F = 483 L, CV 7%, 95% CI (417, 549).
    # Not restated by Rohatagi 2008, which describes only "an open
    # two-compartment model with first-order absorption".

    lq <- log(75)
    label("Apparent inter-compartmental clearance Q/F (L/h)")
    # Kastrissios 2006 Table IV: Q/F = 75 L/h, CV 7%, 95% CI (64, 86).

    lcl <- log(34.1)
    label("Apparent oral clearance CL/F, 2-200 mg doses, female reference subject (L/h)")
    # Kastrissios 2006 Table IV row "CL/F, L/h, extensive metabolizer
    # phenotype / 2- to 200-mg doses" = 34.1 L/h, CV 6%, 95% CI (29.8,
    # 38.4). This is the FEMALE value: equation 7's Gender indicator is
    # 1 for MALE, so the male typical value is 34.1 * exp(0.325) = 47.2
    # L/h, which is exactly the number Rohatagi 2008 Methods quotes
    # ("Apparent oral clearance (CL/F) was 47.2 l h-1 in the dose range
    # 2-200 mg"). See the SEXF covariateData notes.

    lcl_highdose <- log(19.5)
    label("Apparent oral clearance CL/F, 400-800 mg doses, female reference subject (L/h)")
    # Kastrissios 2006 Table IV row "CL/F ... / 400- to 800-mg doses" =
    # 19.5 L/h, CV 17%, 95% CI (12.9, 26.1). Selected inside model() by
    # DOSE_HIGH = 1. 1 - 19.5/34.1 = 42.8%, Rohatagi 2008's "reduced by
    # 43% at higher doses (>200 mg)". Never active in the dental-pain
    # cohort, whose doses are 10 to 200 mg.

    lka <- log(0.542)
    label("First-order absorption rate constant KA (1/h)")
    # Kastrissios 2006 Table IV: KA = 0.542 1/h, CV 5%, 95% CI (0.489,
    # 0.595); log(2)/0.542 = 1.28 h absorption half-life.

    ltlag <- log(0.236)
    label("Absorption lag time TLAG (h)")
    # Kastrissios 2006 Table IV: TLAG = 0.236 h, CV 1%, 95% CI (0.232,
    # 0.240). Rohatagi 2008 Methods: "an absorption lag time (median 14
    # min)"; 0.236 h * 60 = 14.2 min.

    led50 <- log(221)
    label("Dose at which relative bioavailability is half maximal, D50 (mg)")
    # Kastrissios 2006 Table IV row "D50 for F, mg" = 221 mg, CV 14%,
    # 95% CI (161, 281). Rohatagi 2008 Methods: bioavailability
    # "decreased with increasing doses according to a saturation model,
    # reaching 50% reduction at a dose of 221 mg"; 221/(221 + 221) =
    # 0.500 exactly.

    e_evening_fdepot <- 0.351
    label("Log-scale increase in relative bioavailability for an evening dose (unitless)")
    # Kastrissios 2006 Table IV row "KFrel-PM Dose" = 0.351, CV 13%,
    # 95% CI (0.261, 0.441). exp(0.351) - 1 = 42.0%, Rohatagi 2008's
    # "Oral bioavailability was 42% greater following night-time
    # relative to day-time doses".

    e_sexf_cl <- 0.325
    label("Log-scale effect of MALE sex on apparent oral clearance (unitless)")
    # Kastrissios 2006 Table IV row "KCL/F-SEX" = 0.325, CV 24%, 95% CI
    # (0.171, 0.479). Applied in model() to (1 - SEXF) because the
    # source indicator is 1 for male. exp(0.325) = 1.384.

    e_cyp2d6_pmim_cl <- -1.01
    label("Log-scale effect of pooled poor/intermediate CYP2D6 phenotype on CL/F (unitless)")
    # Kastrissios 2006 Table IV row "KCL/F-CYP2D6 (poor and intermediate
    # metabolizer)" = -1.01, CV 16%, 95% CI (-1.33, -0.69).
    # 1 - exp(-1.01) = 63.6%, Rohatagi 2008's "reduced ... by 64% in
    # subjects expressing poor and intermediate ... CYP 2D6 phenotypes".

    e_cyp2c9_rh_cl <- -0.163
    label("Log-scale effect of reduced-hydroxylator CYP2C9 phenotype on CL/F (unitless)")
    # Kastrissios 2006 Table IV row "KCL/F-CYP2C9 (reduced
    # hydroxylator)", printed there as "-00.163" (a typesetting artifact
    # of -0.163, confirmed by its own 95% CI (-0.350, 0.024) and CV
    # 59%). 1 - exp(-0.163) = 15.0%, Rohatagi 2008's "reduced ... by 15%
    # in subjects expressing the CYP 2C9 reduced hydroxylator
    # phenotype".

    e_wt_vc <- 0.831
    label("Power exponent for body weight on apparent central volume (unitless)")
    # Kastrissios 2006 Table IV row "KVc/F-WT" = 0.831, CV 33%, 95% CI
    # (0.288, 1.374); equation 8 is Vc/F = (Vc/F)_Typ *
    # (Weight/73.3)^KVc/F-WT. Rohatagi 2008 Methods cross-check: Vc/F
    # "was increased approximately 8% per 10% increase in body weight";
    # 1.10^0.831 = 1.0824, i.e. +8.2%.

    # Kastrissios 2006 equation 1 is theta_i = theta_T * exp(eta_i) and
    # Table IV reports the omega^2 VARIANCES directly (its "Estimated
    # Variability (%)" column is sqrt(omega^2): sqrt(0.127) = 35.6%,
    # sqrt(0.234) = 48.4%, sqrt(0.229) = 47.9%, sqrt(0.125) = 35.4%,
    # sqrt(0.052) = 22.7%, sqrt(0.002) = 4.5% against the printed
    # 4.36%). Entered below as variances without transformation. No
    # off-diagonal covariances are reported, so the PK omega block is
    # diagonal.
    etalvc   ~ 0.127   # Kastrissios 2006 Table IV: omega^2 Vc/F  = 0.127, CV 28%, 95% CI (0.057, 0.197)
    etalvp   ~ 0.234   # Kastrissios 2006 Table IV: omega^2 Vp/F  = 0.234, CV 15%, 95% CI (0.166, 0.302)
    etalq    ~ 0.229   # Kastrissios 2006 Table IV: omega^2 Q/F   = 0.229, CV 20%, 95% CI (0.140, 0.318)
    etalcl   ~ 0.125   # Kastrissios 2006 Table IV: omega^2 CL/F  = 0.125, CV 16%, 95% CI (0.086, 0.164)
    etalka   ~ 0.052   # Kastrissios 2006 Table IV: omega^2 Ka    = 0.052, CV 47%, 95% CI (0.004, 0.099)
    etaltlag ~ 0.002   # Kastrissios 2006 Table IV: omega^2 Tlag  = 0.002, CV 64%, 95% CI (0.000, 0.004)

    propSd <- sqrt(0.069)
    label("Proportional residual error on the apricoxib plasma concentration (fraction)")
    # Kastrissios 2006 equation 3, y_ij = yhat_ij * (1 + eps_ij), i.e.
    # proportional in linear space; Table IV reports sigma^2 = 0.069, a
    # VARIANCE, CV 6%, 95% CI (0.061, 0.077). sqrt(0.069) = 0.2627,
    # matching that paper's printed 26.3% residual variability.

    # ==================================================================
    # PAIN RELIEF MODEL -- Rohatagi 2008 Table 3. A proportional-odds
    # categorical response model, equation 4:
    #   P(Y_ij >= k | eta_i) =
    #     expit(beta_k + f_p(t_ij) + f_D(C_ij) + eta_i)
    # with k = 1..4 and P(Y_ij >= 0) = 1. Equation 5 parameterises the
    # intercepts incrementally, beta_1 = theta_1, beta_2 = beta_1 +
    # theta_2, beta_3 = beta_2 + theta_3, beta_4 = beta_3 + theta_4,
    # "because, with the exception of theta_1, theta estimates can be
    # constrained to be negative, keeping the beta-values decreasing
    # with increasing pain score". Nothing in Table 3 is flagged fixed;
    # every row carries a standard error.
    # ==================================================================
    b1_pr <- -3.30
    label("Logit of P(pain relief score >= 1) extrapolated to time 0 (logit units)")
    # Table 3 row "Logit of the probability that PR >= 1 extrapolated to
    # time = 0 h", theta_1 = -3.30, SE 0.29. The table's dagger footnote
    # gives the round-trip: "Corresponds to probability of PR >= 1
    # extrapolated to 0 h = 0.04 or 4%"; expit(-3.30) = 0.0355.

    b2b1_pr <- -2.39
    label("Incremental change in logit from PR >= 1 to PR >= 2 (logit units)")
    # Table 3: theta_2 = -2.39, SE 0.11, odds ratio exp(-2.39) = 0.092
    # against the printed 0.09.

    b3b2_pr <- -1.86
    label("Incremental change in logit from PR >= 2 to PR >= 3 (logit units)")
    # Table 3: theta_3 = -1.86, SE 0.09, odds ratio exp(-1.86) = 0.156
    # against the printed 0.16.

    b4b3_pr <- -3.45
    label("Incremental change in logit from PR >= 3 to PR >= 4 (logit units)")
    # Table 3: theta_4 = -3.45, SE 0.11, odds ratio exp(-3.45) = 0.032
    # against the printed 0.03.

    eplac_pr <- 12.0
    label("Maximum extent of the placebo response on the pain relief logit, Ep (logit units)")
    # Table 3 row "Maximum extent of placebo response", Ep = 12.0, SE
    # 1.2. Equation 6: f_p(t) = Ep * (1 - exp(-Kp * t)).

    lkplac_pr <- log(0.055)
    label("First-order rate constant for stabilization of the placebo response, Kp (1/h)")
    # Table 3 row "Rate of stabilization of placebo response over time
    # (h-1)", Kp = 0.055, SE 0.009 (16% RSE). Held on the log scale here
    # so it stays positive; the paper reports it untransformed. See the
    # vignette Assumptions and deviations section for the prose-versus-
    # table note: the Results and Discussion describe the placebo
    # response as having "stabilized after about 4 h", which is a
    # statement about the raw score bar plots of Figure 3, whereas
    # Kp = 0.055 1/h gives a 12.6 h half-life so that f_p reaches only
    # 20% of Ep by 4 h and 73% by 24 h. The estimate, not the prose, is
    # encoded; the SE rules out a factor-of-ten transcription error
    # (0.55 1/h would imply a 1.6% RSE).

    emax_pr <- 12.6
    label("Maximum extent of the apricoxib response on the pain relief logit, Emax (logit units)")
    # Table 3 row "Maximum extent of CS-706 response", Emax = 12.6, SE
    # 0.6. Equation 7: f_D(Cp) = Emax * Cp / (Cp + EC50).

    lec50_pr <- log(87.0)
    label("Apricoxib plasma concentration producing half the maximum pain relief response, EC50 (ng/mL)")
    # Table 3 row "Plasma concentration producing 50% of maximum
    # response (ng ml-1)", EC50 = 87.0, SE 8.9. Abstract and Discussion:
    # 87 ng/mL is "the median peak plasma concentration achieved after a
    # 50-mg oral dose".

    etab1_pr ~ 9.90
    # Table 3 row "Intersubject variability", omega^2 = 9.90, SE 1.21,
    # printed in the placebo-response group. It is the variance of the
    # single additive subject-level random effect eta_i of equation 4,
    # which shifts the whole linear predictor and is therefore exactly
    # equivalent to intersubject variability on the baseline intercept
    # beta_1 = theta_1 (all four beta_k shift together). Entered as a
    # VARIANCE on the logit scale, not as a CV: equation 4 adds eta_i
    # inside the logit rather than multiplying a typical value, so the
    # log-normal parameterisation of equation 8 does not apply to it.
    # sqrt(9.90) = 3.15 logit units, a large but unremarkable spread for
    # a categorical pain-relief model of this family (the paper's
    # reference 4, Mandema & Stanski 1996, uses the same construction).

    # ==================================================================
    # RESCUE MEDICATION MODEL -- Rohatagi 2008 Table 4. Equation 11 is
    # the hazard h_ij = h0 * lambda^PR_ij, an "exponentially declining
    # function of the last observed pain relief score"; equation 10
    # converts it to the interval probability P_ij = 1 - exp(-h_ij *
    # dT_ij); equation 12 gives T50 = log(2)/h.
    # ==================================================================
    lh0_remd <- log(2.08)
    label("Rescue-medication (discontinuation) hazard at pain relief score 0, h0 (1/h)")
    # Table 4 row "Discontinuation hazard at PR = 0 (h-1)", h0 = 2.08,
    # SE 0.21. Held on the log scale so it stays positive; the paper
    # reports it untransformed. Results cross-check: "patients with a
    # pain relief score of 0 have a hazard of 2.08, and therefore a 50%
    # chance of requiring rescue medication within 20 min";
    # log(2)/2.08 = 0.333 h = 20.0 min, which also confirms the per-hour
    # (not the per-day of the Figure 5 upper-panel axis label) time base.

    lambda_remd <- 0.201
    label("Fractional decrease in the rescue-medication hazard per unit increment in pain relief score (unitless)")
    # Table 4 row "Fractional decrease in discontinuation hazard per
    # unit increment in PR", lambda = 0.201, SE 0.011. (The symbol is
    # rendered as "7" by the PDF's symbol font; the row description and
    # the equation-11 definition identify it as lambda.) Enters equation
    # 11 as a POWER of the pain relief score, h = h0 * lambda^PR, not as
    # a linear multiplier: the Results state "because lambda is 0.2,
    # this rescue time increases fivefold for every unit increase in PR
    # score", and 1/0.201 = 4.98. Constrained by construction to (0, 1).

    # ==================================================================
    # ONSET OF MEANINGFUL PAIN RELIEF (MPR) MODEL -- Rohatagi 2008
    # Table 5. Equations 13 to 15, split by whether the patient required
    # rescue medication, and recombined by equations 2 and 3. Table 5
    # reports 95% confidence intervals rather than standard errors; the
    # two variability rows are marked "Not estimated", meaning no
    # interval was computed for them, not that they were fixed, so
    # nothing here is wrapped in fixed().
    # ==================================================================
    logitp0_mpr <- qlogis(0.16)
    label("Logit of the probability of meaningful pain relief on placebo in patients who required rescue medication, logit(P0) (logit units)")
    # Table 5 row "Probability of MPR on placebo (%)", P0 = 16%, 95% CI
    # (10, 26). The paper states its own parameterisation explicitly:
    # "The model parameters are logit(P0), logit(Pmax), and
    # log(D50PMPR). The transformations allows more reliable estimates
    # of parameter precision, taking into account the constraints that
    # P0 and Pmax must be in the interval 0-1, and D50MPR must be
    # positive." qlogis(0.16) = -1.6582; expit(-1.6582) = 0.16 exactly.

    logitpmax_mpr <- qlogis(0.72)
    label("Logit of the maximum achievable probability of meaningful pain relief in patients who required rescue medication, logit(Pmax) (logit units)")
    # Table 5 row "Maximum possible probability of MPR", Pmax = 72%, 95%
    # CI (59, 83). Discussion: the probability "was dose-dependent,
    # ranging between 16% on placebo up to a maximum achievable
    # probability of 72%". qlogis(0.72) = 0.9445.

    ld50_pmpr <- log(8.8)
    label("Log of the apricoxib dose giving half-maximal meaningful-pain-relief probability, D50PMPR (mg)")
    # Table 5 row "Dose at which half maximal MPR is achieved (mg)",
    # D50PMPR = 8.8 mg, 95% CI (3.0, 26.1).

    logitpmpr_noremd <- qlogis(0.982)
    label("Logit of the probability of meaningful pain relief in patients who did not require rescue medication (logit units)")
    # Table 5 row "Probability of MPR (%)" in the "Patient does not
    # require rescue medication" block, PMPR = 98.2%, 95% CI (95.0,
    # 99.3). Dose-independent: "Almost all (98.2%) of the patients who
    # did not require rescue medication had MPR ... This percentage was
    # not dose-dependent". qlogis(0.982) = 4.0011.

    ltr0_mpr <- -0.95
    label("Log of the ratio of onset time of meaningful pain relief to rescue time on placebo, LTR0 (log h/h)")
    # Table 5 row "Logarithm of ratio between TMPR and time of rescue
    # medication on placebo", LTR0 = -0.95, 95% CI (-1.42, -0.48).
    # Results cross-check: "on average TMPR was 39% of the time of
    # rescue medication administration on placebo (calculated as the
    # antilogarithm of LTR0)"; exp(-0.95) = 0.387.

    ltrmax_mpr <- -1.00
    label("Maximum possible dose-driven decrease in the log time ratio, LTRmax (log h/h)")
    # Table 5 row "Logarithm of ratio between TMPR and time of rescue
    # medication, maximum possible decrease", LTRmax = -1.00, 95% CI
    # (-1.52, -0.47). Results cross-check: the ratio decreases "to a
    # minimum possible fraction of 14%"; exp(-0.95 - 1.00) = exp(-1.95)
    # = 0.142.

    ld50_ltr <- log(5.8)
    label("Log of the apricoxib dose giving half the maximal time-ratio change, D50LTR (mg)")
    # Table 5 row "Dose at which half maximal TMPR to time of rescue
    # medication ratio is achieved (mg)", D50LTR = 5.8 mg, 95% CI (0.9,
    # 35.8).

    lt0_mpr <- 0.45
    label("Log of the onset time of meaningful pain relief on placebo in patients who did not require rescue medication, LT0 (log h)")
    # Table 5 row "Logarithm of TMPR on placebo", LT0 = 0.45, 95% CI
    # (0.23, 0.67). Results cross-check: "median TMPR was 1.6 h for a
    # placebo dose (calculated as the antilogarithm of LT0)";
    # exp(0.45) = 1.568 h.

    tslope_mpr <- -0.0035
    label("Slope of log onset time of meaningful pain relief on apricoxib dose, LTSlope (log h per mg)")
    # Table 5 row "Slope relating dose to logarithm of TMPR", LTSlope =
    # -0.0035, 95% CI (-0.0053, -0.0018). Results cross-check: TMPR
    # "decreased by 3.5% for every 10-mg increase in dose";
    # 1 - exp(-0.0035 * 10) = 3.44%. Deliberately NOT given an `l`
    # prefix: it is a slope acting ON the log scale, not the logarithm
    # of a slope.

    etaltr0_mpr ~ 0.4096
    # Table 5 row "Residual variability in the logarithm of the time
    # ratio", sigma_LTR = 0.64 (95% CI "Not estimated"); entered as the
    # VARIANCE 0.64^2 = 0.4096. Equation 14 writes this term as
    # epsilon_LTR,i -- subject-indexed -- and the equation-3 text
    # defines sigma as "a normally distributed subject-specific random
    # variable", so it is encoded as inter-individual variability on the
    # intercept LTR0 rather than as residual error. TMPR is observed at
    # most once per patient, so the two are not distinguishable in the
    # source data; see the vignette Assumptions and deviations section.

    etalt0_mpr ~ 0.4761
    # Table 5 row "Residual variability in the logarithm of TMPR",
    # sigma_LT = 0.69 (95% CI "Not estimated"); entered as the VARIANCE
    # 0.69^2 = 0.4761. Equation 15 writes this term as epsilon_LT,i and
    # its defining sentence calls it "normally distributed
    # interindividual variability with mean 0 and standard deviation
    # sLT", so the inter-individual reading is the paper's own for this
    # branch. Encoded on the intercept LT0.
  })

  model({
    # ==================================================================
    # 1. PHARMACOKINETIC LAYER (Kastrissios 2006).
    #
    #    Reproduced verbatim from modellib('Kastrissios_2006_apricoxib')
    #    so that this file simulates the concentration that drives
    #    equation 7 without an external input. Rohatagi 2008 Methods
    #    summarise it as "an open two-compartment model with first-order
    #    absorption, an absorption lag time (median 14 min) and
    #    first-order elimination".
    # ==================================================================

    # Per-dose evening indicator, Kastrissios 2006 equation 6 ("PM is an
    # indicator variable taking on the value of 0 for daytime doses and
    # 1 for evening doses"), derived from the model clock: `t` is hours
    # from the first event, so a dose in the second half of the dosing
    # day is an evening dose. The dental-pain study gave a single dose,
    # so this is 0 throughout an event table that starts at the dose.
    evening <- (t - 24 * floor(t / 24)) >= 12

    # Apparent oral clearance, Kastrissios 2006 equation 7:
    #   CL/F = [(CL/F)_Typ * (1 - Dhi) + (CL/F)_Typ,hi * Dhi]
    #          * exp(Sex * K_CL/F-SEX) * exp(CYPD * K_CL/F-CYP2D6)
    #          * exp(CYPC * K_CL/F-CYP2C9)
    # The bracketed two-value switch is written on the log scale so that
    # it returns exp(lcl) = 34.1 at DOSE_HIGH = 0 and
    # exp(lcl_highdose) = 19.5 at DOSE_HIGH = 1. The source Gender
    # indicator is 1 for MALE, hence (1 - SEXF).
    cl <- exp(lcl + (lcl_highdose - lcl) * DOSE_HIGH +
                e_sexf_cl * (1 - SEXF) +
                e_cyp2d6_pmim_cl * CYP2D6_PM_IM +
                e_cyp2c9_rh_cl * CYP2C9_RH +
                etalcl)

    # Apparent central volume, Kastrissios 2006 equation 8: a power of
    # weight normalised to the 73.3 kg cohort median printed inside the
    # equation itself.
    vc <- exp(lvc + etalvc) * (WT / 73.3)^e_wt_vc

    # Vp/F, Q/F, KA and TLAG carry no covariate effects.
    vp   <- exp(lvp + etalvp)
    q    <- exp(lq  + etalq)
    ka   <- exp(lka + etalka)
    tlag <- exp(ltlag + etaltlag)

    # Relative bioavailability, Kastrissios 2006 equation 6:
    #   Frel = 1 * exp(K_Frel-PM * PM) * D50 / (DOSE + D50)
    # DOSE is the amount of the dose being administered, read off the
    # event record with podo(depot) so it cannot drift out of sync with
    # `amt`. The leading 1 is the authors' non-identifiable absolute
    # bioavailability, so Frel -> 1 as the dose approaches 0 (which is
    # also the value a placebo subject with no dose record takes) and
    # Frel = 0.5 at DOSE = D50 = 221 mg.
    ed50 <- exp(led50)
    frel <- exp(e_evening_fdepot * evening) * ed50 / (podo(depot) + ed50)

    kel <- cl / vc
    k12 <- q / vc
    k21 <- q / vp

    d/dt(depot)       <- -ka * depot
    d/dt(central)     <-  ka * depot - kel * central - k12 * central + k21 * peripheral1
    d/dt(peripheral1) <-  k12 * central - k21 * peripheral1

    f(depot)    <- frel
    alag(depot) <- tlag

    # Apricoxib plasma concentration. Doses are mg and volumes L, so
    # central/vc is mg/L = ug/mL and the factor 1000 converts to the
    # ng/mL scale on which EC50 = 87 ng/mL is reported.
    Cc <- 1000 * central / vc

    # ==================================================================
    # 2. PAIN RELIEF MODEL (Rohatagi 2008 equations 4 to 7, Table 3).
    # ==================================================================

    # Placebo response, equation 6: f_p(t) = Ep * (1 - exp(-Kp * t)).
    # `t` is the model clock; the dental-pain study gave a single dose
    # at the start of the pain-relief assessment schedule, so an event
    # table whose first record is the dose makes `t` the time postdose
    # that the equation intends.
    kplac_pr <- exp(lkplac_pr)
    fplac_pr <- eplac_pr * (1 - exp(-kplac_pr * t))

    # Drug effect, equation 7: f_D(Cp) = Emax * Cp / (Cp + EC50), with
    # Cp the population-PK-model-predicted plasma concentration. Zero
    # for a placebo subject, for whom Cc is 0 throughout.
    ec50_pr  <- exp(lec50_pr)
    fdrug_pr <- emax_pr * Cc / (Cc + ec50_pr)

    # Shared linear predictor of equation 4. The single additive
    # subject-level random effect is carried on the baseline intercept
    # (see the etab1_pr note in ini()).
    lp_pr <- fplac_pr + fdrug_pr

    # Cumulative logits, equation 5.
    b1_i <- b1_pr + etab1_pr
    b2_i <- b1_i + b2b1_pr
    b3_i <- b2_i + b3b2_pr
    b4_i <- b3_i + b4b3_pr

    # Equation 4: P(Y >= k) = expit(beta_k + f_p + f_D + eta).
    pge1_pr <- expit(b1_i + lp_pr)
    pge2_pr <- expit(b2_i + lp_pr)
    pge3_pr <- expit(b3_i + lp_pr)
    pge4_pr <- expit(b4_i + lp_pr)

    # Category probabilities implied by the cumulative form. Non-
    # negative by construction because the incremental thetas are
    # negative, so beta_1 > beta_2 > beta_3 > beta_4 and the cumulative
    # probabilities decrease with k.
    peq0_pr <- 1 - pge1_pr
    peq1_pr <- pge1_pr - pge2_pr
    peq2_pr <- pge2_pr - pge3_pr
    peq3_pr <- pge3_pr - pge4_pr
    peq4_pr <- pge4_pr

    # Expected pain relief score, sum over k of P(Y >= k) for k = 1..4.
    # Its time integral over 0 to T is the paper's TOPAR_T validation
    # metric ("the area under the pain relief score vs. time curve over
    # predefined intervals of time"); the vignette integrates this
    # output rather than adding a bookkeeping ODE state for it.
    score_pr <- pge1_pr + pge2_pr + pge3_pr + pge4_pr

    # ==================================================================
    # 3. RESCUE MEDICATION MODEL (equations 10 to 12, Table 4).
    #
    #    Equation 11 is h = h0 * lambda^PR, where PR is the last
    #    OBSERVED pain relief score, an integer 0 to 4. A continuous-
    #    time solve has a distribution over that score rather than a
    #    realised value, so the hazard integrated here is its
    #    expectation over the equation-4 category probabilities,
    #      E[h] = h0 * sum_k P(Y = k) * lambda^k,
    #    which is exact for the mean hazard (it marginalises the
    #    categorical outcome rather than approximating it by plugging
    #    the mean score into the power law). This is the one place where
    #    the encoding is not a literal transcription of a published
    #    equation; see the vignette Assumptions and deviations section.
    # ==================================================================
    h0_remd   <- exp(lh0_remd)
    haz_remd  <- h0_remd * (peq0_pr +
                            peq1_pr * lambda_remd +
                            peq2_pr * lambda_remd^2 +
                            peq3_pr * lambda_remd^3 +
                            peq4_pr * lambda_remd^4)

    d/dt(cumhaz) <- haz_remd
    cumhaz(0)    <- 0

    # Equation 10, P = 1 - exp(-h * dT), accumulated from time 0: the
    # probability that rescue medication has been required by time t,
    # and its complement, the Kaplan-Meier-style "still on treatment"
    # curve of Figure 2.
    premd_remd <- 1 - exp(-cumhaz)
    sur_remd   <- exp(-cumhaz)

    # Equation 12, T50 = log(2)/h: the time over which half of patients
    # at the current hazard would require rescue medication.
    t50_remd <- log(2) / haz_remd

    # ==================================================================
    # 4. ONSET OF MEANINGFUL PAIN RELIEF (equations 2, 13 to 15,
    #    Table 5). Algebraic in the administered dose.
    # ==================================================================

    # Equation 13, patients who required rescue medication:
    #   P(MPR) = P0 + (Pmax - P0) * Dose / (Dose + D50PMPR).
    # At Dose = 0 this returns P0 = 0.16 exactly.
    p0_mpr      <- expit(logitp0_mpr)
    pmax_mpr    <- expit(logitpmax_mpr)
    d50p_mpr    <- exp(ld50_pmpr)
    pmpr_remd   <- p0_mpr + (pmax_mpr - p0_mpr) *
      DOSE_APRICOXIB_MG / (DOSE_APRICOXIB_MG + d50p_mpr)

    # Patients who did not require rescue medication: dose-independent.
    pmpr_noremd <- expit(logitpmpr_noremd)

    # Equation 2, the mixture over whether rescue medication occurred:
    #   P(MPR) = P(MPR | REMD) * P(REMD) + P(MPR | no REMD) * P(no REMD)
    # with P(REMD) supplied by the rescue-medication sub-model above.
    pmpr <- pmpr_remd * premd_remd + pmpr_noremd * (1 - premd_remd)

    # Equation 14, patients who required rescue medication. The model
    # predicts the RATIO of the onset time to that patient's own rescue
    # time, which is the quantity plotted against dose in the lower
    # right panel of Figure 1; multiply by an individual rescue time to
    # obtain an absolute TMPR.
    d50_ltr_mpr  <- exp(ld50_ltr)
    logratio_mpr <- ltr0_mpr + etaltr0_mpr +
      ltrmax_mpr * DOSE_APRICOXIB_MG / (DOSE_APRICOXIB_MG + d50_ltr_mpr)
    ratio_mpr    <- exp(logratio_mpr)

    # Equation 15, patients who did not require rescue medication:
    #   log(TMPR) = LT0 + LTSlope * Dose + eps.
    logtmpr_mpr <- lt0_mpr + etalt0_mpr + tslope_mpr * DOSE_APRICOXIB_MG
    tmpr_mpr    <- exp(logtmpr_mpr)

    # ==================================================================
    # 5. Observation. The only endpoint carrying a published residual
    #    error is the apricoxib plasma concentration (Kastrissios 2006
    #    equation 3, proportional). The pain-relief endpoint is
    #    categorical -- its likelihood is the multinomial implied by the
    #    equation-4 cumulative probabilities, which has no residual-error
    #    term to attach -- and the rescue-medication and onset-time
    #    endpoints are a time-to-event hazard and a subject-level
    #    log-normal draw. Those quantities are exposed as derived
    #    outputs above rather than being given fabricated residual
    #    errors; every rxode2 solve returns them as columns.
    # ==================================================================
    Cc ~ prop(propSd)
  })
}
