Shchelokov_2023_nivolumab_qsp <- function() {
  description <- "QSP. Nivolumab PK linked to single-cell PD-1 receptor occupancy: two-compartment IV PK drives a receptor module with PD-1 synthesis, degradation, two-step bivalent antibody binding and internalization of all bound forms on CD4 and CD8 T cells, and returns the four receptor-occupancy readouts (free-receptor vs bound-receptor assay format, each normalized either to the predose baseline or to total receptor at each time point) that flow-cytometry RO assays report (Shchelokov 2023)"
  reference <- "Shchelokov D, Demin O Jr. Receptor occupancy assessment and interpretation in terms of quantitative systems pharmacology: nivolumab case study. MAbs. 2023;15(1):e2156317. doi:10.1080/19420862.2022.2156317"
  vignette <- "Shchelokov_2023_nivolumab_qsp"
  units <- list(time = "h", dosing = "mg", concentration = "ug/mL")

  # Receptor-module states are per-single-cell molecule counts of PD-1 and of
  # its two nivolumab-bound forms, stratified by T-cell subset. They are not
  # members of any canonical compartment family: `target` / `complex` are
  # amount- or concentration-valued TMDD states in a physiologic compartment,
  # and the registered `trimer` is the drug:CD3:antigen ternary complex of a
  # T-cell engager, not a receptor:mAb:receptor crosslink. Declared per the
  # `paper_specific_compartments` mechanism documented in
  # inst/references/compartment-names.md (QSP cell-binding states).
  paper_specific_compartments <- c(
    "pd1_cd4", "nivo_pd1_cd4", "pd1_nivo_pd1_cd4",
    "pd1_cd8", "nivo_pd1_cd8", "pd1_nivo_pd1_cd8"
  )

  covariateData <- list(
    WT = list(
      description        = "Baseline body weight",
      units              = "kg",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Power scaling on CL and Vc (Shchelokov 2023 Eq. 5; exponents CL_BW and Vc_BW in Table 1). Shchelokov 2023 does not print the reference weight BW_REF; it is 80 kg in the upstream popPK analysis the PK block is taken from (Bajaj 2017 Table 1 footnote), which is the value used here. See the model file comment on ref_wt.",
      source_name        = "BW"
    )
  )

  compartmentData <- list(
    central          = list(analyte = "nivolumab",             units = "mg",              specimen = "plasma",     verified = TRUE),
    peripheral1      = list(analyte = "nivolumab",             units = "mg",              specimen = "plasma",     verified = TRUE),
    pd1_cd4          = list(analyte = "PD-1",                  units = "molecules/cell",  specimen = "blood cell", verified = TRUE),
    nivo_pd1_cd4     = list(analyte = "nivolumab:PD-1",        units = "molecules/cell",  specimen = "blood cell", verified = TRUE),
    pd1_nivo_pd1_cd4 = list(analyte = "PD-1:nivolumab:PD-1",   units = "molecules/cell",  specimen = "blood cell", verified = TRUE),
    pd1_cd8          = list(analyte = "PD-1",                  units = "molecules/cell",  specimen = "blood cell", verified = TRUE),
    nivo_pd1_cd8     = list(analyte = "nivolumab:PD-1",        units = "molecules/cell",  specimen = "blood cell", verified = TRUE),
    pd1_nivo_pd1_cd8 = list(analyte = "PD-1:nivolumab:PD-1",   units = "molecules/cell",  specimen = "blood cell", verified = TRUE)
  )

  population <- list(
    species        = "human",
    n_subjects     = 100L,
    n_studies      = 1L,
    disease_state  = "Advanced / metastatic solid tumors (virtual population; the model was evaluated against nivolumab clinical RO and PK data from NCT00730639 and NCT01358721)",
    dose_range     = "0.1 - 10 mg/kg IV Q2W or Q3W, plus flat doses of 240 mg and 480 mg; 1-hour (zero-order) IV infusion",
    notes          = "Shchelokov 2023 is a simulation study, not a fit: no data were fitted and no parameter was estimated in the paper. Every value in ini() is inherited from a cited source and is therefore fixed(). The 'population' is the N = 100 virtual patients of the Methods section 'Parameter variability implementation', generated by sampling each parameter's log-normal inter-individual distribution from Table 1 (Eq. 5). The PK block and its inter-individual variances come from the nivolumab population-PK analysis of Bajaj 2017 (N = 1,895 patients with advanced solid tumors across 11 trials); the PD-1 baseline receptor counts and their variances come from the anti-PD-1 RO assay cohort of Fu 2019; the PD-1 turnover rate comes from the 13C6-leucine in vivo labeling study of Lassman 2021."
  )

  ini({
    # ---------------------------------------------------------------------
    # Pharmacokinetic module (Shchelokov 2023 Table 1, rows under
    # "Pharmacokinetic module"). Nothing here was estimated by Shchelokov
    # 2023: the whole block is carried over from the nivolumab population-PK
    # analysis of Bajaj 2017 (Methods, "Nivolumab pharmacokinetics"), so
    # every value is fixed(). Shchelokov 2023 keeps only Bajaj's baseline
    # (time-invariant) clearance and the body-weight covariate; the
    # time-varying-clearance, eGFR, sex, ECOG and race terms of Bajaj 2017
    # are not carried into this model.
    #
    # NOTE ON TABLE 1'S "Source" COLUMN. Table 1 cites reference 23 for the
    # PK rows, 27 for kdeg and 28 for SAcell. Those superscripts are stale by
    # four positions: the values match reference 27 (Bajaj 2017), 31 (Lassman
    # 2021) and 32 (Chapman 1981) respectively, which are also the references
    # the Methods text cites for exactly these quantities. Entries citing
    # references <= 18 are unaffected. Each affected value is verified
    # numerically in the comment on its own line.
    lvc     <- fixed(log(3.63));   label("Central volume of distribution Vc (L)")                     # Table 1: Vc = 3.63 L; = Bajaj 2017 Table 1 VC_REF = 3.63 L
    lcl     <- fixed(log(0.0094)); label("Clearance CL (L/h)")                                        # Table 1: CL = 0.0094 L/h; = Bajaj 2017 Table 1 CL_REF = 9.4 mL/h
    lvp     <- fixed(log(2.78));   label("Peripheral volume of distribution Vp (L)")                  # Table 1: Vp = 2.78 L; = Bajaj 2017 Table 1 VP_REF = 2.78 L
    lq      <- fixed(log(0.0321)); label("Inter-compartmental clearance Q (L/h)")                     # Table 1: Q = 0.0321 L/h; = Bajaj 2017 Table 1 Q_REF = 32.1 mL/h
    e_wt_vc <- fixed(0.597);       label("Power exponent of body weight on Vc (unitless)")            # Table 1: VcBW = 0.597; = Bajaj 2017 Table 1 VC_BW = 0.597
    e_wt_cl <- fixed(0.566);       label("Power exponent of body weight on CL (unitless)")            # Table 1: CLBW = 0.566; = Bajaj 2017 Table 1 CL_BW = 0.566

    # ---------------------------------------------------------------------
    # PD-1 receptor module (Shchelokov 2023 Table 1, rows under "PD-1
    # receptor module"). Also all inherited, hence fixed().
    kdeg        <- fixed(0.01402); label("Rate constant of free PD-1 degradation (1/h)")              # Table 1: kdeg = 0.01402 1/h; = ln(2)/49.4 h, the median PD-1 half-life of 49.5 h reported by Lassman 2021 (Methods, "PD-1 receptor dynamics")
    bl_pd1_cd4  <- fixed(2213);    label("Baseline PD-1 count on a CD4 T cell (molecules/cell)")      # Table 1: PD1(CD4)baseline = 2213 items
    bl_pd1_cd8  <- fixed(2639);    label("Baseline PD-1 count on a CD8 T cell (molecules/cell)")      # Table 1: PD1(CD8)baseline = 2639 items
    f_expression <- fixed(0.752);  label("Fold change in PD-1 surface expression during treatment (unitless)") # Table 1: Expression = 0.752; Methods "median fold change ~0.75"
    koff        <- fixed(2.7648);  label("Dissociation rate constant of the nivolumab:PD-1 complex (1/h)")     # Table 1: koff = 2.7648 1/h
    kd_3d       <- fixed(3.06);    label("Equilibrium dissociation constant of nivolumab:PD-1 in solution (nM)") # Table 1: Kd(3D) = 3.06 nM
    sa_cell     <- fixed(152);     label("Surface area of a T cell (um^2)")                           # Table 1: SAcell = 152 um^2; estimated from the spherical volume of a mononuclear cell (Chapman 1981)

    # ---------------------------------------------------------------------
    # Inter-individual variability. Shchelokov 2023 Eq. 5 applies a single
    # independent log-normal eta per parameter, theta_i = theta_REF *
    # exp(eta), with the variances omega^2 given in Table 1's
    # "Inter-individual variability" column. No covariance terms are
    # reported, so the etas are independent here; in particular the CL:Vc
    # covariance of Bajaj 2017 is NOT carried over, matching Eq. 5. The
    # variances are inherited rather than estimated, hence fixed().
    # Table 1 reports no variability for Q, VcBW, CLBW, koff, Kd(3D) or
    # SAcell; those parameters carry no eta.
    etalvc         ~ fixed(0.123)                                                                    # Table 1: omega^2(Vc) = 0.123
    etalcl         ~ fixed(0.123)                                                                    # Table 1: omega^2(CL) = 0.123
    etalvp         ~ fixed(0.258)                                                                    # Table 1: omega^2(Vp) = 0.258
    etakdeg        ~ fixed(0.645)                                                                    # Table 1: omega^2(kdeg) = 0.645
    etabl_pd1_cd4  ~ fixed(0.272)                                                                    # Table 1: omega^2(PD1(CD4)baseline) = 0.272
    etabl_pd1_cd8  ~ fixed(0.258)                                                                    # Table 1: omega^2(PD1(CD8)baseline) = 0.258
    etaf_expression ~ fixed(0.218)                                                                   # Table 1: omega^2(Expression) = 0.218

    # No residual-error model. Shchelokov 2023 is a forward-simulation study;
    # it reports no residual error for either the PK or the RO readouts, and
    # its figures show simulated medians with 95% prediction intervals
    # generated from the inter-individual distributions above alone.
  })

  model({
    # -------------------------------------------------------------------
    # Constants.
    #
    # ref_wt: Eq. 5 normalizes body weight to BW_REF but Shchelokov 2023
    # never prints its value. The PK block and both body-weight exponents
    # are taken verbatim from Bajaj 2017 (Methods, "Nivolumab
    # pharmacokinetics"), whose reference weight is 80 kg (Bajaj 2017
    # Table 1 footnote a, Eqs. 7 and 10); Vc = 3.63 L and CL = 9.4 mL/h are
    # that paper's typical values AT 80 kg, so 80 kg is the only weight at
    # which this model reproduces them. Inherited from the on-disk upstream
    # source, not from the lead paper.
    ref_wt <- 80 # kg

    # mw_mab: nivolumab molar mass, needed to convert the mg/L plasma
    # concentration of the PK module into the nM concentration the binding
    # terms consume. Shchelokov 2023 does not tabulate it; 146 kDa is the
    # calculated molecular mass in the OPDIVO US prescribing information,
    # which is reference 12 of the lead paper (FDA label 125554s112, 2022,
    # Section 11 Description).
    mw_mab <- 146 # kDa

    # nm_per_molecule_um3: 1 nM = 1e-9 mol/L * 6.02214076e23 /mol
    # = 6.02214076e14 molecules/L, and 1 L = 1e15 um^3, so 1 nM
    # = 0.602214076 molecules/um^3. Used only to give Kd(2D) the
    # molecules/um^2 units of a surface density.
    nm_per_molecule_um3 <- 0.602214076

    # confinement_length: the proportionality coefficient that converts a
    # solution (3D) dissociation constant into a surface (2D) one under
    # reduction of dimensionality (Bell 1978). Supplement, "Calculation of
    # equilibrium dissociation constant (Kd) for surface interactions":
    # "The reported value of the coefficient, which authors referred to as
    # 'confinement length', is about 3 micrometers", measured in situ for
    # receptor-ligand pairs including PD-1/PD-L1 (Li 2017).
    confinement_length <- 3 # um

    # -------------------------------------------------------------------
    # Individual parameters (Shchelokov 2023 Eq. 5).
    vc <- exp(lvc + etalvc) * (WT / ref_wt)^e_wt_vc
    cl <- exp(lcl + etalcl) * (WT / ref_wt)^e_wt_cl
    vp <- exp(lvp + etalvp)
    q  <- exp(lq)

    kdeg_i        <- kdeg        * exp(etakdeg)
    bl_pd1_cd4_i  <- bl_pd1_cd4  * exp(etabl_pd1_cd4)
    bl_pd1_cd8_i  <- bl_pd1_cd8  * exp(etabl_pd1_cd8)
    f_expression_i <- f_expression * exp(etaf_expression)

    # Derived receptor-module constants (Table 1, "Estimate" column, rows
    # Ksyn and kint, which are given as formulas rather than numbers).
    ksyn_cd4 <- kdeg_i * bl_pd1_cd4_i # Table 1: Ksyn = kdeg * PD1baseline
    ksyn_cd8 <- kdeg_i * bl_pd1_cd8_i # Table 1: Ksyn = kdeg * PD1baseline
    kint     <- kdeg_i / f_expression_i # Table 1: kint = kdeg / Expression

    # Surface (2D) dissociation constant, molecules/um^2. Supplement:
    # Kd(2D) = sigma * Kd(3D) * N_A. With sigma = 3 um and Kd(3D) = 3.06 nM
    # this is 5.53 molecules/um^2, matching the supplement's own arithmetic
    # ("simple calculations give an estimated Kd(2D) value of ~5.4 molecules
    # per um^2" for a round Kd(3D) of 3 nM) and its cross-check that Kd(2D)
    # is "approximately 3 times less than PD-1 concentration on the surface
    # of T cell" (2213/152 = 14.6 and 2639/152 = 17.4 molecules/um^2).
    kd_2d <- confinement_length * kd_3d * nm_per_molecule_um3

    # -------------------------------------------------------------------
    # PK module (Supplement, "System of model ODEs", "Nivolumab
    # pharmacokinetics"). Two-compartment disposition with zero-order IV
    # infusion; the infusion is supplied through the event table's rate
    # column rather than as a model term.
    d/dt(central)     <- -cl * central / vc - q * (central / vc - peripheral1 / vp)
    d/dt(peripheral1) <-                      q * (central / vc - peripheral1 / vp)

    # Plasma concentration, mg/L = ug/mL, and the same concentration in nM
    # (mg/L * 1e6 / (mw_mab in g/mol) = mg/L * 1e3 / (mw_mab in kDa)).
    Cc    <- central / vc
    Cc_nM <- Cc * 1000 / mw_mab

    # -------------------------------------------------------------------
    # PD-1 receptor module (Supplement, "System of model ODEs", "PD-1
    # receptors on CD4/CD8 T cells in blood"). Amounts are molecules per
    # single cell. Binding is written as the paper writes it, with the
    # association rate expressed as koff/Kd rather than as a separate kon.
    #
    # bind1 is the first, bulk-phase-to-surface binding step: nivolumab in
    # blood binds one PD-1 with either arm, hence the stoichiometric factor
    # 2 on the forward term.
    # bind2 is the second, surface-limited step in which the already-bound
    # antibody captures a second PD-1 with its free arm; its reverse term
    # carries the factor 2 because either of the two engaged arms may
    # release. Kd(2D) * SAcell converts the surface density into the
    # molecules-per-cell units of the states.
    bind1_cd4 <- koff * (2 * Cc_nM * pd1_cd4 / kd_3d - nivo_pd1_cd4)
    bind2_cd4 <- koff * (nivo_pd1_cd4 * pd1_cd4 / (kd_2d * sa_cell) - 2 * pd1_nivo_pd1_cd4)

    d/dt(pd1_cd4)          <- ksyn_cd4 - kdeg_i * pd1_cd4 - bind1_cd4 - bind2_cd4
    d/dt(nivo_pd1_cd4)     <- bind1_cd4 - bind2_cd4 - kint * nivo_pd1_cd4
    d/dt(pd1_nivo_pd1_cd4) <- bind2_cd4 - kint * pd1_nivo_pd1_cd4

    bind1_cd8 <- koff * (2 * Cc_nM * pd1_cd8 / kd_3d - nivo_pd1_cd8)
    bind2_cd8 <- koff * (nivo_pd1_cd8 * pd1_cd8 / (kd_2d * sa_cell) - 2 * pd1_nivo_pd1_cd8)

    d/dt(pd1_cd8)          <- ksyn_cd8 - kdeg_i * pd1_cd8 - bind1_cd8 - bind2_cd8
    d/dt(nivo_pd1_cd8)     <- bind1_cd8 - bind2_cd8 - kint * nivo_pd1_cd8
    d/dt(pd1_nivo_pd1_cd8) <- bind2_cd8 - kint * pd1_nivo_pd1_cd8

    # The receptor system starts at its drug-free steady state: with
    # Ksyn = kdeg * PD1baseline the free-receptor equation balances at
    # PD1baseline, and no antibody is present before the first dose.
    pd1_cd4(0) <- bl_pd1_cd4_i
    pd1_cd8(0) <- bl_pd1_cd8_i

    # -------------------------------------------------------------------
    # Receptor-occupancy readouts (Shchelokov 2023 Eqs. 1-4, Methods,
    # "Receptor occupancy assessment"). All four are reported because the
    # point of the paper is that they diverge; which one to compare against
    # a given clinical dataset depends on that study's assay format.
    #
    # The denominators differ: Eqs. 1 and 3 normalize to the predose
    # baseline receptor amount, Eqs. 2 and 4 to the total receptor at the
    # current time point, which counts the ternary complex twice because it
    # holds two receptors. The numerator of Eqs. 3 and 4 is the amount of
    # DRUG bound to receptor, [mAb:R] + [R:mAb:R], not the amount of bound
    # receptor (Results: "the bound strategy detects the drug bound to
    # receptors ... instead of bound receptors").
    pd1_total_cd4 <- pd1_cd4 + nivo_pd1_cd4 + 2 * pd1_nivo_pd1_cd4
    pd1_bound_cd4 <- nivo_pd1_cd4 + pd1_nivo_pd1_cd4
    pd1_total_cd8 <- pd1_cd8 + nivo_pd1_cd8 + 2 * pd1_nivo_pd1_cd8
    pd1_bound_cd8 <- nivo_pd1_cd8 + pd1_nivo_pd1_cd8

    ro1_cd4 <- 100 * (1 - pd1_cd4 / bl_pd1_cd4_i) # Eq. 1: free receptor, normalized to baseline
    ro2_cd4 <- 100 * (1 - pd1_cd4 / pd1_total_cd4) # Eq. 2: free receptor, normalized to total at each time point
    ro3_cd4 <- 100 * pd1_bound_cd4 / bl_pd1_cd4_i # Eq. 3: bound receptor, normalized to baseline
    ro4_cd4 <- 100 * pd1_bound_cd4 / pd1_total_cd4 # Eq. 4: bound receptor, normalized to total at each time point

    ro1_cd8 <- 100 * (1 - pd1_cd8 / bl_pd1_cd8_i) # Eq. 1
    ro2_cd8 <- 100 * (1 - pd1_cd8 / pd1_total_cd8) # Eq. 2
    ro3_cd8 <- 100 * pd1_bound_cd8 / bl_pd1_cd8_i # Eq. 3
    ro4_cd8 <- 100 * pd1_bound_cd8 / pd1_total_cd8 # Eq. 4
  })
}
