Verner_2015_pfos_pbpk <- function() {
  description <- paste(
    "PBPK (whole-body, gestational; original implementation in acslX).",
    "perfluorooctane sulfonate (PFOS) in pregnant women, from the Verner et al. 2015 modification of",
    "the Loccisano et al. 2013 human gestation PBPK model. Fifteen",
    "mass-balance states: maternal plasma, liver, gut, fat, mammary tissue,",
    "skin, kidney, rest of body, a glomerular filtrate compartment feeding a",
    "urinary storage compartment through saturable renal reabsorption, the",
    "placenta, and a separate fetal circulation (fetal plasma, rest of fetal",
    "body, amniotic fluid) reached only by bidirectional placental diffusion.",
    "Model time is HOURS SINCE CONCEPTION, so gestational week wk = time/168",
    "drives the maternal renal plasma flow, glomerular filtration rate,",
    "plasma volume, haematocrit and amniotic-fluid volume lookup tables and",
    "the fetal, placental, fat and mammary growth curves. Exposure is a",
    "constant hourly intake back-calculated from a pre-pregnancy plasma level",
    "assumed to be at steady state, so there are no dose records. The",
    "Verner 2015 modification is the GFR-birth-weight coupling: the covariate",
    "RENALFUNC_REL (the paper's GFRratio) simultaneously scales the whole",
    "gestational GFR profile and sets birth weight through a meta-analytic",
    "regression, and birth weight in turn rescales the fetal growth curve, so",
    "a single subject-level renal-function draw induces the confounded",
    "association between plasma PFAS and birth weight that the paper",
    "quantifies. Deterministic typical-value model (no IIV, no residual",
    "error): population variability was generated by Monte Carlo sampling of",
    "the parameters in Table 1, not by estimated random effects."
  )
  reference <- paste(
    "Verner MA, Loccisano AE, Morken NH, Yoon M, Wu H, McDougall R,",
    "Maisonet M, Marcus M, Kishi R, Miyashita C, Chen MH, Hsieh WS,",
    "Andersen ME, Clewell HJ 3rd, Longnecker MP. (2015). Associations of",
    "Perfluoroalkyl Substances (PFAS) with Lower Birth Weight: An Evaluation",
    "of Potential Confounding by Glomerular Filtration Rate Using a",
    "Physiologically Based Pharmacokinetic Model (PBPK).",
    "Environ Health Perspect 123(12):1317-1324. doi:10.1289/ehp.1408837.",
    "PMCID PMC4671243. Structure, parameter values and gestational lookup",
    "tables from Supplemental Material, 'PBPK Model Code' (acslX listing)",
    "and Figure S1; Monte Carlo distributions from Table 1.",
    "Structural parent model: Loccisano AE, Longnecker MP, Campbell JL Jr,",
    "Andersen ME, Clewell HJ 3rd. (2013) J Toxicol Environ Health A",
    "76(1):25-57."
  )
  vignette <- "Verner_2015_pfas_birthweight"

  units <- list(
    time = "h",
    dosing = "mg",
    concentration = "mg/L",
    amount = "mg",
    weight = "kg"
  )

  paper_specific_compartments <- c(
    "plasma",
    "gut",
    "fat",
    "mammary",
    "rest",
    "filtrate",
    "storage",
    "placenta",
    "plasma_fet",
    "rest_fet",
    "amniotic",
    "auc_plasma",
    "auc_plasma_fet",
    "a_intake"
  )

  compartmentData <- list(
    plasma = list(analyte = "PFOS", units = "mg", specimen = "plasma", verified = TRUE),
    liver = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    gut = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    fat = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    mammary = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    skin = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    kidney = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    rest = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    filtrate = list(analyte = "PFOS", units = "mg", specimen = "urine", verified = TRUE),
    storage = list(analyte = "PFOS", units = "mg", specimen = "urine", verified = TRUE),
    urine = list(analyte = "PFOS", units = "mg", specimen = "urine", verified = TRUE),
    placenta = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    plasma_fet = list(analyte = "PFOS", units = "mg", specimen = "plasma", verified = TRUE),
    rest_fet = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    amniotic = list(analyte = "PFOS", units = "mg", specimen = "tissue", verified = TRUE),
    auc_plasma = list(analyte = "PFOS", units = "mg*h/L", specimen = "not applicable", verified = TRUE),
    auc_plasma_fet = list(analyte = "PFOS", units = "mg*h/L", specimen = "not applicable", verified = TRUE),
    a_intake = list(analyte = "PFOS", units = "mg", specimen = "not applicable", verified = TRUE)
  )

  covariateData <- list(
    WT = list(
      description = "Body weight",
      units = "kg",
      type = "continuous",
      reference_category = NULL,
      notes = paste(
        "Maternal PRE-PREGNANCY body weight (acslX constant BWINIT). The",
        "acslX listing carries BWINIT = 60.9 kg, the Loccisano et al. 2013",
        "reference pregnant woman; the Monte Carlo analysis resamples it.",
        "Every maternal tissue volume except skin is a fixed fraction of",
        "this pre-pregnancy weight, the initial cardiac output and the",
        "urinary rate constant are allometric in it, and the time-varying",
        "gestational body weight BW = WT + fat + mammary + placental +",
        "fetal + amniotic increments (which drives the saturable",
        "reabsorption Tm) is built up from it. Table 1 gives the Monte",
        "Carlo distribution as 70.3 +/- 14.3 kg (range 37.0-134.0) from",
        "the Norwegian Mother and Child Cohort Study; the deposited",
        "automation script instead draws N(74.7, 17.8) truncated to",
        "50-114 kg. See the vignette Errata for that conflict.",
        sep = " "
      ),
      source_name = "BWINIT"
    ),
    RENALFUNC_REL = list(
      description = "Relative renal function, 1 = normal",
      units = "(dimensionless)",
      type = "continuous",
      reference_category = NULL,
      notes = paste(
        "The paper's GFRratio: the ratio of a woman's observed glomerular",
        "filtration rate to the MEAN GFR AT HER GESTATIONAL AGE, so 1 is",
        "normal filtration for that point in pregnancy (Verner 2015",
        "Methods, 'The PBPK model'). It enters the model directly as a",
        "multiplier on the whole gestational GFR profile (Eq. 3,",
        "GFR_t = GFRratio * reference GFR_t, acslX QFil = Ratio_GFR *",
        "DQFil(WK)) and, through the meta-analytic regression of Eq. 4,",
        "as the sole systematic determinant of birth weight. Monte Carlo",
        "distribution 1.000 +/- 0.246, truncated to 0.508-1.492 (Table 1;",
        "distribution of GFRratio in Morken et al. 2014).",
        sep = " "
      ),
      source_name = "GFRratio"
    )
  )

  population <- list(
    species = "human",
    n_subjects = 0L,
    n_studies = 0L,
    age_range = "reproductive age (not otherwise specified)",
    weight_range = paste(
      "Pre-pregnancy 37.0-134.0 kg, mean 70.3 (SD 14.3), from the Norwegian",
      "Mother and Child Cohort Study (Table 1). The acslX listing default is",
      "the Loccisano et al. 2013 reference woman at 60.9 kg."
    ),
    sex_female_pct = 100,
    disease_state = "healthy singleton pregnancy, conception to delivery at 6,570 h (39.1 weeks)",
    dose_range = paste(
      "No dose records. Chronic background environmental exposure entered as",
      "a constant hourly intake back-calculated from the pre-pregnancy plasma",
      "level under a steady-state assumption (Eq. 2). Monte Carlo initial",
      "plasma PFOS 13.02 ng/mL (CV 0.368), truncated to 0.01-100 ng/mL;",
      "that mean is the equal-weight average of the reported maternal or cord",
      "means/medians of the seven epidemiologic studies in the meta-analysis."
    ),
    regions = paste(
      "Exposure distributions pooled from cohorts in the USA, Denmark,",
      "Canada, Japan, Taiwan, Norway and Great Britain (Table S1);",
      "GFRratio distribution and pre-pregnancy weight from Norway (MoBa)."
    ),
    notes = paste(
      "NO SUBJECTS WERE FITTED. This is a forward Monte Carlo simulation, so",
      "n_subjects and n_studies are 0. The model was run 250,000 times with",
      "the Table 1 parameter distributions to generate paired predictions of",
      "plasma PFOS and birth weight, which were then regressed on one",
      "another. The published slopes are -1.46 g birth weight per ng/mL",
      "(95% CI -1.81, -1.11) for maternal plasma at delivery and -2.72 g",
      "per ng/mL (95% CI -3.40, -2.04) for cord plasma (Table 2, main results",
      "row). Model accuracy was assessed only at the population level, by",
      "visual comparison of simulated maternal plasma trajectories against",
      "serial measurements from Glynn et al. 2012 and Monroy et al. 2008",
      "(Figure 2); no individual-level PFAS kinetic data were fitted."
    )
  )

  ini({
    # =====================================================================
    # Everything in this model is a recoded literature constant: nothing was
    # estimated from data, so every parameter is fixed(). Sources are the
    # acslX listing in Supplemental Material, 'PBPK Model Code', unless
    # noted. The listing selects PFOS with the compound flag
    # `constant PFOS = 1`.
    # =====================================================================

    # --- Maternal physiology: blood flows -------------------------------
    qc_per_kg        <- fixed(20.0)   ; label("Cardiac blood output (L/h/kg^0.75)")                       # acslX QCC = 20.0
    fq_liver         <- fixed(0.065)  ; label("Hepatic-artery flow, fraction of cardiac plasma output")   # acslX QLC = 0.065
    fq_skin          <- fixed(0.058)  ; label("Skin flow, fraction of cardiac plasma output")             # acslX QSkC = 0.058
    fq_gut           <- fixed(0.181)  ; label("Gut flow, fraction of cardiac plasma output")              # acslX QGC = 0.181
    fq_mammary       <- fixed(0.027)  ; label("Initial mammary flow, fraction of cardiac plasma output")  # acslX QMamC = 0.027
    fq_fat           <- fixed(0.052)  ; label("Initial fat flow, fraction of cardiac plasma output")      # acslX QFatC = 0.052
    fq_placenta      <- fixed(0.33)   ; label("Placental flow, fraction of fetal cardiac plasma output")  # acslX QPlaC = 0.33
    qc_fet_per_kg    <- fixed(24.0)   ; label("Fetal cardiac blood output (L/h/kg fetal weight)")         # acslX QFetC = 24.0

    # --- Maternal physiology: tissue volumes ----------------------------
    fv_liver         <- fixed(0.026)  ; label("Liver volume, fraction of pre-pregnancy body weight")      # acslX VLC = 0.026
    fv_kidney        <- fixed(0.004)  ; label("Kidney volume, fraction of pre-pregnancy body weight")     # acslX VKC = 0.004
    fv_filtrate      <- fixed(0.0004) ; label("Filtrate volume, fraction of pre-pregnancy body weight")   # acslX VfilC = 0.0004
    fv_gut           <- fixed(0.0171) ; label("Gut volume, fraction of pre-pregnancy body weight")        # acslX VGC = 0.0171
    fv_mammary       <- fixed(0.0062) ; label("Initial mammary volume, fraction of pre-pregnancy body weight")  # acslX VMamC = 0.0062
    fv_fat           <- fixed(0.214)  ; label("Initial fat volume, fraction of pre-pregnancy body weight")      # acslX VFatC = 0.214
    v_skin           <- fixed(0.0972) ; label("Skin volume (L)")                                          # acslX VSk = 0.0972, commented 'Skin volume (L)' -- see vignette Errata
    f_perfused       <- fixed(0.84)   ; label("Fraction of pre-pregnancy body weight available as perfused tissue (unitless)")  # acslX VR = (0.84*BWINIT) - ...
    fv_body_fet      <- fixed(0.92)   ; label("Fraction of fetal weight available as perfused fetal tissue (unitless)")         # acslX VRF = (0.92*VFet) - VPlasF
    fv_plasma_fet    <- fixed(0.0428) ; label("Fetal plasma volume, fraction of fetal weight")            # acslX VPlasFC = 0.0428
    htc_fet          <- fixed(0.5)    ; label("Fetal haematocrit (unitless)")                             # acslX HtcF = 0.5

    # --- Gestational growth curves --------------------------------------
    # Fetal weight (kg): the sum of two Gompertz terms in hours since
    # conception; it reaches 3.50857 kg at t = 6,570 h, which is exactly the
    # reference birth weight the listing divides by in Eq. 5.
    v_fet_a1         <- fixed(3.779)    ; label("Fetal growth curve, amplitude of first Gompertz term (kg)")       # acslX VFet_av, 3.779
    v_fet_b1         <- fixed(16.081)   ; label("Fetal growth curve, displacement of first Gompertz term")         # acslX VFet_av, 16.081
    v_fet_c1         <- fixed(5.67e-4)  ; label("Fetal growth curve, rate of first Gompertz term (1/h)")           # acslX VFet_av, 5.67e-4
    v_fet_a2         <- fixed(3.833)    ; label("Fetal growth curve, amplitude of second Gompertz term (kg)")      # acslX VFet_av, 3.833
    v_fet_b2         <- fixed(140.178)  ; label("Fetal growth curve, displacement of second Gompertz term")        # acslX VFet_av, 140.178
    v_fet_c2         <- fixed(7.01e-4)  ; label("Fetal growth curve, rate of second Gompertz term (1/h)")          # acslX VFet_av, 7.01e-4
    wt_fet_ref       <- fixed(3.50857)  ; label("Reference fetal weight at delivery (kg)")                         # acslX Birthweight = 3.50857 and VFet = (Birthweight/3.50857)*VFet_av
    v_pla_a          <- fixed(0.85)     ; label("Placenta growth curve, amplitude (L)")                            # acslX VPla_av, 0.85
    v_pla_b          <- fixed(9.434)    ; label("Placenta growth curve, displacement")                             # acslX VPla_av, 9.434
    v_pla_c          <- fixed(5.23e-4)  ; label("Placenta growth curve, rate (1/h)")                               # acslX VPla_av, 5.23e-4
    v_mam_a          <- fixed(0.0065)   ; label("Mammary growth curve, amplitude (fraction of pre-pregnancy body weight)")  # acslX VMam, 0.0065
    v_mam_b          <- fixed(7.444868477) ; label("Mammary growth curve, displacement")                           # acslX VMam, 7.444868477
    v_mam_c          <- fixed(0.000678) ; label("Mammary growth curve, rate (1/h)")                                # acslX VMam, 0.000678
    v_fat_a          <- fixed(0.09)     ; label("Fat growth curve, amplitude (fraction of pre-pregnancy body weight)")      # acslX VFat, 0.09
    v_fat_b          <- fixed(12.90995862) ; label("Fat growth curve, displacement")                               # acslX VFat, 12.90995862
    v_fat_c          <- fixed(0.000797) ; label("Fat growth curve, rate (1/h)")                                    # acslX VFat, 0.000797

    # --- Chemical-specific: tissue:plasma partition coefficients --------
    # acslX block 'Tissue:plasma partition coefficients (from rat)'.
    lkp_liver         <- fixed(log(3.72))   ; label("Liver:plasma partition coefficient (unitless)")         # acslX PFOS_PL = 3.72; Table 1 Monte Carlo mean 3.72, SD 0.558
    lkp_fat           <- fixed(log(0.14))     ; label("Fat:plasma partition coefficient (unitless)")           # acslX PFOS_PFat = 0.14
    lkp_kidney        <- fixed(log(0.80))  ; label("Kidney:plasma partition coefficient (unitless)")        # acslX PFOS_PK = 0.80
    lkp_skin          <- fixed(log(0.29))    ; label("Skin:plasma partition coefficient (unitless)")          # acslX PFOS_PSk = 0.29
    lkp_rest          <- fixed(log(0.20))    ; label("Rest-of-body:plasma partition coefficient (unitless)")  # acslX PFOS_PR = 0.20; Table 1 Monte Carlo mean 0.20, SD 0.030
    lkp_gut           <- fixed(log(0.57))     ; label("Gut:plasma partition coefficient (unitless)")           # acslX PFOS_PG = 0.57
    lkp_mammary       <- fixed(log(0.16)) ; label("Mammary:plasma partition coefficient (unitless)")       # acslX PFOS_PMam = 0.16
    lkp_placenta      <- fixed(log(0.41)); label("Placenta:plasma partition coefficient (unitless)")      # acslX PFOS_PPla = 0.41
    lkp_rest_fet      <- fixed(log(0.20)); label("Rest-of-fetal-body:plasma partition coefficient (unitless)")  # acslX PFOS_PRF = 0.20

    # --- Chemical-specific: plasma protein binding ----------------------
    fu               <- fixed(0.025)     ; label("Free fraction in maternal plasma (unitless)")  # acslX PFOS_Free = 0.025; Table 1 Monte Carlo mean 0.025, SD 0.004
    fu_fet           <- fixed(0.025) ; label("Free fraction in fetal plasma (unitless)")     # acslX PFOS_FreeF = 0.025; Table 1 Monte Carlo mean 0.025, SD 0.004

    # --- Chemical-specific: renal reabsorption and urinary excretion ----
    tm_per_kg        <- fixed(3.5) ; label("Maximum renal reabsorption velocity (mg/h/kg^0.75)")  # acslX PFOS_TMC = 3.5; Table 1 Monte Carlo mean 3.5, SD 0.525
    km               <- fixed(0.023)        ; label("Renal transporter affinity constant (mg/L)")          # acslX PFOS_KT = 0.023; Table 1 Monte Carlo mean 0.023, SD 0.003
    kurine_per_kg    <- fixed(0.005)       ; label("Urinary elimination rate constant (1/h per kg^-0.25)")  # acslX kurinec = 0.005

    # --- Chemical-specific: placental and amniotic-fluid transfer -------
    ktrans1_per_kg   <- fixed(0.46) ; label("Placenta-to-fetal-plasma transfer constant (L/h/kg^0.75)")     # acslX PFOS_k1c = 0.46
    ktrans2_per_kg   <- fixed(1.01) ; label("Fetal-plasma-to-placenta transfer constant (L/h/kg^0.75)")     # acslX PFOS_k2c = 1.01
    ktrans3_per_kg   <- fixed(0.006) ; label("Fetal-body-to-amniotic-fluid transfer constant (L/h/kg^0.75)") # acslX ktrans3c = PFOS*0.006
    ktrans4_per_kg   <- fixed(0.001) ; label("Amniotic-fluid-to-fetal-body transfer constant (L/h/kg^0.75)") # acslX ktrans4c = PFOS*0.001

    # --- Exposure -------------------------------------------------------
    # The pre-pregnancy plasma level is the single exposure knob. The
    # listing's default is 0.013 mg/L; the value carried here is the
    # Monte Carlo mean of Table 1 (13.02 ng/mL). Override per scenario or
    # per simulated subject through rxSolve(params = ...).
    cvinit           <- fixed(0.01302) ; label("Pre-pregnancy (steady-state) plasma PFOS concentration (mg/L)")  # Table 1, initial plasma PFOS 13.02 ng/mL; acslX CVINIT default 0.013
    half_life_yr     <- fixed(5.4)     ; label("PFOS elimination half-life (years)")                             # acslX PFOS_HL = 5.4, from Olsen et al. 2007
    dose_interval    <- fixed(1)        ; label("Intake dosing interval (h)")                                       # acslX DOSE_INT = 1
    ln2_recip        <- fixed(1.44)     ; label("Reciprocal of ln(2) as rounded in the acslX listing (unitless)")   # acslX IVHOURLYDOSE = CVINIT*Vol_dist*DOSE_INT/(1.44*HALF_LIFE); Eq. 2 writes ln(2)/half-life

    # --- The Verner 2015 GFR / birth-weight coupling (Eq. 4) ------------
    # Birth weight (kg) = intercept + beta * GFRratio + residual. The
    # residual defaults to 0, giving the typical-value birth weight; the
    # Monte Carlo draws N(0, 0.441) kg truncated to +/- 0.882 kg and passes
    # it through rxSolve(params = ...).
    bw_intercept     <- fixed(3.376)  ; label("Birth-weight regression intercept (kg)")                        # Methods Eq. 4, intercept 3,376 g; acslX script CONSTANT_REG = 3.376
    bw_beta_gfr      <- fixed(0.1755) ; label("Birth-weight increase per unit increase in GFRratio (kg)")      # Methods Eq. 4, beta 175.5 +/- 75.9 g; acslX script BETA_REG = 0.1755
    bw_resid         <- fixed(0)      ; label("Birth-weight regression residual for this subject (kg)")        # Table 1, residual birth weight 0 +/- 441 g, bounds -882 to 882 g

    # =====================================================================
    # No IIV and no residual error. Verner et al. ran a deterministic PBPK
    # model 250,000 times under the Table 1 input distributions; they did
    # not estimate random effects and report no residual-error model.
    # =====================================================================
  })

  model({
    # =====================================================================
    # 1. Time base. Model time is HOURS SINCE CONCEPTION.
    # =====================================================================
    gd <- time / 24    # gestation day   (acslX GD = T/24)
    wk <- gd / 7       # gestation week  (acslX WK = GD/7)

    # Partition coefficients are carried on the log scale in ini() (package
    # convention; cf. Zhang_2024_f53b_human_pbpk.R) and back-transformed here.
    kp_fat      <- exp(lkp_fat)
    kp_gut      <- exp(lkp_gut)
    kp_kidney   <- exp(lkp_kidney)
    kp_liver    <- exp(lkp_liver)
    kp_mammary  <- exp(lkp_mammary)
    kp_placenta <- exp(lkp_placenta)
    kp_rest     <- exp(lkp_rest)
    kp_rest_fet <- exp(lkp_rest_fet)
    kp_skin     <- exp(lkp_skin)

    # =====================================================================
    # 2. Gestational physiology lookup tables.
    #
    # The acslX listing supplies five TABLE() functions of gestational week
    # and interpolates them linearly, holding the end values outside the
    # tabulated range. Each is written here in hinge form,
    #     f  <- y[1]
    #     f  <- f + (y[k+1] - y[k]) * min(1, max(0, (wk - x[k])/(x[k+1] - x[k])))
    # which is algebraically identical to linear interpolation with clamped
    # ends (verified against stats::approx(..., rule = 2) to machine zero
    # over wk in [-2, 45]) and keeps every tabulated knot visible on the
    # line that uses it. Units: q_kidney_ref and gfr_ref L/h, fv_plasma a
    # fraction of body weight, htc unitless, v_amniotic L.
    # =====================================================================
    # q_kidney_ref
    q_kidney_ref <- 24.42
    q_kidney_ref <- q_kidney_ref + (50.58 - 24.42) * min(1, max(0, (wk - 0) / (8 - 0)))
    q_kidney_ref <- q_kidney_ref + (45.42 - 50.58) * min(1, max(0, (wk - 8) / (10 - 8)))
    q_kidney_ref <- q_kidney_ref + (51.36 - 45.42) * min(1, max(0, (wk - 10) / (11 - 10)))
    q_kidney_ref <- q_kidney_ref + (57.12 - 51.36) * min(1, max(0, (wk - 11) / (12 - 11)))
    q_kidney_ref <- q_kidney_ref + (46.32 - 57.12) * min(1, max(0, (wk - 12) / (13 - 12)))
    q_kidney_ref <- q_kidney_ref + (44.73 - 46.32) * min(1, max(0, (wk - 13) / (15 - 13)))
    q_kidney_ref <- q_kidney_ref + (45.36 - 44.73) * min(1, max(0, (wk - 15) / (17 - 15)))
    q_kidney_ref <- q_kidney_ref + (41.8 - 45.36) * min(1, max(0, (wk - 17) / (18 - 17)))
    q_kidney_ref <- q_kidney_ref + (46.53 - 41.8) * min(1, max(0, (wk - 18) / (19 - 18)))
    q_kidney_ref <- q_kidney_ref + (46.08 - 46.53) * min(1, max(0, (wk - 19) / (22 - 19)))
    q_kidney_ref <- q_kidney_ref + (47.85 - 46.08) * min(1, max(0, (wk - 22) / (23 - 22)))
    q_kidney_ref <- q_kidney_ref + (43.05 - 47.85) * min(1, max(0, (wk - 23) / (24 - 23)))
    q_kidney_ref <- q_kidney_ref + (41.16 - 43.05) * min(1, max(0, (wk - 24) / (25 - 24)))
    q_kidney_ref <- q_kidney_ref + (47.52 - 41.16) * min(1, max(0, (wk - 25) / (26 - 25)))
    q_kidney_ref <- q_kidney_ref + (43.41 - 47.52) * min(1, max(0, (wk - 26) / (27 - 26)))
    q_kidney_ref <- q_kidney_ref + (48.57 - 43.41) * min(1, max(0, (wk - 27) / (28 - 27)))
    q_kidney_ref <- q_kidney_ref + (46.36 - 48.57) * min(1, max(0, (wk - 28) / (29 - 28)))
    q_kidney_ref <- q_kidney_ref + (36.68 - 46.36) * min(1, max(0, (wk - 29) / (31 - 29)))
    q_kidney_ref <- q_kidney_ref + (39.44 - 36.68) * min(1, max(0, (wk - 31) / (32 - 31)))
    q_kidney_ref <- q_kidney_ref + (46.46 - 39.44) * min(1, max(0, (wk - 32) / (33 - 32)))
    q_kidney_ref <- q_kidney_ref + (44.13 - 46.46) * min(1, max(0, (wk - 33) / (34 - 33)))
    q_kidney_ref <- q_kidney_ref + (26.7 - 44.13) * min(1, max(0, (wk - 34) / (36 - 34)))
    q_kidney_ref <- q_kidney_ref + (33.92 - 26.7) * min(1, max(0, (wk - 36) / (37 - 36)))
    q_kidney_ref <- q_kidney_ref + (35.46 - 33.92) * min(1, max(0, (wk - 37) / (38 - 37)))
    q_kidney_ref <- q_kidney_ref + (40.26 - 35.46) * min(1, max(0, (wk - 38) / (40 - 38)))

    # gfr_ref
    gfr_ref <- 6
    gfr_ref <- gfr_ref + (6 - 6) * min(1, max(0, (wk - 0) / (1 - 0)))
    gfr_ref <- gfr_ref + (6 - 6) * min(1, max(0, (wk - 1) / (2 - 1)))
    gfr_ref <- gfr_ref + (6 - 6) * min(1, max(0, (wk - 2) / (3 - 2)))
    gfr_ref <- gfr_ref + (6 - 6) * min(1, max(0, (wk - 3) / (4 - 3)))
    gfr_ref <- gfr_ref + (6.03 - 6) * min(1, max(0, (wk - 4) / (5 - 4)))
    gfr_ref <- gfr_ref + (6.09 - 6.03) * min(1, max(0, (wk - 5) / (6 - 5)))
    gfr_ref <- gfr_ref + (6.18 - 6.09) * min(1, max(0, (wk - 6) / (7 - 6)))
    gfr_ref <- gfr_ref + (6.32 - 6.18) * min(1, max(0, (wk - 7) / (8 - 7)))
    gfr_ref <- gfr_ref + (6.5 - 6.32) * min(1, max(0, (wk - 8) / (9 - 8)))
    gfr_ref <- gfr_ref + (6.72 - 6.5) * min(1, max(0, (wk - 9) / (10 - 9)))
    gfr_ref <- gfr_ref + (6.97 - 6.72) * min(1, max(0, (wk - 10) / (11 - 10)))
    gfr_ref <- gfr_ref + (7.23 - 6.97) * min(1, max(0, (wk - 11) / (12 - 11)))
    gfr_ref <- gfr_ref + (7.5 - 7.23) * min(1, max(0, (wk - 12) / (13 - 12)))
    gfr_ref <- gfr_ref + (7.76 - 7.5) * min(1, max(0, (wk - 13) / (14 - 13)))
    gfr_ref <- gfr_ref + (8.01 - 7.76) * min(1, max(0, (wk - 14) / (15 - 14)))
    gfr_ref <- gfr_ref + (8.23 - 8.01) * min(1, max(0, (wk - 15) / (16 - 15)))
    gfr_ref <- gfr_ref + (8.43 - 8.23) * min(1, max(0, (wk - 16) / (17 - 16)))
    gfr_ref <- gfr_ref + (8.6 - 8.43) * min(1, max(0, (wk - 17) / (18 - 17)))
    gfr_ref <- gfr_ref + (8.75 - 8.6) * min(1, max(0, (wk - 18) / (19 - 18)))
    gfr_ref <- gfr_ref + (8.86 - 8.75) * min(1, max(0, (wk - 19) / (20 - 19)))
    gfr_ref <- gfr_ref + (8.95 - 8.86) * min(1, max(0, (wk - 20) / (21 - 20)))
    gfr_ref <- gfr_ref + (9.01 - 8.95) * min(1, max(0, (wk - 21) / (22 - 21)))
    gfr_ref <- gfr_ref + (9.05 - 9.01) * min(1, max(0, (wk - 22) / (23 - 22)))
    gfr_ref <- gfr_ref + (9.06 - 9.05) * min(1, max(0, (wk - 23) / (24 - 23)))
    gfr_ref <- gfr_ref + (9.06 - 9.06) * min(1, max(0, (wk - 24) / (25 - 24)))
    gfr_ref <- gfr_ref + (9.04 - 9.06) * min(1, max(0, (wk - 25) / (26 - 25)))
    gfr_ref <- gfr_ref + (8.99 - 9.04) * min(1, max(0, (wk - 26) / (27 - 26)))
    gfr_ref <- gfr_ref + (8.95 - 8.99) * min(1, max(0, (wk - 27) / (28 - 27)))
    gfr_ref <- gfr_ref + (8.88 - 8.95) * min(1, max(0, (wk - 28) / (29 - 28)))
    gfr_ref <- gfr_ref + (8.81 - 8.88) * min(1, max(0, (wk - 29) / (30 - 29)))
    gfr_ref <- gfr_ref + (8.72 - 8.81) * min(1, max(0, (wk - 30) / (31 - 30)))
    gfr_ref <- gfr_ref + (8.62 - 8.72) * min(1, max(0, (wk - 31) / (32 - 31)))
    gfr_ref <- gfr_ref + (8.52 - 8.62) * min(1, max(0, (wk - 32) / (33 - 32)))
    gfr_ref <- gfr_ref + (8.41 - 8.52) * min(1, max(0, (wk - 33) / (34 - 33)))
    gfr_ref <- gfr_ref + (8.29 - 8.41) * min(1, max(0, (wk - 34) / (35 - 34)))
    gfr_ref <- gfr_ref + (8.16 - 8.29) * min(1, max(0, (wk - 35) / (36 - 35)))
    gfr_ref <- gfr_ref + (8.03 - 8.16) * min(1, max(0, (wk - 36) / (37 - 36)))
    gfr_ref <- gfr_ref + (7.89 - 8.03) * min(1, max(0, (wk - 37) / (38 - 37)))
    gfr_ref <- gfr_ref + (7.75 - 7.89) * min(1, max(0, (wk - 38) / (39 - 38)))

    # fv_plasma
    fv_plasma <- 0.0442
    fv_plasma <- fv_plasma + (0.0445 - 0.0442) * min(1, max(0, (wk - 9) / (10 - 9)))
    fv_plasma <- fv_plasma + (0.0448 - 0.0445) * min(1, max(0, (wk - 10) / (11 - 10)))
    fv_plasma <- fv_plasma + (0.0451 - 0.0448) * min(1, max(0, (wk - 11) / (12 - 11)))
    fv_plasma <- fv_plasma + (0.0454 - 0.0451) * min(1, max(0, (wk - 12) / (13 - 12)))
    fv_plasma <- fv_plasma + (0.0456 - 0.0454) * min(1, max(0, (wk - 13) / (14 - 13)))
    fv_plasma <- fv_plasma + (0.0458 - 0.0456) * min(1, max(0, (wk - 14) / (15 - 14)))
    fv_plasma <- fv_plasma + (0.046 - 0.0458) * min(1, max(0, (wk - 15) / (16 - 15)))
    fv_plasma <- fv_plasma + (0.0461 - 0.046) * min(1, max(0, (wk - 16) / (17 - 16)))
    fv_plasma <- fv_plasma + (0.0462 - 0.0461) * min(1, max(0, (wk - 17) / (18 - 17)))
    fv_plasma <- fv_plasma + (0.0463 - 0.0462) * min(1, max(0, (wk - 18) / (19 - 18)))
    fv_plasma <- fv_plasma + (0.0464 - 0.0463) * min(1, max(0, (wk - 19) / (20 - 19)))
    fv_plasma <- fv_plasma + (0.0464 - 0.0464) * min(1, max(0, (wk - 20) / (21 - 20)))
    fv_plasma <- fv_plasma + (0.0464 - 0.0464) * min(1, max(0, (wk - 21) / (22 - 21)))
    fv_plasma <- fv_plasma + (0.0464 - 0.0464) * min(1, max(0, (wk - 22) / (23 - 22)))
    fv_plasma <- fv_plasma + (0.0463 - 0.0464) * min(1, max(0, (wk - 23) / (24 - 23)))
    fv_plasma <- fv_plasma + (0.0463 - 0.0463) * min(1, max(0, (wk - 24) / (25 - 24)))
    fv_plasma <- fv_plasma + (0.0461 - 0.0463) * min(1, max(0, (wk - 25) / (26 - 25)))
    fv_plasma <- fv_plasma + (0.046 - 0.0461) * min(1, max(0, (wk - 26) / (27 - 26)))
    fv_plasma <- fv_plasma + (0.0458 - 0.046) * min(1, max(0, (wk - 27) / (28 - 27)))
    fv_plasma <- fv_plasma + (0.0456 - 0.0458) * min(1, max(0, (wk - 28) / (29 - 28)))
    fv_plasma <- fv_plasma + (0.0454 - 0.0456) * min(1, max(0, (wk - 29) / (30 - 29)))
    fv_plasma <- fv_plasma + (0.0451 - 0.0454) * min(1, max(0, (wk - 30) / (31 - 30)))
    fv_plasma <- fv_plasma + (0.0448 - 0.0451) * min(1, max(0, (wk - 31) / (32 - 31)))
    fv_plasma <- fv_plasma + (0.0445 - 0.0448) * min(1, max(0, (wk - 32) / (33 - 32)))
    fv_plasma <- fv_plasma + (0.0441 - 0.0445) * min(1, max(0, (wk - 33) / (34 - 33)))
    fv_plasma <- fv_plasma + (0.0437 - 0.0441) * min(1, max(0, (wk - 34) / (35 - 34)))
    fv_plasma <- fv_plasma + (0.0433 - 0.0437) * min(1, max(0, (wk - 35) / (36 - 35)))

    # htc
    htc <- 0.38
    htc <- htc + (0.372 - 0.38) * min(1, max(0, (wk - 0) / (11 - 0)))
    htc <- htc + (0.356 - 0.372) * min(1, max(0, (wk - 11) / (16 - 11)))
    htc <- htc + (0.354 - 0.356) * min(1, max(0, (wk - 16) / (20 - 16)))
    htc <- htc + (0.349 - 0.354) * min(1, max(0, (wk - 20) / (24 - 20)))
    htc <- htc + (0.347 - 0.349) * min(1, max(0, (wk - 24) / (28 - 24)))
    htc <- htc + (0.346 - 0.347) * min(1, max(0, (wk - 28) / (32 - 28)))
    htc <- htc + (0.354 - 0.346) * min(1, max(0, (wk - 32) / (36 - 32)))
    htc <- htc + (0.367 - 0.354) * min(1, max(0, (wk - 36) / (40 - 36)))

    # v_amniotic
    v_amniotic <- 0.0237
    v_amniotic <- v_amniotic + (0.0235 - 0.0237) * min(1, max(0, (wk - 0) / (8 - 0)))
    v_amniotic <- v_amniotic + (0.0234 - 0.0235) * min(1, max(0, (wk - 8) / (9 - 8)))
    v_amniotic <- v_amniotic + (0.0232 - 0.0234) * min(1, max(0, (wk - 9) / (10 - 9)))
    v_amniotic <- v_amniotic + (0.0766 - 0.0232) * min(1, max(0, (wk - 10) / (11 - 10)))
    v_amniotic <- v_amniotic + (0.124 - 0.0766) * min(1, max(0, (wk - 11) / (12 - 11)))
    v_amniotic <- v_amniotic + (0.195 - 0.124) * min(1, max(0, (wk - 12) / (16 - 12)))
    v_amniotic <- v_amniotic + (0.284 - 0.195) * min(1, max(0, (wk - 16) / (18 - 16)))
    v_amniotic <- v_amniotic + (0.361 - 0.284) * min(1, max(0, (wk - 18) / (20 - 18)))
    v_amniotic <- v_amniotic + (0.646 - 0.361) * min(1, max(0, (wk - 20) / (22 - 20)))
    v_amniotic <- v_amniotic + (0.64 - 0.646) * min(1, max(0, (wk - 22) / (24 - 22)))
    v_amniotic <- v_amniotic + (0.687 - 0.64) * min(1, max(0, (wk - 24) / (26 - 24)))
    v_amniotic <- v_amniotic + (0.77 - 0.687) * min(1, max(0, (wk - 26) / (28 - 26)))
    v_amniotic <- v_amniotic + (0.824 - 0.77) * min(1, max(0, (wk - 28) / (30 - 28)))
    v_amniotic <- v_amniotic + (0.776 - 0.824) * min(1, max(0, (wk - 30) / (32 - 30)))
    v_amniotic <- v_amniotic + (0.817 - 0.776) * min(1, max(0, (wk - 32) / (34 - 32)))
    v_amniotic <- v_amniotic + (0.817 - 0.817) * min(1, max(0, (wk - 34) / (36 - 34)))
    v_amniotic <- v_amniotic + (0.799 - 0.817) * min(1, max(0, (wk - 36) / (38 - 36)))
    v_amniotic <- v_amniotic + (0.53 - 0.799) * min(1, max(0, (wk - 38) / (40 - 38)))
    v_amniotic <- v_amniotic + (0.506 - 0.53) * min(1, max(0, (wk - 40) / (42 - 40)))

    # Week-zero values of the same tables, used for the pre-pregnancy
    # anchors (acslX DQK(0), DQFil(0), DVPlasC(0), DHtc(0)). Note that the
    # maternal plasma-volume table starts at week 9, so DVPlasC(0) returns
    # its first tabulated value under the clamping rule.
    q_kidney_ref_0 <- 24.42     # acslX DQK(0)
    gfr_ref_0      <- 6         # acslX DQFil(0)
    fv_plasma_0    <- 0.0442    # acslX DVPlasC(0), clamped from week 9
    htc_0          <- 0.38      # acslX DHtc(0)

    # =====================================================================
    # 3. Birth weight and the growth curves it rescales (Eqs. 4 and 5).
    #    RENALFUNC_REL is the paper's GFRratio.
    # =====================================================================
    wt_birth <- bw_intercept + bw_beta_gfr * RENALFUNC_REL + bw_resid

    v_fet_av <- v_fet_a1 * exp(-v_fet_b1 * exp(-v_fet_c1 * time)) +
                v_fet_a2 * exp(-v_fet_b2 * exp(-v_fet_c2 * time))
    v_fet    <- (wt_birth / wt_fet_ref) * v_fet_av        # Eq. 5
    v_pla    <- v_pla_a * exp(-v_pla_b * exp(-v_pla_c * time))
    v_amn    <- v_amniotic                                # acslX VAF = AF_VAF*VAFX(WK)

    # =====================================================================
    # 4. Maternal volumes (L) and gestational body weight (kg).
    # =====================================================================
    v_liver       <- fv_liver    * WT
    v_kidney      <- fv_kidney   * WT
    v_filtrate    <- fv_filtrate * WT
    v_gut         <- fv_gut      * WT
    v_mammary_0   <- fv_mammary  * WT
    v_fat_0       <- fv_fat      * WT
    v_plasma_0    <- fv_plasma_0 * WT

    v_rest <- f_perfused * WT - v_liver - v_kidney - v_filtrate - v_gut -
              v_plasma_0 - v_skin - v_mammary_0 - v_fat_0

    v_mammary <- WT * (fv_mammary + v_mam_a * exp(-v_mam_b * exp(-v_mam_c * time)))
    v_fat     <- WT * (fv_fat     + v_fat_a * exp(-v_fat_b * exp(-v_fat_c * time)))

    bw        <- WT + (v_fat - v_fat_0) + (v_mammary - v_mammary_0) +
                 v_pla + v_fet + v_amn
    v_plasma  <- fv_plasma * bw

    v_plasma_fet <- fv_plasma_fet * v_fet
    v_rest_fet   <- fv_body_fet * v_fet - v_plasma_fet

    # =====================================================================
    # 5. Blood (plasma) flows, L/h.
    # =====================================================================
    qc_0        <- qc_per_kg * WT^0.75
    qcp_0       <- qc_0 * (1 - htc_0)                  # initial cardiac PLASMA output
    q_liver     <- fq_liver * qcp_0
    q_gut       <- fq_gut   * qcp_0
    q_skin      <- fq_skin  * qcp_0
    q_fat_0     <- fq_fat   * qcp_0
    q_fat       <- q_fat_0 * (v_fat / v_fat_0)
    q_mammary_0 <- fq_mammary * qcp_0
    q_mammary   <- q_mammary_0 * (v_mammary / v_mammary_0)

    q_kidney    <- q_kidney_ref                        # acslX QK = AF_QK*DQK(WK)
    q_kidney_0  <- q_kidney_ref_0

    # Eq. 3: the whole gestational GFR profile is scaled by GFRratio, and so
    # is its pre-pregnancy anchor (acslX QFilINIT = Ratio_GFR*DQFil(0)).
    gfr         <- RENALFUNC_REL * gfr_ref
    gfr_0       <- RENALFUNC_REL * gfr_ref_0

    q_fet       <- qc_fet_per_kg * v_fet * (1 - htc_fet)
    q_rest_fet  <- q_fet
    q_placenta  <- fq_placenta * q_fet

    qc      <- qcp_0 + (q_fat - q_fat_0) + (q_mammary - q_mammary_0) +
               (q_kidney - q_kidney_0) + (gfr - gfr_0) + q_placenta
    q_rest  <- qc - (q_liver + q_kidney + q_gut + q_skin + q_fat +
                     q_mammary + q_placenta)

    # =====================================================================
    # 6. Allometrically scaled kinetic parameters.
    # =====================================================================
    kurine   <- kurine_per_kg * WT^(-0.25)      # acslX kurine = kurinec*(BWINIT**(-0.25))
    tm       <- tm_per_kg * bw^0.75             # acslX Tm = Tmc*BW**0.75, on gestational BW
    ktrans1  <- ktrans1_per_kg * v_fet^0.75
    ktrans2  <- ktrans2_per_kg * v_fet^0.75
    ktrans3  <- ktrans3_per_kg * v_fet^0.75
    ktrans4  <- ktrans4_per_kg * v_fet^0.75

    # =====================================================================
    # 7. Exposure (Eq. 2). The pre-pregnancy plasma level is assumed to be
    #    at steady state, so the hourly intake that sustains it is
    #    C_initial * Vd * tau / (ln(2)^-1 * half-life). The volume of
    #    distribution is the partition-weighted sum of the pre-pregnancy
    #    maternal tissue volumes.
    # =====================================================================
    vd <- v_plasma_0 + kp_gut * v_gut + kp_liver * v_liver +
          kp_fat * v_fat_0 + kp_kidney * v_kidney + kp_rest * v_rest +
          kp_mammary * v_mammary_0 + kp_skin * v_skin
    intake <- cvinit * vd * dose_interval / (ln2_recip * half_life_yr * 365 * 24)

    # =====================================================================
    # 8. Concentrations (mg/L). The plasma states hold FREE amounts, so the
    #    total plasma concentration divides the free concentration by the
    #    free fraction.
    # =====================================================================
    c_plasma_free <- plasma / v_plasma
    ca            <- c_plasma_free / fu
    c_fat         <- fat / v_fat
    cv_fat        <- c_fat / kp_fat
    c_mammary     <- mammary / v_mammary
    cv_mammary    <- c_mammary / kp_mammary
    c_gut         <- gut / v_gut
    cv_gut        <- c_gut / kp_gut
    c_liver       <- liver / v_liver
    cv_liver      <- c_liver / kp_liver
    c_kidney      <- kidney / v_kidney
    cv_kidney     <- c_kidney / kp_kidney
    c_skin        <- skin / v_skin
    cv_skin       <- c_skin / kp_skin
    c_rest        <- rest / v_rest
    cv_rest       <- c_rest / kp_rest
    c_filtrate    <- filtrate / v_filtrate
    c_placenta    <- placenta / v_pla
    cv_placenta   <- c_placenta / kp_placenta

    c_plasma_fet_free <- plasma_fet / (v_plasma_fet + 1e-7)
    ca_fet            <- c_plasma_fet_free / fu_fet
    c_rest_fet        <- rest_fet / (v_rest_fet + 1e-33)
    cv_rest_fet       <- c_rest_fet / kp_rest_fet
    c_amniotic        <- amniotic / (v_amn + 1e-7)

    # =====================================================================
    # 9. Placental and amniotic-fluid fluxes (mg/h).
    # =====================================================================
    rtrans1 <- ktrans1 * cv_placenta * fu        # placenta -> fetal plasma
    rtrans2 <- ktrans2 * ca_fet * fu_fet         # fetal plasma -> placenta
    rtrans3 <- ktrans3 * cv_rest_fet * fu_fet    # fetal body -> amniotic fluid
    rtrans4 <- ktrans4 * c_amniotic              # amniotic fluid -> fetal body

    # =====================================================================
    # 10. Mass-balance ODE system (Supplemental Material Figure S1 and the
    #     acslX DERIVATIVE block). The saturable reabsorption term is
    #     written with the filtrate state INLINE: a named intermediate that
    #     reads an ODE state can silently evaluate to zero inside d/dt() in
    #     the nlmixr2 model-function form.
    # =====================================================================
    d/dt(fat)      <- q_fat     * (ca * fu - cv_fat * fu)
    d/dt(mammary)  <- q_mammary * (ca * fu - cv_mammary * fu)
    d/dt(gut)      <- q_gut     * (ca * fu - cv_gut * fu)
    d/dt(liver)    <- q_liver * ca * fu + q_gut * cv_gut * fu -
                      (q_liver + q_gut) * cv_liver * fu
    d/dt(skin)     <- q_skin * (ca * fu - cv_skin * fu)
    d/dt(rest)     <- q_rest * (ca * fu - cv_rest * fu)

    d/dt(kidney)   <- q_kidney * (ca * fu - cv_kidney * fu) +
                      tm * (filtrate / v_filtrate) / (km + filtrate / v_filtrate)
    d/dt(filtrate) <- gfr * (ca * fu - filtrate / v_filtrate) -
                      tm * (filtrate / v_filtrate) / (km + filtrate / v_filtrate)
    d/dt(storage)  <- gfr * (filtrate / v_filtrate) - kurine * storage
    d/dt(urine)    <- kurine * storage

    d/dt(placenta) <- q_placenta * (ca * fu - cv_placenta * fu) - rtrans1 + rtrans2

    d/dt(plasma)   <- q_fat * cv_fat * fu +
                      (q_liver + q_gut) * cv_liver * fu +
                      q_rest * cv_rest * fu +
                      q_skin * cv_skin * fu +
                      q_kidney * cv_kidney * fu +
                      q_mammary * cv_mammary * fu +
                      q_placenta * cv_placenta * fu -
                      qc * ca * fu +
                      intake -
                      gfr * ca * fu

    d/dt(rest_fet)   <- q_rest_fet * (ca_fet * fu_fet - cv_rest_fet * fu_fet) -
                        rtrans3 + rtrans4
    d/dt(amniotic)   <- rtrans3 - rtrans4
    d/dt(plasma_fet) <- q_rest_fet * cv_rest_fet * fu_fet -
                        q_rest_fet * ca_fet * fu_fet + rtrans1 - rtrans2

    # Bookkeeping accumulators carried by the acslX listing.
    d/dt(auc_plasma)     <- ca        # acslX AUCPlas
    d/dt(auc_plasma_fet) <- ca_fet    # acslX AUCPLASF
    d/dt(a_intake)       <- intake    # acslX IV_TOTAL

    # =====================================================================
    # 11. Initial conditions (Eq. 1). The pre-pregnancy body burden is the
    #     product of the initial plasma level, the tissue:plasma partition
    #     coefficient and the pre-pregnancy tissue volume. The plasma state
    #     holds the FREE amount. Filtrate, storage, urine, placenta and all
    #     fetal states start empty, as in the listing.
    # =====================================================================
    plasma(0)  <- cvinit * v_plasma_0 * fu     # acslX APLAS0
    gut(0)     <- cvinit * kp_gut * v_gut      # acslX AG0
    liver(0)   <- cvinit * kp_liver * v_liver  # acslX AL0
    fat(0)     <- cvinit * kp_fat * v_fat_0    # acslX AFAT0
    kidney(0)  <- cvinit * kp_kidney * v_kidney    # acslX AK0
    rest(0)    <- cvinit * kp_rest * v_rest        # acslX AR0
    mammary(0) <- cvinit * kp_mammary * v_mammary_0  # acslX AMAM0
    skin(0)    <- cvinit * kp_skin * v_skin          # acslX ASK0

    # =====================================================================
    # 12. Outputs.
    # =====================================================================
    Cc          <- ca                 # maternal plasma, TOTAL concentration (mg/L)
    Cplasma_fet <- ca_fet             # fetal (cord) plasma, TOTAL concentration (mg/L)
    Cplacenta   <- c_placenta
    Camniotic   <- c_amniotic
    Cliver      <- c_liver
    Ckidney     <- c_kidney
    Cfat        <- c_fat
    Crest       <- c_rest
    Crest_fet   <- c_rest_fet
    Cfiltrate   <- c_filtrate
    WTbirth     <- wt_birth           # birth weight for this subject (kg)
    WTfet       <- v_fet              # fetal weight (kg)
    BWmat       <- bw                 # maternal gestational body weight (kg)
    GFR         <- gfr                # maternal glomerular filtration rate (L/h)
    Vplasma     <- v_plasma
    Vamniotic   <- v_amn              # acslX VAF, the VAFX(WK) lookup
    Qkidney     <- q_kidney           # acslX QK, the DQK(WK) lookup
    Vdist       <- vd                 # acslX Vol_dist, used by Eq. 2
    Intake      <- intake             # acslX IVHOURLYDOSE (mg/h), Eq. 2
    Htcmat      <- htc                # acslX computes Htc from DHtc(WK) but uses only HtcINIT
    Aplasma_tot <- ca * v_plasma      # acslX APlastot, TOTAL amount in maternal plasma

    # acslX BALANCE_DOSE: (cumulative intake + initial body burden) minus
    # everything currently in the system. Should hold at zero to solver
    # tolerance for the whole pregnancy.
    a_initial <- cvinit * (v_plasma_0 * fu + kp_gut * v_gut + kp_liver * v_liver +
                           kp_fat * v_fat_0 + kp_kidney * v_kidney +
                           kp_rest * v_rest + kp_mammary * v_mammary_0 +
                           kp_skin * v_skin)
    MassBalance <- (a_intake + a_initial) -
                   (plasma + gut + liver + fat + kidney + rest + mammary + skin +
                    placenta + plasma_fet + filtrate + storage + urine +
                    rest_fet + amniotic)
  })
}
