Xu_2025_checkpoint_bsab_qsp <- function() {
  description <- paste(
    "QSP. Preclinical (mouse). Multi-scale mechanistic quantitative systems",
    "pharmacology platform for checkpoint-targeting immuno-modulatory bispecific",
    "antibodies in syngeneic tumour-bearing mice. Couples a TCR/CD3-driven T cell",
    "intracellular signalling network (ZAP70, PI3K, AKT, ERK, NF-kB, IL-2, IFN-gamma",
    "and two transcriptional promoters) to mass-action binding of eleven immune",
    "checkpoints across T cells, tumour cells and antigen-presenting cells",
    "(PD-1/PD-L1, CTLA4/CD80-CD86, CD28/CD80-CD86, TIGIT/CD155, LAG3, 4-1BB/4-1BBL,",
    "OX40/OX40L and MHC/TCR), logistic tumour and T cell growth, and a three-stage",
    "dead-cell clearance chain that determines measured tumour volume. Two",
    "bispecific antibodies are parameterised end to end - anti-TIGIT/PD-L1 (drug_3)",
    "and anti-4-1BB/PD-L1 (drug_11) - each with its own two-compartment mouse",
    "plasma PK, an intraperitoneal depot, a tumour partition coefficient and the",
    "full drug-checkpoint dimer and trimer cascade on both tumour and APC surfaces.",
    "A SHP2-inhibitor (SHP099) module is carried structurally but is not dosed by",
    "default because its published PK constants are not reproducible (see the",
    "vignette Errata). 59 ODE states and 122 parameters, translated from the",
    "SimBiology model in Supplementary Table S1. Deterministic mechanism model:",
    "virtual mice were generated by sampling parameters within physiological",
    "ranges rather than by estimating IIV or residual error, so no etas and no",
    "error model are encoded.",
    sep = " "
  )
  reference <- paste(
    "Xu Y, Yang S, Rao Q, Gao Y, Zhou G, Zhao D, Shi X, Chai Y, Zhao C.",
    "A mechanistic quantitative systems pharmacology model platform for",
    "translational efficacy evaluation and checkpoint combination design of",
    "bispecific immuno-modulatory antibodies. Front Pharmacol. 2025;16:1571844.",
    "doi:10.3389/fphar.2025.1571844.",
    sep = " "
  )
  vignette <- "Xu_2025_checkpoint_bsab_qsp"

  units <- list(
    time          = "h",
    dosing        = "nmol",
    concentration = "nmol/L"
  )

  covariateData <- list()

  # Every ODE state in this model is a paper-mechanistic species from
  # Supplementary Table S1 (Species / Reactions / Equations sheets); none map
  # onto the canonical central / peripheral1 / effect vocabulary except the
  # per-drug plasma PK states, which are drug-suffixed here because the two
  # bispecific antibodies can be dosed simultaneously.
  paper_specific_compartments <- c(
    "drug3_abdominal", "drug3_central", "drug3_peripheral",
    "drug11_abdominal", "drug11_central", "drug11_peripheral",
    "shp099_gi", "shp099_central", "shp099_peripheral",
    "TCRCD3", "CD28", "ZAP70_n", "ZAP70_a", "PI3K_n", "PI3K_a",
    "Akt_n", "Akt_a", "Erk_n", "Erk_a", "NFkB", "IL2", "IFNg",
    "promoter_1_n", "promoter_1_a", "promoter_2_n", "promoter_2_a",
    "inhibitor_1", "inhibitor_2", "inhibitor_3", "inhibitor_n",
    "activation_1", "activation_2",
    "APC_MHC_TCR_total", "tumor_MHC_TCR_total", "CD28_CD8086_total",
    "CTLA4_CD8086_total", "PD1_APC_PDL1_total", "PD1_tumor_PDL1_total",
    "CD137_CD137L_total", "OX40_OX40L_total",
    "TIGIT_APC_CD155_total", "TIGIT_tumor_CD155_total", "CTLA4_per_cell",
    "tumor_cell", "t_cell", "M1", "M2", "M3", "death_cell",
    "dimer3_PDL1_tumor", "dimer3_PDL1_APC", "dimer3_TIGIT",
    "trimer3_tumor", "trimer3_APC",
    "dimer11_PDL1_tumor", "dimer11_PDL1_APC", "dimer11_CD137",
    "trimer11_tumor", "trimer11_APC"
  )

  compartmentData <- list(
    # ---- anti-TIGIT/PD-L1 bispecific antibody (drug_3) plasma PK ----
    drug3_abdominal  = list(analyte = "anti-TIGIT/PD-L1 bispecific antibody", units = "nmol", specimen = "administration site", verified = TRUE),
    drug3_central    = list(analyte = "anti-TIGIT/PD-L1 bispecific antibody", units = "nmol", specimen = "plasma", verified = TRUE),
    drug3_peripheral = list(analyte = "anti-TIGIT/PD-L1 bispecific antibody", units = "nmol", specimen = "tissue", verified = TRUE),
    # ---- anti-4-1BB/PD-L1 bispecific antibody (drug_11) plasma PK ----
    drug11_abdominal  = list(analyte = "anti-4-1BB/PD-L1 bispecific antibody", units = "nmol", specimen = "administration site", verified = TRUE),
    drug11_central    = list(analyte = "anti-4-1BB/PD-L1 bispecific antibody", units = "nmol", specimen = "plasma", verified = TRUE),
    drug11_peripheral = list(analyte = "anti-4-1BB/PD-L1 bispecific antibody", units = "nmol", specimen = "tissue", verified = TRUE),
    # ---- SHP099 (SHP2 inhibitor) PK; not dosed by default ----
    shp099_gi         = list(analyte = "SHP099", units = "nmol", specimen = "administration site", verified = TRUE),
    shp099_central    = list(analyte = "SHP099", units = "nmol", specimen = "plasma", verified = TRUE),
    shp099_peripheral = list(analyte = "SHP099", units = "nmol", specimen = "tissue", verified = TRUE),
    # ---- T cell surface receptors available to anti-CD3 / anti-CD28 stimulation ----
    TCRCD3 = list(analyte = "TCR/CD3 complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    CD28   = list(analyte = "CD28", units = "nmol/L", specimen = "tumor", verified = TRUE),
    # ---- T cell intracellular signalling network ----
    ZAP70_n = list(analyte = "inactive ZAP70", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    ZAP70_a = list(analyte = "phosphorylated ZAP70", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    PI3K_n  = list(analyte = "inactive PI3K", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    PI3K_a  = list(analyte = "phosphorylated PI3K", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    Akt_n   = list(analyte = "inactive AKT", units = "nmol/L", specimen = "not applicable", verified = TRUE),
    Akt_a   = list(analyte = "phosphorylated AKT", units = "nmol/L", specimen = "not applicable", verified = TRUE),
    Erk_n   = list(analyte = "inactive ERK", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    Erk_a   = list(analyte = "phosphorylated ERK", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    NFkB    = list(analyte = "NF-kB", units = "nmol/L", specimen = "not applicable", verified = TRUE),
    IL2     = list(analyte = "interleukin-2", units = "nmol/L", specimen = "tumor", verified = TRUE),
    IFNg    = list(analyte = "interferon gamma", units = "nmol/L", specimen = "tumor", verified = TRUE),
    promoter_1_n = list(analyte = "inactive ERK-driven promoter", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    promoter_1_a = list(analyte = "active ERK-driven promoter", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    promoter_2_n = list(analyte = "inactive NF-kB-driven promoter", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    promoter_2_a = list(analyte = "active NF-kB-driven promoter", units = "dimensionless", specimen = "not applicable", verified = TRUE),
    # ---- checkpoint-recruited second messengers ----
    inhibitor_1  = list(analyte = "PD-1/PD-L1-recruited inhibitor (SHP2)", units = "nmol/L", specimen = "not applicable", verified = TRUE),
    inhibitor_2  = list(analyte = "CTLA4/CD80-CD86-recruited inhibitor", units = "nmol/L", specimen = "not applicable", verified = TRUE),
    inhibitor_3  = list(analyte = "TIGIT/CD155-recruited inhibitor", units = "nmol/L", specimen = "not applicable", verified = TRUE),
    inhibitor_n  = list(analyte = "SHP099-inactivated inhibitor_1", units = "nmol/L", specimen = "not applicable", verified = TRUE),
    activation_1 = list(analyte = "4-1BB-recruited activator", units = "nmol/L", specimen = "not applicable", verified = TRUE),
    activation_2 = list(analyte = "OX40-recruited activator", units = "nmol/L", specimen = "not applicable", verified = TRUE),
    # ---- endogenous checkpoint complexes (tumour-volume concentrations) ----
    APC_MHC_TCR_total      = list(analyte = "APC MHC:TCR/CD3 complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    tumor_MHC_TCR_total    = list(analyte = "tumour MHC:TCR/CD3 complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    CD28_CD8086_total      = list(analyte = "CD28:CD80/86 complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    CTLA4_CD8086_total     = list(analyte = "CTLA4:CD80/86 complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    PD1_APC_PDL1_total     = list(analyte = "PD-1:APC PD-L1 complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    PD1_tumor_PDL1_total   = list(analyte = "PD-1:tumour PD-L1 complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    CD137_CD137L_total     = list(analyte = "4-1BB:4-1BBL complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    OX40_OX40L_total       = list(analyte = "OX40:OX40L complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    TIGIT_APC_CD155_total  = list(analyte = "TIGIT:APC CD155 complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    TIGIT_tumor_CD155_total= list(analyte = "TIGIT:tumour CD155 complex", units = "nmol/L", specimen = "tumor", verified = TRUE),
    CTLA4_per_cell         = list(analyte = "CTLA4 surface density per T cell", units = "nmol/L", specimen = "tumor", verified = TRUE),
    # ---- cell populations ----
    tumor_cell = list(analyte = "viable tumour cells", units = "cell", specimen = "tumor", verified = TRUE),
    t_cell     = list(analyte = "T cells", units = "cell", specimen = "tumor", verified = TRUE),
    M1         = list(analyte = "killed tumour cells, clearance stage 1", units = "cell", specimen = "tumor", verified = TRUE),
    M2         = list(analyte = "killed tumour cells, clearance stage 2", units = "cell", specimen = "tumor", verified = TRUE),
    M3         = list(analyte = "killed tumour cells, clearance stage 3", units = "cell", specimen = "tumor", verified = TRUE),
    death_cell = list(analyte = "cleared dead tumour cells", units = "cell", specimen = "tumor", verified = TRUE),
    # ---- anti-TIGIT/PD-L1 (drug_3) drug-checkpoint complexes ----
    dimer3_PDL1_tumor = list(analyte = "drug_3:tumour PD-L1 dimer", units = "nmol/L", specimen = "tumor", verified = TRUE),
    dimer3_PDL1_APC   = list(analyte = "drug_3:APC PD-L1 dimer", units = "nmol/L", specimen = "tumor", verified = TRUE),
    dimer3_TIGIT      = list(analyte = "drug_3:TIGIT dimer", units = "nmol/L", specimen = "tumor", verified = TRUE),
    trimer3_tumor     = list(analyte = "TIGIT:drug_3:tumour PD-L1 trimer", units = "nmol/L", specimen = "tumor", verified = TRUE),
    trimer3_APC       = list(analyte = "TIGIT:drug_3:APC PD-L1 trimer", units = "nmol/L", specimen = "tumor", verified = TRUE),
    # ---- anti-4-1BB/PD-L1 (drug_11) drug-checkpoint complexes ----
    dimer11_PDL1_tumor = list(analyte = "drug_11:tumour PD-L1 dimer", units = "nmol/L", specimen = "tumor", verified = TRUE),
    dimer11_PDL1_APC   = list(analyte = "drug_11:APC PD-L1 dimer", units = "nmol/L", specimen = "tumor", verified = TRUE),
    dimer11_CD137      = list(analyte = "drug_11:4-1BB dimer", units = "nmol/L", specimen = "tumor", verified = TRUE),
    trimer11_tumor     = list(analyte = "4-1BB:drug_11:tumour PD-L1 trimer", units = "nmol/L", specimen = "tumor", verified = TRUE),
    trimer11_APC       = list(analyte = "4-1BB:drug_11:APC PD-L1 trimer", units = "nmol/L", specimen = "tumor", verified = TRUE)
  )

  population <- list(
    species       = "mouse (MC38 syngeneic; CT26, EL-4 and B16F10 as secondary models)",
    n_subjects    = 100L,
    disease_state = "syngeneic solid tumour (MC38 colon adenocarcinoma primarily)",
    dose_range    = paste(
      "Calibration and validation spanned 12 mAb and BsAb regimens at 35 doses",
      "(calibration) and 23 doses/regimens covering 5 BsAbs, 2 mAbs and 6 mAb",
      "combinations (validation). Simulated screening used 1 mg/kg (low) and",
      "10 mg/kg (high) BsAb doses; dosing-regimen analyses covered",
      "anti-TIGIT/PD-L1 3-18 mg/kg, anti-LAG3/PD-L1 1-10 mg/kg, anti-CTLA4",
      "0.1-5 mg/kg and anti-4-1BB/PD-L1 3.25-26 mg/kg, each also compared as",
      "half-dose twice weekly versus full-dose once weekly.",
      sep = " "
    ),
    notes = paste(
      "Not a fitted population model. Initial tumour microenvironment composition",
      "was set from literature knowledge at 1e5 tumour cells, 370 T cells and 10",
      "APCs per 1 mm3 of tumour. A virtual mouse population is 100 parameter sets",
      "sampled within physiological ranges (initial tumour volume, tumour growth",
      "and death rates, checkpoint expression levels and initial cell counts).",
      "The global sensitivity analysis assumed a 100 mm3 starting tumour and used",
      "day-25 tumour volume as the output. Implemented in MATLAB SimBiology and",
      "solved with ode15s; parameters were estimated globally with patternsearch.",
      sep = " "
    )
  )

  ini({
    # ================================================================
    # Compartment capacities -- Supplementary Table S1, "Compartments"
    # ================================================================
    Vc <- fixed(7e-4); label("Central compartment volume for antibody drugs in mice [L]")  # Table S1 Compartments: central = 6.9999999999999999E-4 liter (doi:10.1208/s12248-019-0332-z)
    Vp <- fixed(1.2e-3); label("Peripheral compartment volume for antibody drugs in mice [L]")  # Table S1 Compartments: peripheral = 1.1999999999999999E-3 liter (fitting)
    Vc_shp <- fixed(7e-4); label("Central compartment volume for SHP099 in mice [L]")  # Table S1 Compartments: central_4 = 6.9999999999999999E-4 liter (doi:10.1208/s12248-019-0332-z)
    Vp_shp <- fixed(3.2e-3); label("Peripheral compartment volume for SHP099 in mice [L]")  # Table S1 Compartments: peripheral_4 = 3.2000000000000002E-3 liter (fitting)
    V <- fixed(3e-3); label("Tumour-microenvironment volume containing all cells, in vivo [L]")  # Table S1 Species: V = 0.003 in vivo liter (in vitro value is 0.0001 L)

    # ================================================================
    # Antibody pharmacokinetics -- Supplementary Table S1, "Parameters"
    #
    # UNITS CORRECTION (see vignette Errata). Table S1 prints CL1 = 12 and
    # Q1 = 1.725E-2 both labelled "L/h". Taken literally CL1/Vc = 17143 /h,
    # a plasma half-life of 0.15 s, which Supplementary Figure S3 falsifies:
    # its general-parameter ("S") curves show a mouse antibody terminal
    # half-life of roughly 140 h. Reading CL1 in uL/h and Q1 in mL/h gives
    # kel = 0.01714 /h, k12 = 0.02464 /h and k21 = 0.01438 /h, a terminal
    # half-life of 144 h, which matches the ~142 h read off Figure S3A.
    # ================================================================
    CL1 <- fixed(1.2e-5); label("Antibody plasma clearance in mice [L/h]")  # Table S1 Parameters: CL1 = 12 (printed "L/h"; read as 12 uL/h, verified against Supplementary Figure S3A terminal slope)
    Q1 <- fixed(1.725e-5); label("Antibody intercompartmental clearance in mice [L/h]")  # Table S1 Parameters: Q1 = 1.725E-2 (printed "L/h"; read as 1.725E-2 mL/h) (doi:10.1038/s41401-020-00550-y)
    kf_abdominal_central <- fixed(0.1); label("Intraperitoneal absorption rate constant for antibodies [1/h]")  # Table S1 Parameters: kf_abdominal_central = 0.1 1/h (fitting)
    p3 <- fixed(5e-3); label("Tumour partition coefficient of the anti-TIGIT/PD-L1 BsAb (drug_3) [dimensionless]")  # Table S1 Species: p3 = 5.0000000000000001E-3 dimensionless (fitting)
    p11 <- fixed(1e-3); label("Tumour partition coefficient of the anti-4-1BB/PD-L1 BsAb (drug_11) [dimensionless]")  # Table S1 Species: p11 = 1E-3 dimensionless (fitting)

    # ---- SHP099 PK. Retained structurally; NOT dosed by default. -----
    # Table S1 prints ka_SHP099 in "L/h" (must be 1/h), and defines
    # kel_SHP099 = CL2/[central] -- referencing the ANTIBODY central
    # compartment rather than central_4. As printed these give a SHP099
    # half-life of 0.05 h and a tmax near 28 h, neither of which matches
    # Supplementary Figure S3J-K (tmax ~2-4 h, half-life ~9-13 h). No
    # self-consistent correction is derivable, so the values are carried
    # verbatim and the module is left undosed. See vignette Errata.
    ka_SHP099 <- fixed(0.07); label("SHP099 oral absorption rate constant [1/h]")  # Table S1 Parameters: ka_SHP099 = 7.0000000000000007E-2 (printed "L/h") (fitting)
    CL2 <- fixed(0.01); label("SHP099 plasma clearance [L/h]")  # Table S1 Parameters: CL2 = 0.01 L/h (fitting)
    Q2 <- fixed(0.01); label("SHP099 intercompartmental clearance [L/h]")  # Table S1 Parameters: Q2 = 0.01 L/h (fitting)

    # ================================================================
    # Checkpoint surface densities -- Supplementary Table S1, "Species"
    # (nmol/L contributed to the tumour volume V by one cell)
    # ================================================================
    APC_MHC_per_cell <- fixed(7e-10); label("MHC expressed on each APC [nmol/L per cell]")  # Table S1 Species: APC_MHC_per_cell = 6.9999999999999996E-10 (doi:10.1073/pnas.0609665104)
    tumor_MHC_per_cell <- fixed(7e-10); label("MHC expressed on each tumour cell [nmol/L per cell]")  # ALIAS: tumor_MHC_per_cell is used in binding_9 but has no Table S1 Species row; set equal to APC_MHC_per_cell, the only tabulated MHC density (both bindings share kon/koff_MHC:TCR/CD3). See vignette Errata.
    TCRCD3_per_cell <- fixed(1.66e-10); label("TCR/CD3 complex expressed on each T cell [nmol/L per cell]")  # Table S1 Species: TCR/CD3_per_cell = 1.66E-10 (doi:10.1016/S1074-7613(00)80490-2)
    CD28_per_cell <- fixed(1.428e-11); label("CD28 expressed on each T cell [nmol/L per cell]")  # Table S1 Species: CD28_per_cell = 1.428E-11 (doi:10.4049/jimmunol.175.3.1575)
    CD8086_per_cell <- fixed(7.8e-11); label("CD80/86 complex expressed on each APC [nmol/L per cell]")  # Table S1 Species: CD80/86_per_cell = 7.8000000000000002E-11 (doi:10.4049/jimmunol.175.3.1575)
    CTLA4_per_cell_0 <- fixed(6.64e-13); label("Baseline CTLA4 expressed on each T cell [nmol/L per cell]")  # Table S1 Species: CTLA4_per_cell = 6.64E-13 (doi:10.4049/jimmunol.175.3.1575)
    PD1_per_cell <- fixed(5.14e-12); label("PD-1 expressed on each T cell [nmol/L per cell]")  # Table S1 Species: PD-1_per_cell = 5.1400000000000003E-12 (doi:10.1074/jbc.M112.448126)
    APC_PDL1_per_cell <- fixed(1.3346e-8); label("PD-L1 expressed on each APC [nmol/L per cell]")  # Table S1 Species: APC_PD-L1_per_cell = 1.3345999999999999E-8 (doi:10.1074/jbc.M112.448126)
    tumor_PDL1_per_cell <- fixed(5.812e-12); label("PD-L1 expressed on each tumour cell [nmol/L per cell]")  # Table S1 Species: tumor_PD-L1_per_cell = 5.8119999999999999E-12 (doi:10.1158/2326-6066.CIR-16-0391)
    APC_CD155_per_cell <- fixed(1.7e-12); label("CD155 expressed on each APC [nmol/L per cell]")  # Table S1 Species: APC_CD155_per_cell = 1.7E-12 (fitting)
    tumor_CD155_per_cell <- fixed(1.7e-12); label("CD155 expressed on each tumour cell [nmol/L per cell]")  # Table S1 Species: tumor_CD155_per_cell = 1.7E-12 (fitting)
    TIGIT_per_cell <- fixed(1.7e-12); label("TIGIT expressed on each T cell [nmol/L per cell]")  # Table S1 Species: TIGIT_per_cell = 1.7E-12 (fitting)
    LAG3_per_cell <- fixed(1.7e-12); label("LAG3 expressed on each T cell [nmol/L per cell]")  # Table S1 Species: LAG3_per_cell = 1.7E-12 (fitting)
    CD137_per_cell <- fixed(8.3e-13); label("4-1BB (CD137) expressed on each T cell [nmol/L per cell]")  # Table S1 Species: 4-1BB_per_cell = 8.3E-13 (fitting)
    CD137L_per_cell <- fixed(8.3e-13); label("4-1BBL (CD137L) expressed on each APC [nmol/L per cell]")  # Table S1 Species: 4-1BBL_per_cell = 8.3E-13 (fitting)
    OX40_per_cell <- fixed(8.3e-13); label("OX40 expressed on each T cell [nmol/L per cell]")  # Table S1 Species: OX40_per_cell = 8.3E-13 (fitting)
    OX40L_per_cell <- fixed(8.3e-13); label("OX40L expressed on each APC [nmol/L per cell]")  # Table S1 Species: OX40L_per_cell = 8.3E-13 (fitting)

    # ================================================================
    # Endogenous checkpoint binding kinetics -- Table S1, "Parameters"
    # ================================================================
    kon_MHC_TCR <- fixed(2.279e-3); label("MHC:TCR/CD3 association rate constant [L/nmol/h]")  # Table S1 Parameters: kon_MHC:TCR/CD3 = 2.2790000000000002E-3 (doi:10.1111/j.1365-2567.2008.03015.x)
    koff_MHC_TCR <- fixed(205.2); label("MHC:TCR/CD3 dissociation rate constant [1/h]")  # Table S1 Parameters: koff_MHC:TCR/CD3 = 205.2
    kon_CD28_CD8086 <- fixed(5.04); label("CD28:CD80/86 association rate constant [L/nmol/h]")  # Table S1 Parameters: kon_CD28:CD80/86_total = 5.04 (doi:10.1016/S1074-7613(02)00362-X)
    koff_CD28_CD8086 <- fixed(100800); label("CD28:CD80/86 dissociation rate constant [1/h]")  # Table S1 Parameters: koff_CD28:CD80/86_total = 100800 (doi:10.1016/S1074-7613(02)00362-X)
    kon_CTLA4_CD8086 <- fixed(0.772); label("CTLA4:CD80/86 association rate constant [L/nmol/h]")  # Table S1 Parameters: kon_CTLA4:CD80/86_total = 0.77200000000000002 (doi:10.1084/jem.185.3.393)
    koff_CTLA4_CD8086 <- fixed(324.3); label("CTLA4:CD80/86 dissociation rate constant [1/h]")  # Table S1 Parameters: koff_CTLA4:CD80/86_total = 324.3 (doi:10.1084/jem.185.3.393)
    kon_PD1_PDL1 <- fixed(1.86e-3); label("PD-1:PD-L1 association rate constant [L/nmol/h]")  # Table S1 Parameters: kon_PD-1:PD-L1_total = 1.8600000000000001E-3 (doi:10.1038/s41598-017-17963-1); used for both the APC and tumour bindings
    koff_PD1_PDL1 <- fixed(158.7); label("PD-1:PD-L1 dissociation rate constant [1/h]")  # Table S1 Parameters: koff_PD-1:PD-L1_total = 158.69999999999999 (doi:10.1038/s41598-017-17963-1); used for both the APC and tumour bindings
    kon_TIGIT_CD155 <- fixed(2.3); label("TIGIT:CD155 association rate constant [L/nmol/h]")  # Table S1 Parameters: kon_TIGIT:CD155 = 2.2999999999999998 (doi:10.1038/ni.1674)
    koff_TIGIT_CD155 <- fixed(1.15); label("TIGIT:CD155 dissociation rate constant [1/h]")  # Table S1 Parameters: koff_TIGIT:CD155 = 1.1499999999999999 (doi:10.1038/ni.1674); the reactions spell this koff_TIGIT:CD155_total
    kon_CD137_CD137L <- fixed(0.147); label("4-1BB:4-1BBL association rate constant [L/nmol/h]")  # Table S1 Parameters: kon_4-1BB:4-1BBL_total = 0.14699999999999999 (doi:10.1038/s41467-018-07136-7)
    koff_CD137_CD137L <- fixed(12.6); label("4-1BB:4-1BBL dissociation rate constant [1/h]")  # Table S1 Parameters: koff_4-1BB:4-1BBL_total = 12.6 (doi:10.1038/s41467-018-07136-7)
    kon_OX40_OX40L <- fixed(0.684); label("OX40:OX40L association rate constant [L/nmol/h]")  # Table S1 Parameters: kon_OX40:OX40L_total = 0.68400000000000005 (doi:10.1074/jbc.272.8.5275)
    koff_OX40_OX40L <- fixed(0.1368); label("OX40:OX40L dissociation rate constant [1/h]")  # Table S1 Parameters: koff_OX40:OX40L_total = 0.1368 (doi:10.1074/jbc.272.8.5275)

    # ================================================================
    # Bispecific antibody binding kinetics -- Table S1, "Parameters"
    # koff values are printed as "L/nmol/h" in Table S1; a dissociation
    # rate constant is first order, so they are used as 1/h.
    # ================================================================
    kon_drug3_PDL1 <- fixed(0.245); label("Anti-TIGIT/PD-L1 BsAb association to PD-L1 [L/nmol/h]")  # Table S1 Parameters: kon_drug_3_PD-L1 = 0.245 (doi:10.1038/s41598-022-22975-7)
    koff_drug3_PDL1 <- fixed(0.669); label("Anti-TIGIT/PD-L1 BsAb dissociation from PD-L1 [1/h]")  # Table S1 Parameters: koff_drug_3_PD-L1 = 0.66900000000000004 (printed "L/nmol/h") (doi:10.1038/s41598-022-22975-7)
    kon_drug3_TIGIT <- fixed(0.648); label("Anti-TIGIT/PD-L1 BsAb association to TIGIT [L/nmol/h]")  # Table S1 Parameters: kon_drug_3_TIGIT = 0.64800000000000002 (doi:10.1038/s41598-022-22975-7)
    koff_drug3_TIGIT <- fixed(0.216); label("Anti-TIGIT/PD-L1 BsAb dissociation from TIGIT [1/h]")  # Table S1 Parameters: koff_drug_3_TIGIT = 0.216 (printed "L/nmol/h") (doi:10.1038/s41598-022-22975-7)
    kon_drug11_PDL1 <- fixed(2.19); label("Anti-4-1BB/PD-L1 BsAb association to PD-L1 [L/nmol/h]")  # Table S1 Parameters: kon_drug_11_PD-L1 = 2.19 (doi:10.1038/s41467-021-24767-5)
    koff_drug11_PDL1 <- fixed(1.0731); label("Anti-4-1BB/PD-L1 BsAb dissociation from PD-L1 [1/h]")  # Table S1 Parameters: koff_drug_11_PD-L1 = 1.0730999999999999 (printed "L/nmol/h") (doi:10.1038/s41467-021-24767-5)
    kon_drug11_CD137 <- fixed(1.23); label("Anti-4-1BB/PD-L1 BsAb association to 4-1BB [L/nmol/h]")  # Table S1 Parameters: kon_drug_11_4-1BB = 1.23 (doi:10.1038/s41467-021-24767-5)
    koff_drug11_CD137 <- fixed(2.4846); label("Anti-4-1BB/PD-L1 BsAb dissociation from 4-1BB [1/h]")  # Table S1 Parameters: koff_drug_11_4-1BB = 2.4845999999999999 (printed "L/nmol/h") (doi:10.1038/s41467-021-24767-5)

    # ================================================================
    # T cell intracellular signalling rates -- Table S1, "Parameters"
    # ================================================================
    kf_antiCD3_ZAP70_1 <- fixed(20); label("ZAP70 phosphorylation by anti-CD3 [1/h]")  # Table S1 Parameters: kf_antiCD3_ZAP70_1 = 20 1/h (fitting)
    kf_antiCD3_ZAP70_2 <- fixed(18000); label("ZAP70 phosphorylation by anti-CD3 plus anti-CD28 [1/h]")  # Table S1 Parameters: kf_antiCD3_ZAP70_2 = 18000 1/h (fitting)
    kel_TCRCD3_1 <- fixed(6.98); label("TCR/CD3 internalisation rate on anti-CD3 binding [1/h]")  # Table S1 Parameters: kel_TCR/CD3_1 = 6.98 1/h (fitting)
    kel_CD28_1 <- fixed(3); label("CD28 internalisation rate on anti-CD28 binding [1/h]")  # Table S1 Parameters: kel_CD28_1 = 3 1/h (fitting)
    kf_MHC_TCR_ZAP70_1 <- fixed(25); label("ZAP70 phosphorylation driven by APC MHC:TCR/CD3 [1/h]")  # Table S1 Parameters: kf_MHC:TCR/CD3_ZAP70_1 = 25 1/h (fitting)
    kf_MHC_TCR_ZAP70_2 <- fixed(2.1e6); label("ZAP70 phosphorylation driven by tumour MHC:TCR/CD3 [1/h]")  # Table S1 Parameters: kf_MHC:TCR/CD3_ZAP70_2 = 2100000 1/h (fitting)
    kf_ZAP70_n <- fixed(2.7); label("ZAP70 dephosphorylation rate [1/h]")  # Table S1 Parameters: kf_ZAP70_n = 2.7 1/h (fitting); the reactions spell this kf_ZAP70_n_1 through kf_ZAP70_n_4
    kf_ZAP70_PI3K <- fixed(45); label("PI3K phosphorylation by active ZAP70 [1/h]")  # Table S1 Parameters: kf_ZAP70_PI3K = 45 1/h (fitting)
    kf_CD28_PI3K <- fixed(250); label("PI3K phosphorylation by anti-CD28-engaged CD28 [1/h]")  # Table S1 Parameters: kf_CD28_PI3K = 250 1/h (fitting)
    kf_CD28_CD8086_PI3K <- fixed(1100); label("PI3K phosphorylation driven by CD28:CD80/86 [1/h]")  # Table S1 Parameters: kf_CD28:CD80/86_PI3K = 1100 1/h (fitting)
    kf_PI3K_n <- fixed(32); label("PI3K dephosphorylation rate [1/h]")  # Table S1 Parameters: kf_PI3K_n = 32 1/h (fitting); the reactions spell this kf_PI3K_n_1 through kf_PI3K_n_3
    kf_PI3K_Akt <- fixed(38.9); label("AKT phosphorylation by active PI3K [1/h]")  # Table S1 Parameters: kf_PI3K_Akt = 38.9 1/h (fitting)
    kf_Akt_n <- fixed(11); label("AKT dephosphorylation rate [1/h]")  # Table S1 Parameters: kf_Akt_n = 11 1/h (fitting)
    kf_ZAP70_Erk <- fixed(20); label("ERK phosphorylation by active ZAP70 [1/h]")  # Table S1 Parameters: kf_ZAP70_Erk = 20 1/h (fitting)
    kf_Erk_n <- fixed(11); label("ERK dephosphorylation rate [1/h]")  # Table S1 Parameters: kf_Erk_n = 11 1/h (fitting)
    kf_NFkB <- fixed(9e6); label("NF-kB phosphorylation by active AKT [1/h]")  # Table S1 Parameters: kf_NF-kB = 9000000 1/h (fitting)
    kel_NFkB <- fixed(5560); label("NF-kB dephosphorylation rate [1/h]")  # Table S1 Parameters: kel_NF-kB = 5560 1/h (fitting)
    kf_Erk_promoter_1 <- fixed(1); label("Activation of the ERK-driven promoter [1/h]")  # Table S1 Parameters: kf_Erk_promoter_1 = 1 1/h (fitting)
    kf_promoter_1_n <- fixed(0.3); label("Deactivation of the ERK-driven promoter [1/h]")  # Table S1 Parameters: kf_promoter_1_n = 0.3 1/h (fitting)
    kf_NFkB_promoter_2 <- fixed(15); label("Activation of the NF-kB-driven promoter [1/h]")  # Table S1 Parameters: kf_NF-kB_promoter_2 = 15 1/h (fitting)
    kf_promoter_2_n <- fixed(30); label("Deactivation of the NF-kB-driven promoter [1/h]")  # Table S1 Parameters: kf_promoter_2_n = 30 1/h (fitting)
    kf_IL2_p <- fixed(4.82e-6); label("IL-2 production rate from active promoters [1/h]")  # Table S1 Parameters: kf_IL-2_p = 4.8199999999999996E-6 1/h (fitting)
    kel_IL2 <- fixed(3.049e-2); label("IL-2 clearance rate [1/h]")  # Table S1 Parameters: kel_IL-2 = 3.049E-2 1/h (fitting)
    kf_IFNg_p <- fixed(1.22e-7); label("IFN-gamma production rate from active promoters [1/h]")  # Table S1 Parameters: kf_IFN-g_p = 1.2200000000000001E-7 1/h (fitting)
    kel_IFNg <- fixed(2.2e-2); label("IFN-gamma clearance rate [1/h]")  # Table S1 Parameters: kel_IFN-g = 2.1999999999999999E-2 1/h (fitting)
    kf_IL2_Erk_a <- fixed(1.5); label("ERK phosphorylation fed back by IL-2 [1/h]")  # Table S1 Parameters: kf_IL-2_Erk_a = 1.5 1/h (fitting)
    kf_IL2_Akt_a <- fixed(1.5); label("AKT phosphorylation fed back by IL-2 [1/h]")  # Table S1 Parameters: kf_IL-2_Akt_a = 1.5 1/h (fitting)

    # ================================================================
    # Checkpoint regulatory strengths -- Table S1, "Parameters"
    # ================================================================
    kf_PD1_ZAP70_n <- fixed(20); label("ZAP70 inactivation by the PD-1/PD-L1 inhibitor [1/h]")  # Table S1 Parameters: kf_PD-1_ZAP70_n = 20 1/h (fitting)
    kf_PD1_PI3K_n <- fixed(70); label("PI3K inactivation by the PD-1/PD-L1 inhibitor [1/h]")  # Table S1 Parameters: kf_PD-1_PI3K_n = 70 1/h (fitting)
    kf_CTLA4_ZAP70_n <- fixed(51); label("ZAP70 inactivation by the CTLA4 inhibitor [1/h]")  # Table S1 Parameters: kf_CTLA4_ZAP70_n = 51 1/h (fitting)
    kf_CTLA4_PI3K_n <- fixed(53); label("PI3K inactivation by the CTLA4 inhibitor [1/h]")  # Table S1 Parameters: kf_CTLA4_PI3K_n = 53 1/h (fitting)
    kf_CTLA4_Akt_n <- fixed(55); label("AKT inactivation by the CTLA4 inhibitor [1/h]")  # Table S1 Parameters: kf_CTLA4_Akt_n = 55 1/h (fitting)
    kf_TIGIT_Erk_n <- fixed(54); label("ERK inactivation by the TIGIT inhibitor [1/h]")  # Table S1 Parameters: kf_TIGIT_Erk_n = 54 1/h (fitting)
    kf_TIGIT_NFkB_n <- fixed(15000); label("NF-kB inactivation by the TIGIT inhibitor [1/h]")  # Table S1 Parameters: kf_TIGIT_NF-kB_n = 15000 1/h (fitting)
    kf_LAG3_Erk_n <- fixed(260); label("ERK inactivation by LAG3 [1/h]")  # Table S1 Parameters: kf_LAG3_Erk_n = 260 1/h (fitting)
    kf_LAG3_Akt_n <- fixed(410); label("AKT inactivation by LAG3 [1/h]")  # Table S1 Parameters: kf_LAG3_Akt_n = 410 1/h (fitting)
    kf_CD137_Erk_a <- fixed(32); label("ERK activation by the 4-1BB activator [1/h]")  # Table S1 Parameters: kf_4-1BB_Erk_a = 32 1/h (fitting)
    kf_CD137_Akt_a <- fixed(56); label("AKT activation by the 4-1BB activator [1/h]")  # Table S1 Parameters: kf_4-1BB_Akt_a = 56 1/h (fitting)
    kf_OX40_Akt_a <- fixed(53); label("AKT activation by the OX40 activator [1/h]")  # Table S1 Parameters: kf_OX40_Akt_a = 53 1/h (fitting)
    kf_OX40_NFkB <- fixed(1e5); label("NF-kB activation by the OX40 activator [1/h]")  # Table S1 Parameters: kf_OX40_NF-kB = 100000 1/h (fitting)
    kf_APC_MHC_TCR_CTLA4 <- fixed(5e-9); label("CTLA4 upregulation driven by APC MHC:TCR/CD3 [1/h]")  # Table S1 Parameters: kf_APC_MHC:TCR/CD3_CTLA4 = 5.0000000000000001E-9 1/h (fitting)

    # ---- Second-messenger production and elimination ----
    kf_PD1_APC_PDL1_inhibitor_1 <- fixed(37.2); label("Production of inhibitor_1 from PD-1:APC PD-L1 [1/h]")  # Table S1 Parameters: kf_PD-1:APC_PD-L1_per_cell_inhibitor_1 = 37.200000000000003 1/h (fitting)
    kel_inhibitor_1 <- fixed(50); label("Elimination of inhibitor_1 [1/h]")  # Table S1 Parameters: kel_inhibitor_1 = 50 1/h (fitting)
    kf_CTLA4_CD8086_inhibitor_2 <- fixed(5); label("Production of inhibitor_2 from CTLA4:CD80/86 [1/h]")  # Table S1 Parameters: kf_CTLA4:CD80/86_per_cell_inhibitor_2 = 5 1/h (fitting)
    kel_inhibitor_2 <- fixed(10); label("Elimination of inhibitor_2 [1/h]")  # Table S1 Parameters: kel_inhibitor_2 = 10 1/h (fitting)
    kf_TIGIT_APC_CD155_inhibitor_3 <- fixed(2); label("Production of inhibitor_3 from TIGIT:APC CD155 [1/h]")  # Table S1 Parameters: kf_TIGIT:APC_CD155_per_cell_inhibitor_3 = 2 1/h (fitting)
    kel_inhibitor_3 <- fixed(14); label("Elimination of inhibitor_3 [1/h]")  # Table S1 Parameters: kel_inhibitor_3 = 14 1/h (fitting)
    kf_CD137_CD137L_activation_1 <- fixed(1e-3); label("Production of activation_1 from 4-1BB:4-1BBL [1/h]")  # Table S1 Parameters: kf_4-1BB:4-1BBL_per_cell_activation_1 = 1E-3 1/h (fitting)
    kf_drug11_activation_1 <- fixed(1e-3); label("Production of activation_1 driven by agonist anti-4-1BB/PD-L1 BsAb complexes [1/h]")  # Table S1 Parameters: kf_drug_activation_1 = 1E-3 1/h (fitting); the reactions spell this kf_drug_11_activation_1
    kel_activation_1 <- fixed(11); label("Elimination of activation_1 [1/h]")  # Table S1 Parameters: kel_activation_1 = 11 1/h (fitting)
    kf_OX40_OX40L_activation_2 <- fixed(1e-3); label("Production of activation_2 from OX40:OX40L [1/h]")  # Table S1 Parameters: kf_drug_activation_2 = 1E-3 1/h (fitting); the reactions spell this kf_OX40:OX40L_per_cell_activation_2. Both drug_activation constants and kf_4-1BB:4-1BBL_per_cell_activation_1 are 1E-3, so the alias is numerically inert.
    kel_activation_2 <- fixed(50); label("Elimination of activation_2 [1/h]")  # Table S1 Parameters: kel_activation_2 = 50 1/h (fitting)
    kf_SHP099_n <- fixed(0.01); label("Inactivation of inhibitor_1 by SHP099 [1/h]")  # Table S1 Parameters: kf_SHP099_n = 0.01 1/h (fitting)
    kf_SHP099_a <- fixed(100); label("Reactivation of SHP099-inactivated inhibitor_1 [1/h]")  # Table S1 Parameters: kf_SHP099_a = 100 1/h (fitting)

    # ================================================================
    # Cell growth, killing and clearance -- Table S1, "Parameters"
    # ================================================================
    kg_tumor_cell <- fixed(0.01); label("Tumour cell proliferation rate [1/h]")  # Table S1 Parameters: kg_tumor cell = 0.01 1/h (fitting)
    kel_tumor_cell <- fixed(2.449e-3); label("Baseline tumour cell death rate, in vivo [1/h]")  # Table S1 Parameters: kel_tumor cell = 0.001-0.006 in vivo (0.01 in vitro); geometric midpoint sqrt(0.001*0.006) = 2.449E-3 used as the platform value. See vignette Errata.
    kg_t_cell <- fixed(5.9e-2); label("T cell proliferation rate [1/h]")  # Table S1 Parameters: kg_t cell = 5.8999999999999997E-2 1/h (fitting)
    kel_t_cell <- fixed(0.03); label("T cell death rate [1/h]")  # Table S1 Parameters: kel_t cell = 0.03 1/h (fitting)
    k <- fixed(5e-3); label("Dead tumour cell clearance-stage transduction rate [1/h]")  # Table S1 Parameters: k = 5.0000000000000001E-3 1/h (fitting)

    # ================================================================
    # Hill / half-saturation constants -- Table S1, "Parameters"
    #
    # Table S1 reports km1, km2, km4, km6-km13 and n3 as RANGES because the
    # Methods state that the checkpoint regulatory strengths km4~km12 and the
    # tumour proliferation and death rates were re-optimised per in vivo
    # dataset. The geometric midpoint of each published range is used as the
    # single platform value; each is recorded below. See vignette Errata.
    # ================================================================
    km1 <- fixed(1e-14); label("Half-saturation for PD-1:tumour PD-L1 suppression of killing [dimensionless]")  # Table S1 Parameters: km1 = 1E-15 to 1E-13; geometric midpoint 1E-14
    km2 <- fixed(1e-10); label("Half-saturation for TIGIT:tumour CD155 suppression of killing [dimensionless]")  # Table S1 Parameters: km2 = 1E-11 to 1E-9; geometric midpoint 1E-10
    n3 <- fixed(6.512e-6); label("Maximal immune-mediated amplification of tumour cell killing [dimensionless]")  # Table S1 Parameters: n3 = 4E-6 to 1.06E-5; geometric midpoint sqrt(4E-6*1.06E-5) = 6.512E-6
    km4 <- fixed(4.123e-6); label("Half-saturation of inhibitor_1 acting on ZAP70 [dimensionless]")  # Table S1 Parameters: km4 = 1.7E-6 to 1E-5; geometric midpoint sqrt(1.7E-6*1E-5) = 4.123E-6
    km5 <- fixed(0.01); label("Half-saturation of inhibitor_1 acting on PI3K [dimensionless]")  # Table S1 Parameters: km5 = 0.01 dimensionless (fitting)
    km6 <- fixed(1e-8); label("Half-saturation of LAG3 acting on ERK and AKT [dimensionless]")  # Table S1 Parameters: km6 = 1E-9 to 1E-7; geometric midpoint 1E-8
    km7 <- fixed(1e-4); label("Half-saturation of inhibitor_2 acting on ZAP70 [dimensionless]")  # Table S1 Parameters: km7 = 1E-5 to 1E-3; geometric midpoint 1E-4
    km8 <- fixed(1e-4); label("Half-saturation of inhibitor_2 acting on PI3K [dimensionless]")  # Table S1 Parameters: km8 = 1E-5 to 1E-3; geometric midpoint 1E-4
    km9 <- fixed(1e-4); label("Half-saturation of inhibitor_2 acting on AKT [dimensionless]")  # Table S1 Parameters: km9 = 1E-5 to 1E-3; geometric midpoint 1E-4
    km10 <- fixed(3.162e-6); label("Half-saturation of activation_2 (OX40) [dimensionless]")  # Table S1 Parameters: km10 = 1E-6 to 1E-5; geometric midpoint 3.162E-6
    km11 <- fixed(3.873e-4); label("Half-saturation of activation_1 (4-1BB) [dimensionless]")  # Table S1 Parameters: km11 = 1E-4 to 1.5E-3; geometric midpoint sqrt(1E-4*1.5E-3) = 3.873E-4
    km12 <- fixed(6.325e-6); label("Half-saturation of inhibitor_3 acting on ERK [dimensionless]")  # Table S1 Parameters: km12 = 2E-6 to 2E-5; geometric midpoint 6.325E-6
    km13 <- fixed(6.325e-6); label("Half-saturation of inhibitor_3 acting on NF-kB [dimensionless]")  # Table S1 Parameters: km13 = 2E-6 to 2E-5; geometric midpoint 6.325E-6
    km14 <- fixed(100); label("Half-saturation of SHP099 promoting tumour cell killing [dimensionless]")  # Table S1 Parameters: km14 = 100 dimensionless (fitting)
    km15 <- fixed(100); label("Half-saturation of SHP099 inactivating inhibitor_1 [dimensionless]")  # Table S1 Parameters: km15 = 100 dimensionless (fitting)
    km16 <- fixed(1.328e-12); label("Maximal CTLA4 surface density on T cells [nmol/L per cell]")  # Table S1 Parameters: km16 = 1.328E-12 dimensionless (fitting)
    km19 <- fixed(1); label("Half-saturation of CD28:CD80/86 driving PI3K [dimensionless]")  # Table S1 Parameters: km19 = 1 dimensionless (fitting)
    km20 <- fixed(0.1); label("Half-saturation of active ERK driving promoter_1 [dimensionless]")  # Table S1 Parameters: km20 = 0.1 dimensionless (fitting)
    km21 <- fixed(1000); label("Half-saturation of NF-kB driving promoter_2 [dimensionless]")  # Table S1 Parameters: km21 = 1000 dimensionless (fitting)
    km22 <- fixed(9); label("Half-saturation of active promoters driving IFN-gamma [dimensionless]")  # Table S1 Parameters: km22 = 9 dimensionless (fitting)
    km23 <- fixed(4000); label("Half-saturation of active promoters driving IL-2 [dimensionless]")  # Table S1 Parameters: km23 = 4000 dimensionless (fitting)
    km24 <- fixed(1e-8); label("Half-saturation of IL-2 feeding back onto ERK [dimensionless]")  # Table S1 Parameters: km24 = 1E-8 dimensionless (fitting)
    km25 <- fixed(1e-8); label("Half-saturation of IL-2 feeding back onto AKT [dimensionless]")  # Table S1 Parameters: km25 = 1E-8 dimensionless (fitting)
    km26 <- fixed(1e-6); label("Half-saturation of tumour MHC:TCR/CD3 driving ZAP70 [dimensionless]")  # Table S1 Parameters: km26 = 9.9999999999999995E-7 dimensionless (fitting)
    km27 <- fixed(1e-8); label("Half-saturation of IL-2 driving T cell proliferation [dimensionless]")  # Table S1 Parameters: km27 = 1E-8 dimensionless (fitting)
    km28 <- fixed(1e-11); label("Half-saturation of PD-1:APC PD-L1 producing inhibitor_1 [dimensionless]")  # Table S1 Parameters: km28 = 9.9999999999999994E-12 dimensionless (fitting)
    km29 <- fixed(1e-14); label("Half-saturation of CTLA4:CD80/86 producing inhibitor_2 [dimensionless]")  # Table S1 Parameters: km29 = 1E-14 dimensionless (fitting)
    km30 <- fixed(1e-10); label("Half-saturation of 4-1BB:4-1BBL producing activation_1 [dimensionless]")  # Table S1 Parameters: km30 = 1E-10 dimensionless (fitting)
    km31 <- fixed(1e-10); label("Half-saturation of OX40:OX40L producing activation_2 [dimensionless]")  # Table S1 Parameters: km31 = 1E-10 dimensionless (fitting)
    km32 <- fixed(1e-10); label("Half-saturation of TIGIT:APC CD155 producing inhibitor_3 [dimensionless]")  # Table S1 Parameters: km32 = 1E-10 dimensionless (fitting)

    # ================================================================
    # Structural switches and tumour seeding
    # ================================================================
    c1 <- fixed(1); label("PD-1/PD-L1 killing-suppression scale factor [dimensionless]")  # Table S1 Species: c1 = 1 dimensionless (fitting)
    c2 <- fixed(1); label("TIGIT/CD155 killing-suppression scale factor [dimensionless]")  # Table S1 Species: c2 = 1 dimensionless (fitting)
    antiCD3 <- fixed(0); label("Anti-CD3 stimulation level; 0 in vivo [dimensionless]")  # In vitro stimulation input (Table S1 Reactions phosphorylation_ZAP70_1/_2, internalization_CD3); zero for the in vivo platform
    antiCD28 <- fixed(0); label("Anti-CD28 stimulation level; 0 in vivo [dimensionless]")  # In vitro stimulation input (Table S1 Reactions phosphorylation_ZAP70_2, phosphorylation_PI3K_2, internalization_CD28); zero for the in vivo platform
    dimer_CTLA4_10 <- fixed(0); label("Anti-CTLA4 mAb:CTLA4 dimer concentration [nmol/L]")  # Table S1 Reactions binding_5 subtracts dimer_CTLA4_10, but the anti-CTLA4 mAb (drug_10) has no Species row, no reactions and no kon/koff in Table S1; pinned at 0 (drug absent). See vignette Errata.
    TV0 <- fixed(100); label("Initial tumour volume [mm^3]")  # Materials and methods, Global sensitivity analysis: "assuming a starting tumor volume of 100 mm3 in vivo"
    tumor_cell_per_mm3 <- fixed(1e5); label("Tumour cells seeded per mm^3 of tumour [cell/mm^3]")  # Materials and methods: "1e5 tumor cells, 370 T cells and 10 APCs per 1 mm3 of tumor" (doi:10.1038/s41467-022-29388-0; doi:10.4161/cc.8.3.7608; doi:10.1182/blood.v93.2.728)
    t_cell_per_mm3 <- fixed(370); label("T cells seeded per mm^3 of tumour [cell/mm^3]")  # Materials and methods: "1e5 tumor cells, 370 T cells and 10 APCs per 1 mm3 of tumor"
    apc_per_mm3 <- fixed(10); label("APCs per mm^3 of tumour, held constant [cell/mm^3]")  # Materials and methods: "1e5 tumor cells, 370 T cells and 10 APCs per 1 mm3 of tumor"; APC has no ODE in Table S1 Equations, so it is constant
    vmaxTumorMult <- fixed(35); label("Tumour carrying capacity as a multiple of the seeded tumour cell number [dimensionless]")  # Table S1 Species: "In vivo: [Vmax_tumor cell] = 35*initial tumor cell number" (in vitro multiplier is 15)
    vmaxTcellMult <- fixed(85); label("T cell carrying capacity as a multiple of the seeded T cell number [dimensionless]")  # Table S1 Species: "[Vmax_t cell] = 85*initial t cell number"
  })

  model({
    # ================================================================
    # Naming note. Table S1 uses SimBiology names that are not valid R
    # identifiers. The mapping applied here is purely syntactic:
    #   4-1BB  -> CD137     4-1BBL -> CD137L     NF-kB -> NFkB
    #   IL-2   -> IL2       IFN-g  -> IFNg       PD-1  -> PD1
    #   CD80/86 -> CD8086   "X:Y_total" -> X_Y_total
    #   drug_3  = anti-TIGIT/PD-L1 BsAb   drug_11 = anti-4-1BB/PD-L1 BsAb
    # Every reaction below is transcribed from the Table S1 "Reactions"
    # sheet and every d/dt line from the "Equations" sheet.
    # ================================================================

    # ---------- derived constants ----------
    kel_drug <- CL1 / Vc                 # Table S1 Parameters: [kel_drug] = [CL1]/[central]
    k12 <- Q1 / Vc                       # Table S1 Parameters: [k12] = [Q1]/[central]
    k21 <- Q1 / Vp                       # Table S1 Parameters: [k21] = [Q1]/[peripheral]
    kel_shp <- CL2 / Vc                  # Table S1 Parameters: [kel_SHP099] = [CL2]/[central] (transcribed as printed; note it references `central`, not `central_4`)
    k12_shp <- Q2 / Vc_shp               # Table S1 Parameters: [k12_SHP099] = [Q2]/[central4]
    k21_shp <- Q2 / Vp_shp               # Table S1 Parameters: [k21_SHP099] = [Q2]/[peripheral4]

    APC <- apc_per_mm3 * TV0             # APC has no ODE in Table S1 Equations, so the seeded number is held constant
    Vmax_tumor_cell <- vmaxTumorMult * tumor_cell_per_mm3 * TV0   # Table S1 Species: Vmax_tumor cell = 35 * initial tumor cell number (in vivo)
    Vmax_t_cell <- vmaxTcellMult * t_cell_per_mm3 * TV0           # Table S1 Species: Vmax_t cell = 85 * initial t cell number

    # ---------- initial conditions ----------
    tumor_cell(0) <- tumor_cell_per_mm3 * TV0
    t_cell(0) <- t_cell_per_mm3 * TV0
    ZAP70_n(0) <- 1
    PI3K_n(0) <- 1
    Akt_n(0) <- 1
    Erk_n(0) <- 1
    promoter_1_n(0) <- 1
    promoter_2_n(0) <- 1
    CTLA4_per_cell(0) <- CTLA4_per_cell_0
    TCRCD3(0) <- TCRCD3_per_cell
    CD28(0) <- CD28_per_cell

    # ---------- drug concentrations ----------
    Cc3 <- drug3_central / Vc            # plasma concentration of the anti-TIGIT/PD-L1 BsAb [nmol/L]
    Cc11 <- drug11_central / Vc          # plasma concentration of the anti-4-1BB/PD-L1 BsAb [nmol/L]
    Cc_shp <- shp099_central / Vc_shp    # plasma concentration of SHP099 [nmol/L]
    drug3 <- p3 * Cc3                    # Table S1 Species: [drug_3_TIGIT*PD-L1] = p3 * central.drug_central
    drug11 <- p11 * Cc11                 # Table S1 Species: [drug_11_4-1BB*PD-L1] = p11 * central.drug_central
    SHP099 <- Cc_shp                     # Table S1 gives no tumour partition coefficient for SHP099; plasma concentration is used directly

    # ---------- repeated assignments (per-T-cell complex densities) ----------
    # Table S1 Species: [X_per_cell] = [X_total] / [t cell]
    APC_MHC_TCR_per_cell <- APC_MHC_TCR_total / t_cell
    tumor_MHC_TCR_per_cell <- tumor_MHC_TCR_total / t_cell
    CD28_CD8086_per_cell <- CD28_CD8086_total / t_cell
    CTLA4_CD8086_per_cell <- CTLA4_CD8086_total / t_cell
    PD1_APC_PDL1_per_cell <- PD1_APC_PDL1_total / t_cell
    PD1_tumor_PDL1_per_cell <- PD1_tumor_PDL1_total / t_cell
    CD137_CD137L_per_cell <- CD137_CD137L_total / t_cell
    OX40_OX40L_per_cell <- OX40_OX40L_total / t_cell
    TIGIT_APC_CD155_per_cell <- TIGIT_APC_CD155_total / t_cell
    TIGIT_tumor_CD155_per_cell <- TIGIT_tumor_CD155_total / t_cell
    dimer11_CD137_per_cell <- dimer11_CD137 / t_cell
    trimer11_APC_per_cell <- trimer11_APC / t_cell
    trimer11_tumor_per_cell <- trimer11_tumor / t_cell

    # Total PD-L1 / CD155 / MHC-bearing tumour mass: viable cells plus the
    # three dead-cell clearance stages (Table S1 Reactions binding_4, _9,
    # _10, _11 all use "[tumor cell]+M1+M2+M3").
    tumorAll <- tumor_cell + M1 + M2 + M3
    lag3Frac <- LAG3_per_cell / V        # Table S1 Reactions inhibition_LAG3_1/_2: ((LAG3_per_cell*[t cell]/V)/[t cell])

    # ================================================================
    # Pharmacokinetics (Table S1 Reactions absorption_drug, clearance_drug,
    # transportation_drug; Equations rows 1-3). The supplement writes these
    # as concentration ODEs scaled by 1/compartment; the equivalent amount
    # form is used here so that doses are given in nmol.
    # ================================================================
    absorption_drug3 <- kf_abdominal_central * drug3_abdominal
    clearance_drug3 <- kel_drug * drug3_central
    transportation_drug3 <- k12 * drug3_central - k21 * drug3_peripheral

    absorption_drug11 <- kf_abdominal_central * drug11_abdominal
    clearance_drug11 <- kel_drug * drug11_central
    transportation_drug11 <- k12 * drug11_central - k21 * drug11_peripheral

    absorption_SHP099 <- ka_SHP099 * shp099_gi
    clearance_SHP099 <- kel_shp * shp099_central
    transportation_SHP099 <- k12_shp * shp099_central - k21_shp * shp099_peripheral

    # ================================================================
    # Endogenous checkpoint binding (Table S1 Reactions binding_1 to _11)
    # ================================================================
    binding_1 <- kon_MHC_TCR * (APC_MHC_per_cell * APC / V - APC_MHC_TCR_total) * (TCRCD3_per_cell * t_cell / V - APC_MHC_TCR_total - tumor_MHC_TCR_total)
    dissociation_APC_MHC_TCR_total <- koff_MHC_TCR * APC_MHC_TCR_total
    binding_9 <- kon_MHC_TCR * (TCRCD3_per_cell * t_cell / V - tumor_MHC_TCR_total) * (tumor_MHC_per_cell * tumorAll / V - tumor_MHC_TCR_total - APC_MHC_TCR_total)
    dissociation_tumor_MHC_TCR_total <- koff_MHC_TCR * tumor_MHC_TCR_total

    binding_2 <- kon_CD28_CD8086 * (CD28_per_cell * t_cell / V - CD28_CD8086_total) * (CD8086_per_cell * APC / V - CD28_CD8086_total - CTLA4_CD8086_total)
    dissociation_CD28_CD8086_total <- koff_CD28_CD8086 * CD28_CD8086_total

    binding_5 <- kon_CTLA4_CD8086 * (CTLA4_per_cell * t_cell / V - CTLA4_CD8086_total - dimer_CTLA4_10) * (CD8086_per_cell * APC / V - CTLA4_CD8086_total - CD28_CD8086_total)
    dissociation_CTLA4_CD8086_total <- koff_CTLA4_CD8086 * CTLA4_CD8086_total

    binding_3 <- kon_PD1_PDL1 * (PD1_per_cell * t_cell / V - PD1_APC_PDL1_total - PD1_tumor_PDL1_total) * (APC_PDL1_per_cell * APC / V - PD1_APC_PDL1_total - dimer3_PDL1_APC - trimer3_APC - dimer11_PDL1_APC - trimer11_APC)
    dissociation_PD1_APC_PDL1_total <- koff_PD1_PDL1 * PD1_APC_PDL1_total
    binding_10 <- kon_PD1_PDL1 * (PD1_per_cell * t_cell / V - PD1_tumor_PDL1_total - PD1_APC_PDL1_total) * (tumor_PDL1_per_cell * tumorAll / V - PD1_tumor_PDL1_total - dimer3_PDL1_tumor - trimer3_tumor - dimer11_PDL1_tumor - trimer11_tumor)
    dissociation_PD1_tumor_PDL1_total <- koff_PD1_PDL1 * PD1_tumor_PDL1_total

    binding_6 <- kon_CD137_CD137L * (CD137_per_cell * t_cell / V - CD137_CD137L_total - dimer11_CD137 - trimer11_APC - trimer11_tumor) * (CD137L_per_cell * APC / V - CD137_CD137L_total)
    dissociation_CD137_CD137L_total <- koff_CD137_CD137L * CD137_CD137L_total

    binding_7 <- kon_OX40_OX40L * (OX40_per_cell * t_cell / V) * (OX40L_per_cell * APC / V - OX40_OX40L_total)
    dissociation_OX40_OX40L_total <- koff_OX40_OX40L * OX40_OX40L_total

    binding_8 <- kon_TIGIT_CD155 * (TIGIT_per_cell * t_cell / V - TIGIT_APC_CD155_total - trimer3_APC - dimer3_TIGIT - TIGIT_tumor_CD155_total - trimer3_tumor) * (APC_CD155_per_cell * APC / V - TIGIT_APC_CD155_total)
    dissociation_TIGIT_APC_CD155_total <- koff_TIGIT_CD155 * TIGIT_APC_CD155_total
    binding_11 <- kon_TIGIT_CD155 * (TIGIT_per_cell * t_cell / V - TIGIT_tumor_CD155_total - TIGIT_APC_CD155_total - dimer3_TIGIT - trimer3_tumor - trimer3_APC) * (tumor_CD155_per_cell * tumorAll / V - TIGIT_tumor_CD155_total)
    dissociation_TIGIT_tumor_CD155_total <- koff_TIGIT_CD155 * TIGIT_tumor_CD155_total

    # ================================================================
    # T cell intracellular signalling (Table S1 Reactions)
    # ================================================================
    phosphorylation_ZAP70_1 <- kf_antiCD3_ZAP70_1 * antiCD3 * ZAP70_n * TCRCD3
    phosphorylation_ZAP70_2 <- kf_antiCD3_ZAP70_2 * ZAP70_n * antiCD3 * antiCD28 * TCRCD3 * CD28
    internalization_CD3 <- kel_TCRCD3_1 * TCRCD3 * antiCD3
    internalization_CD28 <- kel_CD28_1 * CD28 * antiCD28
    phosphorylation_ZAP70_APC_MHC_TCR <- kf_MHC_TCR_ZAP70_1 * ZAP70_n * (APC_MHC_TCR_per_cell / (APC_MHC_TCR_per_cell + 1e-10)) * (CD28_CD8086_per_cell / (CD28_CD8086_per_cell + 1e-4))
    phosphorylation_ZAP70_MHC_TCR <- kf_MHC_TCR_ZAP70_2 * ZAP70_n * (tumor_MHC_TCR_per_cell / (tumor_MHC_TCR_per_cell + km26))
    dephosphorylation_ZAP70_1 <- kf_ZAP70_n * ZAP70_a
    dephosphorylation_ZAP70_2 <- kf_ZAP70_n * ZAP70_a
    dephosphorylation_ZAP70_3 <- kf_ZAP70_n * ZAP70_a
    dephosphorylation_ZAP70_4 <- kf_ZAP70_n * ZAP70_a
    inhibition_PD1_1 <- kf_PD1_ZAP70_n * ZAP70_a * (inhibitor_1 / (inhibitor_1 + km4))
    inhibition_CTLA4_1 <- kf_CTLA4_ZAP70_n * ZAP70_a * (inhibitor_2 / (inhibitor_2 + km7))

    phosphorylation_PI3K_1 <- kf_ZAP70_PI3K * PI3K_n * ZAP70_a
    phosphorylation_PI3K_2 <- kf_CD28_PI3K * PI3K_n * antiCD28 * CD28
    phosphorylation_PI3K_3 <- kf_CD28_CD8086_PI3K * PI3K_n * (CD28_CD8086_per_cell / (CD28_CD8086_per_cell + km19))
    dephosphorylation_PI3K_1 <- kf_PI3K_n * PI3K_a
    dephosphorylation_PI3K_2 <- kf_PI3K_n * PI3K_a
    dephosphorylation_PI3K_3 <- kf_PI3K_n * PI3K_a
    inhibition_PD1_2 <- kf_PD1_PI3K_n * PI3K_a * (inhibitor_1 / (inhibitor_1 + km5))
    inhibition_CTLA4_2 <- kf_CTLA4_PI3K_n * PI3K_a * (inhibitor_2 / (inhibitor_2 + km8))

    phosphorylation_AKT <- kf_PI3K_Akt * Akt_n * PI3K_a
    dephosphorylation_AKT <- kf_Akt_n * Akt_a
    inhibition_CTLA4_3 <- kf_CTLA4_Akt_n * Akt_a * (inhibitor_2 / (inhibitor_2 + km9))
    activation_OX40_2 <- kf_OX40_Akt_a * Akt_n * (activation_2 / (activation_2 + km10))
    inhibition_LAG3_2 <- kf_LAG3_Akt_n * Akt_a * (lag3Frac / (lag3Frac + km6))
    phosphorylation_AKT_IL2 <- kf_IL2_Akt_a * (IL2 / (IL2 + km25)) * Akt_n
    activation_CD137_2 <- kf_CD137_Akt_a * Akt_n * (activation_1 / (activation_1 + km11))

    phosphorylation_ERK <- kf_ZAP70_Erk * Erk_n * ZAP70_a
    dephosphorylation_ERK <- kf_Erk_n * Erk_a
    activation_CD137_1 <- kf_CD137_Erk_a * Erk_n * (activation_1 / (activation_1 + km11))
    inhibition_TIGIT_1 <- kf_TIGIT_Erk_n * Erk_a * (inhibitor_3 / (inhibitor_3 + km12))
    inhibition_LAG3_1 <- kf_LAG3_Erk_n * Erk_a * (lag3Frac / (lag3Frac + km6))
    phosphorylation_ERK_IL2 <- kf_IL2_Erk_a * (IL2 / (IL2 + km24)) * Erk_n

    phosphorylation_NFkB <- kf_NFkB * Akt_a
    dephosphorylation_NFkB <- kel_NFkB * NFkB
    inhibition_TIGIT_2 <- kf_TIGIT_NFkB_n * (inhibitor_3 / (inhibitor_3 + km13)) * NFkB
    activation_OX40_1 <- kf_OX40_NFkB * (activation_2 / (activation_2 + km10))

    phosphorylation_ERK_promoter_1 <- kf_Erk_promoter_1 * promoter_1_n * (Erk_a / (km20 + Erk_a))
    deactivation_promoter_1 <- kf_promoter_1_n * promoter_1_a
    production_NFkB_promoter_2 <- kf_NFkB_promoter_2 * promoter_2_n * (NFkB / (NFkB + km21))
    deactivation_promoter_2 <- kf_promoter_2_n * promoter_2_a

    production_IL2 <- kf_IL2_p * ((promoter_2_a + promoter_1_a) / (promoter_2_a + promoter_1_a + km23))
    clearance_IL2 <- kel_IL2 * IL2
    production_IFNg <- kf_IFNg_p * ((promoter_2_a + promoter_1_a) / (promoter_2_a + promoter_1_a + km22))
    clearance_IFNg <- kel_IFNg * IFNg

    # ---------- checkpoint-recruited second messengers ----------
    production_inhibitor_1 <- kf_PD1_APC_PDL1_inhibitor_1 * (PD1_APC_PDL1_per_cell / (PD1_APC_PDL1_per_cell + km28))
    elimination_inhibitor_1 <- kel_inhibitor_1 * inhibitor_1
    production_inhibitor_2 <- kf_CTLA4_CD8086_inhibitor_2 * (CTLA4_CD8086_per_cell / (CTLA4_CD8086_per_cell + km29))
    elimination_inhibitor_2 <- kel_inhibitor_2 * inhibitor_2
    production_inhibitor_3 <- kf_TIGIT_APC_CD155_inhibitor_3 * (TIGIT_APC_CD155_per_cell / (TIGIT_APC_CD155_per_cell + km32))
    elimination_inhibitor_3 <- kel_inhibitor_3 * inhibitor_3
    production_activation_1 <- kf_CD137_CD137L_activation_1 * (CD137_CD137L_per_cell / (CD137_CD137L_per_cell + km30))
    production_activation_1_drug11 <- kf_drug11_activation_1 * ((dimer11_CD137_per_cell + trimer11_APC_per_cell + trimer11_tumor_per_cell) / (dimer11_CD137_per_cell + trimer11_APC_per_cell + trimer11_tumor_per_cell + 1e-10))
    elimination_activation_1 <- kel_activation_1 * activation_1
    production_activation_2 <- kf_OX40_OX40L_activation_2 * (OX40_OX40L_per_cell / (OX40_OX40L_per_cell + km31))
    elimination_activation_2 <- kel_activation_2 * activation_2
    inhibitor_1_n_flux <- kf_SHP099_n * inhibitor_1 * (SHP099 / (SHP099 + km15))
    inhibitor_1_a_flux <- kf_SHP099_a * inhibitor_n
    increase_CTLA4 <- kf_APC_MHC_TCR_CTLA4 * (APC_MHC_TCR_per_cell / (APC_MHC_TCR_per_cell + 1e-5)) * (1 - CTLA4_per_cell / km16)

    # ---------- cell growth, killing and dead-cell clearance ----------
    growth_tumor <- kg_tumor_cell * tumor_cell * (1 - tumor_cell / Vmax_tumor_cell)
    killing_tumor_vivo <- kel_tumor_cell * (1 + 5 * (SHP099 / (SHP099 + km14)) + n3 * (Erk_a / (Erk_a + 1e-1)) * (Akt_a / (Akt_a + 1e-1)) * (NFkB / (NFkB + 1e-1)) * (IFNg / (IFNg + 1e-3)) * (c1 - (PD1_tumor_PDL1_per_cell / (PD1_tumor_PDL1_per_cell + km1))) * (c2 - (TIGIT_tumor_CD155_per_cell / (TIGIT_tumor_CD155_per_cell + km2)))) * tumor_cell
    growth_t <- kg_t_cell * (IL2 / (IL2 + km27)) * t_cell * (1 - t_cell / Vmax_t_cell)
    killing_t <- kel_t_cell * t_cell
    transduction_1_2 <- k * M1
    transduction_2_3 <- k * M2
    transduction_3_n <- k * M3

    # ================================================================
    # Anti-TIGIT/PD-L1 BsAb (drug_3) dimer and trimer cascade
    # (Table S1 Reactions binding_dimer_* / dissociation_*_3).
    #
    # NOTE: several Table S1 rows carry swapped "binding_"/"dissociation_"
    # LABELS -- e.g. `binding_dimer_PD-L1_tumor_3_2` holds a koff*trimer
    # term and `dissociation_ dimer_PD-L1_tumor_3_2` holds a kon*dimer*free
    # term. The Equations sheet signs them so that the mass balance is
    # correct as written, so both the expressions and their signs are
    # transcribed verbatim rather than renamed.
    # ================================================================
    free3 <- drug3 - dimer3_TIGIT - dimer3_PDL1_tumor - dimer3_PDL1_APC - trimer3_tumor - trimer3_APC
    free3b <- drug3 - dimer3_TIGIT - dimer3_PDL1_tumor - dimer3_PDL1_APC
    freeTIGIT3 <- TIGIT_per_cell * t_cell / V - trimer3_APC - TIGIT_tumor_CD155_total - dimer3_TIGIT - TIGIT_APC_CD155_total - trimer3_tumor
    freePDL1t3 <- tumor_PDL1_per_cell * tumorAll / V - dimer3_PDL1_tumor - trimer3_tumor - PD1_tumor_PDL1_total
    freePDL1a3 <- APC_PDL1_per_cell * APC / V - dimer3_PDL1_APC - trimer3_APC - PD1_APC_PDL1_total

    binding_dimer_PDL1_tumor_3 <- kon_drug3_PDL1 * free3 * freePDL1t3
    dissociation_dimer_PDL1_tumor_3 <- koff_drug3_PDL1 * dimer3_PDL1_tumor
    binding_dimer_PDL1_tumor_3_2 <- koff_drug3_TIGIT * trimer3_tumor
    dissociation_dimer_PDL1_tumor_3_2 <- kon_drug3_TIGIT * dimer3_PDL1_tumor * freeTIGIT3

    binding_dimer_TIGIT <- kon_drug3_TIGIT * free3 * freeTIGIT3
    dissociation_dimer_TIGIT <- koff_drug3_TIGIT * dimer3_TIGIT
    binding_dimer_TIGIT_2 <- koff_drug3_PDL1 * trimer3_tumor
    dissociation_dimer_TIGIT_2 <- kon_drug3_PDL1 * dimer3_TIGIT * freePDL1t3
    binding_dimer_TIGIT_3 <- koff_drug3_PDL1 * trimer3_APC
    dissociation_dimer_TIGIT_3 <- kon_drug3_PDL1 * dimer3_TIGIT * freePDL1a3

    binding_dimer_PDL1_APC_3 <- kon_drug3_PDL1 * free3b * freePDL1a3
    dissociation_dimer_PDL1_APC_3 <- koff_drug3_PDL1 * dimer3_PDL1_APC
    binding_dimer_PDL1_APC_3_2 <- koff_drug3_TIGIT * trimer3_APC
    dissociation_dimer_PDL1_APC_3_2 <- kon_drug3_TIGIT * dimer3_PDL1_APC * freeTIGIT3

    binding_dimer_PDL1_tumor_TIGIT <- kon_drug3_TIGIT * dimer3_PDL1_tumor * freeTIGIT3
    dissociation_trimer3_tumor_1 <- koff_drug3_TIGIT * trimer3_tumor
    binding_dimer_TIGIT_PDL1_tumor <- kon_drug3_PDL1 * dimer3_TIGIT * freePDL1t3
    dissociation_trimer3_tumor_2 <- koff_drug3_PDL1 * trimer3_tumor

    binding_dimer_PDL1_APC_TIGIT <- kon_drug3_TIGIT * dimer3_PDL1_APC * freeTIGIT3
    dissociation_trimer3_APC_1 <- koff_drug3_TIGIT * trimer3_APC
    binding_dimer_TIGIT_PDL1_APC <- kon_drug3_PDL1 * dimer3_TIGIT * freePDL1a3
    dissociation_trimer3_APC_2 <- koff_drug3_PDL1 * trimer3_APC

    # ================================================================
    # Anti-4-1BB/PD-L1 BsAb (drug_11) dimer and trimer cascade
    # (Table S1 Reactions binding_dimer_* / dissociation_*_11).
    #
    # TYPO CORRECTED: Table S1 gives
    #   dissociation_ trimer_4-1BB*PD-L1_tumor_2 =
    #     [koff_drug_11_PD-L1] * [trimer_4-1BB*PD-L1_APC_11]
    # i.e. the loss term in the TUMOUR trimer ODE reads the APC trimer.
    # That breaks mass balance against its partner gain term
    # `binding_dimer_4-1BB_3 = koff_drug_11_PD-L1 * trimer_..._tumor_11`,
    # and the drug_3 analogue (dissociation_ trimer_TIGIT*PD-L1_tumor_2)
    # correctly reads its own tumour trimer. The tumour trimer is used
    # here. See vignette Errata.
    # ================================================================
    free11 <- drug11 - dimer11_PDL1_APC - dimer11_CD137 - dimer11_PDL1_tumor - trimer11_APC - trimer11_tumor
    freeCD137_11 <- CD137_per_cell * t_cell / V - dimer11_CD137 - trimer11_APC - trimer11_tumor - CD137_CD137L_total
    freePDL1t11 <- tumor_PDL1_per_cell * tumorAll / V - dimer11_PDL1_tumor - trimer11_tumor - PD1_tumor_PDL1_total
    freePDL1a11 <- APC_PDL1_per_cell * APC / V - dimer11_PDL1_APC - trimer11_APC - PD1_APC_PDL1_total

    binding_dimer_PDL1_tumor <- kon_drug11_PDL1 * free11 * freePDL1t11
    dissociation_dimer_PDL1_tumor <- koff_drug11_PDL1 * dimer11_PDL1_tumor
    binding_dimer_PDL1_tumor_2 <- koff_drug11_CD137 * trimer11_tumor
    dissociation_dimer_PDL1_tumor_2 <- kon_drug11_CD137 * dimer11_PDL1_tumor * freeCD137_11

    binding_dimer_PDL1_APC <- kon_drug11_PDL1 * free11 * freePDL1a11
    dissociation_dimer_PDL1_APC <- koff_drug11_PDL1 * dimer11_PDL1_APC
    binding_dimer_PDL1_APC_2 <- koff_drug11_CD137 * trimer11_APC
    dissociation_dimer_PDL1_APC_2 <- kon_drug11_CD137 * dimer11_PDL1_APC * freeCD137_11

    binding_dimer_CD137 <- kon_drug11_CD137 * free11 * freeCD137_11
    dissociation_dimer_CD137 <- koff_drug11_CD137 * dimer11_CD137
    binding_dimer_CD137_2 <- koff_drug11_PDL1 * trimer11_APC
    dissociation_dimer_CD137_2 <- kon_drug11_PDL1 * dimer11_CD137 * freePDL1a11
    binding_dimer_CD137_3 <- koff_drug11_PDL1 * trimer11_tumor
    dissociation_dimer_CD137_3 <- kon_drug11_PDL1 * dimer11_CD137 * freePDL1t11

    binding_dimer_PDL1_tumor_CD137 <- kon_drug11_CD137 * dimer11_PDL1_tumor * freeCD137_11
    dissociation_trimer11_tumor_1 <- koff_drug11_CD137 * trimer11_tumor
    binding_dimer_CD137_PDL1_tumor <- kon_drug11_PDL1 * dimer11_CD137 * freePDL1t11
    dissociation_trimer11_tumor_2 <- koff_drug11_PDL1 * trimer11_tumor

    binding_dimer_CD137_PDL1_APC <- kon_drug11_PDL1 * dimer11_CD137 * freePDL1a11
    dissociation_trimer11_APC_1 <- koff_drug11_PDL1 * trimer11_APC
    binding_dimer_PDL1_APC_CD137 <- kon_drug11_CD137 * dimer11_PDL1_APC * freeCD137_11
    dissociation_trimer11_APC_2 <- koff_drug11_CD137 * trimer11_APC

    # ================================================================
    # Observables
    # ================================================================
    # Materials and methods: the tumour is seeded at 1e5 tumour cells per
    # mm3. The dead-cell stages M1-M3 are carried in the tumour mass by
    # Table S1 Reactions binding_4/_9/_10/_11, so they contribute to the
    # measured volume until they are cleared to `death_cell`.
    tumorVolume <- tumorAll / tumor_cell_per_mm3
    Cc <- Cc3 + Cc11

    # ================================================================
    # ODEs -- transcribed from the Table S1 "Equations" sheet
    # ================================================================
    d/dt(drug3_abdominal) <- -absorption_drug3
    d/dt(drug3_central) <- absorption_drug3 - transportation_drug3 - clearance_drug3
    d/dt(drug3_peripheral) <- transportation_drug3
    d/dt(drug11_abdominal) <- -absorption_drug11
    d/dt(drug11_central) <- absorption_drug11 - transportation_drug11 - clearance_drug11
    d/dt(drug11_peripheral) <- transportation_drug11
    d/dt(shp099_gi) <- -absorption_SHP099
    d/dt(shp099_central) <- absorption_SHP099 - transportation_SHP099 - clearance_SHP099
    d/dt(shp099_peripheral) <- transportation_SHP099

    d/dt(TCRCD3) <- -internalization_CD3
    d/dt(CD28) <- -internalization_CD28

    d/dt(ZAP70_n) <- -phosphorylation_ZAP70_APC_MHC_TCR - phosphorylation_ZAP70_1 + dephosphorylation_ZAP70_1 - phosphorylation_ZAP70_2 + dephosphorylation_ZAP70_2 + dephosphorylation_ZAP70_3 + inhibition_PD1_1 + inhibition_CTLA4_1 - phosphorylation_ZAP70_MHC_TCR + dephosphorylation_ZAP70_4
    d/dt(ZAP70_a) <- phosphorylation_ZAP70_APC_MHC_TCR + phosphorylation_ZAP70_1 - dephosphorylation_ZAP70_1 + phosphorylation_ZAP70_2 - dephosphorylation_ZAP70_2 - dephosphorylation_ZAP70_3 - inhibition_PD1_1 - inhibition_CTLA4_1 + phosphorylation_ZAP70_MHC_TCR - dephosphorylation_ZAP70_4

    d/dt(PI3K_n) <- -phosphorylation_PI3K_1 - phosphorylation_PI3K_2 + dephosphorylation_PI3K_1 + dephosphorylation_PI3K_2 - phosphorylation_PI3K_3 + dephosphorylation_PI3K_3 + inhibition_PD1_2 + inhibition_CTLA4_2
    d/dt(PI3K_a) <- phosphorylation_PI3K_1 + phosphorylation_PI3K_2 - dephosphorylation_PI3K_1 - dephosphorylation_PI3K_2 + phosphorylation_PI3K_3 - dephosphorylation_PI3K_3 - inhibition_PD1_2 - inhibition_CTLA4_2

    d/dt(Akt_a) <- phosphorylation_AKT - dephosphorylation_AKT - inhibition_CTLA4_3 + activation_OX40_2 - inhibition_LAG3_2 + phosphorylation_AKT_IL2 + activation_CD137_2
    d/dt(Akt_n) <- -phosphorylation_AKT + dephosphorylation_AKT + inhibition_CTLA4_3 - activation_OX40_2 + inhibition_LAG3_2 - phosphorylation_AKT_IL2 - activation_CD137_2

    d/dt(Erk_n) <- -phosphorylation_ERK + dephosphorylation_ERK - activation_CD137_1 + inhibition_TIGIT_1 + inhibition_LAG3_1 - phosphorylation_ERK_IL2
    d/dt(Erk_a) <- phosphorylation_ERK - dephosphorylation_ERK + activation_CD137_1 - inhibition_TIGIT_1 - inhibition_LAG3_1 + phosphorylation_ERK_IL2

    d/dt(NFkB) <- phosphorylation_NFkB - dephosphorylation_NFkB - inhibition_TIGIT_2 + activation_OX40_1
    d/dt(IL2) <- production_IL2 - clearance_IL2
    d/dt(IFNg) <- production_IFNg - clearance_IFNg

    d/dt(promoter_1_n) <- -phosphorylation_ERK_promoter_1 + deactivation_promoter_1
    d/dt(promoter_1_a) <- phosphorylation_ERK_promoter_1 - deactivation_promoter_1
    d/dt(promoter_2_n) <- -production_NFkB_promoter_2 + deactivation_promoter_2
    d/dt(promoter_2_a) <- production_NFkB_promoter_2 - deactivation_promoter_2

    d/dt(inhibitor_1) <- -elimination_inhibitor_1 + production_inhibitor_1 - inhibitor_1_n_flux + inhibitor_1_a_flux
    # Table S1 lists no ODE for `inhibitor_n`; it is the SHP099-inactivated
    # pool that inhibitor_1 exchanges with, so its ODE is the mass-balance
    # complement of the two SHP099 fluxes in d(inhibitor_1)/dt.
    d/dt(inhibitor_n) <- inhibitor_1_n_flux - inhibitor_1_a_flux
    d/dt(inhibitor_2) <- -elimination_inhibitor_2 + production_inhibitor_2
    d/dt(inhibitor_3) <- -elimination_inhibitor_3 + production_inhibitor_3
    d/dt(activation_1) <- -elimination_activation_1 + production_activation_1 + production_activation_1_drug11
    d/dt(activation_2) <- -elimination_activation_2 + production_activation_2

    d/dt(APC_MHC_TCR_total) <- binding_1 - dissociation_APC_MHC_TCR_total
    d/dt(tumor_MHC_TCR_total) <- -dissociation_tumor_MHC_TCR_total + binding_9
    d/dt(CD28_CD8086_total) <- binding_2 - dissociation_CD28_CD8086_total
    d/dt(PD1_APC_PDL1_total) <- binding_3 - dissociation_PD1_APC_PDL1_total
    d/dt(PD1_tumor_PDL1_total) <- binding_10 - dissociation_PD1_tumor_PDL1_total
    d/dt(CTLA4_CD8086_total) <- binding_5 - dissociation_CTLA4_CD8086_total
    d/dt(CD137_CD137L_total) <- binding_6 - dissociation_CD137_CD137L_total
    d/dt(OX40_OX40L_total) <- binding_7 - dissociation_OX40_OX40L_total
    d/dt(TIGIT_APC_CD155_total) <- binding_8 - dissociation_TIGIT_APC_CD155_total
    d/dt(TIGIT_tumor_CD155_total) <- binding_11 - dissociation_TIGIT_tumor_CD155_total
    d/dt(CTLA4_per_cell) <- increase_CTLA4

    d/dt(tumor_cell) <- growth_tumor - killing_tumor_vivo
    d/dt(t_cell) <- growth_t - killing_t
    d/dt(M1) <- -transduction_1_2 + killing_tumor_vivo
    d/dt(M2) <- transduction_1_2 - transduction_2_3
    d/dt(M3) <- transduction_2_3 - transduction_3_n
    # Table S1 lists no ODE for `Death cell`; it is the terminal sink of the
    # M1 -> M2 -> M3 clearance chain (Table S1 Reactions transduction_3_n)
    # and feeds back into nothing.
    d/dt(death_cell) <- transduction_3_n

    d/dt(dimer3_PDL1_tumor) <- binding_dimer_PDL1_tumor_3 - dissociation_dimer_PDL1_tumor_3 + binding_dimer_PDL1_tumor_3_2 - dissociation_dimer_PDL1_tumor_3_2
    d/dt(dimer3_TIGIT) <- binding_dimer_TIGIT - dissociation_dimer_TIGIT + binding_dimer_TIGIT_2 - dissociation_dimer_TIGIT_2 + binding_dimer_TIGIT_3 - dissociation_dimer_TIGIT_3
    d/dt(trimer3_tumor) <- binding_dimer_PDL1_tumor_TIGIT - dissociation_trimer3_tumor_1 + binding_dimer_TIGIT_PDL1_tumor - dissociation_trimer3_tumor_2
    d/dt(dimer3_PDL1_APC) <- binding_dimer_PDL1_APC_3 - dissociation_dimer_PDL1_APC_3 + binding_dimer_PDL1_APC_3_2 - dissociation_dimer_PDL1_APC_3_2
    d/dt(trimer3_APC) <- -dissociation_trimer3_APC_1 + binding_dimer_PDL1_APC_TIGIT + binding_dimer_TIGIT_PDL1_APC - dissociation_trimer3_APC_2

    d/dt(dimer11_PDL1_tumor) <- -dissociation_dimer_PDL1_tumor + binding_dimer_PDL1_tumor + binding_dimer_PDL1_tumor_2 - dissociation_dimer_PDL1_tumor_2
    d/dt(dimer11_PDL1_APC) <- -dissociation_dimer_PDL1_APC + binding_dimer_PDL1_APC + binding_dimer_PDL1_APC_2 - dissociation_dimer_PDL1_APC_2
    d/dt(dimer11_CD137) <- -dissociation_dimer_CD137 + binding_dimer_CD137 + binding_dimer_CD137_2 - dissociation_dimer_CD137_2 + binding_dimer_CD137_3 - dissociation_dimer_CD137_3
    d/dt(trimer11_tumor) <- -dissociation_trimer11_tumor_1 + binding_dimer_PDL1_tumor_CD137 - dissociation_trimer11_tumor_2 + binding_dimer_CD137_PDL1_tumor
    d/dt(trimer11_APC) <- -dissociation_trimer11_APC_1 + binding_dimer_CD137_PDL1_APC - dissociation_trimer11_APC_2 + binding_dimer_PDL1_APC_CD137
  })
}
