Yang_2017_buagafuran_rat <- function() {
  description <- paste(
    "Preclinical (rat). Direct sigmoid Emax pharmacodynamic model relating the",
    "brain concentration of the anxiolytic buagafuran to the time spent on the",
    "open arms of the elevated plus-maze (EPM) in male Wistar rats (Yang 2017",
    "equation 4). The source paper fits the EPM time course after a single",
    "4 mg/kg oral dose against the brain concentration-time profile predicted by",
    "a GastroPlus whole-body PBPK model, and reports no effect delay, so the",
    "concentration-effect relationship is direct (no effect compartment). Only",
    "this PD layer is reproduced here: the rat and human PBPK layers are",
    "GastroPlus platform models whose tissue partition coefficients, organ",
    "volumes and blood flows are software-database outputs that the paper never",
    "prints, so they are not reproducible from the publication (see the vignette",
    "'Assumptions and deviations'). Buagafuran brain concentration is therefore",
    "supplied by the user as the canonical effect-site covariate CEFFECT rather",
    "than generated by a PK model in this file. No inter-individual variability",
    "and no residual-error model are reported by the source (the EPM data are",
    "group means of n = 10 rats per time point), so both are encoded as zero.",
    sep = " "
  )
  reference <- paste(
    "Yang F, Wang B, Liu Z, Xia X, Wang W, Yin D, Sheng L, Li Y. (2017).",
    "Prediction of a Therapeutic Dose for Buagafuran, a Potent Anxiolytic Agent",
    "by Physiologically Based Pharmacokinetic/Pharmacodynamic Modeling Starting",
    "from Pharmacokinetics in Rats and Human.",
    "Frontiers in Pharmacology 8:683. doi:10.3389/fphar.2017.00683.",
    sep = " "
  )
  vignette <- "Yang_2017_buagafuran"
  units <- list(
    time = "min",
    dosing = "(not applicable; brain concentration is supplied as the CEFFECT covariate, not as a dose record)",
    concentration = "ng/mL (buagafuran brain concentration via CEFFECT; the PD output epm_openarm_time is in seconds)"
  )

  covariateData <- list(
    CEFFECT = list(
      description = "Buagafuran concentration in rat brain tissue homogenate (ng/mL), supplied as the driver of the direct sigmoid Emax EPM response",
      units = "ng/mL",
      type = "continuous",
      reference_category = NULL,
      notes = paste(
        "Member of the canonical effect-site PD driver family CEFFECT; here the",
        "biophase is whole rat brain, homogenised in a threefold volume (w/v) of",
        "saline and assayed by LC-MS/MS (Yang 2017, 'PK in the Rat'). Yang 2017",
        "equation 4 states 'C is in ng/mL'. In the source study CEFFECT is the",
        "brain concentration-time profile predicted by the authors' GastroPlus",
        "rat PBPK model (brain Kp optimised to 6.7 by parameter sensitivity",
        "analysis; refined hepatic CL 36.8 mL/min/kg) after a single oral",
        "4 mg/kg dose; that PBPK model is NOT reproduced in this file and cannot",
        "be reproduced from the publication. The concentration range covered by",
        "the fitted data is approximately 5.6 to 29.5 ng/mL (Yang 2017 Figure 6",
        "x-axis and observed markers), which brackets the EC50 of 10.6 ng/mL --",
        "the Discussion notes 'the rat data provided appropriate coverage of the",
        "EC50 region'. Observed rat brain concentrations were measurable from",
        "5 min after dosing with a maximum at 15-30 min (Yang 2017 Results,",
        "'Prediction of Plasma or Brain PK in Rat and Human'). For downstream",
        "simulation users supply CEFFECT from their own rat brain PK model or",
        "from observed brain concentrations."
      ),
      source_name = "(none; brain concentration is a PBPK-predicted profile, not a named data column in the source)"
    )
  )

  population <- list(
    species = "rat (Wistar, male)",
    n_subjects = 90L,
    n_studies = 1L,
    age_range = "not reported",
    weight_range = "130-160 g (elevated plus-maze cohort); 180-200 g (the separate plasma / brain PK cohort)",
    sex_female_pct = 0,
    disease_state = "healthy (elevated plus-maze model of unconditioned anxiety)",
    dose_range = paste(
      "Buagafuran polyvinylpyrrolidone (PVP) formulation suspended in deionised",
      "water, administered orally. Dose-response arm (Group I): vehicle, 2, 4 and",
      "8 mg/kg, tested 10 min after dosing. Time-course arm (Group II), the arm",
      "the PD model was fitted to: a single 4 mg/kg oral dose with EPM testing at",
      "5, 10, 15, 30, 60, 90, 120 and 180 min after dosing."
    ),
    regions = "China (Institute of Materia Medica, Chinese Academy of Medical Sciences, Beijing)",
    notes = paste(
      "Elevated plus-maze: two open arms (50 x 10 cm) and two closed arms",
      "(50 x 10 x 40 cm) extending from a 10 x 10 cm central platform, raised",
      "50 cm from the floor; each rat explored freely for a 5 min test period and",
      "the time spent in each arm type was recorded. Rats were handled daily for",
      "1 week before the study and fasted 12 h before the experiment; tests ran",
      "between 09:00 and 12:00 and the maze was wiped with 10% ethanol between",
      "tests (Yang 2017, 'PD in the Rat'). Each EPM group was n = 10 (Figure 4",
      "and Figure 5 captions); n_subjects = 90 assumes independent groups of 10",
      "for the vehicle control plus each of the eight post-dose times of the",
      "time-course arm, which the paper does not state explicitly but which the",
      "single-trial design of the EPM implies. The dose-response arm showed an",
      "inverted U-shaped curve with the maximum effect at 4 mg/kg, which is why",
      "the PD model was fitted to the 4 mg/kg time course -- 'the dose on the",
      "plateau of the effectiveness dose-response curve' (Yang 2017 Discussion).",
      "Group means only are reported; no individual-level data and no",
      "inter-individual variability estimates are given. Animal protocols",
      "approved by the Animal Care and Welfare Committee of the Institute of",
      "Materia Medica (permission SYXK 2014-0023)."
    )
  )

  ini({
    # ------------------------------------------------------------------
    # Yang 2017 equation 4 (Methods, 'PBPK/PD Modeling'):
    #
    #                 Emax * C^gamma
    #   E = E0 + ---------------------------
    #             EC50^gamma  +  C^gamma
    #
    # 'where C is in ng/mL, E0 is the time spent by the control group in
    # the open arms which is equal to 0.63, Emax is the maximum response,
    # EC50 is the concentration of a compound at which 50% of its maximum
    # response is observed and gamma is the Hill coefficient. The set of
    # parameter values for the model was determined by GastroPlus
    # software.'
    #
    # E and E0 are the time spent on the open arms in SECONDS (Figure 5
    # and Figure 6 y-axis labels, 'Time spent on the open arms (s)').
    #
    # PARAMETER-SOURCE SUMMARY
    #   E0    0.63  s        printed, Methods equation-4 paragraph
    #   EC50  10.6  ng/mL    printed, Results 'PD in the EPM Model'
    #   gamma 2.5   unitless printed, Results 'PD in the EPM Model'
    #   Emax  10.1  s        NOT printed anywhere in the paper; recovered
    #                        from the fitted curve of Figure 6 -- see the
    #                        comment on lemax below.
    #
    # No inter-individual variability and no residual-error model are
    # reported for the PD fit (the EPM data are group means of n = 10;
    # GastroPlus PDPlus reports no OMEGA / SIGMA block and the paper gives
    # no standard errors or RSEs on any of the four parameters), so no eta
    # is declared and the additive residual SD is fixed at zero.
    # ------------------------------------------------------------------

    le0 <- fixed(log(0.63))
    label("Log of E0, baseline time spent on the open arms in vehicle-treated rats (s)")
    # Yang 2017 Methods, equation-4 paragraph: 'E0 is the time spent by the
    # control group in the open arms which is equal to 0.63'. Fixed: it is a
    # measured control-group mean carried into the model, not an estimated
    # parameter, and it is consistent with the vehicle column of Figure 5.

    lemax <- log(10.1)
    label("Log of Emax, maximum drug-attributable increase in time on the open arms (s)")
    # NOT REPORTED IN THE PAPER. Digitised from the fitted sigmoid Emax curve
    # of Yang 2017 Figure 6 ('The solid line represents the prediction for
    # buagafuran'), which is the final model itself rather than an unadjusted
    # side fit, so the digitised curve carries the model's own parameters.
    # Procedure: the Figure 6 panel was rendered from the PDF at 300 dpi, the
    # axes calibrated on the six y ticks (0-15 s) and seven x ticks
    # (0-30 ng/mL), and the solid curve traced column by column (856 points
    # after excluding the 17 columns where the trace crosses an observed-data
    # marker). Fitting equation 4 to the traced curve with E0, EC50 and gamma
    # held at the printed 0.63 / 10.6 / 2.5 gives Emax = 10.07 s
    # (RMSE 0.022 s). Refitting all four parameters freely recovers
    # E0 = 0.625, EC50 = 10.58, gamma = 2.546 and Emax = 10.03 (RMSE 0.008 s),
    # i.e. it reproduces the three printed values to within 2%, which
    # validates both the digitisation and the equation-4 form. 10.1 s is used
    # here, matching the paper's own 3-significant-figure style; the value is
    # determined to about +/- 0.05 s (constrained-fit 10.07, free-fit 10.03,
    # printed-parameter grid 10.03-10.12). The implied plateau E0 + Emax =
    # 10.7 s is consistent with the Figure 6 curve approaching 10 s at the
    # highest observed concentration. See the vignette 'Assumptions and
    # deviations'.

    lec50 <- log(10.6)
    label("Log of EC50, brain concentration producing half the maximum EPM response (ng/mL)")
    # Yang 2017 Results, 'PD in the EPM Model': 'EC50 was 10.6 ng/mL and Hill
    # coefficient was 2.5.' No standard error or confidence interval reported.

    lhill <- log(2.5)
    label("Log of the Hill coefficient gamma of the sigmoid Emax function (unitless)")
    # Yang 2017 Results, 'PD in the EPM Model': 'EC50 was 10.6 ng/mL and Hill
    # coefficient was 2.5.' Restated in the Discussion: 'A relatively steeper
    # sigmoid C-E curve was obtained with the Hill coefficient of 2.5.'

    addSd <- fixed(0)
    label("Additive residual SD on the time spent on the open arms (s; ZERO - no residual-error model is reported by the source)")
  })

  model({
    # 1. Effect-site (brain) buagafuran concentration for this record, in
    #    ng/mL, supplied through the canonical CEFFECT covariate column.
    #    Yang 2017 reports no hysteresis between the brain concentration and
    #    the EPM response -- 'No effect delays between the response and
    #    effects were found' (Results, 'PD in the EPM Model') -- so the model
    #    is a direct concentration-effect map with no effect compartment.
    conc <- CEFFECT

    # 2. Typical-value PD parameters. No IIV is reported, so these carry no
    #    eta terms.
    e0 <- exp(le0)
    emax <- exp(lemax)
    ec50 <- exp(lec50)
    hill <- exp(lhill)

    # 3. Yang 2017 equation 4: direct sigmoid Emax on brain concentration.
    epm_openarm_time <- e0 + emax * conc^hill / (ec50^hill + conc^hill)

    # 4. Observation. The additive residual SD is fixed at zero because the
    #    source reports no residual-error model; users refitting this model
    #    to individual EPM data should free addSd.
    epm_openarm_time ~ add(addSd)
  })
}
