Zhang_2024_f53b_human_pbpk <- function() {
  description <- paste(
    "PBPK (whole-body, gestational; original implementation in",
    "R/mrgsolve). Chlorinated polyfluorinated ether sulfonic acid",
    "(F-53B, 6:2 Cl-PFESA) in pregnant women, extrapolated from the",
    "authors' pregnant-mouse model by allometric scaling of every rate",
    "constant as K_human = K_mouse * (BW_human / BW_mouse)^-0.25 (Zhang",
    "et al. 2024, Environ Sci Technol). The compartmental structure is",
    "identical to Zhang_2024_f53b_mouse_pbpk -- two-compartment",
    "gastrointestinal tract, plasma, liver, fat, mammary gland,",
    "placenta, rest of body, a three-subcompartment kidney with",
    "saturable basolateral/apical reabsorption plus glomerular",
    "filtration, and a separate fetal circulation (fetal plasma, brain,",
    "liver, rest of body) reached only by bidirectional placental",
    "diffusion, with a further bidirectional exchange to amniotic fluid",
    "-- but maternal and fetal physiology follow the human gestational",
    "growth equations of Abduljalil, Kapraun and Loccisano rather than",
    "the murine O'Flaherty equations. Model time is HOURS SINCE",
    "CONCEPTION, so gestational age GA = time / 168 weeks drives every",
    "volume, blood flow, haematocrit and glomerular filtration rate.",
    "Intended for chronic dietary-intake simulation: the paper drives it",
    "with an estimated daily intake of 0.122 ng/kg/day and compares",
    "predicted maternal plasma and cord blood at 38 weeks against",
    "Chinese biomonitoring data. Deterministic; population variability",
    "was addressed by Monte Carlo sampling of body weight and five",
    "chemical-specific parameters (Table S9), not by estimated random",
    "effects. Pre-conception body burden is generated by the companion",
    "model Zhang_2024_f53b_human_prepregnancy_pbpk."
  )
  reference <- paste(
    "Zhang J, Li SP, Li QQ, Zhang YT, Dong GH, Canchola A, Zeng X, Chou",
    "WC. Development of a Physiologically Based Pharmacokinetic (PBPK)",
    "Model for F-53B in Pregnant Mice and Its Extrapolation to Humans.",
    "Environ Sci Technol. 2024;58(43):18928-18939.",
    "doi:10.1021/acs.est.4c05405. Model equations and parameters from",
    "Supporting Information Sections S4-S5 and Tables S3-S4, S6-S7."
  )
  vignette <- "Zhang_2024_f53b_pbpk"
  units <- list(time = "h", dosing = "mg", concentration = "mg/L")

  paper_specific_compartments <- c(
    "kidney_blood", "ptc", "filtrate", "fat", "mammary", "rest",
    "placenta", "feces", "plasma_fet", "liver_fet", "brain_fet",
    "rest_fet", "amniotic", "trans_mf", "trans_fm"
  )

  compartmentData <- list(
    stomach      = list(analyte = "F-53B", units = "mg", specimen = "administration site",      verified = TRUE),
    intestine    = list(analyte = "F-53B", units = "mg", specimen = "administration site",       verified = TRUE),
    plasma       = list(analyte = "F-53B", units = "mg", specimen = "plasma",       verified = TRUE),
    liver        = list(analyte = "F-53B", units = "mg", specimen = "tissue",        verified = TRUE),
    kidney_blood = list(analyte = "F-53B", units = "mg", specimen = "tissue",          verified = TRUE),
    ptc          = list(analyte = "F-53B", units = "mg", specimen = "tissue", verified = TRUE),
    filtrate     = list(analyte = "F-53B", units = "mg", specimen = "urine",      verified = TRUE),
    fat          = list(analyte = "F-53B", units = "mg", specimen = "tissue",          verified = TRUE),
    mammary      = list(analyte = "F-53B", units = "mg", specimen = "tissue",         verified = TRUE),
    rest         = list(analyte = "F-53B", units = "mg", specimen = "tissue", verified = TRUE),
    placenta     = list(analyte = "F-53B", units = "mg", specimen = "tissue",              verified = TRUE),
    urine        = list(analyte = "F-53B", units = "mg", specimen = "urine",                 verified = TRUE),
    feces        = list(analyte = "F-53B", units = "mg", specimen = "faeces",                 verified = TRUE),
    plasma_fet   = list(analyte = "F-53B", units = "mg", specimen = "plasma", verified = TRUE),
    liver_fet    = list(analyte = "F-53B", units = "mg", specimen = "tissue",           verified = TRUE),
    brain_fet    = list(analyte = "F-53B", units = "mg", specimen = "tissue",           verified = TRUE),
    rest_fet     = list(analyte = "F-53B", units = "mg", specimen = "tissue",    verified = TRUE),
    amniotic     = list(analyte = "F-53B", units = "mg", specimen = "tissue",        verified = TRUE),
    trans_mf     = list(analyte = "F-53B", units = "mg", specimen = "not applicable", verified = TRUE),
    trans_fm     = list(analyte = "F-53B", units = "mg", specimen = "not applicable", verified = TRUE)
  )

  covariateData <- list(
    WT = list(
      description        = "Body weight",
      units              = "kg",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Maternal pre-pregnancy body weight. Zhang 2024 Table S4 gives",
        "60 kg for the pregnant woman (54 kg pre-pregnant); 60 kg is the",
        "default carried in ini() and the mean of the Monte Carlo",
        "distribution (Table S9: normal, SD 18 kg, CV 30%, truncated to",
        "24.72-95.28 kg). Liver, kidney, mammary and plasma volumes and",
        "the pre-gestational cardiac output are fractions of WT; the",
        "gestational body weight BW_P = WT plus the fat, mammary,",
        "placental, fetal and amniotic increments drives all allometric",
        "BW^-0.25 rate-constant and BW^0.75 Vmax scaling. WT is the most",
        "influential parameter in the paper's local sensitivity analysis",
        "(Table S13: NSC -0.70 for both maternal and fetal plasma AUC).",
        "Note that gestational fat volume and all gestational blood",
        "flows are absolute functions of gestational age (Table S6) and",
        "so do NOT scale with WT."
      ),
      source_name        = "BW"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 1000L,
    n_studies      = 21L,
    age_range      = "conception assumed at age 30 years",
    weight_range   = "60 kg pregnant (54 kg pre-pregnant); Monte Carlo 24.7-95.3 kg",
    sex_female_pct = 100,
    disease_state  = paste(
      "Healthy pregnant women. No clinical study was conducted: the",
      "model was extrapolated from the pregnant-mouse model and",
      "evaluated against maternal plasma and cord blood F-53B",
      "concentrations pooled from published Chinese biomonitoring",
      "studies (Table S10). A Monte Carlo population of 1000 virtual",
      "pregnancies was generated by sampling body weight and the five",
      "chemical-specific parameters with normalized sensitivity",
      "coefficient at or above 0.30 (Table S9)."
    ),
    dose_range     = paste(
      "Chronic dietary intake. Published estimated daily intakes for",
      "F-53B in China range from 0.067 to 1.87 ng/kg/day (Table S8);",
      "the paper simulates 0.122 ng/kg/day given continuously from",
      "birth to age 30 years and then through 38 weeks of pregnancy."
    ),
    regions        = "China (biomonitoring evaluation data)",
    notes          = paste(
      "Predicted maternal plasma F-53B at 38 weeks had a median of",
      "1.43-1.44 ng/mL against an observed biomonitoring median of",
      "1.66 ng/mL (range 0.094-5.48). For cord blood the paper",
      "contradicts itself: Results section 3.4 reports predicted 0.59",
      "(range 0.091-1.16) versus measured 2.75 (range 1.26-5.27) and",
      "concludes the model UNDERestimates, while Discussion 4.2 reports",
      "predicted 2.76 versus observed 0.59 and concludes the model",
      "OVERestimates. Table S10, which tabulates the 14 underlying",
      "biomonitoring studies, gives an observed cord-blood median of",
      "0.59 ng/mL (range 0.091-1.16), so the Discussion is correct and",
      "the Results section has predicted and observed transposed.",
      "Replicating this model end to end predicts cord blood of about",
      "2.3 ng/mL, confirming that the model overpredicts fetal",
      "exposure roughly 4-fold. See the vignette Errata."
    )
  )

  ini({
    # ---------------------------------------------------------------------
    # Chemical-specific parameters for F-53B in the pregnant woman.
    # Zhang 2024 Supporting Information Table S7, "Human / Pregnant"
    # column. Rows footnoted "b" in that table were obtained from the
    # mouse values by the paper's own allometric equation
    #   K_human = K_mouse * (60 / 0.025)^-0.25 = K_mouse * 0.142887
    # which was verified during extraction to reproduce every one of
    # those rows exactly (K0C, KabsC, KunabsC, KbileC, KurineC, Ktrans1C,
    # Ktrans2C, Ktrans3C, Ktrans4C, Kdif, KeffluxC). Everything is FIXED:
    # the paper reports a deterministic PBPK model with no estimated
    # random effects.
    # ---------------------------------------------------------------------

    # Plasma protein binding
    lfu     <- fixed(log(0.067)); label("Free fraction of F-53B in maternal plasma (unitless)")  # Zhang 2024 Table S7, human Free = 0.067
    lfu_fet <- fixed(log(0.076)); label("Free fraction of F-53B in fetal plasma (unitless)")     # Zhang 2024 Table S7, human Free_Fet = 0.076

    # Absorption / gastric emptying
    lk0     <- fixed(log(0.774));    label("Stomach absorption rate constant K0C (1/h per BW^-0.25)")           # Zhang 2024 Table S7, human K0C = 0.774
    lkabs   <- fixed(log(0.347));    label("Small-intestine absorption rate constant KabsC (1/h per BW^-0.25)") # Zhang 2024 Table S7, human KabsC = 0.347
    lkunabs <- fixed(log(7.715e-5)); label("Unabsorbed-to-faeces rate constant KunabsC (1/h per BW^-0.25)")     # Zhang 2024 Table S7, human KunabsC = 7.715E-05
    lge     <- fixed(log(3.51));     label("Gastric emptying rate constant GEC (1/h per BW^-0.25)")             # Zhang 2024 Table S4, human GEC = 3.51

    # Tissue-to-plasma partition coefficients
    lkp_liver     <- fixed(log(2.10)); label("Liver-to-plasma partition coefficient PL (unitless)")            # Zhang 2024 Table S7, human PL = 2.10
    lkp_kidney    <- fixed(log(1.26)); label("Kidney-to-plasma partition coefficient PK (unitless)")           # Zhang 2024 Table S7, human PK = 1.26
    lkp_fat       <- fixed(log(0.29)); label("Fat-to-plasma partition coefficient PF (unitless)")              # Zhang 2024 Table S7, human PF = 0.29
    lkp_mammary   <- fixed(log(0.16)); label("Mammary-to-plasma partition coefficient PM (unitless)")          # Zhang 2024 Table S7, human PM = 0.16
    lkp_placenta  <- fixed(log(0.08)); label("Placenta-to-plasma partition coefficient PPla (unitless)")       # Zhang 2024 Table S7, human PPla = 0.08
    lkp_rest      <- fixed(log(0.43)); label("Rest-of-body-to-plasma partition coefficient PRest (unitless)")  # Zhang 2024 Table S7, human PRest = 0.43
    lkp_liver_fet <- fixed(log(2.10)); label("Fetal liver-to-plasma partition coefficient PL_Fet (unitless)")  # Zhang 2024 Table S7, human PL_Fet = 2.10
    lkp_brain_fet <- fixed(log(1.55)); label("Fetal brain-to-plasma partition coefficient PB_Fet (unitless)")  # Zhang 2024 Table S7, human PB_Fet = 1.55
    lkp_rest_fet  <- fixed(log(0.22)); label("Fetal rest-of-body-to-plasma partition coefficient PRest_Fet (unitless)")  # Zhang 2024 Table S7, human PRest_Fet = 0.22

    # Placental and amniotic-fluid bidirectional transfer
    lktrans1 <- fixed(log(0.199));    label("Mother-to-fetus placental transfer constant Ktrans1C (L/h per kg^0.75)")  # Zhang 2024 Table S7, human Ktrans1C = 0.199
    lktrans2 <- fixed(log(0.086));    label("Fetus-to-mother placental transfer constant Ktrans2C (L/h per kg^0.75)")  # Zhang 2024 Table S7, human Ktrans2C = 0.086
    lktrans3 <- fixed(log(0.033));    label("Fetus-to-amniotic-fluid transfer constant Ktrans3C (L/h per kg^0.75)")    # Zhang 2024 Table S7, human Ktrans3C = 0.033
    lktrans4 <- fixed(log(1.429e-4)); label("Amniotic-fluid-to-fetus transfer constant Ktrans4C (L/h per kg^0.75)")    # Zhang 2024 Table S7, human Ktrans4C = 1.429E-04

    # Elimination
    lkbile  <- fixed(log(1.429e-6)); label("Biliary elimination rate constant KbileC (1/h per BW^-0.25)")  # Zhang 2024 Table S7, human KbileC = 1.429E-06
    lkurine <- fixed(log(0.003));    label("Urinary elimination rate constant KurineC (1/h per BW^-0.25)") # Zhang 2024 Table S7, human KurineC = 0.003

    # Renal reabsorption
    lvmax_baso_invitro   <- fixed(log(479.00));   label("In vitro Vmax, basolateral Oat1/Oat3 (pmol/mg protein/min)")  # Zhang 2024 Table S7, human Vmax_baso_invitro = 479.00
    lvmax_apical_invitro <- fixed(log(51803.00)); label("In vitro Vmax, apical Oatp1a1 (pmol/mg protein/min)")         # Zhang 2024 Table S7, human Vmax_apical_invitro = 51803.00
    lkm_baso             <- fixed(log(64.40));    label("Michaelis constant, basolateral transporters (mg/L)")         # Zhang 2024 Table S7, human Km_baso = 64.40
    lkm_apical           <- fixed(log(20.10));    label("Michaelis constant, apical transporters (mg/L)")              # Zhang 2024 Table S7, human Km_apical = 20.10
    lrafbaso             <- fixed(log(1));        label("Relative activity factor, basolateral transporters (unitless)")  # Zhang 2024 Table S7, human RAFbaso = 1
    lrafapi              <- fixed(log(0.001));    label("Relative activity factor, apical transporters (unitless)")       # Zhang 2024 Table S7, human RAFapi = 0.001
    lkdif                <- fixed(log(7.715e-6)); label("Diffusion rate, kidney blood to proximal tubule cells (L/h)")    # Zhang 2024 Table S7, human Kdif = 7.715E-06
    lkefflux             <- fixed(log(0.800));    label("Efflux rate constant, tubule cells to plasma KeffluxC (1/h per BW^-0.25)")  # Zhang 2024 Table S7, human KeffluxC = 0.800

    # Residual error. Zhang 2024 report no residual-error model for the
    # human extrapolation: it is a forward prediction compared against
    # pooled biomonitoring medians, not a fit. These FIXED placeholders
    # exist only to complete the nlmixr2 object and carry no information
    # from the paper. See the vignette Errata.
    propSd             <- fixed(0.30); label("Proportional residual error placeholder, maternal plasma (fraction)")  # not reported in Zhang 2024; placeholder only
    propSd_Cplasma_fet <- fixed(0.30); label("Proportional residual error placeholder, cord blood (fraction)")       # not reported in Zhang 2024; placeholder only
  })

  model({
    # =====================================================================
    # 0. Back-transforms
    # =====================================================================
    fu      <- exp(lfu)
    fu_fet  <- exp(lfu_fet)
    K0C     <- exp(lk0)
    KabsC   <- exp(lkabs)
    KunabsC <- exp(lkunabs)
    GEC     <- exp(lge)
    PL      <- exp(lkp_liver)
    PK      <- exp(lkp_kidney)
    PF      <- exp(lkp_fat)
    PM      <- exp(lkp_mammary)
    PPla    <- exp(lkp_placenta)
    PRest   <- exp(lkp_rest)
    PL_Fet  <- exp(lkp_liver_fet)
    PB_Fet  <- exp(lkp_brain_fet)
    PRest_Fet <- exp(lkp_rest_fet)
    Ktrans1C  <- exp(lktrans1)
    Ktrans2C  <- exp(lktrans2)
    Ktrans3C  <- exp(lktrans3)
    Ktrans4C  <- exp(lktrans4)
    KbileC    <- exp(lkbile)
    KurineC   <- exp(lkurine)
    Vmax_baso_invitro   <- exp(lvmax_baso_invitro)
    Vmax_apical_invitro <- exp(lvmax_apical_invitro)
    Km_baso   <- exp(lkm_baso)
    Km_apical <- exp(lkm_apical)
    RAFbaso   <- exp(lrafbaso)
    RAFapi    <- exp(lrafapi)
    Kdif      <- exp(lkdif)
    KeffluxC  <- exp(lkefflux)

    # =====================================================================
    # 1. Time base
    #
    # Model time is HOURS SINCE CONCEPTION. Gestational age GA (weeks)
    # drives every maternal and fetal growth equation of Table S6, so a
    # 38-week pregnancy runs from t = 0 to t = 6384 h.
    # =====================================================================
    GD <- time / 24    # gestational day
    GA <- GD / 7       # gestational age (weeks); Zhang 2024 SI code

    # =====================================================================
    # 2. Fixed maternal physiology (Zhang 2024 Table S4, "Human")
    # =====================================================================
    QCC    <- 16.4     # Zhang 2024 Table S4, human QCC (L/h/kg^0.75)
    QLC    <- 0.25     # Zhang 2024 Table S4, human QLC
    QKC    <- 0.175    # Zhang 2024 Table S4, human QKC
    QMC    <- 0.027    # Zhang 2024 Table S4, human QMC
    QFC    <- 0.052    # Zhang 2024 Table S4, human QFC
    VLC    <- 0.026    # Zhang 2024 Table S4, human VLC
    VKC    <- 0.004    # Zhang 2024 Table S4, human VKC
    VMC    <- 0.0062   # Zhang 2024 Table S4, human VMC
    VFC    <- 0.214    # Zhang 2024 Table S4, human VFC
    VFilC  <- 0.00084  # Zhang 2024 Table S4, human VFilC (L/kg BW)
    VPTCC  <- 1.35e-4  # Zhang 2024 Table S4, VPTCC (L/kg kidney)
    protein <- 2.0e-6  # Zhang 2024 Table S4, protein (mg protein/PTC)
    MW     <- 570.67   # Zhang 2024 Table S1, F-53B molecular weight (g/mol)
    VPlasC_Fet <- 0.0428  # Zhang 2024 Table S4, human VPlasC_Fet (assumed same as mother)

    # =====================================================================
    # 3. Maternal gestational growth equations (Zhang 2024 Table S6)
    #    Haematocrit, GFR, plasma volume, amniotic fluid, placenta and fat
    #    are absolute functions of gestational age, not fractions of body
    #    weight.
    # =====================================================================
    Htc   <- (39.192 - 0.10562 * GA - 7.1045e-4 * GA^2) / 100
    GFR   <- (113.73 + 3.5784 * GA - 0.067272 * GA^2) * 0.06
    VPlas <- 1.2406 / (1 + exp(-0.31338 * (GA - 17.813))) + 2.4958
    VAm   <- (822.34 / (1 + exp(-0.26988 * (GA - 20.150)))) / 1000

    VPla <- 0
    if (GA >= 2) {
      VPla <- (-1.7646 * GA + 0.91775 * GA^2 - 0.011543 * GA^3) / 1000
    }

    VF_P <- (1 / 0.95) * (17.067 + 0.14937 * GA)
    VF_0 <- VFC * WT
    VM_0 <- VMC * WT
    VM_P <- WT * (VMC + 0.0065 * exp(-7.444868 * exp(-0.000678 * (GD * 24))))

    VL   <- VLC * WT
    VK   <- VKC * WT
    MK   <- VKC * WT * 1000       # kidney mass (g)
    VKb  <- VK * 0.16
    VFil <- VFilC * WT
    VPTC <- VK * VPTCC            # Zhang 2024 SI code (human): VPTC = VK * VPTCC

    # =====================================================================
    # 4. Fetal gestational growth equations (Zhang 2024 Table S6, fetus)
    # =====================================================================
    Htc_Fet   <- (4.5061 * GA - 0.18487 * GA^2 + 0.0026766 * GA^3) / 100
    VFet      <- (0.0018282 * exp(15.12691 * (1 - exp(-0.077577 * GA)))) / 1000
    VPlas_Fet <- VPlasC_Fet * VFet
    VL_Fet    <- (0.0075 * exp(10.68 * (1 - exp(-0.062 * GA)))) / 1050
    VB_Fet    <- ((0.01574 * exp(10.91 * (1 - exp(-0.065 * GA)))) / 1040) / 1000
    VRest_Fet <- 0.93 * VFet - VPlas_Fet - VL_Fet - VB_Fet
    # As published, the Table S6 growth equations make the fetal
    # rest-of-body volume NEGATIVE before GA 3.5 weeks, because the fetal
    # liver and brain equations are non-zero at GA 0 while whole-fetus
    # volume is still ~2 mg. A negative volume makes the fetal
    # concentrations diverge and the solver fail. Floor it at 1e-9 L. The
    # window is physiologically inert: placental blood flow is zero until
    # GA 3.6 weeks and the placental transfer clearances scale as
    # VFet^0.75, so no F-53B can reach the fetus before the floor stops
    # binding. See the vignette Errata.
    if (VRest_Fet < 1e-9) {
      VRest_Fet <- 1e-9
    }

    # Fetal plasma flows (L/h). The 54 mL/kg fetal cardiac index and the
    # 6.5/54, 26.5/75 and 14.3/75 fractional splits are the Kapraun 2019
    # values used in the SI code.
    QC_Fet    <- 54 * VPlas_Fet * (1 - Htc_Fet)
    QL_Fet    <- (6.5 / 54) * (1 - 26.5 / 75) * QC_Fet
    QB_Fet    <- (14.3 / 75) * QC_Fet
    QRest_Fet <- QC_Fet - QL_Fet - QB_Fet

    # =====================================================================
    # 5. Gestational body weight, remaining volume and blood flows
    # =====================================================================
    BW_P  <- WT + (VF_P - VF_0) + (VM_P - VM_0) + VPla + VFet + VAm
    VRest <- 0.93 * BW_P - (VL + VK + VM_P + VF_P + VPlas + VPla + VFet + VAm)

    QC_0 <- QCC * WT^0.75 * (1 - Htc)
    QC   <- QC_0 + 3.2512 * GA + 0.15947 * GA^2 - 0.0047059 * GA^3
    QF_P <- 0.01 * (8.5 - 0.0175 * GA) * QC
    QK_P <- 0.01 * (17 - 0.01 * GA) * QC
    QL_P <- 0.01 * (27 - 0.175 * GA) * QC
    QM   <- QMC * QC_0
    QM_P <- QM * (VM_P / VM_0)

    QPla <- 0
    if (GA >= 3.6) {
      QPla <- 0.00022 * (GA - 3.6) * (0.4 + 0.29 * GA) * QC
    }
    QRest <- QC - (QK_P + QL_P + QM_P + QF_P + QPla)

    # =====================================================================
    # 6. Allometrically scaled kinetic parameters
    # =====================================================================
    GE     <- GEC * BW_P^(-0.25)
    K0     <- K0C * BW_P^(-0.25)
    Kbile  <- KbileC * BW_P^(-0.25)
    Kurine <- KurineC * BW_P^(-0.25)
    Kabs   <- KabsC * BW_P^(-0.25)
    Kunabs <- KunabsC * BW_P^(-0.25)

    PTC          <- VKC * 6e7 * 1000
    Vmax_basoC   <- Vmax_baso_invitro * RAFbaso * PTC * protein * 60 * (MW / 1e12) * 1000
    Vmax_apicalC <- Vmax_apical_invitro * RAFapi * PTC * protein * 60 * (MW / 1e12) * 1000
    Vmax_baso    <- Vmax_basoC * BW_P^0.75
    Vmax_apical  <- Vmax_apicalC * BW_P^0.75
    Kefflux      <- KeffluxC * BW_P^(-0.25)

    # Single fetus: no litter-size multiplier (contrast with the mouse
    # model, where these are multiplied by N).
    Ktrans_1 <- Ktrans1C * VFet^0.75
    Ktrans_2 <- Ktrans2C * VFet^0.75
    Ktrans_3 <- Ktrans3C * VFet^0.75
    Ktrans_4 <- Ktrans4C * VFet^0.75

    # =====================================================================
    # 7. Concentrations
    # =====================================================================
    CPlas_free <- plasma / VPlas
    CPlas      <- CPlas_free / fu
    CL         <- liver / VL
    CVL        <- CL / PL
    CKb        <- kidney_blood / VKb
    CVK        <- CKb
    CKid       <- CKb * PK
    CM         <- mammary / VM_P
    CVM        <- CM / PM
    CF         <- fat / VF_P
    CVF        <- CF / PF
    CRest      <- rest / VRest
    CVRest     <- CRest / PRest
    CPTC       <- ptc / VPTC
    CFil       <- filtrate / VFil
    CPla       <- placenta / (VPla + 1e-10)
    CVPla      <- CPla / PPla
    CAm        <- amniotic / (VAm + 1e-10)

    CPlas_Fet_free <- plasma_fet / (VPlas_Fet + 1e-10)
    CPlas_Fet      <- CPlas_Fet_free / fu_fet
    CRest_Fet      <- rest_fet / (VRest_Fet + 1e-10)
    CVRest_Fet     <- CRest_Fet / PRest_Fet
    CL_Fet         <- liver_fet / (VL_Fet + 1e-10)
    CVL_Fet        <- CL_Fet / PL_Fet
    CB_Fet         <- brain_fet / (VB_Fet + 1e-10)
    CVB_Fet        <- CB_Fet / PB_Fet

    # =====================================================================
    # 8. Renal, biliary and placental fluxes (mg/h)
    #    Michaelis-Menten terms written with the state expression INLINE:
    #    a named intermediate that reads an ODE state can silently
    #    evaluate to zero inside d/dt() in the nlmixr2 model-function form.
    # =====================================================================
    RA_baso   <- Vmax_baso * (kidney_blood / VKb) / (Km_baso + kidney_blood / VKb)
    RA_apical <- Vmax_apical * (filtrate / VFil) / (Km_apical + filtrate / VFil)
    Rdif      <- Kdif * (CKb - CPTC)
    RAefflux  <- Kefflux * ptc
    RCI       <- CPlas * GFR * fu

    # In the human model Rtrans_2 is driven by the FETAL free fraction
    # (Zhang 2024 SI code, human); the mouse model uses the maternal free
    # fraction in the same term. Both are replicated as published.
    Rtrans_1 <- Ktrans_1 * CVPla * fu
    Rtrans_2 <- Ktrans_2 * CPlas_Fet * fu_fet
    Rtrans_3 <- Ktrans_3 * CVRest_Fet * fu_fet
    Rtrans_4 <- Ktrans_4 * CAm

    # =====================================================================
    # 9. Mass-balance ODEs
    # =====================================================================
    d/dt(stomach)   <- -K0 * stomach - GE * stomach
    d/dt(intestine) <- GE * stomach - Kabs * intestine - Kunabs * intestine

    d/dt(liver)   <- QL_P * (CPlas - CVL) * fu - Kbile * liver +
                     Kabs * intestine + K0 * stomach
    d/dt(fat)     <- QF_P * (CPlas - CVF) * fu
    d/dt(mammary) <- QM_P * (CPlas - CVM) * fu
    d/dt(rest)    <- QRest * (CPlas - CVRest) * fu

    d/dt(kidney_blood) <- QK_P * (CPlas - CVK) * fu - RCI - Rdif - RA_baso
    d/dt(ptc)          <- Rdif + RA_apical + RA_baso - RAefflux
    d/dt(filtrate)     <- RCI - RA_apical - Kurine * filtrate

    d/dt(placenta) <- QPla * (CPlas - CVPla) * fu + Rtrans_2 - Rtrans_1

    d/dt(plasma) <- QRest * CVRest * fu + QK_P * CVK * fu + QL_P * CVL * fu +
                    QM_P * CVM * fu + QF_P * CVF * fu + QPla * CVPla * fu -
                    QC * CPlas * fu + RAefflux

    d/dt(urine) <- Kurine * filtrate
    d/dt(feces) <- Kbile * liver + Kunabs * intestine

    d/dt(liver_fet) <- QL_Fet * (CPlas_Fet - CVL_Fet) * fu_fet
    d/dt(brain_fet) <- QB_Fet * (CPlas_Fet - CVB_Fet) * fu_fet
    d/dt(rest_fet)  <- QRest_Fet * (CPlas_Fet - CVRest_Fet) * fu_fet -
                       Rtrans_3 + Rtrans_4
    d/dt(plasma_fet) <- QRest_Fet * CVRest_Fet * fu_fet +
                        QL_Fet * CVL_Fet * fu_fet +
                        QB_Fet * CVB_Fet * fu_fet -
                        QC_Fet * CPlas_Fet * fu_fet + Rtrans_1 - Rtrans_2
    d/dt(amniotic)  <- Rtrans_3 - Rtrans_4

    d/dt(trans_mf) <- Rtrans_1
    d/dt(trans_fm) <- Rtrans_2

    # =====================================================================
    # 10. Observations
    # =====================================================================
    Cc          <- CPlas       # maternal plasma, total concentration (mg/L)
    Cplasma_fet <- CPlas_Fet   # fetal plasma == cord blood (mg/L)
    Cliver      <- CL
    Cplacenta   <- CPla
    Cbrain_fet  <- CB_Fet
    Cliver_fet  <- CL_Fet
    Camniotic   <- CAm
    Ckidney     <- CKid
    Cfat        <- CF
    Cmammary    <- CM
    Crest       <- CRest
    Crest_fet   <- CRest_Fet

    Cc          ~ prop(propSd)
    Cplasma_fet ~ prop(propSd_Cplasma_fet)
  })
}
