Schoning_2026_oral1cmt_groundtruth <- function() {
  description <- paste(
    "Methodology reference. Ground-truth (data-generating) one-compartment",
    "oral population PK model for a HYPOTHETICAL drug, from Schoning 2026,",
    "the proof-of-concept study on augmenting popPK data sets with artificial",
    "patients generated by a Wasserstein GAN with gradient penalty (WGAN-GP).",
    "There is no real molecule and no real patients: the authors DEFINED these",
    "population parameters, simulated 20 synthetic adults given a single 300 mg",
    "extravascular dose, and then used the simulated profiles as the training",
    "set for the WGAN-GP. Every value here is therefore an author-chosen",
    "constant, not an estimate, and all are encoded with fixed().",
    "Structure is first-order absorption into a depot, one-compartment",
    "distribution and linear elimination, with body weight on central volume",
    "as an allometric term referenced to 70 kg and a coefficient of 0.75.",
    "Residual error is Monolix combined1, i.e. the residual standard deviation",
    "is addSd + propSd * Cc, NOT the nlmixr2 default combined2 root-sum-square;",
    "the combined1() modifier in the error line preserves the published form.",
    "This model is the reference against which the five fitted companions",
    "(Schoning_2026_oral1cmt_original, _artificial, _combinedlow,",
    "_combinedequal and _combinedhigh) are compared in the vignette.",
    sep = " "
  )
  reference <- paste(
    "Schoning V, Hammann F. Improving Population Pharmacokinetic Modelling",
    "with Artificial Patients using Generative Artificial Intelligence.",
    "Pharmacol Res Perspect. 2026;14(3):e70241.",
    "doi:10.1002/prp2.70241. PMCID PMC13052321.",
    "Ground-truth structure and parameter values transcribed from the authors'",
    "own RsSimulx inlineModel and parameter data frame in the deposited code",
    "base at https://github.com/cptbern/WGAN_PopPK",
    "(Scripts/WGAN_R.Rmd), which the paper cites as its supplementary source;",
    "the same values appear in the paper's Table 1 'Ground truth' column.",
    sep = " "
  )
  vignette <- "Schoning_2026_oral1cmt_wgan"
  units    <- list(time = "h", dosing = "mg", concentration = "mg/L")

  # Issue #482: what each ODE state holds, in what amount units, in what
  # biological matrix. Verified against Schoning 2026 section 2.2, which
  # specifies extravascular administration of a hypothetical drug with
  # first-order absorption, one-compartment distribution and linear
  # elimination, and against the deposited RsSimulx model, which builds the
  # profile with pkmodel(ka, V, Cl). The analyte has no name because the drug
  # is hypothetical.
  compartmentData <- list(
    depot = list(
      analyte = "hypothetical drug", units = "mg",
      specimen = "administration site", verified = TRUE
    ),
    central = list(
      analyte = "hypothetical drug", units = "mg",
      specimen = "whole blood", verified = TRUE
    )
  )

  covariateData <- list(
    WT = list(
      description        = "Body weight",
      units              = "kg",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "The only covariate carried in the PK model. Enters central volume as",
        "(WT/70)^0.75. The 70 kg reference is NOT stated in the paper text or",
        "Table 1; it is read from the deposited RsSimulx [COVARIATE] block,",
        "which defines logWT = log(WT) - log(70).",
        sep = " "
      ),
      source_name        = "WT"
    )
  )

  # Simulated demographics that the authors generated and handed to the
  # WGAN-GP as patient characteristics, but which were never tested as
  # covariates in the popPK model itself. Documented here so the provenance of
  # the synthetic cohort is preserved without creating unused-covariate
  # warnings.
  covariatesDataExcluded <- list(
    SEXF = list(
      description = "Female sex indicator (1 = female, 0 = male)",
      units       = "(binary)",
      type        = "categorical",
      notes       = paste(
        "Balanced 10 female / 10 male by construction (section 2.2). Used to",
        "condition the simulated weight and height distributions and supplied",
        "to the WGAN-GP one-hot encoded, but never entered the popPK model.",
        sep = " "
      ),
      source_name = "sex"
    ),
    AGE = list(
      description = "Age",
      units       = "years",
      type        = "continuous",
      notes       = paste(
        "Supplied to the WGAN-GP but never entered the popPK model. The paper",
        "text (section 2.2) states a range of 18 to 65 years while the",
        "deposited generator draws runif(20, 18, 60); see the vignette Errata.",
        sep = " "
      ),
      source_name = "AGE"
    ),
    HT = list(
      description = "Height",
      units       = "cm",
      type        = "continuous",
      notes       = paste(
        "Supplied to the WGAN-GP but never entered the popPK model.",
        "Normally distributed with mean 164 cm (female) and 179 cm (male),",
        "SD 7 cm (section 2.2).",
        sep = " "
      ),
      source_name = "HT"
    )
  )

  population <- list(
    species        = "None (methodology paper; a hypothetical drug simulated in 20 synthetic adult subjects, not a fit of any real molecule).",
    n_subjects     = 20L,
    n_studies      = 1L,
    age_range      = "18-65 years per section 2.2 text; the deposited generator draws runif(20, 18, 60), so the simulated cohort spans 18-60 years.",
    weight_range   = "Normally distributed, mean 64 kg (female) and 85 kg (male), SD 10 kg (section 2.2).",
    sex_female_pct = 50,
    disease_state  = "N/A (Monte Carlo simulation study).",
    dose_range     = "Single 300 mg extravascular dose at time 0 (section 2.2).",
    regions        = "N/A",
    scope_note     = paste(
      "Filed under inst/modeldb/pharmacokinetics/ rather than specificDrugs/",
      "because there is no drug: this follows the precedent set by",
      "Beal_2001_iv1cmt_bql, the other methodology-reference toy model in the",
      "library. The file stem uses the structural descriptor oral1cmt in the",
      "slot where a drug name would normally go, again as Beal_2001 does with",
      "iv1cmt.",
      sep = " "
    ),
    notes          = paste(
      "Sampling times 0.5, 1, 1.5, 2, 4, 6, 8 and 12 h after the dose;",
      "concentrations below 0.5 mg/L were censored as BLQ (section 2.2).",
      "The first author's surname is published with an o-diaeresis; the",
      "diaeresis is stripped for the ASCII file stem, following the existing",
      "Muller_2007_penicillin_G convention.",
      sep = " "
    )
  )

  ini({
    # All values are author-defined simulation constants (Table 1 'Ground
    # truth' column; deposited cmt1_oa.model2.params data frame), so every
    # one is fixed() rather than estimated.
    lka <- fixed(log(0.5)); label("Absorption rate constant (1/h)")        # Table 1 ground truth ka_pop = 0.5; deposit ka_pop = 0.5
    lvc <- fixed(log(14));  label("Central volume of distribution (L)")    # Table 1 ground truth V_pop = 14.0; deposit V_pop = 14
    lcl <- fixed(log(5));   label("Clearance (L/h)")                       # Table 1 ground truth Cl_pop = 5.0; deposit CL_pop = 5

    e_wt_vc <- fixed(0.75); label("Coefficient of log body weight on central volume (unitless)")  # Table 1 ground truth 0.75; deposit coefficient=0.75 on logWT

    # Monolix reports lognormal IIV as sd on the log scale, so variance is
    # the square of the Table 1 value.
    etalka ~ fixed(0.04)  # variance = 0.2^2; Table 1 ground truth ka IIV = 0.2; deposit ka_sd = 0.2
    etalvc ~ fixed(0.09)  # variance = 0.3^2; Table 1 ground truth V IIV = 0.3; deposit V_sd = 0.3
    etalcl ~ fixed(0.04)  # variance = 0.2^2; Table 1 ground truth Cl IIV = 0.2; deposit CL_sd = 0.2

    addSd  <- fixed(0.2); label("Additive residual error (mg/L)")        # Table 1 ground truth additive error a = 0.2; deposit add = 0.2
    propSd <- fixed(0.1); label("Proportional residual error (fraction)")  # Table 1 ground truth proportional error b = 0.1; deposit prop = 0.1
  })

  model({
    ka <- exp(lka + etalka)
    vc <- exp(lvc + etalvc) * (WT / 70)^e_wt_vc  # deposit: logWT = log(WT) - log(70), coefficient 0.75 on log V
    cl <- exp(lcl + etalcl)
    kel <- cl / vc

    d/dt(depot)   <- -ka * depot
    d/dt(central) <-  ka * depot - kel * central

    Cc <- central / vc
    # Monolix errorModel=combined1(add, prop): sd = addSd + propSd * Cc.
    Cc ~ add(addSd) + prop(propSd) + combined1()
  })
}
