Schoning_2026_oral1cmt_combinedhigh <- function() {
  description <- paste(
    "Methodology reference. One-compartment oral population PK model for a",
    "HYPOTHETICAL drug, fitted to the Combined-high data set of Schoning 2026,",
    "the proof-of-concept study on augmenting popPK data sets with artificial",
    "patients generated by a Wasserstein GAN with gradient penalty (WGAN-GP).",
    "There is no real molecule and no real patients. The authors defined a",
    "ground-truth model (see Schoning_2026_oral1cmt_groundtruth), simulated 20",
    "synthetic adults from it, trained a WGAN-GP on those profiles, and then",
    "re-estimated the same structural model from five data sets mixing original",
    "and artificial patients in different proportions. This file carries the",
    "Combined-high arm: 20 original and 40 artificial patients, 60 in total",
    "(Table 2).",
    "Fitted to the 20 original patients plus 40 artificial patients (Table 2), the most heavily augmented arm. It yields the largest weight coefficient of the five (0.85 against a ground truth of 0.75), which is the 'accentuated' allometric effect the abstract reports.",
    "Structure is first-order absorption into a depot, one-compartment",
    "distribution and linear elimination, with body weight on central volume",
    "as an allometric term referenced to 70 kg. Residual error is Monolix",
    "combined1, i.e. the residual standard deviation is addSd + propSd * Cc,",
    "NOT the nlmixr2 default combined2 root-sum-square.",
    "All values are Monolix 2024R1 point estimates from the paper Table 1;",
    "the bootstrap median and 95% CI (n = 200) for each are recorded in the",
    "per-parameter source-trace comments.",
    sep = " "
  )
  reference <- paste(
    "Schoning V, Hammann F. Improving Population Pharmacokinetic Modelling",
    "with Artificial Patients using Generative Artificial Intelligence.",
    "Pharmacol Res Perspect. 2026;14(3):e70241.",
    "doi:10.1002/prp2.70241. PMCID PMC13052321.",
    "Parameter estimates from Table 1, column 'Combined-high'.",
    "The structural form and the 70 kg weight reference are taken from the",
    "authors' deposited RsSimulx model at",
    "https://github.com/cptbern/WGAN_PopPK (Scripts/WGAN_R.Rmd).",
    sep = " "
  )
  vignette <- "Schoning_2026_oral1cmt_wgan"
  units    <- list(time = "h", dosing = "mg", concentration = "mg/L")

  # Issue #482: what each ODE state holds, in what amount units, in what
  # biological matrix. Verified against Schoning 2026 section 2.2 (a
  # hypothetical drug given extravascularly, with first-order absorption,
  # one-compartment distribution and linear elimination) and the deposited
  # RsSimulx model, which builds the profile with pkmodel(ka, V, Cl).
  compartmentData <- list(
    depot = list(
      analyte = "hypothetical drug", units = "mg",
      specimen = "administration site", verified = TRUE
    ),
    central = list(
      analyte = "hypothetical drug", units = "mg",
      specimen = "whole blood", verified = TRUE
    )
  )

  covariateData <- list(
    WT = list(
      description        = "Body weight",
      units              = "kg",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "The only covariate carried in the PK model. Enters central volume as",
        "(WT/70)^e_wt_vc. The 70 kg reference is NOT stated in the paper text",
        "or Table 1; it is read from the deposited RsSimulx [COVARIATE] block,",
        "which defines logWT = log(WT) - log(70), and is assumed to have been",
        "kept for the fitted models.",
        sep = " "
      ),
      source_name        = "WT"
    )
  )

  # Demographics handed to the WGAN-GP as patient characteristics but never
  # tested as covariates in the popPK model itself.
  covariatesDataExcluded <- list(
    SEXF = list(
      description = "Female sex indicator (1 = female, 0 = male)",
      units       = "(binary)",
      type        = "categorical",
      notes       = "Supplied to the WGAN-GP one-hot encoded; never entered the popPK model.",
      source_name = "sex"
    ),
    AGE = list(
      description = "Age",
      units       = "years",
      type        = "continuous",
      notes       = "Supplied to the WGAN-GP; never entered the popPK model.",
      source_name = "AGE"
    ),
    HT = list(
      description = "Height",
      units       = "cm",
      type        = "continuous",
      notes       = "Supplied to the WGAN-GP; never entered the popPK model.",
      source_name = "HT"
    )
  )

  population <- list(
    species        = "None (methodology paper; a hypothetical drug in synthetic subjects, not a fit of any real molecule).",
    n_subjects     = 60L,
    n_studies      = 1L,
    age_range      = "18-65 years per section 2.2 text; the deposited generator draws runif(20, 18, 60) for the original patients.",
    weight_range   = "Original patients normally distributed, mean 64 kg (female) and 85 kg (male), SD 10 kg (section 2.2); artificial patients drawn from the WGAN-GP.",
    sex_female_pct = 50,
    disease_state  = "N/A (Monte Carlo simulation study).",
    dose_range     = "Single 300 mg extravascular dose at time 0 (section 2.2).",
    regions        = "N/A",
    n_original_patients   = 20L,
    n_artificial_patients = 40L,
    scope_note     = paste(
      "Filed under inst/modeldb/pharmacokinetics/ rather than specificDrugs/",
      "because there is no drug, following the precedent set by",
      "Beal_2001_iv1cmt_bql.",
      "This is one of five fitted arms extracted from Table 1; the sixth file,",
      "Schoning_2026_oral1cmt_groundtruth, carries the data-generating model.",
      sep = " "
    ),
    notes          = paste(
      "Sampling times 0.5, 1, 1.5, 2, 4, 6, 8 and 12 h after the dose;",
      "concentrations below 0.5 mg/L were censored as BLQ (section 2.2).",
      "Estimation in Monolix 2024R1 with a non-parametric bootstrap of 200",
      "replicates (section 2.4).",
      sep = " "
    )
  )

  ini({
    lka <- log(0.52); label("Absorption rate constant (1/h)")      # Table 1 Combined-high: 0.52 [bootstrap 0.54, 0.36-0.65]
    lvc <- log(15.92); label("Central volume of distribution (L)")  # Table 1 Combined-high: 15.92 [bootstrap 16.33, 11.53-19.25]
    lcl <- log(5.06); label("Clearance (L/h)")                     # Table 1 Combined-high: 5.06 [bootstrap 5.05, 4.78-5.34]

    e_wt_vc <- 0.85; label("Coefficient of log body weight on central volume (unitless)")  # Table 1 Combined-high: 0.85 [bootstrap 0.72, 0.10-1.34]

    # Monolix reports lognormal IIV as sd on the log scale, so the variance
    # below is the square of the Table 1 value.
    etalka ~ 0.0784  # variance = 0.28^2; Table 1 Combined-high ka IIV [bootstrap 0.24, 0.10-0.38]
    etalvc ~ 0.0576  # variance = 0.24^2; Table 1 Combined-high V IIV [bootstrap 0.27, 0.10-0.35]
    etalcl ~ 0.0324  # variance = 0.18^2; Table 1 Combined-high Cl IIV [bootstrap 0.17, 0.14-0.2]

    addSd  <- 0.49; label("Additive residual error (mg/L)")          # Table 1 Combined-high additive error a: 0.49 [bootstrap 0.5, 0.34-0.63]
    propSd <- 0.052; label("Proportional residual error (fraction)")  # Table 1 Combined-high proportional error b: 0.052 [bootstrap 0.051, 0.029-0.077]
  })

  model({
    ka <- exp(lka + etalka)
    vc <- exp(lvc + etalvc) * (WT / 70)^e_wt_vc  # deposit: logWT = log(WT) - log(70)
    cl <- exp(lcl + etalcl)
    kel <- cl / vc

    d/dt(depot)   <- -ka * depot
    d/dt(central) <-  ka * depot - kel * central

    Cc <- central / vc
    # Monolix errorModel=combined1(add, prop): sd = addSd + propSd * Cc.
    Cc ~ add(addSd) + prop(propSd) + combined1()
  })
}

