Schoning_2026_oral1cmt_artificial <- function() {
  description <- paste(
    "Methodology reference. One-compartment oral population PK model for a",
    "HYPOTHETICAL drug, fitted to the Artificial data set of Schoning 2026,",
    "the proof-of-concept study on augmenting popPK data sets with artificial",
    "patients generated by a Wasserstein GAN with gradient penalty (WGAN-GP).",
    "There is no real molecule and no real patients. The authors defined a",
    "ground-truth model (see Schoning_2026_oral1cmt_groundtruth), simulated 20",
    "synthetic adults from it, trained a WGAN-GP on those profiles, and then",
    "re-estimated the same structural model from five data sets mixing original",
    "and artificial patients in different proportions. This file carries the",
    "Artificial arm: 0 original and 60 artificial patients, 60 in total",
    "(Table 2).",
    "Fitted to 60 WGAN-GP artificial patients and NO original patients, so every observation behind these estimates is synthetic. The weight coefficient recovers to 0.73 against a ground truth of 0.75 and its bootstrap interval excludes zero.",
    "Structure is first-order absorption into a depot, one-compartment",
    "distribution and linear elimination, with body weight on central volume",
    "as an allometric term referenced to 70 kg. Residual error is Monolix",
    "combined1, i.e. the residual standard deviation is addSd + propSd * Cc,",
    "NOT the nlmixr2 default combined2 root-sum-square.",
    "All values are Monolix 2024R1 point estimates from the paper Table 1;",
    "the bootstrap median and 95% CI (n = 200) for each are recorded in the",
    "per-parameter source-trace comments.",
    sep = " "
  )
  reference <- paste(
    "Schoning V, Hammann F. Improving Population Pharmacokinetic Modelling",
    "with Artificial Patients using Generative Artificial Intelligence.",
    "Pharmacol Res Perspect. 2026;14(3):e70241.",
    "doi:10.1002/prp2.70241. PMCID PMC13052321.",
    "Parameter estimates from Table 1, column 'Artificial'.",
    "The structural form and the 70 kg weight reference are taken from the",
    "authors' deposited RsSimulx model at",
    "https://github.com/cptbern/WGAN_PopPK (Scripts/WGAN_R.Rmd).",
    sep = " "
  )
  vignette <- "Schoning_2026_oral1cmt_wgan"
  units    <- list(time = "h", dosing = "mg", concentration = "mg/L")

  # Issue #482: what each ODE state holds, in what amount units, in what
  # biological matrix. Verified against Schoning 2026 section 2.2 (a
  # hypothetical drug given extravascularly, with first-order absorption,
  # one-compartment distribution and linear elimination) and the deposited
  # RsSimulx model, which builds the profile with pkmodel(ka, V, Cl).
  compartmentData <- list(
    depot = list(
      analyte = "hypothetical drug", units = "mg",
      specimen = "administration site", verified = TRUE
    ),
    central = list(
      analyte = "hypothetical drug", units = "mg",
      specimen = "whole blood", verified = TRUE
    )
  )

  covariateData <- list(
    WT = list(
      description        = "Body weight",
      units              = "kg",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "The only covariate carried in the PK model. Enters central volume as",
        "(WT/70)^e_wt_vc. The 70 kg reference is NOT stated in the paper text",
        "or Table 1; it is read from the deposited RsSimulx [COVARIATE] block,",
        "which defines logWT = log(WT) - log(70), and is assumed to have been",
        "kept for the fitted models.",
        sep = " "
      ),
      source_name        = "WT"
    )
  )

  # Demographics handed to the WGAN-GP as patient characteristics but never
  # tested as covariates in the popPK model itself.
  covariatesDataExcluded <- list(
    SEXF = list(
      description = "Female sex indicator (1 = female, 0 = male)",
      units       = "(binary)",
      type        = "categorical",
      notes       = "Supplied to the WGAN-GP one-hot encoded; never entered the popPK model.",
      source_name = "sex"
    ),
    AGE = list(
      description = "Age",
      units       = "years",
      type        = "continuous",
      notes       = "Supplied to the WGAN-GP; never entered the popPK model.",
      source_name = "AGE"
    ),
    HT = list(
      description = "Height",
      units       = "cm",
      type        = "continuous",
      notes       = "Supplied to the WGAN-GP; never entered the popPK model.",
      source_name = "HT"
    )
  )

  population <- list(
    species        = "None (methodology paper; a hypothetical drug in synthetic subjects, not a fit of any real molecule).",
    n_subjects     = 60L,
    n_studies      = 1L,
    age_range      = "18-65 years per section 2.2 text; the deposited generator draws runif(20, 18, 60) for the original patients.",
    weight_range   = "Original patients normally distributed, mean 64 kg (female) and 85 kg (male), SD 10 kg (section 2.2); artificial patients drawn from the WGAN-GP.",
    sex_female_pct = 50,
    disease_state  = "N/A (Monte Carlo simulation study).",
    dose_range     = "Single 300 mg extravascular dose at time 0 (section 2.2).",
    regions        = "N/A",
    n_original_patients   = 0L,
    n_artificial_patients = 60L,
    scope_note     = paste(
      "Filed under inst/modeldb/pharmacokinetics/ rather than specificDrugs/",
      "because there is no drug, following the precedent set by",
      "Beal_2001_iv1cmt_bql.",
      "This is one of five fitted arms extracted from Table 1; the sixth file,",
      "Schoning_2026_oral1cmt_groundtruth, carries the data-generating model.",
      sep = " "
    ),
    notes          = paste(
      "Sampling times 0.5, 1, 1.5, 2, 4, 6, 8 and 12 h after the dose;",
      "concentrations below 0.5 mg/L were censored as BLQ (section 2.2).",
      "Estimation in Monolix 2024R1 with a non-parametric bootstrap of 200",
      "replicates (section 2.4).",
      sep = " "
    )
  )

  ini({
    lka <- log(0.55); label("Absorption rate constant (1/h)")      # Table 1 Artificial: 0.55 [bootstrap 0.54, 0.35-0.65]
    lvc <- log(16.86); label("Central volume of distribution (L)")  # Table 1 Artificial: 16.86 [bootstrap 16.51, 10.92-19.75]
    lcl <- log(5.02); label("Clearance (L/h)")                     # Table 1 Artificial: 5.02 [bootstrap 5.05, 4.75-5.28]

    e_wt_vc <- 0.73; label("Coefficient of log body weight on central volume (unitless)")  # Table 1 Artificial: 0.73 [bootstrap 0.77, 0.065-1.29]

    # Monolix reports lognormal IIV as sd on the log scale, so the variance
    # below is the square of the Table 1 value.
    etalka ~ 0.0169  # variance = 0.13^2; Table 1 Artificial ka IIV [bootstrap 0.21, 0.079-0.35]
    etalvc ~ 0.0961  # variance = 0.31^2; Table 1 Artificial V IIV [bootstrap 0.26, 0.11-0.34]
    etalcl ~ 0.0256  # variance = 0.16^2; Table 1 Artificial Cl IIV [bootstrap 0.16, 0.13-0.19]

    addSd  <- 0.51; label("Additive residual error (mg/L)")          # Table 1 Artificial additive error a: 0.51 [bootstrap 0.5, 0.34-0.65]
    propSd <- 0.049; label("Proportional residual error (fraction)")  # Table 1 Artificial proportional error b: 0.049 [bootstrap 0.05, 0.024-0.076]
  })

  model({
    ka <- exp(lka + etalka)
    vc <- exp(lvc + etalvc) * (WT / 70)^e_wt_vc  # deposit: logWT = log(WT) - log(70)
    cl <- exp(lcl + etalcl)
    kel <- cl / vc

    d/dt(depot)   <- -ka * depot
    d/dt(central) <-  ka * depot - kel * central

    Cc <- central / vc
    # Monolix errorModel=combined1(add, prop): sd = addSd + propSd * Cc.
    Cc ~ add(addSd) + prop(propSd) + combined1()
  })
}

