Karlsson_2010_acute_stroke_nihss <- function() {
  description <- paste0(
    "Drug-free disease-progression model for the National Institutes of ",
    "Health Stroke Scale (NIHSS, 0-42 points, LOWER is better) in acute ",
    "stroke, fitted to the placebo arm of the CLASS-I trial (Karlsson ",
    "2010, n = 580). Five submodels are fitted simultaneously: three ",
    "logit probability submodels for improvement versus decline ",
    "(p_improve), failure to reach the maximum/fully-recovered score ",
    "(p_notmax) and dropout (p_dropout), plus two continuous submodels ",
    "for the relative magnitude of an improvement (imz) or a decline ",
    "(dez) on the logit scale. The relative magnitudes are mapped back ",
    "to the raw NIHSS by the authors' reconstruction rules ",
    "nihss_improve = (1 - imz) * (SCORE_NIHSS_PREV + 1) and ",
    "nihss_decline = dez * (42 - SCORE_NIHSS_PREV) + SCORE_NIHSS_PREV. ",
    "Dropout is INFORMATIVE: its logit enters proportionally as ",
    "logitp_dropout * (1 + slope_score_p_dropout * nihss_decline), so ",
    "the probability of dropping out rises with the model-predicted ",
    "declined score. Break points on days since stroke: the relative ",
    "improvement intercept and all four IIV terms switch at day 14, the ",
    "p_notmax intercept at day 45, and the dropout intercept over three ",
    "intervals (<= 14, 14-45, > 45 days). There is no PK layer and no ",
    "ODE: the source is a NONMEM $PRED model whose Markovian ",
    "predictors (previous score, baseline score, time since the ",
    "previous observation) are supplied as data columns, so a ",
    "trajectory is generated by drawing the probabilistic events at ",
    "each visit and carrying the reconstructed score forward (see the ",
    "vignette). Companion Barthel Index model in ",
    "Karlsson_2010_acute_stroke_bi."
  )
  reference <- paste(
    "Karlsson KE, Wilkins JJ, Jonsson F, Zingmark PH, Karlsson MO, Jonsson EN.",
    "Modeling disease progression in acute stroke using clinical assessment scales.",
    "AAPS J. 2010;12(4):683-692. doi:10.1208/s12248-010-9230-0.",
    "Final parameter estimates from Supplement A (NIHSS table);",
    "model structure from the Supplement B NONMEM control stream",
    "for the NIH Stroke Scale model.",
    sep = " "
  )
  vignette <- "Karlsson_2010_acute_stroke"
  units <- list(
    time          = "day (days since the stroke event; the source NONMEM DAY / TSS column)",
    dosing        = "n/a (no dose events; drug-free placebo-arm disease-progression model)",
    concentration = "NIHSS points (0-42) for nihss_improve / nihss_decline; unitless 0-1 for imz, dez and the three probabilities"
  )

  covariateData <- list(
    AGE = list(
      description        = "Age at study entry.",
      units              = "years",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Centred at 73 years inside model(), matching the source control stream `A1AGE = THETA(12)*(AGE-73)`. Analysis-set mean 71.7 years, range 26-90 (Karlsson 2010 Methods, Patients and Data). The source dataset used AGE = -99 as a missing-value code; that NONMEM data convention is NOT reproduced here -- supply a real age.",
      source_name        = "AGE"
    ),
    SCORE_NIHSS = list(
      description        = "Baseline (admission) NIHSS total score on the RAW 0-42 scale, where 0 is normal and 42 is maximal deficit. Time-fixed per subject.",
      units              = "(NIHSS points, 0-42)",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Source column BNH, which maps to the `BASE` column of the Supplement B dataset excerpt (raw, not the reversed `cBASE = 42 - BASE`). Enters the relative-improvement magnitude submodel only. Analysis-set mean 16.8, range 4-31 (Karlsson 2010 Methods). Not centred in the source stream.",
      source_name        = "BNH"
    ),
    SCORE_NIHSS_PREV = list(
      description        = "NIHSS total score recorded at the immediately preceding observation occasion, on the RAW 0-42 scale. The Markov-state predictor that conditions the current occasion's transition probabilities and score reconstruction.",
      units              = "(NIHSS points, 0-42)",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Source column PNH, mapping to `PNIH` in the Supplement B dataset excerpt (raw, not reversed: in the excerpt subject 1 has BASE = 17 and PNIH = 17 at day 7, then PNIH = 23 at day 29 after a day-7 score of 23). At the first modelled occasion set SCORE_NIHSS_PREV to the admission score (= SCORE_NIHSS). Enters p_notmax, the relative-decline magnitude submodel, and both reconstruction rules. Not centred in the source stream.",
      source_name        = "PNH"
    ),
    T_PREVOBS = list(
      description        = "Time elapsed since the subject's previous observation occasion.",
      units              = "day",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Source column TLS. The Supplement B dataset legend calls TLS 'Time since start of study (i.e. time since stroke)', but the tabulated data falsify that label and the value is time since the PREVIOUS observation: subject 2 has DAY 8 -> TLS 7, DAY 33 -> TLS 25 (= 33 - 8), DAY 62 -> TLS 29 (= 62 - 33), and in the BI excerpt TLS is non-monotonic in DAY, which time-since-stroke cannot be. Corroborated by Karlsson 2010 Table II, which lists 'Influence of time since previous observation' for this term and lists 'Influence of time since baseline' separately (that second clock is TSS = DAY, carried here by rxode2's `time`). Not centred in the source stream.",
      source_name        = "TLS"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 580L,
    n_studies      = 1L,
    n_observations = "NIHSS assessed at admission and on days 7, 30 and 90; one imputed record was added for subjects whose observations ended before the day-90 endpoint, placed halfway between the last measured observation and the next intended appointment, to inform the dropout submodel (Karlsson 2010 Data Preparation)",
    age_range      = "mean 71.7 years, range 26-90 (Karlsson 2010 Methods, Patients and Data)",
    disease_state  = "acute stroke with onset within 12 h of treatment; mean baseline NIHSS 16.8, range 4-31",
    dose_range     = "none -- placebo arm only; no drug was modelled",
    regions        = "multinational, multicentre",
    notes          = paste0(
      "Placebo arm of the double-blind, multinational, multicentre ",
      "CLASS-I trial of the novel acute-stroke compound clomethiazole ",
      "(Karlsson 2010 reference 32 = Lyden et al., Stroke ",
      "2002;33:122-128). The population PK model from the same trial is ",
      "packaged separately as Zingmark_2003_clomethiazole. Fitted in ",
      "NONMEM 7 by the Laplace method; confidence intervals from ",
      "Perl-speaks-NONMEM log-likelihood profiling. Final OFV -703.665, ",
      "condition number 1484 (Karlsson 2010 Supplement A)."
    )
  )

  ini({
    # ==================================================================
    # Every value below is the FINAL estimate from Karlsson 2010
    # Supplement A, "Table of the parameter estimates, NONMEM produced
    # standard errors and a log-likelihood profiling produced 95%
    # confidence interval of the NIHSS model". The THETA / OMEGA numbers
    # in the Supplement B control stream are NONMEM *initial* estimates
    # and disagree with Supplement A on several parameters -- they are
    # NOT used here. The paper's own Results text adjudicates: it states
    # the probability of improvement "decreased 0.05 units with 10
    # years, between ages 64 and 74", which Supplement A reproduces
    # (0.6506 -> 0.5978, difference 0.0527) and Supplement B's initials
    # do not (0.6795 -> 0.6385, difference 0.0411). Supplement B is used
    # for MODEL STRUCTURE only.
    #
    # All logit-scale intercepts and slopes are unitless.
    # ==================================================================

    # ----- Probability of improvement (vs decline); source P1 ---------
    logitp_improve              <- 0.419
    label("Logit of the probability of score improvement at a visit, at the reference age of 73 years (unitless)")
    # Supplement A NIHSS table, "PrIM (1)" = 0.419 (rel SE 0.1286; LLP 95% CI 0.31601-0.52343); source THETA(1)
    e_age_p_improve             <- -0.0225
    label("Change in the improvement logit per year of age above 73 years (unitless per year)")
    # Supplement A NIHSS table, "A1AGE (12)" = -0.0225 (rel SE 0.1969; LLP 95% CI -0.0314 to -0.01373); source THETA(12), A1AGE = THETA(12)*(AGE-73)

    # ----- Probability of NOT reaching the maximum (recovered) score;
    #       source P2. Break point at day 45. -------------------------
    logitp_notmax               <- -1.73
    label("Logit of the probability of not reaching a fully recovered score, on days <= 45 since stroke (unitless)")
    # Supplement A NIHSS table, "PrMAX (2)" = -1.73 (rel SE 0.3884; LLP 95% CI -2.84178 to -0.67416); source THETA(2)
    logitp_notmax_dgt45         <- -2.64
    label("Logit of the probability of not reaching a fully recovered score, on days > 45 since stroke (unitless)")
    # Supplement A NIHSS table, "PrMAX Day > 45 (15)" = -2.64 (rel SE 0.5455; LLP 95% CI -5.00496 to -0.36735); source THETA(15)
    e_score_nihss_prev_p_notmax <- 0.474
    label("Change in the not-maximum logit per NIHSS point of the previous score (unitless per NIHSS point)")
    # Supplement A NIHSS table, "A2PNH (8)" = 0.474 (rel SE 0.3161; LLP 95% CI 0.38347-0.57751); source THETA(8), A2PNH = THETA(8)*PNH
    e_t_prevobs_p_notmax        <- 0.0277
    label("Change in the not-maximum logit per day since the previous observation (unitless per day)")
    # Supplement A NIHSS table, "A2TLS (11)" = 0.0277 (rel SE 0.7834; LLP 95% CI -0.00613 to 0.06297 -- spans zero, retained by the authors); source THETA(11), A2TLS = THETA(11)*TLS

    # ----- Probability of dropout; source P3. Three day intervals and a
    #       PROPORTIONAL informative-dropout term on the predicted
    #       declined score. -----------------------------------------
    logitp_dropout              <- -4.14
    label("Baseline dropout logit multiplier on days <= 14 since stroke (unitless)")
    # Supplement A NIHSS table, "PrDO (3)" = -4.14 (rel SE 0.09734; LLP 95% CI -4.92048 to -3.42328); source THETA(3)
    logitp_dropout_d14to45      <- -2.97
    label("Baseline dropout logit multiplier on days 14-45 since stroke (unitless)")
    # Supplement A NIHSS table, "PrDO Interval 2 (13)" = -2.97 (rel SE 0.1886; LLP 95% CI -4.06983 to -2.07763); source THETA(13)
    logitp_dropout_dgt45        <- -4.05
    label("Baseline dropout logit multiplier on days > 45 since stroke (unitless)")
    # Supplement A NIHSS table, "PrDO Interval 3 (14)" = -4.05 (rel SE 0.1237; LLP 95% CI -5.29258 to -3.08706); source THETA(14)
    slope_score_p_dropout       <- -0.0334
    label("Proportional informative-dropout coefficient on the model-predicted declined NIHSS score (unitless per NIHSS point)")
    # Supplement A NIHSS table, "InfDropout (7)" = -0.0334 (rel SE 0.03862; LLP 95% CI -0.03599 to -0.03069); source THETA(7), TVA3 = THETA(3)*(1 + THETA(7)*NDE)

    # ----- Relative improvement magnitude on the logit scale; source
    #       IM / IMZ. Break point at day 14. -------------------------
    logitimpr_dlt14             <- 0.599
    label("Logit-scale relative-improvement intercept on days < 14 since stroke (unitless)")
    # Supplement A NIHSS table, "Impr (4)" = 0.599 (rel SE 0.2788; LLP 95% CI 0.33227-0.86381); source THETA(4)
    logitimpr_dge14             <- 0.365
    label("Logit-scale relative-improvement intercept on days >= 14 since stroke (unitless)")
    # Supplement A NIHSS table, "Impr Day > 14 (16)" = 0.365 (rel SE 0.4301; LLP 95% CI 0.11472-0.61887); source THETA(16)
    e_score_nihss_impr          <- -0.0602
    label("Change in the logit-scale relative improvement per NIHSS point of the baseline score (unitless per NIHSS point)")
    # Supplement A NIHSS table, "IMBNH (10)" = -0.0602 (rel SE 0.1543; LLP 95% CI -0.0741 to -0.04633); source THETA(10), IMBNH = THETA(10)*BNH

    # ----- Relative decline magnitude on the logit scale; source
    #       DE / DEZ. No fixed-effect break point: only the IIV
    #       switches at day 14 ("no other changes over time could be
    #       supported", Karlsson 2010 Results). --------------------
    logitdecl                   <- -3.56
    label("Logit-scale relative-decline intercept (unitless)")
    # Supplement A NIHSS table, "Decl (5)" = -3.56 (rel SE 0.03792; LLP 95% CI -3.71835 to -3.40546); source THETA(5), used in BOTH day branches of DE
    e_score_nihss_prev_decl     <- 0.0765
    label("Change in the logit-scale relative decline per NIHSS point of the previous score (unitless per NIHSS point)")
    # Supplement A NIHSS table, "DEPNH (9)" = 0.0765 (rel SE 0.1065; LLP 95% CI 0.06364-0.09001); source THETA(9), DEPNH = THETA(9)*PNH

    # ----- Residual variability on the logit scale --------------------
    # The source declares $SIGMA 1 FIX and RV = THETA(6)*EPS(1), so
    # THETA(6) IS the residual SD on the logit scale. ONE THETA is
    # shared between the improvement and the decline function; rxode2
    # requires a distinct endpoint parameter per endpoint, so the same
    # estimate is written twice.
    addSd_imz                   <- 0.595
    label("Residual SD on the logit scale for the relative-improvement magnitude (unitless)")
    # Supplement A NIHSS table, "ResErr (6)" = 0.595 (rel SE 0.09311; LLP 95% CI 0.54245-0.65844); source THETA(6) with $SIGMA 1 FIX
    addSd_dez                   <- 0.595
    label("Residual SD on the logit scale for the relative-decline magnitude (unitless)")
    # Supplement A NIHSS table, "ResErr (6)" = 0.595 -- the SAME THETA(6) as addSd_imz; the source stream applies one RV term to both IM and DE

    # ----- Placeholder residuals for the three probability endpoints --
    # The source likelihood for P1/P2/P3 is Bernoulli on the observed
    # binary event (NONMEM F_FLAG = 1), which has no residual-error
    # parameter. rxode2 requires an error model per endpoint, so each
    # probability is emitted with a tiny fixed additive residual, as in
    # Fukae_2024_valemetostat_orr_investigator.
    addSd_p_improve             <- fixed(0.001)
    label("Placeholder additive residual SD on the improvement probability (unitless)")
    # not from source; the source likelihood is Bernoulli (see vignette Assumptions and deviations)
    addSd_p_notmax              <- fixed(0.001)
    label("Placeholder additive residual SD on the not-maximum probability (unitless)")
    # not from source; the source likelihood is Bernoulli (see vignette Assumptions and deviations)
    addSd_p_dropout             <- fixed(0.001)
    label("Placeholder additive residual SD on the dropout probability (unitless)")
    # not from source; the source likelihood is Bernoulli (see vignette Assumptions and deviations)

    # ----- Interindividual variability --------------------------------
    # OMEGA variances on the logit scale. The eta that applies switches
    # at day 14 for BOTH the improvement and the decline function; the
    # OMEGA labels alone are ambiguous, so the mapping was recovered
    # from the Supplement B control-stream branches:
    #   IM = ... + ETA(3) ; IF(DAY.GE.14) IM = ... + ETA(1)
    #   DE = ... + ETA(4) ; IF(DAY.GE.14) DE = ... + ETA(2)
    etalogitimpr_dlt14 ~ 0.902
    # Supplement A NIHSS table, "IIV on improvement DAY 7 (3)" = 0.902 (rel SE 0.1863; LLP 95% CI 0.64598-1.20706); source OMEGA(3), applied via ETA(3) on days < 14
    etalogitimpr_dge14 ~ 0.434
    # Supplement A NIHSS table, "IIV on improvement (1)" = 0.434 (rel SE 0.2157; LLP 95% CI 0.30932-0.57782); source OMEGA(1), applied via ETA(1) on days >= 14
    etalogitdecl_dlt14 ~ 2.27
    # Supplement A NIHSS table, "IIV on decline DAY 7 (4)" = 2.27 (rel SE 0.1551; LLP 95% CI 1.79728-2.8732); source OMEGA(4), applied via ETA(4) on days < 14
    etalogitdecl_dge14 ~ 0.690
    # Supplement A NIHSS table, "IIV on decline (2)" = 0.690 (rel SE 0.1667; LLP 95% CI 0.5391-0.88797); source OMEGA(2), applied via ETA(2) on days >= 14
  })

  model({
    # ------------------------------------------------------------------
    # 1. Day break points. rxode2's `time` carries days since the stroke
    #    event, which is the source stream's DAY column (the stream sets
    #    TSS = DAY explicitly). Encoded as 0/1 indicators rather than
    #    if/else so the switch stays a single algebraic expression.
    #
    #    Note the boundaries differ between submodels, exactly as in the
    #    source: the magnitude submodels switch at DAY >= 14, while the
    #    dropout intercept's first interval is DAY <= 14.
    # ------------------------------------------------------------------
    dge14   <- time >= 14
    dle14   <- time <= 14
    d14to45 <- (time > 14) * (time <= 45)
    dgt45   <- time > 45

    # ------------------------------------------------------------------
    # 2. Continuous submodels for the RELATIVE magnitude of a score
    #    change, on the logit scale (source: IM, DE -> IMZ, DEZ).
    # ------------------------------------------------------------------
    # IM = IMCOV + THETA(4) + ETA(3);  IF(DAY.GE.14) IM = IMCOV + THETA(16) + ETA(1)
    logitimpr <- e_score_nihss_impr * SCORE_NIHSS +
      (1 - dge14) * (logitimpr_dlt14 + etalogitimpr_dlt14) +
      dge14 * (logitimpr_dge14 + etalogitimpr_dge14)

    # DE = DECOV + THETA(5) + ETA(4);  IF(DAY.GE.14) DE = DECOV + THETA(5) + ETA(2)
    # The fixed effect is THETA(5) in both branches -- only the eta switches.
    logitdecl_i <- e_score_nihss_prev_decl * SCORE_NIHSS_PREV + logitdecl +
      (1 - dge14) * etalogitdecl_dlt14 +
      dge14 * etalogitdecl_dge14

    imz <- expit(logitimpr)
    dez <- expit(logitdecl_i)

    # ------------------------------------------------------------------
    # 3. Reconstruction onto the raw 0-42 NIHSS scale (source NIM2, NDE).
    #    An improvement moves the score toward 0; a decline moves it
    #    toward 42. The "+ 1" offset lets a full improvement reach 0.
    # ------------------------------------------------------------------
    nihss_improve <- (1 - imz) * (SCORE_NIHSS_PREV + 1)
    nihss_decline <- dez * (42 - SCORE_NIHSS_PREV) + SCORE_NIHSS_PREV

    # ------------------------------------------------------------------
    # 4. Probability submodels (source P1, P2, P3).
    # ------------------------------------------------------------------
    # TVA1 = A1COV + THETA(1), with A1COV = THETA(12)*(AGE - 73)
    p_improve <- expit(logitp_improve + e_age_p_improve * (AGE - 73))

    # TVA2 = A2COV + THETA(2); IF(DAY.GT.45) TVA2 = A2COV + THETA(15)
    # with A2COV = THETA(8)*PNH + THETA(11)*TLS
    p_notmax <- expit(
      (1 - dgt45) * logitp_notmax + dgt45 * logitp_notmax_dgt45 +
        e_score_nihss_prev_p_notmax * SCORE_NIHSS_PREV +
        e_t_prevobs_p_notmax * T_PREVOBS
    )

    # Informative dropout, PROPORTIONAL form (Karlsson 2010 Table II
    # footnote b): TVA3 = THETA(3 | 13 | 14) * (1 + THETA(7)*NDE)
    prop_dropout <- 1 + slope_score_p_dropout * nihss_decline
    p_dropout <- expit(
      (dle14 * logitp_dropout +
         d14to45 * logitp_dropout_d14to45 +
         dgt45 * logitp_dropout_dgt45) * prop_dropout
    )

    # ------------------------------------------------------------------
    # 5. Endpoints. The source fits all five submodels simultaneously.
    #    The two magnitude endpoints are logit-normal on (0, 1): the
    #    source adds RV = THETA(6)*EPS(1) INSIDE the logit before the
    #    expit, which is exactly rxode2's logitNorm(sd, low, hi).
    # ------------------------------------------------------------------
    p_improve ~ add(addSd_p_improve)
    p_notmax  ~ add(addSd_p_notmax)
    p_dropout ~ add(addSd_p_dropout)
    imz       ~ logitNorm(addSd_imz, 0, 1)
    dez       ~ logitNorm(addSd_dez, 0, 1)
  })
}
