Karlsson_2010_acute_stroke_bi <- function() {
  description <- paste0(
    "Drug-free disease-progression model for the Barthel Index (BI, ",
    "0-100 points in five-point steps, HIGHER is better) in acute ",
    "stroke, fitted to the placebo arm of the CLASS-I trial (Karlsson ",
    "2010, n = 580). Five submodels are fitted simultaneously: three ",
    "logit probability submodels for improvement versus decline ",
    "(p_improve), failure to reach the maximum/fully-recovered score ",
    "(p_notmax) and dropout (p_dropout), plus two continuous submodels ",
    "for the relative magnitude of an improvement (imz) or a decline ",
    "(dez) on the logit scale. The relative magnitudes are mapped back ",
    "to the raw BI by the authors' reconstruction rules ",
    "bi_improve = SCORE_BI_PREV + imz * (100 - SCORE_BI_PREV) and ",
    "bi_decline = (1 - dez) * (SCORE_BI_PREV + 1). Dropout is ",
    "INFORMATIVE: its logit enters proportionally as logitp_dropout * ",
    "(1 + slope_score_p_dropout * bi_decline), so the probability of ",
    "dropping out falls as the model-predicted declined score rises. ",
    "The BI has no day break points -- unlike the companion NIHSS ",
    "model it carries a single dropout interval, a single p_notmax ",
    "intercept and a single (decline-only) IIV term -- but it does ",
    "carry TWO distinct time clocks: time since the previous ",
    "observation (T_PREVOBS) on the relative decline, and time since ",
    "stroke (rxode2 `time`) on p_notmax. There is no PK layer and no ",
    "ODE: the source is a NONMEM $PRED model whose Markovian ",
    "predictors are supplied as data columns, so a trajectory is ",
    "generated by drawing the probabilistic events at each visit and ",
    "carrying the reconstructed score forward (see the vignette). ",
    "The BI was not measured at admission, so the model starts from ",
    "the day-7 assessment. Companion NIHSS model in ",
    "Karlsson_2010_acute_stroke_nihss."
  )
  reference <- paste(
    "Karlsson KE, Wilkins JJ, Jonsson F, Zingmark PH, Karlsson MO, Jonsson EN.",
    "Modeling disease progression in acute stroke using clinical assessment scales.",
    "AAPS J. 2010;12(4):683-692. doi:10.1208/s12248-010-9230-0.",
    "Final parameter estimates from Supplement A (BI table);",
    "model structure from the Supplement B NONMEM control stream",
    "for the Barthel Index model.",
    sep = " "
  )
  vignette <- "Karlsson_2010_acute_stroke"
  units <- list(
    time          = "day (days since the stroke event; the source NONMEM DAY / TSS column)",
    dosing        = "n/a (no dose events; drug-free placebo-arm disease-progression model)",
    concentration = "Barthel Index points (0-100) for bi_improve / bi_decline; unitless 0-1 for imz, dez and the three probabilities"
  )

  covariateData <- list(
    AGE = list(
      description        = "Age at study entry.",
      units              = "years",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Centred at 73 years inside model(), matching the source control stream `A1AGE = THETA(13)*(AGE-73)` and `IMAGE = THETA(14)*(AGE-73)`. Analysis-set mean 71.7 years, range 26-90 (Karlsson 2010 Methods, Patients and Data). The source stream branches on AGE = -99 to zero both age effects; that NONMEM missing-value convention is NOT reproduced here -- supply a real age.",
      source_name        = "AGE"
    ),
    SCORE_BI_PREV = list(
      description        = "Barthel Index total score recorded at the immediately preceding observation occasion, on the raw 0-100 scale in five-point steps, where 100 is full independent function. The Markov-state predictor that conditions the current occasion's transition probabilities and score reconstruction.",
      units              = "(Barthel Index points, 0-100)",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Source column PBI, mapping to `PBI` in the Supplement B BI dataset excerpt. The BI was not assessed at admission (Karlsson 2010 Data Preparation: imputed baselines between 0 and 20 were tested and rejected for insufficient predictive power), so the model starts at the day-7 assessment and SCORE_BI_PREV is the day-7 score at the first modelled transition. Enters p_improve, p_notmax, the relative-improvement magnitude submodel, and both reconstruction rules. Not centred in the source stream.",
      source_name        = "PBI"
    ),
    SCORE_NIHSS = list(
      description        = "Baseline (admission) NIHSS total score on the RAW 0-42 scale, where 0 is normal and 42 is maximal deficit. Time-fixed per subject; used here as a cross-scale severity covariate on the Barthel Index improvement magnitude.",
      units              = "(NIHSS points, 0-42)",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Source column BNIH, the raw baseline NIHSS carried into the BI dataset. Note the BI control stream also computes `CBNH = 42 - BNIH` (the reversed baseline NIHSS) but never uses it -- the retained effect IMBNH = THETA(15)*BNIH is on the RAW score. Analysis-set mean 16.8, range 4-31 (Karlsson 2010 Methods). Not centred in the source stream.",
      source_name        = "BNIH"
    ),
    T_PREVOBS = list(
      description        = "Time elapsed since the subject's previous observation occasion.",
      units              = "day",
      type               = "continuous",
      reference_category = NULL,
      notes              = "Source column TLS. The Supplement B dataset legend calls TLS 'Time since start of study (i.e. time since stroke)', but the tabulated data falsify that label and the value is time since the PREVIOUS observation: in the BI excerpt subject 1 has DAY 29 -> TLS 22, DAY 60 -> TLS 31 (= 60 - 29), DAY 89 -> TLS 29 (= 89 - 60), i.e. non-monotonic in DAY, which time-since-stroke cannot be. Corroborated by Karlsson 2010 Table II, which lists 'Influence of time since previous observation' for the BI relative decline and lists 'Influence of time since baseline' separately for BI p_notmax (that second clock is TSS = DAY, carried here by rxode2's `time`). Not centred in the source stream.",
      source_name        = "TLS"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 580L,
    n_studies      = 1L,
    n_observations = "Barthel Index assessed on days 7, 30 and 90, plus a telephone assessment at day 60; no admission assessment. One imputed record was added for subjects whose observations ended before the day-90 endpoint, placed halfway between the last measured observation and the next intended appointment, to inform the dropout submodel (Karlsson 2010 Data Preparation)",
    age_range      = "mean 71.7 years, range 26-90 (Karlsson 2010 Methods, Patients and Data)",
    disease_state  = "acute stroke with onset within 12 h of treatment; mean baseline NIHSS 16.8, range 4-31",
    dose_range     = "none -- placebo arm only; no drug was modelled",
    regions        = "multinational, multicentre",
    notes          = paste0(
      "Placebo arm of the double-blind, multinational, multicentre ",
      "CLASS-I trial of the novel acute-stroke compound clomethiazole ",
      "(Karlsson 2010 reference 32 = Lyden et al., Stroke ",
      "2002;33:122-128). The population PK model from the same trial is ",
      "packaged separately as Zingmark_2003_clomethiazole. Fitted in ",
      "NONMEM 7 by the Laplace method; confidence intervals from ",
      "Perl-speaks-NONMEM log-likelihood profiling. Final OFV 1002.597, ",
      "condition number 389.2 (Karlsson 2010 Supplement A). The authors ",
      "note the BI model 'was harder to establish than the NIHSS model, ",
      "and displayed some imprecision in a few of the structural ",
      "parameters', which they attribute to the BI's coarser 20-value ",
      "range; two parameters (logitp_improve and logitdecl) have ",
      "confidence intervals spanning zero."
    )
  )

  ini({
    # ==================================================================
    # Every value below is the FINAL estimate from Karlsson 2010
    # Supplement A, "Table of the parameter estimates, NONMEM produced
    # standard errors and a log-likelihood profiling produced 95%
    # confidence interval of the BI model". The THETA / OMEGA numbers in
    # the Supplement B control stream are NONMEM *initial* estimates and
    # disagree with Supplement A on 11 of 15 thetas and on the omega
    # (1.25 vs 2.08) -- they are NOT used here. Supplement B is used for
    # MODEL STRUCTURE only. See the NIHSS companion file for the
    # decisive adjudication against the paper's own Results text.
    #
    # All logit-scale intercepts and slopes are unitless.
    # ==================================================================

    # ----- Probability of improvement (vs decline); source P1 ---------
    logitp_improve            <- -0.027
    label("Logit of the probability of score improvement at a visit, at a previous BI of 0 and the reference age of 73 years (unitless)")
    # Supplement A BI table, "PrIM (1)" = -0.027 (rel SE 3.256; LLP 95% CI -0.194322 to 0.14053 -- spans zero); source THETA(1). The Supplement B inline comment calls THETA(1) "Probability of decline"; the code assigns P1A = P1 ; Improvement, Supplement A names it PrIM, and the covariate signs match improvement, so the stream comment is wrong.
    e_score_bi_prev_p_improve <- 0.0113
    label("Change in the improvement logit per Barthel Index point of the previous score (unitless per BI point)")
    # Supplement A BI table, "A1PBI (10)" = 0.0113 (rel SE 0.1549; LLP 95% CI 0.00821-0.01451); source THETA(10), A1PBI = THETA(10)*PBI
    e_age_p_improve           <- -0.0357
    label("Change in the improvement logit per year of age above 73 years (unitless per year)")
    # Supplement A BI table, "A1AGE (13)" = -0.0357 (rel SE 0.1426; LLP 95% CI -0.0464674 to -0.0252872); source THETA(13), A1AGE = THETA(13)*(AGE-73)

    # ----- Probability of NOT reaching the maximum (recovered) score;
    #       source P2. No day break point. --------------------------
    logitp_notmax             <- 5.92
    label("Logit of the probability of not reaching a fully recovered score, at a previous BI of 0 on the day of the stroke (unitless)")
    # Supplement A BI table, "PrMAX (2)" = 5.92 (rel SE 0.1108; LLP 95% CI 4.9916-6.94358); source THETA(2)
    e_score_bi_prev_p_notmax  <- -0.0984
    label("Change in the not-maximum logit per Barthel Index point of the previous score (unitless per BI point)")
    # Supplement A BI table, "A2PBI(8)" = -0.0984 (rel SE 0.09451; LLP 95% CI -0.112243 to -0.0859533); source THETA(8), A2PBI = THETA(8)*PBI
    slope_p_notmax            <- 0.0195
    label("Change in the not-maximum logit per day since the stroke event (unitless per day)")
    # Supplement A BI table, "A2TSS (12)" = 0.0195 (rel SE 0.2667; LLP 95% CI 0.00972-0.02965); source THETA(12), A2TSS = THETA(12)*TSS with TSS = DAY set in the stream. This multiplies rxode2's `time`, not a covariate column, hence the `slope_` rather than `e_` prefix.

    # ----- Probability of dropout; source P3. One interval and a
    #       PROPORTIONAL informative-dropout term on the predicted
    #       declined score. ------------------------------------------
    logitp_dropout            <- -0.511
    label("Baseline dropout logit multiplier (unitless)")
    # Supplement A BI table, "PrDO (3)" = -0.511 (rel SE 0.1072; LLP 95% CI -0.786937 to -0.233678); source THETA(3)
    slope_score_p_dropout     <- 0.128
    label("Proportional informative-dropout coefficient on the model-predicted declined Barthel Index score (unitless per BI point)")
    # Supplement A BI table, "InfDropout (7)" = 0.128 (rel SE 0.5312; LLP 95% CI 0.06007-0.37545); source THETA(7), TVA3 = THETA(3)*(1 + THETA(7)*BDE2)

    # ----- Relative improvement magnitude on the logit scale; source
    #       IM / IMZ. No IIV -- see the note below. -----------------
    logitimpr                 <- -0.666
    label("Logit-scale relative-improvement intercept (unitless)")
    # Supplement A BI table, "Impr (4)" = -0.666 (rel SE 0.3153; LLP 95% CI -1.0247 to -0.303974); source THETA(4)
    e_score_bi_prev_impr      <- 0.0156
    label("Change in the logit-scale relative improvement per Barthel Index point of the previous score (unitless per BI point)")
    # Supplement A BI table, "IMPBI (11)" = 0.0156 (rel SE 0.1288; LLP 95% CI 0.01176-0.01938); source THETA(11), IMPBI = THETA(11)*PBI
    e_age_impr                <- -0.0124
    label("Change in the logit-scale relative improvement per year of age above 73 years (unitless per year)")
    # Supplement A BI table, "IMAGE (14)" = -0.0124 (rel SE 0.3540; LLP 95% CI -0.0200412 to -0.00494234); source THETA(14), IMAGE = THETA(14)*(AGE-73)
    e_score_nihss_impr        <- -0.0325
    label("Change in the logit-scale relative improvement per NIHSS point of the baseline NIHSS score (unitless per NIHSS point)")
    # Supplement A BI table, "IMBNIH (15)" = -0.0325 (rel SE 0.3323; LLP 95% CI -0.0503072 to -0.0143383); source THETA(15), IMBNH = THETA(15)*BNIH

    # ----- Relative decline magnitude on the logit scale; source
    #       DE / DEZ. ----------------------------------------------
    logitdecl                 <- 0.0417
    label("Logit-scale relative-decline intercept (unitless)")
    # Supplement A BI table, "Decl (5)" = 0.0417 (rel SE 10.58; LLP 95% CI -0.344889 to 0.5067 -- spans zero); source THETA(5)
    e_t_prevobs_decl          <- -0.0332
    label("Change in the logit-scale relative decline per day since the previous observation (unitless per day)")
    # Supplement A BI table, "DETLS (9)" = -0.0332 (rel SE 0.5151; LLP 95% CI -0.0496589 to -0.0204928); source THETA(9), DETLS = THETA(9)*TLS

    # ----- Residual variability on the logit scale --------------------
    # $SIGMA 1 FIX and RV = THETA(6)*EPS(1), so THETA(6) IS the residual
    # SD on the logit scale, shared between the improvement and decline
    # functions (Karlsson 2010 Results: "the latter shared with the
    # function for improvement"). rxode2 requires a distinct endpoint
    # parameter per endpoint, so the same estimate is written twice.
    addSd_imz                 <- 1.14
    label("Residual SD on the logit scale for the relative-improvement magnitude (unitless)")
    # Supplement A BI table, "ResErr (6)" = 1.14 (rel SE 0.04246; LLP 95% CI 1.06576-1.21313); source THETA(6) with $SIGMA 1 FIX
    addSd_dez                 <- 1.14
    label("Residual SD on the logit scale for the relative-decline magnitude (unitless)")
    # Supplement A BI table, "ResErr (6)" = 1.14 -- the SAME THETA(6) as addSd_imz; the source stream applies one RV term to both IM and DE

    # ----- Placeholder residuals for the three probability endpoints --
    # The source likelihood for P1/P2/P3 is Bernoulli on the observed
    # binary event (NONMEM F_FLAG = 1), which has no residual-error
    # parameter. rxode2 requires an error model per endpoint.
    addSd_p_improve           <- fixed(0.001)
    label("Placeholder additive residual SD on the improvement probability (unitless)")
    # not from source; the source likelihood is Bernoulli (see vignette Assumptions and deviations)
    addSd_p_notmax            <- fixed(0.001)
    label("Placeholder additive residual SD on the not-maximum probability (unitless)")
    # not from source; the source likelihood is Bernoulli (see vignette Assumptions and deviations)
    addSd_p_dropout           <- fixed(0.001)
    label("Placeholder additive residual SD on the dropout probability (unitless)")
    # not from source; the source likelihood is Bernoulli (see vignette Assumptions and deviations)

    # ----- Interindividual variability --------------------------------
    # The BI model estimates ONE omega, on the relative decline. The
    # improvement function carries no eta: the Supplement B stream has
    # IM = TVIM + RV (no ETA term) while DE = TVDE + ETA(1) + RV, and
    # Supplement A lists a single omega labelled "IIV on decline".
    # Karlsson 2010 Results prose claims the BI improvement model
    # included "terms for interindividual variability and residual
    # variability"; the control stream and the estimates table both
    # contradict that, and the equation governs. Recorded in the
    # vignette Assumptions and deviations.
    etalogitdecl ~ 1.25
    # Supplement A BI table, "IIV on decline (1)" = 1.25 (rel SE 0.4064; LLP 95% CI 0.74843-1.93402); source OMEGA(1)
  })

  model({
    # ------------------------------------------------------------------
    # 1. Continuous submodels for the RELATIVE magnitude of a score
    #    change, on the logit scale (source: IM, DE -> IMZ, DEZ).
    #    IMCOV = THETA(11)*PBI + THETA(14)*(AGE-73) + THETA(15)*BNIH
    #    DECOV = THETA(9)*TLS
    #    IM = THETA(4) + IMCOV + RV          (no eta)
    #    DE = THETA(5) + DECOV + ETA(1) + RV
    # ------------------------------------------------------------------
    logitimpr_i <- logitimpr +
      e_score_bi_prev_impr * SCORE_BI_PREV +
      e_age_impr * (AGE - 73) +
      e_score_nihss_impr * SCORE_NIHSS

    logitdecl_i <- logitdecl +
      e_t_prevobs_decl * T_PREVOBS +
      etalogitdecl

    imz <- expit(logitimpr_i)
    dez <- expit(logitdecl_i)

    # ------------------------------------------------------------------
    # 2. Reconstruction onto the raw 0-100 Barthel Index (source BIM1,
    #    BDE2). An improvement moves the score toward 100; a decline
    #    moves it toward 0. The "+ 1" offset lets a full decline reach 0.
    # ------------------------------------------------------------------
    bi_improve <- SCORE_BI_PREV + imz * (100 - SCORE_BI_PREV)
    bi_decline <- (1 - dez) * (SCORE_BI_PREV + 1)

    # ------------------------------------------------------------------
    # 3. Probability submodels (source P1, P2, P3).
    #
    #    The BI control stream writes DECOV = DETLS + DEGGT + DEANG,
    #    A1COV = A1PBI + A1AGE + A1CGL and A2COV = A2PBI + A2TLS +
    #    A2TSS, but DEGGT, DEANG, A1CGL and A2TLS are never assigned in
    #    that stream -- they are vestigial covariate-screening terms
    #    (GGT, ANG and CGL survive undropped in the BI $INPUT). None has
    #    a counterpart among Supplement A's 15 BI thetas or in Table II,
    #    so all four are zero in the final model and are omitted here.
    # ------------------------------------------------------------------
    # TVA1 = THETA(1) + THETA(10)*PBI + THETA(13)*(AGE - 73)
    p_improve <- expit(
      logitp_improve +
        e_score_bi_prev_p_improve * SCORE_BI_PREV +
        e_age_p_improve * (AGE - 73)
    )

    # TVA2 = THETA(2) + THETA(8)*PBI + THETA(12)*TSS, with TSS = DAY.
    # rxode2's `time` carries days since the stroke event.
    p_notmax <- expit(
      logitp_notmax +
        e_score_bi_prev_p_notmax * SCORE_BI_PREV +
        slope_p_notmax * time
    )

    # Informative dropout, PROPORTIONAL form (Karlsson 2010 Table II
    # footnote b): TVA3 = THETA(3) * (1 + THETA(7)*BDE2)
    prop_dropout <- 1 + slope_score_p_dropout * bi_decline
    p_dropout <- expit(logitp_dropout * prop_dropout)

    # ------------------------------------------------------------------
    # 4. Endpoints. The source fits all five submodels simultaneously.
    #    The two magnitude endpoints are logit-normal on (0, 1): the
    #    source adds RV = THETA(6)*EPS(1) INSIDE the logit before the
    #    expit, which is exactly rxode2's logitNorm(sd, low, hi).
    # ------------------------------------------------------------------
    p_improve ~ add(addSd_p_improve)
    p_notmax  ~ add(addSd_p_notmax)
    p_dropout ~ add(addSd_p_dropout)
    imz       ~ logitNorm(addSd_imz, 0, 1)
    dez       ~ logitNorm(addSd_dez, 0, 1)
  })
}
