Rao_2023_covid19_qsp <- function() {
  description <- paste(
    "QSP. Quantitative systems pharmacology model of SARS-CoV-2",
    "within-host viral dynamics coupled to the innate and adaptive",
    "immune response and alveolar tissue damage, with pluggable",
    "anti-SARS-CoV-2 neutralizing-antibody (nAb) and antiviral",
    "treatment arms. 54 ODE states spanning an alveolar and a plasma",
    "compartment: virus, healthy/infected/damaged alveolar type I and",
    "type II cells, dendritic cells, macrophages, neutrophils, CD4+",
    "Th1/Th17/Treg and CD8+ cytotoxic T cells, eleven cytokines",
    "(TNFa, IL-6, IL-1b, IFN-b, IFN-g, IL-2, IL-12, IL-17, IL-10,",
    "TGF-b, GM-CSF), the biomarkers surfactant protein D, ferritin",
    "and C-reactive protein, a two-compartment PK model for each of",
    "the two nAbs in a cocktail, and an endogenous antibody response.",
    "The distinguishing feature of this release is log-sensing",
    "(Weber-Fechner) activation of the innate immune cells by virus,",
    "infected cells and damaged cells, which keeps the immune",
    "response sensitive over orders of magnitude of viral load.",
    "Calibrated to a curated set of observational COVID-19 studies",
    "and to the Blaze-1 Ph3 (bamlanivimab + etesevimab), REGEN-COV",
    "Ph2/Ph3 (casirivimab + imdevimab) and molnupiravir Ph2",
    "outpatient randomized controlled trials. All parameters are",
    "hand-calibrated literature / assumed constants rather than",
    "maximum-likelihood estimates; no fitted IIV or residual error",
    "(the published heterogeneity is generated by Latin-hypercube",
    "resampling of the parameters, not by an omega matrix).",
    sep = " "
  )
  reference <- paste(
    "Rao R, Musante CJ, Allen R.",
    "A quantitative systems pharmacology model of the pathophysiology",
    "and treatment of COVID-19 predicts optimal timing of",
    "pharmacological interventions.",
    "npj Syst Biol Appl. 2023;9(1):13.",
    "doi:10.1038/s41540-023-00269-6.",
    "Model equations from Supplementary Information (Model Equations",
    "sections 1-30); parameter values, initial conditions and the",
    "treatment sub-models from the authors' own MATLAB implementation",
    "released with the paper at",
    "https://github.com/openPfizer/QSP_model_COVID19 (tag v0.1.1,",
    "commit d0549bc, 2022-01-20), files src/covid19_dxdt.m and",
    "src/Initialize.xlsx, which the Methods section cites as the full",
    "code release.",
    sep = " "
  )
  vignette <- "Rao_2023_covid19_qsp"

  paper_specific_compartments <- c(
    "V", "AT1", "AT2", "I", "dAT1", "dAT2",
    "pDC", "M1", "N", "Th1", "Th17", "CTL", "Treg",
    "TNFa", "IL6", "IL1b", "IFNb", "IFNg", "IL2", "IL12", "IL17",
    "IL10", "TGFb", "GMCSF", "SPD", "FER",
    "TNFa_c", "IL6_c", "IL1b_c", "IFNb_c", "IFNg_c", "IL2_c",
    "IL12_c", "IL17_c", "IL10_c", "TGFb_c", "GMCSF_c", "SPD_c",
    "FER_c", "Ab", "pDC_c", "M1_c", "N_c", "Th1_c", "Th17_c",
    "CTL_c", "Treg_c", "CRPExtracellular", "Blood_CRP", "pDC1",
    "Ab_Igx", "Ab12", "Ab21", "Ab22",
    "vpeaked"
  )

  units <- list(
    time          = "h",
    dosing        = "mg",
    concentration = "ug/mL"
  )

  # Issue #482: what each ODE state holds, in what amount units, in what
  # biological matrix. analyte/specimen proposed by a local model from the
  # model description; units derived from the units block. verified = FALSE
  # means NOT checked against the source paper.
  compartmentData <- list(
    V                = list(analyte = "virus", units = "mg", specimen = "plasma", verified = FALSE),
    AT2              = list(analyte = "healthy alveolar type II cells", units = "mg", specimen = "not applicable", verified = FALSE),
    I                = list(analyte = "infected alveolar type I cells", units = "mg", specimen = "not applicable", verified = FALSE),
    AT1              = list(analyte = "damaged alveolar type I cells", units = "mg", specimen = "not applicable", verified = FALSE),
    dAT1             = list(analyte = "damaged alveolar type I cells", units = "mg", specimen = "not applicable", verified = FALSE),
    dAT2             = list(analyte = "damaged alveolar type II cells", units = "mg", specimen = "not applicable", verified = FALSE),
    vpeaked          = list(analyte = "virus", units = "mg", specimen = "plasma", verified = FALSE),
    pDC              = list(analyte = "plasmacytoid dendritic cells", units = "mg", specimen = "not applicable", verified = FALSE),
    pDC1             = list(analyte = "plasmacytoid dendritic cells", units = "mg", specimen = "not applicable", verified = FALSE),
    M1               = list(analyte = "macrophages", units = "mg", specimen = "not applicable", verified = FALSE),
    N                = list(analyte = "neutrophils", units = "mg", specimen = "not applicable", verified = FALSE),
    Th1              = list(analyte = "CD4+ Th1 cells", units = "mg", specimen = "not applicable", verified = FALSE),
    Th17             = list(analyte = "CD4+ Th17 cells", units = "mg", specimen = "not applicable", verified = FALSE),
    CTL              = list(analyte = "CD8+ cytotoxic T cells", units = "mg", specimen = "not applicable", verified = FALSE),
    Treg             = list(analyte = "CD4+ regulatory T cells", units = "mg", specimen = "not applicable", verified = FALSE),
    TNFa             = list(analyte = "tumor necrosis factor-alpha", units = "mg", specimen = "plasma", verified = FALSE),
    IL6              = list(analyte = "interleukin-6", units = "mg", specimen = "plasma", verified = FALSE),
    IL1b             = list(analyte = "interleukin-1 beta", units = "mg", specimen = "plasma", verified = FALSE),
    IFNg             = list(analyte = "interferon-gamma", units = "mg", specimen = "plasma", verified = FALSE),
    IFNb             = list(analyte = "interferon-beta", units = "mg", specimen = "plasma", verified = FALSE),
    IL2              = list(analyte = "interleukin-2", units = "mg", specimen = "plasma", verified = FALSE),
    IL12             = list(analyte = "interleukin-12", units = "mg", specimen = "plasma", verified = FALSE),
    IL17             = list(analyte = "interleukin-17", units = "mg", specimen = "plasma", verified = FALSE),
    IL10             = list(analyte = "interleukin-10", units = "mg", specimen = "plasma", verified = FALSE),
    TGFb             = list(analyte = "transforming growth factor-beta", units = "mg", specimen = "plasma", verified = FALSE),
    GMCSF            = list(analyte = "granulocyte-macrophage colony-stimulating factor", units = "mg", specimen = "plasma", verified = FALSE),
    SPD              = list(analyte = "surfactant protein D", units = "mg", specimen = "not applicable", verified = FALSE),
    FER              = list(analyte = "ferritin", units = "mg", specimen = "not applicable", verified = FALSE),
    TNFa_c           = list(analyte = "tumor necrosis factor-alpha complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    IL6_c            = list(analyte = "interleukin-6 complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    IL1b_c           = list(analyte = "interleukin-1 beta complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    IFNb_c           = list(analyte = "interferon-beta complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    IFNg_c           = list(analyte = "interferon-gamma complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    IL2_c            = list(analyte = "interleukin-2 complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    IL12_c           = list(analyte = "interleukin-12 complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    IL17_c           = list(analyte = "interleukin-17 complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    IL10_c           = list(analyte = "interleukin-10 complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    TGFb_c           = list(analyte = "transforming growth factor-beta complexed to antibodies", units = "mg", specimen = "plasma", verified = FALSE),
    GMCSF_c          = list(analyte = "granulocyte-macrophage colony-stimulating factor complexed to antibodi", units = "mg", specimen = "plasma", verified = FALSE),
    SPD_c            = list(analyte = "surfactant protein D complexed to antibodies", units = "mg", specimen = "not applicable", verified = FALSE),
    FER_c            = list(analyte = "ferritin complexed to antibodies", units = "mg", specimen = "not applicable", verified = FALSE),
    pDC_c            = list(analyte = "plasmacytoid dendritic cells complexed to antibodies", units = "mg", specimen = "not applicable", verified = FALSE),
    M1_c             = list(analyte = "macrophages complexed to antibodies", units = "mg", specimen = "not applicable", verified = FALSE),
    N_c              = list(analyte = "neutrophils complexed to antibodies", units = "mg", specimen = "not applicable", verified = FALSE),
    Th1_c            = list(analyte = "CD4+ Th1 cells complexed to antibodies", units = "mg", specimen = "not applicable", verified = FALSE),
    Th17_c           = list(analyte = "CD4+ Th17 cells complexed to antibodies", units = "mg", specimen = "not applicable", verified = FALSE),
    CTL_c            = list(analyte = "CD8+ cytotoxic T cells complexed to antibodies", units = "mg", specimen = "not applicable", verified = FALSE),
    Treg_c           = list(analyte = "CD4+ regulatory T cells complexed to antibodies", units = "mg", specimen = "not applicable", verified = FALSE),
    CRPExtracellular = list(analyte = "C-reactive protein extracellular", units = "mg", specimen = "plasma", verified = FALSE),
    Blood_CRP        = list(analyte = "C-reactive protein in blood", units = "mg", specimen = "plasma", verified = FALSE),
    Ab               = list(analyte = "neutralizing antibodies", units = "mg", specimen = "administration site", verified = FALSE),
    Ab12             = list(analyte = "neutralizing antibody 1", units = "mg", specimen = "administration site", verified = FALSE),
    Ab21             = list(analyte = "neutralizing antibody 2", units = "mg", specimen = "administration site", verified = FALSE),
    Ab22             = list(analyte = "neutralizing antibody 3", units = "mg", specimen = "administration site", verified = FALSE),
    Ab_Igx           = list(analyte = "IgX antibodies", units = "mg", specimen = "plasma", verified = FALSE)
  )

  covariateData <- list(
    CP_EIDD_NGML = list(
      description        = paste(
        "Instantaneous plasma concentration of EIDD-1931, the",
        "pharmacologically active nucleoside analogue metabolite of",
        "the antiviral prodrug molnupiravir, supplied as a",
        "time-varying regressor rather than computed from a coupled",
        "PK model."
      ),
      units              = "ng/mL",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "Time-varying regressor; supplied at every event row and",
        "linearly interpolated between rows via the",
        "linear(CP_EIDD_NGML) declaration in model(). Drives the",
        "Imax inhibition of viable-virus production from infected",
        "cells. Set to 0 for placebo and nAb-only arms. Rao 2023",
        "Methods (Modeling antiviral therapeutics) states the",
        "EIDD-1931 plasma concentrations used for simulation were",
        "digitized from Painter et al. 2021 (AAC,",
        "doi:10.1128/AAC.02428-20) and shown in Supplementary",
        "Figure 16; the digitized 0-12 h profiles for the 50, 100,",
        "200, 300, 400, 600 and 800 mg single doses ship with the",
        "authors' code release as data/molnupiravir_PK.csv. The",
        "model was optimized against the plasma (not intracellular)",
        "EIDD-1931 concentration as an explicit simplification."
      ),
      source_name        = "Cav / Cantiviral"
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 502,
    n_studies      = 3,
    age_range      = "not reported for the virtual population",
    disease_state  = paste(
      "Outpatients with recently diagnosed mild-to-moderate COVID-19",
      "at high risk of hospitalization (SARS-CoV-2 clades prevalent",
      "2019-2021, i.e. pre-Delta/pre-Omicron); the underlying",
      "plausible population is additionally constrained to",
      "observational data that is predominantly from hospitalized",
      "COVID-19 patients."
    ),
    dose_range     = paste(
      "2800 mg bamlanivimab + 2800 mg etesevimab IV (Blaze-1 Ph3);",
      "8 g (4000 mg casirivimab + 4000 mg imdevimab), 2.4 g and",
      "1.2 g REGEN-COV IV; 800 mg molnupiravir PO BID"
    ),
    notes          = paste(
      "This is a virtual population, not an observed cohort. A",
      "plausible population of N = 14,545 virtual subjects was",
      "generated by uniform Latin-hypercube sampling of sensitive,",
      "uncertain parameters within five-fold bounds of the nominal",
      "parameter set (Supplementary Table S2) and filtering to within",
      "two-fold of the curated observational data (Supplementary",
      "Table S1). A refined virtual population of N = 502 was then",
      "selected by importance sampling to match the Blaze-1 Ph3",
      "placebo (N = 517) and 2800 mg bamlanivimab + 2800 mg",
      "etesevimab (N = 518) arms; a further N = 402 subset was",
      "selected for the REGEN-COV Ph2 trial. Supplementary Table S2,",
      "which names the sampled parameters, is published as a bitmap",
      "with no machine-readable text, so the per-parameter sampling",
      "ranges are not reproduced here. The model itself is the",
      "nominal (typical) parameter set."
    )
  )

  ini({
    # =====================================================================
    # ALL values below are hand-calibrated literature / assumed constants
    # from the authors' released implementation, not maximum-likelihood
    # estimates. Source for every value unless otherwise noted:
    #   PAR = Rao 2023 code release src/Initialize.xlsx, sheet "Parameters"
    #   DXDT = hard-coded in src/covid19_dxdt.m
    # They are exposed as estimable typical values (no fixed() wrapper, as
    # in Lu_2023_sglt_qsp) so downstream users can recalibrate.
    # Model time unit is hours throughout.
    # =====================================================================

    # ---- Viral & alveolar cell dynamics (Suppl. Eq. 1-6) ----------------
    A_V           <- 0.8         ; label("Viral shedding by infected cells (virus/mL/cell/h)")                  # PAR A_V
    k_int         <- 4.725e-12   ; label("Viral endocytosis by AT2 cells (mL/virus/h)")                          # PAR k_int
    km_int_IFNb   <- 180         ; label("IC50 for antiviral effect of type I IFN on infection (pmol)")           # PAR km_int_IFNb
    b_V           <- 0.08325     ; label("Endogenous viral clearance rate (1/h)")                                 # PAR b_V
    mu_AT2        <- 2.674167e-4 ; label("Basal regeneration rate of AT2 cells (1/h)")                            # PAR mu_AT2
    mu_AT1        <- 0           ; label("Regeneration rate of AT1 cells (1/h); 0 = AT1 sourced only from AT2")   # PAR mu_AT1
    k_ROS_AT2     <- 3.2e-7      ; label("Neutrophil-ROS induced damage rate of alveolar cells (1/h)")             # PAR k_ROS_AT2
    km_ROS_AT2    <- 5e10        ; label("EC50 (neutrophil count) for ROS-induced alveolar damage (cells)")        # PAR km_ROS_AT2
    k_AT1_AT2     <- 1.069667e-4 ; label("Basal differentiation rate of AT2 to AT1 cells (1/h)")                   # PAR k_AT1_AT2
    km_AT1_AT2    <- 0.9         ; label("Km (fraction of baseline deficit) for AT2 regeneration/differentiation") # PAR km_AT1_AT2
    k_mu_AT2      <- 30          ; label("Amplification of AT2 regeneration by alveolar-cell deficit (unitless)")  # PAR k_mu_AT2
    k_diff_AT1    <- 30          ; label("Amplification of AT2->AT1 differentiation by AT1 deficit (unitless)")    # PAR k_diff_AT1
    b_AT2         <- 1.6045e-4   ; label("Death rate of healthy AT2 cells (1/h)")                                  # PAR b_AT2
    b_AT1         <- 1.6045e-4   ; label("Death rate of healthy AT1 cells (1/h)")                                  # PAR b_AT1
    b_I           <- 0.015       ; label("Non-specific death rate of infected cells (1/h)")                        # PAR b_I
    b_dAT1        <- 0.05        ; label("Death rate of damaged AT1 (and AT2) cells (1/h)")                        # PAR b_dAT1
    k_kill        <- 1.841659e-8 ; label("CTL-mediated killing rate of infected cells (1/cell/h)")                 # PAR k_kill
    k_IFNb_kill   <- 0.022       ; label("Type I IFN potentiation of infected-cell death (1/pmol)")                # PAR k_IFNb_kill
    hAT1          <- 2e10        ; label("Homeostatic healthy AT1 cell number (cells)")                            # PAR IC sheet AT1; DXDT p.hAT1
    hAT2          <- 3e10        ; label("Homeostatic healthy AT2 cell number (cells)")                            # PAR IC sheet AT2; DXDT p.hAT2

    # ---- Cytokine-mediated alveolar damage (Suppl. Eq. 2) ---------------
    k_damage_cyt   <- 0.05       ; label("Overall scaling of cytokine-mediated alveolar damage (1/h)")             # PAR k_damage_cyt
    k_damage_TNFa  <- 0.01       ; label("Relative weight of TNFa-induced alveolar damage (unitless)")             # PAR k_damage_TNFa
    km_damage_TNFa <- 3.193344e5 ; label("EC50 for TNFa-induced alveolar damage (pmol)")                           # PAR km_damage_TNFa
    k_damage_IL6   <- 0.01       ; label("Relative weight of IL-6-induced alveolar damage (unitless)")             # PAR k_damage_IL6
    km_damage_IL6  <- 1.1592e4   ; label("EC50 for IL-6-induced alveolar damage (pmol)")                           # PAR km_damage_IL6
    k_damage_IL1b  <- 0.01       ; label("Relative weight of IL-1b-induced alveolar damage (unitless)")            # PAR k_damage_IL1b
    km_damage_IL1b <- 1.7274e6   ; label("EC50 for IL-1b-induced alveolar damage (pmol)")                          # PAR km_damage_IL1b
    k_damage_IFNg  <- 0.005      ; label("Relative weight of IFN-g-induced alveolar damage (unitless)")            # PAR k_damage_IFNg
    km_damage_IFNg <- 5.32224e4  ; label("EC50 for IFN-g-induced alveolar damage (pmol)")                          # PAR km_damage_IFNg

    # ---- Log-sensing innate activation (Rao 2023 Methods; Suppl. Eq. 7-9)
    k_v   <- 3e-3   ; label("Log-sensing weight of viable virus on innate-cell activation (unitless)")             # PAR k_v
    k_I   <- 3e-4   ; label("Log-sensing weight of infected cells on innate-cell activation (unitless)")           # PAR k_I
    k_dAT <- 3e-5   ; label("Log-sensing weight of damaged alveolar cells on innate-cell activation (unitless)")   # PAR k_dAT

    # ---- Dendritic cells (Suppl. Eq. 7) ---------------------------------
    a_DC       <- 6.9e5      ; label("Rate constant for maturation of dendritic cells (cells/h)")                  # PAR a_DC
    kbasal_DC  <- 0          ; label("Basal activation of dendritic cells (unitless)")                             # PAR kbasal_DC
    b_DC       <- 5.208333e-3; label("Death rate of mature dendritic cells (1/h)")                                 # PAR b_DC
    lb_DC      <- 2          ; label("Lung clearance adjustment factor for dendritic cells (unitless)")            # PAR lb_DC
    k_DC_TNFa  <- 10         ; label("DC maturation induced by TNFa (unitless)")                                   # PAR k_DC_TNFa
    km_DC_TNFa <- 3.193344e3 ; label("EC50 for DC maturation by TNFa (pmol)")                                      # PAR km_DC_TNFa
    k_DC_IFNg  <- 10         ; label("DC maturation induced by IFN-g (unitless)")                                  # PAR k_DC_IFNg
    km_DC_IFNg <- 1.064448e3 ; label("EC50 for DC maturation by IFN-g (pmol)")                                     # PAR km_DC_IFNg
    km_DC_IL10 <- 46.2672    ; label("IC50 for IL-10 inhibition of DC maturation (pmol)")                          # PAR km_DC_IL10
    mtr        <- 0.05       ; label("Transit rate of mature DC into the antigen-presenting pool pDC1 (1/h)")       # DXDT mtr (and kdie = mtr)

    # ---- Macrophages (Suppl. Eq. 8) -------------------------------------
    a_M1        <- 2.5e6      ; label("Rate constant for activation of macrophages (cells/h)")                     # PAR a_M1
    kbasal_M1   <- 0          ; label("Basal activation of macrophages (unitless)")                                # PAR kbasal_M1
    b_M1        <- 2.791667e-3; label("Death rate of activated macrophages (1/h)")                                 # PAR b_M1
    pb_M1       <- 4          ; label("Plasma monocyte clearance adjustment factor (unitless)")                    # PAR pb_M1
    k_M1_TNFa   <- 10         ; label("Macrophage activation induced by TNFa (unitless)")                          # PAR k_M1_TNFa
    km_M1_TNFa  <- 3.2006e3   ; label("EC50 for macrophage activation by TNFa (pmol)")                             # PAR km_M1_TNFa
    k_M1_GMCSF  <- 10         ; label("Macrophage (and DC) activation induced by GM-CSF (unitless)")               # PAR k_M1_GMCSF
    km_M1_GMCSF <- 567.302    ; label("EC50 for macrophage (and DC) activation by GM-CSF (pmol)")                  # PAR km_M1_GMCSF
    k_M1_IFNg   <- 10         ; label("Macrophage activation induced by IFN-g (unitless)")                         # PAR k_M1_IFNg
    km_M1_IFNg  <- 800.15     ; label("EC50 for macrophage activation by IFN-g (pmol)")                            # PAR km_M1_IFNg
    km_M1_IL10  <- 167.409    ; label("IC50 for IL-10 inhibition of macrophage activation (pmol)")                 # PAR km_M1_IL10

    # ---- Neutrophils (Suppl. Eq. 9) -------------------------------------
    a_N        <- 7.935427e10; label("Rate constant for activation of neutrophils (cells/h)")                      # PAR a_N
    kbasal_N   <- 0          ; label("Basal recruitment of activated neutrophils (unitless)")                      # PAR kbasal_N
    b_N        <- 0.1236014  ; label("Death rate of activated neutrophils (1/h)")                                  # PAR b_N
    k_N_IFNg   <- 10         ; label("Neutrophil activation induced by IFN-g (unitless)")                          # PAR k_N_IFNg
    km_N_IFNg  <- 5.32224e4  ; label("EC50 for neutrophil activation by IFN-g (pmol)")                             # PAR km_N_IFNg
    k_N_TNFa   <- 0.1        ; label("Neutrophil activation induced by TNFa (unitless)")                           # PAR k_N_TNFa
    km_N_TNFa  <- 5.26176e3  ; label("EC50 for neutrophil activation by TNFa (pmol)")                              # PAR km_N_TNFa
    k_N_GMCSF  <- 1          ; label("Neutrophil activation induced by GM-CSF (unitless)")                         # PAR k_N_GMCSF
    km_N_GMCSF <- 725.76     ; label("EC50 for neutrophil activation by GM-CSF (pmol)")                            # PAR km_N_GMCSF
    k_N_IL17c  <- 10         ; label("Neutrophil recruitment by plasma IL-17 (cells/h)")                           # PAR k_N_IL17c
    km_N_IL17c <- 2.23776e3  ; label("EC50 for neutrophil recruitment by plasma IL-17 (pmol/mL)")                  # PAR km_N_IL17c

    # ---- CD4+ Th1 cells (Suppl. Eq. 10) ---------------------------------
    a_Th1         <- 4e-3      ; label("Rate constant for activation of Th1 cells (1/h)")                          # PAR a_Th1
    b_Th1         <- 1.962917e-2; label("Death rate of activated Th1 cells (1/h)")                                 # PAR b_Th1
    k_Th1_IL2     <- 1.5      ; label("Th1 activation induced by IL-12 (unitless)")                                # PAR k_Th1_IL2
    K_Th1_IL12    <- 0.501984 ; label("EC50 for Th1 activation by IL-12 (pmol)")                                   # PAR K_Th1_IL12
    k_Th1_IL12IL2 <- 2        ; label("IL-2 potentiation of IL-12-driven Th1 activation (unitless)")               # PAR k_Th1_IL12IL2
    K_Th1_IL12IL2 <- 7.52976  ; label("EC50 for IL-2 potentiation of Th1 activation (pmol)")                       # PAR K_Th1_IL12IL2
    K_Th1_IL10    <- 3.251606e4; label("IC50 for IL-10 inhibition of Th1 activation (pmol)")                       # PAR K_Th1_IL10
    K_Th1_TGFb    <- 1.832731e6; label("IC50 for TGF-b inhibition of Th1 activation (pmol)")                       # PAR K_Th1_TGFb
    k_Th1_IFNg    <- 1        ; label("Th1 activation induced by IFN-g (unitless)")                                # PAR k_Th1_IFNg
    K_IFNg_Th1    <- 931.392  ; label("EC50 for Th1 activation by IFN-g (pmol)")                                   # PAR K_IFNg_Th1
    K_Th1_IL6     <- 2.676106e5; label("IC50 for IL-6 inhibition of IFN-g-driven Th1 activation (pmol)")           # PAR K_Th1_IL6
    k_Th1_Th17    <- 0.01     ; label("Differentiation rate of Th17 to Th1 cells (1/h)")                           # PAR k_Th1_Th17
    K_Th1_Th17    <- 3.28608e-2; label("EC50 (IL-12) for Th17 to Th1 differentiation (pmol)")                      # PAR K_Th1_Th17
    k_Th1_Treg    <- 5e-3     ; label("Differentiation rate of Treg to Th1 cells (1/h)")                           # PAR k_Th1_Treg
    K_Th1_Treg    <- 20.9261  ; label("EC50 (IL-12) for Treg to Th1 differentiation (pmol)")                       # PAR K_Th1_Treg

    # ---- CD4+ Th17 cells (Suppl. Eq. 11) --------------------------------
    a_Th17       <- 6.92e-3   ; label("Rate constant for activation of Th17 cells (1/h)")                          # PAR a_Th17
    b_Th17       <- 2.161250e-2; label("Death rate of activated Th17 cells (1/h)")                                 # PAR b_Th17
    k_Th17_TGFb  <- 4         ; label("Th17 activation induced by TGF-b (unitless)")                               # PAR k_Th17_TGFb
    K_Th17_TGFb  <- 638.3717  ; label("EC50 for Th17 activation by TGF-b (pmol)")                                  # PAR K_Th17_TGFb
    k_Th17_IL6   <- 1         ; label("Th17 activation induced by IL-6 (unitless)")                                # PAR k_Th17_IL6
    km_Th17_IL6  <- 42.336    ; label("EC50 for Th17 activation by IL-6 (pmol)")                                   # PAR km_Th17_IL6
    k_Th17_IL1b  <- 1         ; label("Th17 activation induced by IL-1b (unitless)")                               # PAR k_Th17_IL1b
    km_Th17_IL1b <- 2.072893e4; label("EC50 for Th17 activation by IL-1b (pmol)")                                  # PAR km_Th17_IL1b
    K_Th17_IL2   <- 7.032556e6; label("IC50 for IL-2 inhibition of Th17 activation (pmol)")                        # PAR K_Th17_IL2
    K_Th17_IFNg  <- 6.833902e6; label("IC50 for IFN-g inhibition of Th17 activation (pmol)")                       # PAR K_Th17_IFNg
    K_Th17_IL10  <- 1.359101e6; label("IC50 for IL-10 inhibition of Th17 activation (pmol)")                       # PAR K_Th17_IL10

    # ---- CD8+ cytotoxic T cells (Suppl. Eq. 1 and 12) -------------------
    a_CTL         <- 2.1645e-3 ; label("Rate constant for CTL activation (1/h)")                                   # PAR a_CTL
    b_CTL         <- 1.96e-2   ; label("Death rate of activated CTL (1/h)")                                        # PAR b_CTL
    k_CTL_IL2     <- 3         ; label("CTL activation induced by IL-12 (unitless)")                               # PAR k_CTL_IL2
    K_CTL_IL12    <- 7.52976   ; label("EC50 for CTL activation by IL-12 (pmol)")                                  # PAR K_CTL_IL12
    k_CTL_IL12IL2 <- 4         ; label("Potentiation of IL-12-driven CTL activation (unitless)")                   # PAR k_CTL_IL12IL2
    K_CTL_IL12IL2 <- 7.52976   ; label("EC50 for potentiation of CTL activation (pmol)")                           # PAR K_CTL_IL12IL2
    K_CTL_IL10    <- 3.251606e4; label("IC50 for IL-10 inhibition of CTL activation (pmol)")                       # PAR K_CTL_IL10
    K_CTL_TGFb    <- 1.832731e6; label("IC50 for TGF-b inhibition of CTL activation (pmol)")                       # PAR K_CTL_TGFb
    K_CTL_IL6     <- 5.352212e5; label("IC50 for IL-6 inhibition of CTL activation (pmol)")                        # PAR K_CTL_IL6
    k_CTL_IFNg    <- 1         ; label("CTL activation induced by IFN-g (unitless)")                               # PAR k_CTL_IFNg
    K_CTL_IFNg    <- 931.392   ; label("EC50 for CTL activation by IFN-g (pmol)")                                  # PAR K_CTL_IFNg
    kmax_MHC1     <- 1         ; label("Maximal type I IFN / MHC-I potentiation of CTL activation (unitless)")     # PAR kmax_MHC1
    km_MHC1_IFNb  <- 5         ; label("EC50 for type I IFN / MHC-I potentiation of CTL activation (pmol)")        # PAR km_MHC1_IFNb

    # ---- CD4+ Treg cells (Suppl. Eq. 13) --------------------------------
    a_Treg      <- 4e-3       ; label("Rate constant for Treg activation (1/h)")                                   # PAR a_Treg
    b_Treg      <- 1.479167e-2; label("Death rate of activated Treg cells (1/h)")                                  # PAR b_Treg
    k_Treg_IL2  <- 1          ; label("Treg activation induced by IL-2 (unitless)")                                # PAR k_Treg_IL2
    K_Treg_IL2  <- 1.796256   ; label("EC50 for Treg activation by IL-2 (pmol)")                                   # PAR K_Treg_IL2
    k_Treg_TGFb <- 1          ; label("Treg activation induced by TGF-b (unitless)")                               # PAR k_Treg_TGFb
    K_Treg_TGFb <- 32.256     ; label("EC50 for Treg activation by TGF-b (pmol)")                                  # PAR K_Treg_TGFb
    K_Treg_IL17 <- 4.917073e5 ; label("IC50 for IL-17 inhibition of Treg activation (pmol)")                       # PAR K_Treg_IL17
    K_Treg_IL6  <- 5.352212e5 ; label("IC50 for IL-6 inhibition of Treg activation (pmol)")                        # PAR K_Treg_IL6

    # ---- Cytokine production / clearance (Suppl. Eq. 14-24) -------------
    a_tnf       <- 6.487987e-2; label("Overall scaling of TNFa production (unitless)")                             # PAR a_tnf
    basal_tnfa  <- 3600       ; label("Basal TNFa production term (cells-equivalent)")                             # PAR basal_tnfa
    a_tnf_at1   <- 1.4e-4     ; label("TNFa production by damaged AT1 cells (pmol/cell/h)")                        # PAR a_tnf_at1
    a_tnf_at2   <- 1.4e-4     ; label("TNFa production by damaged AT2 cells (pmol/cell/h)")                        # PAR a_tnf_at2
    a_tnf_i     <- 1.4e-5     ; label("TNFa production by infected AT2 cells (pmol/cell/h)")                       # PAR a_tnf_i
    a_tnf_m1    <- 2.1e-4     ; label("TNFa production by activated macrophages (pmol/cell/h)")                    # PAR a_tnf_m1
    a_tnf_th1   <- 1.128e-9   ; label("TNFa production by activated Th1 cells (pmol/cell/h)")                      # PAR a_tnf_th1
    a_tnf_th17  <- 1.128e-9   ; label("TNFa production by activated Th17 cells (pmol/cell/h)")                     # PAR a_tnf_th17
    b_tnf       <- 3.16       ; label("Clearance rate of TNFa (1/h)")                                              # PAR b_tnf

    a_il6       <- 1.69344e-2 ; label("Overall scaling of IL-6 production (unitless)")                             # PAR a_il6
    basalil6    <- 40         ; label("Basal IL-6 production term (cells-equivalent)")                             # PAR basalil6
    a_il6_at1   <- 3.122e-6   ; label("IL-6 production by damaged AT1 cells (pmol/cell/h)")                        # PAR a_il6_at1
    a_il6_at2   <- 3.122e-6   ; label("IL-6 production by damaged AT2 cells (pmol/cell/h)")                        # PAR a_il6_at2
    a_il6_i     <- 6.244e-7   ; label("IL-6 production by infected AT2 cells (pmol/cell/h)")                       # PAR a_il6_i
    a_il6_m1    <- 2.8952e-4  ; label("IL-6 production by activated macrophages (pmol/cell/h)")                    # PAR a_il6_m1
    a_il6_th17  <- 2.4976e-4  ; label("IL-6 production by activated Th17 cells (pmol/cell/h)")                     # PAR a_il6_th17
    a_il6_neu   <- 1.0836e-8  ; label("IL-6 production by activated neutrophils (pmol/cell/h)")                    # PAR a_il6_neu
    b_il6       <- 1.32       ; label("Clearance rate of IL-6 (1/h)")                                              # PAR b_il6

    a_il1b      <- 0.84672    ; label("Overall scaling of IL-1b production (unitless)")                            # PAR a_il1b
    basalil1    <- 0.2857143  ; label("Basal IL-1b production term (cells-equivalent)")                            # PAR basalil1
    a_il1b_at2  <- 2.585e-9   ; label("IL-1b production by damaged AT1 and AT2 cells (pmol/cell/h)")               # PAR a_il1b_at2
    a_il1b_i    <- 2.068e-9   ; label("IL-1b production by infected AT2 cells (pmol/cell/h)")                      # PAR a_il1b_i
    a_il1b_m1   <- 2.068e-8   ; label("IL-1b production by activated macrophages (pmol/cell/h)")                   # PAR a_il1b_m1
    a_il1b_dc   <- 1.035e-7   ; label("IL-1b production by mature dendritic cells (pmol/cell/h)")                  # PAR a_il1b_dc
    b_il1b      <- 0.088      ; label("Clearance rate of IL-1b (1/h)")                                             # PAR b_il1b

    a_ifng      <- 6.34896    ; label("Overall scaling of IFN-g production (unitless)")                            # PAR a_ifng
    basalifng   <- 4          ; label("Basal IFN-g production term (cells-equivalent)")                            # PAR basalifng
    a_ifng_dc   <- 1.085e-8   ; label("IFN-g production by mature dendritic cells (pmol/cell/h)")                  # PAR a_ifng_dc
    a_ifng_th1  <- 6.15e-7    ; label("IFN-g production by activated Th1 cells (pmol/cell/h)")                     # PAR a_ifng_th1
    a_ifng_ctl  <- 2.928e-5   ; label("IFN-g production by activated CTL (pmol/cell/h)")                           # PAR a_ifng_ctl
    b_ifng      <- 3.59       ; label("Clearance rate of IFN-g (1/h)")                                             # PAR b_ifng

    a_ifnb      <- 6.34896e-2 ; label("Overall scaling of type I IFN production (unitless)")                       # PAR a_ifnb
    basalifnb   <- 1600       ; label("Basal type I IFN production term (cells-equivalent)")                       # PAR basalifnb
    a_ifnb_i    <- 7e-5       ; label("Type I IFN production by infected AT2 cells (pmol/cell/h)")                 # PAR a_ifnb_i
    a_ifnb_dc   <- 1.05e-2    ; label("Type I IFN production by mature dendritic cells (pmol/cell/h)")             # PAR a_ifnb_dc
    b_ifnb      <- 1.795      ; label("Clearance rate of type I IFN (1/h)")                                        # PAR b_ifnb

    a_il2       <- 259.6608   ; label("Overall scaling of IL-2 production (unitless)")                             # PAR a_il2
    basalil2    <- 0.01       ; label("Basal IL-2 production term (cells-equivalent)")                             # PAR basalil2
    a_il2_dc    <- 2.8e-7     ; label("IL-2 production by mature dendritic cells (pmol/cell/h)")                   # PAR a_il2_dc
    a_il2_th1   <- 2e-8       ; label("IL-2 production by activated Th1 cells (pmol/cell/h)")                      # PAR a_il2_th1
    b_il2       <- 1.913      ; label("Clearance rate of IL-2 (1/h)")                                              # PAR b_il2

    a_il12      <- 12.0658    ; label("Overall scaling of IL-12 production (unitless)")                            # PAR a_il12
    basalil12   <- 0.4        ; label("Basal IL-12 production term (cells-equivalent)")                            # PAR basalil12
    a_il12_dc   <- 2.49e-7    ; label("IL-12 production by mature dendritic cells (pmol/cell/h)")                  # PAR a_il12_dc
    a_il12_m1   <- 6.18e-8    ; label("IL-12 production by activated macrophages (pmol/cell/h)")                   # PAR a_il12_m1
    b_il12      <- 2.73       ; label("Clearance rate of IL-12 (1/h)")                                             # PAR b_il12

    a_il17      <- 0.1299715  ; label("Overall scaling of IL-17 production (unitless)")                            # PAR a_il17
    a_il17_th17 <- 1.05e-5    ; label("IL-17 production by activated Th17 cells (pmol/cell/h)")                    # PAR a_il17_th17
    a_il17_ctl  <- 3.45e-9    ; label("IL-17 production by activated CTL (pmol/cell/h)")                           # PAR a_il17_ctl
    b_il17      <- 0.0825     ; label("Clearance rate of IL-17 (1/h)")                                             # PAR b_il17

    a_il10      <- 1.362686   ; label("Overall scaling of IL-10 production (unitless)")                            # PAR a_il10
    basalil10   <- 2          ; label("Basal IL-10 production term (cells-equivalent)")                            # PAR basalil10
    a_il10_treg <- 1.146e-5   ; label("IL-10 production by activated Treg cells (pmol/cell/h)")                    # PAR a_il10_treg
    b_il10      <- 1.22       ; label("Clearance rate of IL-10 (1/h)")                                             # PAR b_il10

    a_tgfb      <- 2.150669   ; label("Overall scaling of TGF-b production (unitless)")                            # PAR a_tgfb
    basaltgfb   <- 1          ; label("Basal TGF-b production term (cells-equivalent)")                            # PAR basaltgfb
    a_tgfb_th17 <- 7.42e-6    ; label("TGF-b production by activated Th17 cells (pmol/cell/h)")                    # PAR a_tgfb_th17
    a_tgfb_treg <- 7.15e-6    ; label("TGF-b production by activated Treg cells (pmol/cell/h)")                    # PAR a_tgfb_treg
    b_tgfb      <- 1.9        ; label("Clearance rate of TGF-b (1/h)")                                             # PAR b_tgfb

    a_gmcsf      <- 1.55232   ; label("Overall scaling of GM-CSF production (unitless)")                           # PAR a_gmcsf
    basalgmcsf   <- 4         ; label("Basal GM-CSF production term (cells-equivalent)")                           # PAR basalgmcsf
    a_gmcsf_m1   <- 1.27e-6   ; label("GM-CSF production by activated macrophages (pmol/cell/h)")                  # PAR a_gmcsf_m1
    a_gmcsf_th1  <- 4.29e-8   ; label("GM-CSF production by activated Th1 cells (pmol/cell/h)")                    # PAR a_gmcsf_th1
    a_gmcsf_th17 <- 1.15e-7   ; label("GM-CSF production by activated Th17 cells (pmol/cell/h)")                   # PAR a_gmcsf_th17
    b_gmcsf      <- 1         ; label("Clearance rate of GM-CSF (1/h)")                                            # PAR b_gmcsf

    # ---- Alveolar -> plasma transport (Suppl. Eq. 28-30) ----------------
    ktr_TNFa  <- 0.1 ; label("Alveolar to plasma transport rate of TNFa (1/h)")                                    # PAR ktr_TNFa
    ktr_IL6   <- 0.1 ; label("Alveolar to plasma transport rate of IL-6 (1/h)")                                    # PAR ktr_IL6
    ktr_IL1b  <- 0.1 ; label("Alveolar to plasma transport rate of IL-1b (1/h)")                                   # PAR ktr_IL1b
    ktr_IFNb  <- 0.1 ; label("Alveolar to plasma transport rate of type I IFN (1/h)")                              # PAR ktr_IFNb
    ktr_IFNg  <- 0.1 ; label("Alveolar to plasma transport rate of IFN-g (1/h)")                                   # PAR ktr_IFNg
    ktr_IL2   <- 0.2 ; label("Alveolar to plasma transport rate of IL-2 (1/h)")                                    # PAR ktr_IL2
    ktr_IL12  <- 0.1 ; label("Alveolar to plasma transport rate of IL-12 (1/h)")                                   # PAR ktr_IL12
    ktr_IL17  <- 0.1 ; label("Alveolar to plasma transport rate of IL-17 (1/h)")                                   # PAR ktr_IL17
    ktr_IL10  <- 0.1 ; label("Alveolar to plasma transport rate of IL-10 (1/h)")                                   # PAR ktr_IL10
    ktr_TGFb  <- 0.1 ; label("Alveolar to plasma transport rate of TGF-b (1/h)")                                   # PAR ktr_TGFb
    ktr_GMCSF <- 0.1 ; label("Alveolar to plasma transport rate of GM-CSF (1/h)")                                  # PAR ktr_GMCSF
    ktr_SPD   <- 0.1 ; label("Alveolar to plasma transport rate of SP-D (1/h)")                                    # PAR ktr_SPD
    ktr_FER   <- 0.1 ; label("Alveolar to plasma transport rate of ferritin (1/h)")                                # PAR ktr_FER
    ktr_pDC   <- 1   ; label("Alveolar to plasma transport rate of dendritic cells (1/h)")                         # PAR ktr_pDC
    ktr_M1    <- 1   ; label("Alveolar to plasma transport rate of macrophages (1/h)")                             # PAR ktr_M1
    ktr_N     <- 1   ; label("Alveolar to plasma transport rate of neutrophils (1/h)")                             # PAR ktr_N
    ktr_Th1   <- 1   ; label("Alveolar to plasma transport rate of Th1 cells (1/h)")                               # PAR ktr_Th1
    ktr_Th17  <- 1   ; label("Alveolar to plasma transport rate of Th17 cells (1/h)")                              # PAR ktr_Th17
    ktr_CTL   <- 1   ; label("Alveolar to plasma transport rate of CTL (1/h)")                                     # PAR ktr_CTL
    ktr_Treg  <- 1   ; label("Alveolar to plasma transport rate of Treg cells (1/h)")                              # PAR ktr_Treg

    # ---- Clinical biomarkers (Suppl. Eq. 25-27) -------------------------
    kbasal_SPD        <- 40         ; label("Basal SP-D production rate (pmol/h)")                                 # PAR kbasal_SPD
    a_SPD             <- 5e-7       ; label("SP-D release per damaged/killed alveolar cell (pmol/cell/h)")         # PAR a_SPD
    b_SPD             <- 6.9315e-2  ; label("Plasma clearance rate of SP-D (1/h)")                                 # PAR b_SPD
    k_CTL_I_SPD       <- 0.1        ; label("SP-D release per CTL-killed infected cell (1/cell)")                  # PAR k_CTL_I_SPD
    kbasal_FER        <- 0          ; label("Basal alveolar ferritin production rate (pmol/h)")                    # PAR kbasal_FER
    a_FER             <- 7e-6       ; label("Ferritin release per damaged/killed alveolar cell (pmol/cell/h)")     # PAR a_FER
    b_FER             <- 4.0773e-2  ; label("Plasma clearance rate of ferritin (1/h)")                             # PAR b_FER
    a_FER_c           <- 2.03865e-2 ; label("Basal plasma ferritin production rate (pmol/mL/h)")                   # PAR a_FER_c
    k_CTL_I_Fer       <- 0.1        ; label("Ferritin release per CTL-killed infected cell (1/cell)")              # PAR k_CTL_I_Fer
    k_livercrp        <- 520        ; label("Scaling of hepatic CRP production by plasma IL-6 (pmol/mL/h)")        # PAR k_livercrp
    Liver             <- 1660       ; label("Liver volume (mL)")                                                   # PAR Liver
    kCRPSecretion     <- 1.979167e-2; label("Rate constant for secretion of hepatic CRP (1/h)")                    # PAR kCRPSecretion
    kCRP_LivertoBlood <- 3.685031e-2; label("Transit rate of CRP from liver to blood (1/h)")                       # PAR kCRP_LivertoBlood
    kCRP_BloodtoLiver <- 3.7875e-2  ; label("Transit rate of CRP from blood to liver (1/h)")                       # PAR kCRP_BloodtoLiver
    kdeg_CRP          <- 0.12       ; label("Degradation rate of CRP (1/h)")                                       # PAR kdeg_CRP
    kbasal_CRP        <- 7.816667   ; label("Basal production rate of CRP in blood (pmol/mL/h)")                   # PAR kbasal_CRP

    # ---- Infection switch and abortive-infection threshold --------------
    hVI     <- 1    ; label("Viral-infection switch: 1 = infection simulation, 0 = healthy burn-in (unitless)")    # DXDT p.hVI; function_run_model_noplots.m
    v_abort <- 1e4  ; label("Post-peak viral load below which new infection ceases (viral RNA copies/mL)")         # Rao 2023 Methods; DXDT covidEventsFcn.m
    t_vpeak_arm <- 1; label("Time above v_abort needed to arm the abortive-infection switch (h)")                  # numerical regularization of the MATLAB terminal event; see vignette Errata

    # ---- Antiviral (molnupiravir / EIDD-1931) sub-model ------------------
    Imax     <- 0    ; label("Maximal inhibition of viable-virus production by the antiviral (unitless)")          # PAR Imax (0 = off); set to 1 for molnupiravir per Rao 2023 Methods
    IC50_av  <- 1086 ; label("EIDD-1931 plasma IC50 for inhibition of virus production (ng/mL)")                   # DXDT scripts/molnupiravir_sfig.m IC50_av
    nhill    <- 1    ; label("Hill coefficient of the antiviral inhibition function (unitless)")                   # DXDT p.nhill = 1

    # ---- Exogenous neutralizing-antibody cocktail sub-model --------------
    # Defaults are the Blaze-1 / Lilly ('LY') cocktail: nAb 1 = bamlanivimab,
    # nAb 2 = etesevimab. See the vignette for the REGEN-COV ('REGN')
    # parameter set (casirivimab + imdevimab).
    Imaxbnab   <- 0.30      ; label("Maximal neutralization of viral entry by the nAb cocktail (unitless)")        # DXDT case 'LY' Imaxbnab
    IC50_bnAb1 <- 0.3       ; label("Neutralization IC50 of nAb 1, bamlanivimab (ug/mL)")                          # DXDT case 'LY' IC50_bnAb1
    IC50_bnAb2 <- 0.09      ; label("Neutralization IC50 of nAb 2, etesevimab (ug/mL)")                            # DXDT case 'LY' IC50_bnAb2
    nhillab    <- 1         ; label("Hill coefficient of the nAb neutralization function (unitless)")              # DXDT nhillab = 1
    CL_Aba     <- 0.01125   ; label("Clearance of nAb 1, bamlanivimab (L/h)")                                      # DXDT case 'LY' CL_Aba = 0.27/24
    Qa         <- 0.015625  ; label("Inter-compartmental clearance of nAb 1 (L/h)")                                # DXDT case 'LY' Qa = 0.375/24
    V_Ab1a     <- 2.87      ; label("Central volume of nAb 1 (L)")                                                 # DXDT case 'LY' V_Ab1a
    V_Ab2a     <- 2.71      ; label("Peripheral volume of nAb 1 (L)")                                              # DXDT case 'LY' V_Ab2a
    CL_Abb     <- 0.00533333; label("Clearance of nAb 2, etesevimab (L/h)")                                        # DXDT case 'LY' CL_Abb = 0.128/24
    Qb         <- 0.02141667; label("Inter-compartmental clearance of nAb 2 (L/h)")                                # DXDT case 'LY' Qb = 0.514/24
    V_Ab1b     <- 2.38      ; label("Central volume of nAb 2 (L)")                                                 # DXDT case 'LY' V_Ab1b
    V_Ab2b     <- 1.98      ; label("Peripheral volume of nAb 2 (L)")                                              # DXDT case 'LY' V_Ab2b

    # ---- Endogenous antibody response ------------------------------------
    tau_Ab_Igx  <- 504  ; label("Time post infection at which the endogenous Ab response starts (h)")              # DXDT scripts p.tau_Ab_Igx = 24*21
    k_prod_igx  <- 2    ; label("Zero-order production rate of endogenous antibody (mg/h)")                        # DXDT k_prod_igx
    thalf_Igx   <- 51   ; label("Half-life parameter of the endogenous antibody (h)")                              # DXDT thalf_Igx
    V_Ab_Igx    <- 3.5  ; label("Distribution volume of the endogenous antibody (L)")                              # DXDT V_Ab_Igx
    IC50_Igx    <- 3    ; label("Neutralization IC50 of the endogenous antibody (ug/mL)")                          # DXDT IC50_Igx (post tau_Ab_Igx)
    ImaxIgx     <- 1    ; label("Maximal neutralization by the endogenous antibody (unitless)")                    # DXDT ImaxIgx
  })

  model({
    # =====================================================================
    # 0. Structural constants (Rao 2023 code release src/get_data_dictionary.m)
    # =====================================================================
    # 480e6 alveoli * 4.2e6 um^3 each * 1e-15 L/um^3 * 1000 mL/L = 2016 mL
    vol_alv_ml <- 2016
    vol_plasma <- 5000        # mL

    # Cytokine molecular weights (g/mol) used only to convert the plasma
    # states from pmol/mL to the clinically reported pg/mL.
    mw_il6   <- 21000
    mw_il2   <- 15500
    mw_il1b  <- 17500
    mw_il10  <- 18000
    mw_il12  <- 70000
    mw_il17  <- 35000
    mw_tnfa  <- 25900
    mw_ifnb  <- 20000
    mw_ifng  <- 23000
    mw_tgfb  <- 4760
    mw_gmcsf <- 25000

    # Antiviral plasma concentration enters as a time-varying regressor
    # (linearly interpolated between event rows), mirroring the MATLAB
    # implementation's interp1() call on the digitized Painter 2021 profile.
    linear(CP_EIDD_NGML)

    # =====================================================================
    # 1. Treatment concentrations and effects
    # =====================================================================
    CONC1     <- Ab / V_Ab1a          # nAb 1 plasma concentration, ug/mL (= mg/L)
    CONC2     <- Ab21 / V_Ab1b        # nAb 2 plasma concentration, ug/mL
    CONC_Igx  <- Ab_Igx / V_Ab_Igx    # endogenous Ab plasma concentration, ug/mL

    # Antiviral (molnupiravir/EIDD-1931): Imax inhibition of viable virus
    # production from infected cells.
    av_inhib <- 1 - Imax * CP_EIDD_NGML^nhill /
      (IC50_av^nhill + CP_EIDD_NGML^nhill)

    # nAb cocktail: the two antibodies contribute additively to the
    # neutralization of viral entry (Rao 2023 Suppl. "Incorporation of
    # anti-viral and SARS-CoV-2 neutralizing antibody cocktail treatment
    # effects").
    nab_inhib <- 1 - Imaxbnab *
      (CONC1^nhillab / (CONC1^nhillab + IC50_bnAb1^nhillab) +
         CONC2^nhillab / (CONC2^nhillab + IC50_bnAb2^nhillab))

    igx_inhib <- 1 - ImaxIgx * CONC_Igx / (CONC_Igx + IC50_Igx)

    # =====================================================================
    # 2. Abortive-infection latch
    # =====================================================================
    # The MATLAB implementation uses a terminal ODE event (covidEventsFcn.m)
    # with direction = -1, so it fires only when V falls back DOWN through
    # v_abort; integration then restarts with k_int = 0 and the virus can no
    # longer infect new susceptible cells. rxode2 has no terminal events, so
    # the same behaviour is reproduced with a single monotone latch state:
    # vpeaked accumulates the time (h) that V has spent above v_abort. Once
    # that exceeds t_vpeak_arm the switch is armed, and infection stops as
    # soon as V drops back below v_abort. The arming window is what makes
    # the encoding directional: without it, solver noise at the *rising*
    # crossing of v_abort would trip the switch before the viral peak.
    kint_on <- 1 - (vpeaked > t_vpeak_arm) * (V < v_abort)

    # =====================================================================
    # 3. Alveolar cell dynamics (Suppl. Eq. 1-6)
    # =====================================================================
    damage_cyt_AT <- k_damage_cyt *
      (k_damage_TNFa * (TNFa / (km_damage_TNFa + TNFa)) +
         k_damage_IL6 * (IL6 / (km_damage_IL6 + IL6)) +
         k_damage_IL1b * (IL1b / (km_damage_IL1b + IL1b)) +
         k_damage_IFNg * (IFNg / (km_damage_IFNg + IFNg)))
    damage_ROS_AT2 <- k_ROS_AT2 * N / (km_ROS_AT2 + N)

    # Alveolar-cell deficit relative to the homeostatic totals, floored at 0
    # (MATLAB max(...,0)).
    dAT_def_raw <- ((hAT1) + (hAT2)) - (AT2 + AT1)
    dAT_def     <- dAT_def_raw * (dAT_def_raw > 0)
    AT1_def_raw <- hAT1 - AT1
    AT1_def     <- AT1_def_raw * (AT1_def_raw > 0)

    growth_AT2 <- mu_AT2 *
      (1 + k_mu_AT2 * (dAT_def / (km_AT1_AT2 * ((hAT1) + (hAT2)) + dAT_def))) * AT2
    diff_AT2   <- k_AT1_AT2 * AT2 *
      (1 + k_diff_AT1 * AT1_def / (km_AT1_AT2 * hAT1 + AT1_def))
    growth_AT1 <- mu_AT1 * (hAT1 - AT1)

    virus_endocytosis <- kint_on * k_int * AT2 * V *
      (km_int_IFNb / (km_int_IFNb + IFNb)) * nab_inhib * igx_inhib

    prod_virus_shedding <- A_V * I * av_inhib
    kill_CTL_I          <- k_kill * I * CTL
    deg_I               <- b_I * I * (1 + k_IFNb_kill * IFNb)

    d/dt(V)    <- hVI * (prod_virus_shedding - b_V * V)
    d/dt(AT2)  <- growth_AT2 - virus_endocytosis - damage_ROS_AT2 * AT2 -
      b_AT2 * AT2 - damage_cyt_AT * AT2 - diff_AT2
    d/dt(I)    <- virus_endocytosis - deg_I - kill_CTL_I - damage_ROS_AT2 * I
    d/dt(AT1)  <- growth_AT1 - damage_ROS_AT2 * AT1 - b_AT1 * AT1 -
      damage_cyt_AT * AT1 + diff_AT2
    d/dt(dAT1) <- damage_ROS_AT2 * AT1 - b_dAT1 * dAT1 + damage_cyt_AT * AT1
    d/dt(dAT2) <- damage_ROS_AT2 * (I + AT2) - b_dAT1 * dAT2 +
      damage_cyt_AT * AT2

    # Latch state (see section 2): hours spent above the abortive threshold
    d/dt(vpeaked) <- (V > v_abort)

    # =====================================================================
    # 4. Innate immune cells (Suppl. Eq. 7-9)
    # =====================================================================
    # Log-sensing (Weber-Fechner) antigen term shared by DC, M1 and N.
    logsense <- k_v * log(1 + V) + k_I * log(1 + I) +
      k_dAT * log(dAT1 + dAT2)

    act_pDC_TNFa  <- k_DC_TNFa * (TNFa / (km_DC_TNFa + TNFa))
    act_pDC_IFNg  <- k_DC_IFNg * (IFNg / (km_DC_IFNg + IFNg))
    act_pDC_GMCSF <- k_M1_GMCSF * (GMCSF / (km_M1_GMCSF + GMCSF))
    inh_pDC_IL10  <- km_DC_IL10 / (km_DC_IL10 + IL10)
    tr_pDC        <- ktr_pDC * (pDC / vol_alv_ml - pDC_c)

    d/dt(pDC) <- a_DC * (kbasal_DC + logsense) *
      (1 + act_pDC_TNFa + act_pDC_IFNg + act_pDC_GMCSF) * inh_pDC_IL10 -
      lb_DC * b_DC * pDC - tr_pDC * vol_alv_ml

    # Transit compartment introducing the delay between DC maturation and
    # activation of the adaptive immune cells.
    d/dt(pDC1) <- mtr * (pDC - mtr * pDC1)

    act_M1_TNFa  <- k_M1_TNFa * (TNFa / (km_M1_TNFa + TNFa))
    act_M1_GMCSF <- k_M1_GMCSF * (GMCSF / (km_M1_GMCSF + GMCSF))
    act_M1_IFNg  <- k_M1_IFNg * (IFNg / (km_M1_IFNg + IFNg))
    inh_M1_IL10  <- km_M1_IL10 / (km_M1_IL10 + IL10)
    tr_M1        <- ktr_M1 * (M1 / vol_alv_ml - M1_c)

    d/dt(M1) <- a_M1 * (kbasal_M1 + logsense) *
      (1 + act_M1_TNFa + act_M1_GMCSF + act_M1_IFNg) * inh_M1_IL10 -
      b_M1 * M1 - tr_M1 * vol_alv_ml

    act_N_IFNg  <- k_N_IFNg * IFNg / (IFNg + km_N_IFNg)
    act_N_TNFa  <- k_N_TNFa * TNFa / (TNFa + km_N_TNFa)
    act_N_GMCSF <- k_N_GMCSF * GMCSF / (GMCSF + km_N_GMCSF)
    rec_N_IL17c <- k_N_IL17c * IL17_c / (IL17_c + km_N_IL17c)
    tr_N        <- ktr_N * (N / vol_alv_ml - N_c)

    d/dt(N) <- a_N * (kbasal_N + logsense) *
      (1 + act_N_IFNg + act_N_TNFa + act_N_GMCSF) + rec_N_IL17c -
      b_N * N - tr_N * vol_alv_ml

    # =====================================================================
    # 5. Adaptive immune cells (Suppl. Eq. 10-13)
    # =====================================================================
    act_Th1_IL12      <- k_Th1_IL2 * (IL12 / (K_Th1_IL12 + IL12)) *
      (1 + k_Th1_IL12IL2 * (IL2 / (K_Th1_IL12IL2 + IL2)))
    act_Th1_IFNg      <- k_Th1_IFNg * (IFNg / (K_IFNg_Th1 + IFNg)) *
      (K_Th1_IL6 / (K_Th1_IL6 + IL6))
    inh_Th1_IL10_TGFb <- (K_Th1_IL10 / (K_Th1_IL10 + IL10)) *
      (K_Th1_TGFb / (K_Th1_TGFb + TGFb))
    diff_Th1_Th17     <- k_Th1_Th17 * Th17 * (IL12 / (K_Th1_Th17 + IL12)) *
      (K_Th1_TGFb / (K_Th1_TGFb + TGFb))
    diff_Th1_Treg     <- k_Th1_Treg * Treg * (IL12 / (K_Th1_Treg + IL12))
    tr_Th1            <- ktr_Th1 * (Th1 / vol_alv_ml - Th1_c)

    d/dt(Th1) <- a_Th1 * pDC1 * (act_Th1_IL12 + act_Th1_IFNg) *
      inh_Th1_IL10_TGFb + diff_Th1_Th17 + diff_Th1_Treg -
      b_Th1 * Th1 - tr_Th1 * vol_alv_ml

    inh_Th17        <- (K_Th17_IL2 / (K_Th17_IL2 + IL2)) *
      (K_Th17_IFNg / (K_Th17_IFNg + IFNg)) *
      (K_Th17_IL10 / (K_Th17_IL10 + IL10))
    act_Th17_TGFb   <- k_Th17_TGFb * (TGFb / (K_Th17_TGFb + TGFb)) * inh_Th17
    act_Th17_IL6    <- k_Th17_IL6 * (IL6 / (km_Th17_IL6 + IL6)) * inh_Th17
    act_Th17_IL1b   <- k_Th17_IL1b * (IL1b / (km_Th17_IL1b + IL1b)) * inh_Th17
    tr_Th17         <- ktr_Th17 * (Th17 / vol_alv_ml - Th17_c)

    d/dt(Th17) <- a_Th17 * pDC1 *
      (act_Th17_TGFb + act_Th17_IL6 + act_Th17_IL1b) - diff_Th1_Th17 -
      b_Th17 * Th17 - tr_Th17 * vol_alv_ml

    act_CTL_IFNb <- kmax_MHC1 * (IFNb / (km_MHC1_IFNb + IFNb))
    act_CTL_IL12 <- k_CTL_IL2 * (IL12 / (K_CTL_IL12 + IL12)) *
      (1 + k_CTL_IL12IL2 * (IL12 / (K_CTL_IL12IL2 + IL12))) *
      (K_CTL_IL10 / (K_CTL_IL10 + IL10)) *
      (K_CTL_TGFb / (K_CTL_TGFb + TGFb))
    act_CTL_IFNg <- k_CTL_IFNg * (IFNg / (K_CTL_IFNg + IFNg)) *
      (K_CTL_IL10 / (K_CTL_IL10 + IL10)) *
      (K_CTL_TGFb / (K_CTL_TGFb + TGFb)) *
      (K_CTL_IL6 / (K_CTL_IL6 + IL6))
    tr_CTL       <- ktr_CTL * (CTL / vol_alv_ml - CTL_c)

    d/dt(CTL) <- a_CTL * pDC1 * (1 + act_CTL_IFNb) *
      (1 + act_CTL_IL12 + act_CTL_IFNg) - b_CTL * CTL - tr_CTL * vol_alv_ml

    act_Treg_IL2  <- k_Treg_IL2 * (IL2 / (K_Treg_IL2 + IL2)) *
      (K_Treg_IL17 / (K_Treg_IL17 + IL17)) *
      (K_Treg_IL6 / (K_Treg_IL6 + IL6))
    act_Treg_TGFb <- k_Treg_TGFb * (TGFb / (K_Treg_TGFb + TGFb)) *
      (K_Treg_IL17 / (K_Treg_IL17 + IL17)) *
      (K_Treg_IL6 / (K_Treg_IL6 + IL6))
    tr_Treg       <- ktr_Treg * (Treg / vol_alv_ml - Treg_c)

    d/dt(Treg) <- a_Treg * pDC1 * (act_Treg_IL2 + act_Treg_TGFb) -
      diff_Th1_Treg - b_Treg * Treg - tr_Treg * vol_alv_ml

    # =====================================================================
    # 6. Alveolar cytokines (Suppl. Eq. 14-24)
    # =====================================================================
    tr_TNFa  <- ktr_TNFa * TNFa
    tr_IL6   <- ktr_IL6 * IL6
    tr_IL1b  <- ktr_IL1b * IL1b
    tr_IFNb  <- ktr_IFNb * IFNb
    tr_IFNg  <- ktr_IFNg * IFNg
    tr_IL2   <- ktr_IL2 * IL2
    tr_IL12  <- ktr_IL12 * IL12
    tr_IL17  <- ktr_IL17 * IL17
    tr_IL10  <- ktr_IL10 * IL10
    tr_TGFb  <- ktr_TGFb * TGFb
    tr_GMCSF <- ktr_GMCSF * GMCSF
    tr_SPD   <- ktr_SPD * SPD
    tr_FER   <- ktr_FER * FER

    d/dt(TNFa) <- a_tnf * (basal_tnfa + a_tnf_i * I + a_tnf_at2 * dAT2 +
      a_tnf_at1 * dAT1 + a_tnf_m1 * M1 + a_tnf_th1 * Th1 +
      a_tnf_th17 * Th17) - b_tnf * TNFa - tr_TNFa

    d/dt(IL6) <- a_il6 * (basalil6 + a_il6_at1 * dAT1 + a_il6_i * I +
      a_il6_at2 * dAT2 + a_il6_m1 * M1 + a_il6_th17 * Th17 +
      a_il6_neu * N) - b_il6 * IL6 - tr_IL6

    # NOTE: damaged AT1 cells use a_il1b_at2 in the released implementation.
    d/dt(IL1b) <- a_il1b * (basalil1 + a_il1b_at2 * dAT1 + a_il1b_i * I +
      a_il1b_at2 * dAT2 + a_il1b_m1 * M1 + a_il1b_dc * pDC) -
      b_il1b * IL1b - tr_IL1b

    d/dt(IFNg) <- a_ifng * (basalifng + a_ifng_dc * pDC + a_ifng_th1 * Th1 +
      a_ifng_ctl * CTL) - b_ifng * IFNg - tr_IFNg

    d/dt(IFNb) <- a_ifnb * (basalifnb + a_ifnb_i * I + a_ifnb_dc * pDC) -
      b_ifnb * IFNb - tr_IFNb

    d/dt(IL2) <- a_il2 * (basalil2 + a_il2_dc * pDC + a_il2_th1 * Th1) -
      b_il2 * IL2 - tr_IL2

    d/dt(IL12) <- a_il12 * (basalil12 + a_il12_m1 * M1 + a_il12_dc * pDC) -
      b_il12 * IL12 - tr_IL12

    d/dt(IL17) <- a_il17 * (a_il17_th17 * Th17 + a_il17_ctl * CTL) -
      b_il17 * IL17 - tr_IL17

    d/dt(IL10) <- a_il10 * (basalil10 + a_il10_treg * Treg) -
      b_il10 * IL10 - tr_IL10

    d/dt(TGFb) <- a_tgfb * (basaltgfb + a_tgfb_th17 * Th17 +
      a_tgfb_treg * Treg) - b_tgfb * TGFb - tr_TGFb

    d/dt(GMCSF) <- a_gmcsf * (basalgmcsf + a_gmcsf_m1 * M1 +
      a_gmcsf_th1 * Th1 + a_gmcsf_th17 * Th17) - b_gmcsf * GMCSF - tr_GMCSF

    # =====================================================================
    # 7. Alveolar biomarkers (Suppl. Eq. 26-27)
    # =====================================================================
    d/dt(SPD) <- kbasal_SPD +
      a_SPD * (dAT1 + dAT2 + k_CTL_I_SPD * kill_CTL_I) - tr_SPD
    d/dt(FER) <- kbasal_FER +
      a_FER * (dAT1 + dAT2 + k_CTL_I_Fer * kill_CTL_I) - tr_FER

    # =====================================================================
    # 8. Plasma compartment (Suppl. Eq. 28-30)
    # =====================================================================
    d/dt(TNFa_c)  <- tr_TNFa / vol_plasma - b_tnf * TNFa_c
    d/dt(IL6_c)   <- tr_IL6 / vol_plasma - b_il6 * IL6_c
    d/dt(IL1b_c)  <- tr_IL1b / vol_plasma - b_il1b * IL1b_c
    d/dt(IFNb_c)  <- tr_IFNb / vol_plasma - b_ifnb * IFNb_c
    d/dt(IFNg_c)  <- tr_IFNg / vol_plasma - b_ifng * IFNg_c
    d/dt(IL2_c)   <- tr_IL2 / vol_plasma - b_il2 * IL2_c
    d/dt(IL12_c)  <- tr_IL12 / vol_plasma - b_il12 * IL12_c
    d/dt(IL17_c)  <- tr_IL17 / vol_plasma - b_il17 * IL17_c
    d/dt(IL10_c)  <- tr_IL10 / vol_plasma - b_il10 * IL10_c
    d/dt(TGFb_c)  <- tr_TGFb / vol_plasma - b_tgfb * TGFb_c
    d/dt(GMCSF_c) <- tr_GMCSF / vol_plasma - b_gmcsf * GMCSF_c
    d/dt(SPD_c)   <- tr_SPD / vol_plasma - b_SPD * SPD_c
    d/dt(FER_c)   <- a_FER_c + tr_FER / vol_plasma - b_FER * FER_c

    d/dt(pDC_c)  <- tr_pDC * vol_alv_ml / vol_plasma - pDC_c * b_DC
    d/dt(M1_c)   <- tr_M1 * vol_alv_ml / vol_plasma - pb_M1 * M1_c * b_M1
    d/dt(N_c)    <- tr_N * vol_alv_ml / vol_plasma - N_c * b_N
    d/dt(Th1_c)  <- tr_Th1 * vol_alv_ml / vol_plasma - Th1_c * b_Th1
    d/dt(Th17_c) <- tr_Th17 * vol_alv_ml / vol_plasma - Th17_c * b_Th17
    d/dt(CTL_c)  <- tr_CTL * vol_alv_ml / vol_plasma - CTL_c * b_CTL
    d/dt(Treg_c) <- tr_Treg * vol_alv_ml / vol_plasma - Treg_c * b_Treg

    # =====================================================================
    # 9. C-reactive protein (Suppl. Eq. 25)
    # =====================================================================
    Liver_CRP      <- k_livercrp * Liver * (IL6_c * Liver)
    prod_CRP_liver <- kCRPSecretion * Liver_CRP
    tr_CRP         <- kCRP_BloodtoLiver * Blood_CRP -
      kCRP_LivertoBlood * Liver_CRP / Liver

    d/dt(CRPExtracellular) <- prod_CRP_liver + tr_CRP * Liver -
      kdeg_CRP * CRPExtracellular
    d/dt(Blood_CRP)        <- -tr_CRP + kbasal_CRP - kdeg_CRP * Blood_CRP

    # =====================================================================
    # 10. Antibody pharmacokinetics
    # =====================================================================
    # Exogenous nAb cocktail: two independent two-compartment models.
    # Ab / Ab12 hold nAb 1; Ab21 / Ab22 hold nAb 2 (amounts, mg).
    d/dt(Ab)   <- hVI * (-Ab * CL_Aba / V_Ab1a - Qa / V_Ab1a * Ab +
      Qa / V_Ab2a * Ab12)
    d/dt(Ab12) <- hVI * (Qa / V_Ab1a * Ab - Qa / V_Ab2a * Ab12)
    d/dt(Ab21) <- hVI * (-Ab21 * CL_Abb / V_Ab1b - Qb / V_Ab1b * Ab21 +
      Qb / V_Ab2b * Ab22)
    d/dt(Ab22) <- hVI * (Qb / V_Ab1b * Ab21 - Qb / V_Ab2b * Ab22)

    # Endogenous antibody: zero-order production switched on at tau_Ab_Igx.
    d/dt(Ab_Igx) <- hVI * (t >= tau_Ab_Igx) *
      (k_prod_igx - Ab_Igx * (log(2) / thalf_Igx) / V_Ab_Igx)

    # =====================================================================
    # 11. Reported outputs
    # =====================================================================
    # Primary clinical endpoint: nasopharyngeal viral load.
    viralLoad <- V                                    # viral RNA copies/mL

    # Plasma cytokines converted from pmol/mL to pg/mL (state * MW in g/mol).
    # Type I IFN additionally carries the authors' 16/20 assay conversion
    # (scripts/plausible_figure.m).
    IL6p   <- IL6_c * mw_il6
    TNFap  <- TNFa_c * mw_tnfa
    IL1bp  <- IL1b_c * mw_il1b
    IFNbp  <- IFNb_c * mw_ifnb * 16 / 20
    IFNgp  <- IFNg_c * mw_ifng
    IL2p   <- IL2_c * mw_il2
    IL12p  <- IL12_c * mw_il12
    IL17p  <- IL17_c * mw_il17
    IL10p  <- IL10_c * mw_il10
    TGFbp  <- TGFb_c * mw_tgfb
    GMCSFp <- GMCSF_c * mw_gmcsf

    # Neutralizing-antibody plasma concentrations (ug/mL).
    Cc_nab1 <- CONC1
    Cc_nab2 <- CONC2

    # =====================================================================
    # 12. Initial conditions (Rao 2023 code release src/Initialize.xlsx,
    #     sheet "IC"). These are the authors' healthy-subject starting
    #     values. They are NOT the model's steady state: the released
    #     driver (src/function_run_model_noplots.m) first integrates the
    #     uninfected system (hVI = 0) for 500 days from these values and
    #     uses the converged state as the healthy baseline before
    #     inoculating virus. Reproduce that burn-in before simulating an
    #     infection; see the vignette.
    # =====================================================================
    V(0)       <- 0          # viral RNA copies/mL; set to the 10 copies/mL inoculum to start an infection
    AT1(0)     <- 2.0e10     # cells
    AT2(0)     <- 3.0e10     # cells
    I(0)       <- 0          # cells
    dAT1(0)    <- 2.5026e2   # cells
    dAT2(0)    <- 3.7540e2   # cells
    pDC(0)     <- 1.4168e3   # cells
    M1(0)      <- 1.8694e3   # cells
    N(0)       <- 2.4556e3   # cells
    Th1(0)     <- 1.6837e3   # cells
    Th17(0)    <- 3.7168e-1  # cells
    CTL(0)     <- 2.0826e3   # cells
    Treg(0)    <- 4.5495e2   # cells
    TNFa(0)    <- 2.4335e-4  # pmol
    IL6(0)     <- 1.4131e-4  # pmol
    IL1b(0)    <- 2.8005e-2  # pmol
    IFNb(0)    <- 2.8677e-3  # pmol
    IFNg(0)    <- 1.8392e-3  # pmol
    IL2(0)     <- 3.5115e-1  # pmol
    IL12(0)    <- 1.2184e0   # pmol
    IL17(0)    <- 1.1300e-5  # pmol
    IL10(0)    <- 5.9298e-2  # pmol
    TGFb(0)    <- 7.7060e-2  # pmol
    GMCSF(0)   <- 2.0209e-1  # pmol
    SPD(0)     <- 4.4011e2   # pmol
    FER(0)     <- 2.1898e-1  # pmol
    TNFa_c(0)  <- 1.54e-9    # pmol/mL
    IL6_c(0)   <- 6.42e-8    # pmol/mL
    IL1b_c(0)  <- 1.27e-5    # pmol/mL
    IFNb_c(0)  <- 1.60e-8    # pmol/mL
    IFNg_c(0)  <- 1.02e-8    # pmol/mL
    IL2_c(0)   <- 7.34e-6    # pmol/mL
    IL12_c(0)  <- 8.93e-6    # pmol/mL
    IL17_c(0)  <- 0          # pmol/mL
    IL10_c(0)  <- 9.72e-7    # pmol/mL
    TGFb_c(0)  <- 8.11e-7    # pmol/mL
    GMCSF_c(0) <- 4.04e-6    # pmol/mL
    SPD_c(0)   <- 1.2699e-1  # pmol/mL
    FER_c(0)   <- 5.0011e-1  # pmol/mL
    pDC_c(0)   <- 7.0096e-1  # cells/uL
    M1_c(0)    <- 9.2091e-1  # cells/uL
    N_c(0)     <- 4.8093e-1  # cells/uL
    Th1_c(0)   <- 7.9640e-1  # cells/uL
    Th17_c(0)  <- 1.7499e-4  # cells/uL
    CTL_c(0)   <- 1.0268e0   # cells/uL
    Treg_c(0)  <- 2.1768e-1  # cells/uL
    CRPExtracellular(0) <- 1.4998e4 # pmol
    Blood_CRP(0)        <- 6.1428e0 # pmol/mL
  })
}
