# Semi-mechanistic pharmacokinetic-pharmacodynamic model of Leishmania blood
# parasite dynamics during and after treatment of visceral leishmaniasis in
# Eastern Africa (Verrest 2024, PLoS Negl Trop Dis 18(4):e0012078;
# doi:10.1371/journal.pntd.0012078). All parameter values come from Table 2.
#
# The published analysis is a sequential PK-then-PD fit: liposomal amphotericin
# B and sodium stibogluconate enter as kinetic-pharmacodynamic (K-PD) body-
# amount compartments built inside this model (Methods 2.4.2), while miltefosine
# and the active fexinidazole metabolites enter as individual predicted
# concentration-time trajectories generated by separate upstream population PK
# models and supplied to NONMEM as data columns. Those two upstream PK models
# are therefore represented here as time-varying covariates
# (CP_MILTEFOSINE_UGML, CP_FEXINIDAZOLE_M1M2_UGML), following the registered
# CP_<DRUG>_<UNITS> plasma-PD-driver convention. Verrest 2024 reports no PK
# parameter values of its own -- Table 2 contains only the parasite-dynamics
# parameters encoded below.
#
# UNIT CORRECTION (see the lambda block in ini() and the vignette's
# "Unit scale of the concentration-driven kill slopes" section). Table 2
# prints the units of lambda_fexi and lambda_MF as "ug^-1 * L * h^-1", which
# would put the driving concentration in ug/L. That reading is falsified by
# the paper's own Table 4: it makes kdrug about 5 /h under miltefosine and
# about 20 /h under fexinidazole, which would drive the parasite load onto
# the 1 parasite/mL floor within hours, whereas Table 4 reports 2027 and 105
# parasites/mL respectively at Day 10. The self-consistent reading is
# ug^-1 * mL * h^-1 (equivalently mg^-1 * L * h^-1), i.e. the driver is in
# ug/mL, which reproduces both arms' Day 1 -> Day 10 declines. The lambda
# VALUES are used exactly as printed; only the unit of the covariate they
# multiply is corrected, and the covariate names carry the corrected unit.

Verrest_2024_leishmania <- function() {
  description <- paste(
    "Semi-mechanistic pharmacokinetic-pharmacodynamic model of Leishmania",
    "blood parasite load during and after treatment of visceral leishmaniasis",
    "(VL) in 172 Eastern African patients pooled across three phase II trials",
    "(Verrest 2024). A single blood-parasite-load compartment (parasites/mL,",
    "quantified by kinetoplast-DNA qPCR) proliferates by exponential growth",
    "at rate kGR, corresponding to an in vivo parasite doubling time of 7.8",
    "days -- the first such estimate reported in humans. Parasite killing by",
    "each of four antileishmanial drugs is linear in that drug's",
    "concentration and additive across a combination regimen:",
    "kdrug = sum(lambda_drug * C_drug). Liposomal amphotericin B and sodium",
    "stibogluconate have no measured concentrations and are encoded as",
    "kinetic-pharmacodynamic body-amount compartments dosed in mg/kg and",
    "eliminated first-order with literature half-lives of 6 h and 2 h",
    "respectively; miltefosine and the active fexinidazole metabolites",
    "(sulfoxide M1 + sulfone M2) are supplied as time-varying concentration",
    "covariates because the source analysis fixed their PK from separate",
    "upstream population PK models. After treatment, parasite regrowth is",
    "suppressed by the emerging host immune response, described empirically",
    "as a sigmoid Imax function of time since start of treatment with",
    "steepness fixed to 5 and Imax fixed to ten times kGR. The parasite state",
    "is floored at 1 parasite/mL so that clinically meaningful recrudescence",
    "remains possible after complete drug-induced depletion. Baseline load,",
    "the miltefosine and fexinidazole slopes, Imax, and IT50 carry",
    "exponential between-subject variability; the variability on baseline",
    "load, Imax, and IT50 exceeds 200 CV%."
  )
  reference <- paste(
    "Verrest L, Monnerat S, Musa AM, Mbui J, Khalil EAG, Olobo J, Wasunna M,",
    "Chu WY, Huitema ADR, Schallig HDFH, Alves F, Dorlo TPC. Leishmania blood",
    "parasite dynamics during and after treatment of visceral leishmaniasis",
    "in Eastern Africa: A pharmacokinetic-pharmacodynamic model.",
    "PLoS Negl Trop Dis. 2024;18(4):e0012078.",
    "doi:10.1371/journal.pntd.0012078.",
    "ClinicalTrials.gov NCT01067443 (LEAP0208), NCT02431143 (LEAP0714),",
    "NCT01980199 (FEXI-VL-001).",
    sep = " "
  )
  vignette <- "Verrest_2024_leishmania"

  units <- list(
    time          = "h",
    dosing        = paste(
      "mg/kg (K-PD body amount per kilogram body weight; dose events land in",
      "depot_kpd_amphotericinb and depot_kpd_ssg. The lambda_Amb and",
      "lambda_SSG units of mg^-1*kg*h^-1 in Table 2 fix the K-PD state to",
      "mg/kg, so an amt of 10 means 10 mg/kg.)"
    ),
    concentration = paste(
      "parasites/mL (blood parasite load, the modelled output). The two",
      "covariate-supplied drug concentrations CP_MILTEFOSINE_UGML and",
      "CP_FEXINIDAZOLE_M1M2_UGML are in ug/mL (= mg/L); see the UNIT",
      "CORRECTION note at the top of this file."
    )
  )

  compartmentData <- list(
    parasites = list(
      analyte  = "Leishmania donovani kinetoplast DNA (blood parasite load)",
      units    = "parasites/mL",
      specimen = "whole blood",
      verified = TRUE
    ),
    depot_kpd_amphotericinb = list(
      analyte  = "liposomal amphotericin B (AmBisome) K-PD body amount",
      units    = "mg/kg",
      specimen = "not applicable",
      verified = TRUE
    ),
    depot_kpd_ssg = list(
      analyte  = "sodium stibogluconate (SSG) K-PD body amount",
      units    = "mg/kg",
      specimen = "not applicable",
      verified = TRUE
    )
  )

  covariateData <- list(
    CP_MILTEFOSINE_UGML = list(
      description        = paste(
        "Instantaneous individual predicted miltefosine plasma concentration,",
        "supplied per event record as a time-varying PD driver."
      ),
      units              = "ug/mL (= mg/L)",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "UNIT: Table 2 prints lambda_MF in ug^-1*L*h^-1, which would put this",
        "column in ug/L. That reading is falsified by the paper's own Table 4.",
        "Miltefosine accumulates to roughly 5 ug/mL averaged over Days 0-10 on",
        "the 2.5 mg/kg/day regimen, so the ug/L reading gives kdrug = 0.0010 *",
        "5180 = 5.2 /h, which floors the parasite load within hours; Table 4",
        "instead reports the MFC28D arm falling only from 4583 (Day 1) to 2027",
        "(Day 10) parasites/mL, an implied kdrug of 0.0075 /h. Reading the",
        "column in ug/mL gives 0.0010 * 5.18 = 0.0052 /h and reproduces that",
        "decline. This column is therefore in ug/mL and lambda_MF is used",
        "exactly as printed.",
        "Verrest 2024 Methods 2.4.2: 'Previously developed population",
        "pharmacokinetic models of miltefosine [29] ... were used to derive",
        "individual predicted pharmacokinetic concentrations, which were used",
        "as pharmacokinetic input to the model.' Reference [29] is Palic S et",
        "al., J Antimicrob Chemother 2020;75:3260-3268",
        "(doi:10.1093/jac/dkaa314), a non-linear miltefosine population PK",
        "model in Eastern African paediatric VL patients. That upstream model",
        "is a separate publication and is NOT encoded in this file; the user",
        "supplies the trajectory. Set to 0 for arms that do not receive",
        "miltefosine (AmB+SSG10D, Fexi10D). The registry model",
        "modellib('Dorlo_2017_miltefosine') is fit to the same LEAP0208 trial",
        "(NCT01067443) and can generate this trajectory (see the vignette",
        "Assumptions and deviations section)."
      ),
      source_name        = "individual predicted miltefosine concentration (Methods 2.4.2; Fig 2 'C drug')"
    ),
    CP_FEXINIDAZOLE_M1M2_UGML = list(
      description        = paste(
        "Instantaneous individual predicted whole-blood concentration of the",
        "SUM of the two active fexinidazole metabolites, fexinidazole",
        "sulfoxide (M1) and fexinidazole sulfone (M2), supplied per event",
        "record as a time-varying PD driver."
      ),
      units              = "ug/mL (= mg/L)",
      type               = "continuous",
      reference_category = NULL,
      notes              = paste(
        "UNIT: as for CP_MILTEFOSINE_UGML, Table 2's printed lambda_fexi unit",
        "of ug^-1*L*h^-1 is falsified by Table 4. Inverting the Fexi10D arm's",
        "Day 1 -> Day 10 decline (3732 -> 105 parasites/mL) gives an implied",
        "kdrug of 0.020 /h, hence a driving concentration of 0.020 / 0.0011 =",
        "18 in this column's units. Whole-blood M1 + M2 after 1800 mg/day sits",
        "in the tens of ug/mL, not the tens of ug/L, so the column is in",
        "ug/mL and lambda_fexi is used exactly as printed.",
        "Fig 2 legend: 'C drug the drug concentration of either miltefosine,",
        "the sum of M1 and M2 for fexinidazole, amphotericin B, or SSG'. The",
        "column carries M1 + M2, NOT parent fexinidazole. Verrest 2024",
        "Methods 2.4.2 sources the trajectory from a fexinidazole / M1 / M2",
        "population PK model held in an unpublished internal report; no",
        "parameter values for it appear anywhere in the paper or its S1 File,",
        "so no upstream PK model is encoded here and the user must supply the",
        "trajectory. Whole-blood concentrations were measured in dried blood",
        "spots (Methods 2.3, assay per Tarral 2014 Clin Pharmacokinet",
        "53:565-580). Set to 0 for arms that do not receive fexinidazole",
        "(all four non-Fexi10D regimens)."
      ),
      source_name        = "individual predicted M1 + M2 concentration (Methods 2.4.2; Fig 2 'C drug')"
    )
  )

  # Haematological and biochemical markers screened as drivers of the immune
  # suppression term (Methods 2.4.3) but NOT retained in the final model:
  # 'None of the haematological markers correlated with parasitological
  # response (Fig D in S1 File) and white blood cell counts were not a
  # significant covariate for k imm or IT50' (Results 3.2.2). They are
  # documented rather than encoded so the paper's covariate screen is
  # preserved without carrying unused-covariate warnings.
  covariatesDataExcluded <- list(
    WBC = list(
      description = "White blood cell count on Day 56, absolute or relative to baseline",
      units       = "10^9/L",
      type        = "continuous",
      notes       = paste(
        "The most extensively screened candidate. Verrest 2024 Methods 2.4.3",
        "tested WBC two ways: (Eq 2) as a linear-slope covariate on Imax and",
        "on IT50, PTV = Ppop * (1 + (WBC_i - WBC_med) * l); and (Eq 3) as the",
        "driver of the sigmoid Imax function in place of empirical time,",
        "kimm = Imax * WBC_i^gamma / (IC50^gamma + WBC_i^gamma). Neither was",
        "significant (Results 3.2.2), so the final model retains time after",
        "start of treatment as the sole driver and neither the slope l nor",
        "IC50 is reported."
      )
    ),
    HGB = list(
      description = "Haemoglobin",
      units       = "g/dL",
      type        = "continuous",
      notes       = "Screened graphically as a driver of parasite suppression (Methods 2.4.3, Fig D in S1 File); no relationship with parasitological response, not retained."
    ),
    CREAT = list(
      description = "Serum creatinine",
      units       = "umol/L",
      type        = "continuous",
      notes       = "Screened graphically as a driver of parasite suppression (Methods 2.4.3, Fig D in S1 File); not retained."
    ),
    NEUT = list(
      description = "Absolute neutrophil count (LEAP0714 and FEXI-VL-001 only)",
      units       = "10^9/L",
      type        = "continuous",
      notes       = "Screened graphically (Methods 2.4.3); available only in two of the three trials; not retained."
    ),
    ALB = list(
      description = "Serum albumin (FEXI-VL-001 only)",
      units       = "g/L",
      type        = "continuous",
      notes       = paste(
        "Screened graphically (Methods 2.4.3); available only in FEXI-VL-001.",
        "The Discussion notes albumin and lymphocytes were higher and total",
        "protein lower in cured patients, 'although these results should be",
        "interpreted with caution as they were only available for a small",
        "proportion of patients'. Not retained in the final model. Platelets,",
        "lymphocytes, monocytes, and total protein were screened alongside",
        "these and likewise not retained; they have no canonical register",
        "entry and are recorded here in prose only."
      )
    )
  )

  population <- list(
    species        = "human",
    n_subjects     = 172L,
    n_studies      = 3L,
    age_range      = "4-50 years",
    age_mean       = "14 years",
    weight_range   = "13-69 kg",
    weight_mean    = "34 kg",
    sex_female_pct = 33.7,
    race_ethnicity = "Eastern African (Kenya, Sudan, Uganda); no further breakdown reported",
    disease_state  = paste(
      "Parasitologically confirmed primary visceral leishmaniasis (fever plus",
      "splenomegaly plus confirmatory microscopy). All patients HIV negative;",
      "none had severe VL, severe malnutrition, or serious underlying disease",
      "or concomitant severe infection at diagnosis. 138 of 172 (80%) achieved",
      "final cure; 34 of 172 (20%) relapsed during 210 days of follow-up."
    ),
    dose_range     = paste(
      "Five regimens across three trials.",
      "AmB+SSG10D (n=40): liposomal amphotericin B 10 mg/kg IV on day 1 then",
      "sodium stibogluconate 20 mg/kg/day IM on days 2-11.",
      "AmB+MF10D (n=44): liposomal amphotericin B 10 mg/kg IV on day 1 then",
      "oral miltefosine 2.5 mg/kg/day (maximum 150 mg/day) on days 2-11.",
      "MFC28D (n=46): oral miltefosine conventional dosing 2.5 mg/kg/day",
      "(maximum 150 mg/day) for 28 days.",
      "MFA28D (n=29): oral miltefosine allometric dosing 30-100 mg/day for 28",
      "days (paediatric).",
      "Fexi10D (n=13): oral fexinidazole 1800 mg/day for 4 days then 1200",
      "mg/day for 6 days."
    ),
    regions        = "Eastern Africa (Kenya: Kimalel, Kacheliba; Sudan: Dooka, Kassab; Uganda: Amudat)",
    trials         = paste(
      "LEAP0208 (NCT01067443; AmB+SSG10D, AmB+MF10D, MFC28D arms),",
      "LEAP0714 (NCT02431143; MFA28D paediatric arm),",
      "FEXI-VL-001 (NCT01980199; Fexi10D arm). All three are phase II",
      "open-label randomized trials."
    ),
    samples        = paste(
      "1260 whole-blood EDTA samples collected for kinetoplast-DNA qPCR from",
      "188 patients; 992 observations from 172 patients retained after",
      "exclusions (21% excluded: 2 initial treatment failures, samples after",
      "rescue treatment, unreliable DNA extractions, physiologically",
      "implausible values, and one patient lacking PK data). 359 of the 992",
      "retained observations (36%) were below the 1 parasite/mL limit of",
      "quantification and were fixed to half the LLOQ (0.5 parasite/mL).",
      "Sampling days: 0, 3, 7, 14, 28, 56, 210 (LEAP0208); 0, 3, 7, 14, 21,",
      "28, 56 (LEAP0714); 0, 1, 3, 5, 8, 11, 14, 28, 56, 210 (FEXI-VL-001)."
    ),
    notes          = paste(
      "Demographics from Verrest 2024 Table 1 (mean and range at baseline,",
      "pooled across the five treatment arms). Sex is reported as 114 of 172",
      "(66%) male, hence 33.7% female. NONMEM 7.5, FOCE-I; parameter",
      "precision by sampling importance resampling (SIR). The model was built",
      "in three sequential steps on data subsets -- parasite growth from the",
      "Fexi10D arm (where inadequate drug response produced rapid",
      "recrudescence), then drug-induced clearance, then host-induced",
      "suppression -- because simultaneous estimation of all parameters",
      "over-parameterised the model (Discussion)."
    )
  )

  ini({
    # ==================================================================
    # Baseline and parasite proliferation -- Verrest 2024 Table 2.
    # No pharmacodynamic data were available before start of treatment,
    # so kGR was estimated from the Fexi10D arm, where an inadequate
    # drug response produced rapid parasite recrudescence directly after
    # treatment (Methods 2.4.1, Results 3.2.1).
    # ==================================================================
    lrbase <- log(5324)
    label("Baseline blood parasite load E_BASE (parasites/mL)")           # Table 2 row 'E BASE (parasites/mL)': 5324 (RSE 16%)
    lkgrow <- log(0.0037)
    label("Parasite exponential growth rate constant kGR (1/h)")          # Table 2 row 'k GR (h -1)': 0.0037 (RSE 12%); Results 3.2.1 doubling time log(2)/0.0037 = 187 h = 7.8 days

    # ==================================================================
    # Drug-induced parasite clearance -- Verrest 2024 Table 2. Killing is
    # first-order linear in the driving drug concentration or K-PD body
    # amount (Results 3.2.1: 'the parasite killing rate was directly
    # proportional to the drug concentration').
    #
    # The two K-PD slopes take their driver units straight from Table 2:
    # mg^-1*kg*h^-1 times a body amount in mg/kg gives h^-1, and that
    # reading reproduces the AmB+SSG10D arm's published Day 10 load
    # (Table 4 reports 11.8 parasites/mL; the encoded model gives about
    # 11 from the Table 4 Day 1 baseline).
    #
    # The two concentration slopes DO NOT: Table 2 prints them as
    # ug^-1*L*h^-1, which puts the driver in ug/L and makes kdrug about
    # 5 /h for miltefosine and 20 /h for fexinidazole -- three orders of
    # magnitude above the rates Table 4's own Day 1 -> Day 10 declines
    # imply (0.0075 /h and 0.020 /h). The self-consistent reading is
    # ug^-1*mL*h^-1 == mg^-1*L*h^-1, i.e. the driver is in ug/mL. Both
    # values below are the printed Table 2 numbers, unaltered; only the
    # unit of the covariate they multiply is corrected, and the
    # covariate names (CP_*_UGML) carry that correction. See the file
    # header and the vignette section "Unit scale of the
    # concentration-driven kill slopes".
    # ==================================================================
    lslope_fexinidazole <- log(0.0011)
    label("Linear parasite-kill slope for fexinidazole M1 + M2, lambda_fexi (mL/(ug*h))")   # Table 2 row 'lambda fexi (ug -1 * L * h -1)': 0.0011 (RSE 15%); driver unit corrected to ug/mL, see comment above
    lslope_miltefosine <- log(0.0010)
    label("Linear parasite-kill slope for miltefosine, lambda_MF (mL/(ug*h))")              # Table 2 row 'lambda MF (ug -1 * L * h -1)': 0.0010 (RSE 5%); driver unit corrected to ug/mL, see comment above
    lslope_amphotericinb <- log(0.0245)
    label("Linear parasite-kill slope for liposomal amphotericin B, lambda_Amb (kg/(mg*h))") # Table 2 row 'lambda Amb (mg -1 * kg * h -1)': 0.0245 (RSE 8%)
    lslope_ssg <- log(0.0112)
    label("Linear parasite-kill slope for sodium stibogluconate, lambda_SSG (kg/(mg*h))")    # Table 2 row 'lambda SSG (mg -1 * kg * h -1)': 0.0112 (RSE 5%)

    # ==================================================================
    # K-PD elimination rate constants. Methods 2.4.2: 'For liposomal
    # amphotericin B and SSG, a kinetic-pharmacodynamic approach was
    # used assuming a one compartment model with first-order
    # elimination, using the administered drug amounts and previously
    # reported elimination half-lives of 6 hours for liposomal
    # amphotericin B [32] and 2 hours for SSG [33,34].' Both half-lives
    # are literature constants, not estimated here, hence fixed().
    # [32] Bekersky 2002 Antimicrob Agents Chemother 46:834-840.
    # ==================================================================
    lkel_amphotericinb <- fixed(log(log(2) / 6))
    label("K-PD elimination rate constant for liposomal amphotericin B (1/h)")  # Methods 2.4.2: elimination half-life 6 h -> kel = log(2)/6 = 0.1155 /h
    lkel_ssg <- fixed(log(log(2) / 2))
    label("K-PD elimination rate constant for sodium stibogluconate (1/h)")     # Methods 2.4.2: elimination half-life 2 h -> kel = log(2)/2 = 0.3466 /h

    # ==================================================================
    # Host-induced parasite suppression after treatment -- Eq 1 and
    # Table 2. kimm = Imax * Time^gamma / (IT50^gamma + Time^gamma),
    # where Time is the time after start of treatment.
    #
    # Imax was NOT estimated: Table 2 footnote b reads 'Fixed to ten
    # times kGR', i.e. 10 * 0.0037 = 0.037 /h, hence fixed(). Its
    # between-subject variability WAS estimated (298 CV%).
    #
    # gamma was 'empirically fixed to 5' (Fig 2 legend and Results
    # 3.2.2), representing a fast onset of suppression.
    #
    # IT50 is reported in Table 2 as 33.7 days; this model runs on an
    # hour timescale (kGR, the lambdas, and Imax are all per hour), so
    # it is converted: 33.7 * 24 = 808.8 h. Fig 5B independently
    # confirms the hour timescale by simulating typical patients with
    # IT50 of 1000 h, 5000 h, and 100,000 h.
    # ==================================================================
    limax <- fixed(log(0.037))
    label("Maximum immune-driven parasite elimination rate Imax (1/h)")   # Table 2 row 'I max (h -1)': 0.037 (fixed), footnote b 'Fixed to ten times kGR'
    lt50 <- log(33.7 * 24)
    label("Time after start of treatment at half-maximal immune effect IT50 (h)")  # Table 2 row 'IT 50 (days)': 33.7 (RSE 0.1%), converted from days to hours
    lhill <- fixed(log(5))
    label("Steepness of the time-effect relationship gamma (unitless)")   # Fig 2 legend: 'gamma, the steepness of the time-effect relationship, which was empirically fixed to 5'; Results 3.2.2

    # ==================================================================
    # Between-subject variability -- Verrest 2024 Table 2 'BSV (CV%)'
    # column. Methods 2.4: 'Between-subject variability (BSV) was
    # evaluated for all parameters and implemented using an exponential
    # error model', so omega^2 = log(1 + CV^2). BSV was not identified
    # for kGR, lambda_Amb, or lambda_SSG (Table 2 shows '-') and is not
    # encoded for them.
    #
    # Results 3.2.2 flags the baseline / Imax / IT50 variability as
    # 'very large and non-normally distributed BSV (>200 CV%)'; the
    # log-normal encoding below is the paper's stated exponential model
    # and reproduces the reported CV%, but users should expect heavy
    # right tails when simulating these three.
    # ==================================================================
    etalrbase ~ log(1 + 2.43^2)
    # Table 2 'E BASE' BSV 243 CV% (RSE 12%, shrinkage 3%) -> omega^2 = log(1 + 2.43^2) = 1.932
    etalslope_fexinidazole ~ log(1 + 0.44^2)
    # Table 2 'lambda fexi' BSV 44 CV% (RSE 59%, shrinkage 3%) -> omega^2 = log(1 + 0.44^2) = 0.1771
    etalslope_miltefosine ~ log(1 + 0.42^2)
    # Table 2 'lambda MF' BSV 42 CV% (RSE 21%, shrinkage 5%) -> omega^2 = log(1 + 0.42^2) = 0.1626
    etalimax ~ log(1 + 2.98^2)
    # Table 2 'I max' BSV 298 CV% (RSE 16%, shrinkage 52%) -> omega^2 = log(1 + 2.98^2) = 2.290
    etalt50 ~ log(1 + 2.30^2)
    # Table 2 'IT 50' BSV 230 CV% (RSE 12%, shrinkage 40%) -> omega^2 = log(1 + 2.30^2) = 1.839

    # ==================================================================
    # Residual variability -- Verrest 2024 Table 2 and Methods 2.4:
    # 'Residual variability was modeled using combined additive and
    # proportional error models, with the additive error fixed to BLQ/2
    # (0.5 parasite/mL).' Table 2 footnote c: 'Fixed to half the lower
    # limit of quantification' (LLOQ = 1 parasite/mL, Methods 2.3).
    # ==================================================================
    propSd <- 1.01
    label("Proportional residual error on blood parasite load (fraction)")   # Table 2 row 'Proportional residual error (%)': 101 (RSE 0.7%, shrinkage 18%)
    addSd <- fixed(0.5)
    label("Additive residual error on blood parasite load (parasites/mL)")   # Table 2 row 'Additive residual error (parasites/mL)': 0.5 (fixed), footnote c
  })

  model({
    # ------------------------------------------------------------------
    # 1. Individual parameters. Exponential (log-normal) BSV on baseline
    #    load, the two concentration-driven kill slopes, Imax, and IT50;
    #    kGR and the two K-PD slopes are typical-value only (Table 2).
    # ------------------------------------------------------------------
    rbase <- exp(lrbase + etalrbase)
    kgrow <- exp(lkgrow)

    slope_fexinidazole  <- exp(lslope_fexinidazole + etalslope_fexinidazole)
    slope_miltefosine   <- exp(lslope_miltefosine + etalslope_miltefosine)
    slope_amphotericinb <- exp(lslope_amphotericinb)
    slope_ssg           <- exp(lslope_ssg)

    kel_amphotericinb <- exp(lkel_amphotericinb)
    kel_ssg           <- exp(lkel_ssg)

    imax <- exp(limax + etalimax)
    t50  <- exp(lt50 + etalt50)
    hill <- exp(lhill)

    # ------------------------------------------------------------------
    # 2. Kinetic-pharmacodynamic sub-models for the two drugs without
    #    measured concentrations (Methods 2.4.2). Each is a one-
    #    compartment body-amount pool with first-order elimination at
    #    the literature half-life; dose events supply the administered
    #    amount in mg/kg. There is no volume term -- Table 2 reports
    #    lambda_Amb and lambda_SSG in mg^-1*kg*h^-1, so the state itself
    #    carries mg/kg and lambda * state has units of 1/h.
    # ------------------------------------------------------------------
    d/dt(depot_kpd_amphotericinb) <- -kel_amphotericinb * depot_kpd_amphotericinb
    d/dt(depot_kpd_ssg)           <- -kel_ssg * depot_kpd_ssg

    # ------------------------------------------------------------------
    # 3. Total drug-induced parasite elimination rate (Fig 2, k drug).
    #    Fig 2 defines a single k drug driven by "the drug concentration
    #    of either miltefosine, the sum of M1 and M2 for fexinidazole,
    #    amphotericin B, or SSG". Three of the five studied regimens are
    #    two-drug combinations (AmB+SSG10D, AmB+MF10D), so the four
    #    drug-specific linear terms are summed; for a monotherapy arm the
    #    other drivers are zero and the sum collapses to a single term.
    #    Miltefosine and fexinidazole M1 + M2 concentrations arrive as
    #    time-varying covariates (see covariateData) because the source
    #    analysis fixed their PK from separate upstream population PK
    #    models rather than estimating it here.
    # ------------------------------------------------------------------
    kdrug <-
      slope_fexinidazole  * CP_FEXINIDAZOLE_M1M2_UGML +
      slope_miltefosine   * CP_MILTEFOSINE_UGML +
      slope_amphotericinb * depot_kpd_amphotericinb +
      slope_ssg           * depot_kpd_ssg

    # ------------------------------------------------------------------
    # 4. Host immune suppression of parasite regrowth (Eq 1):
    #       kimm = Imax * Time^gamma / (IT50^gamma + Time^gamma)
    #    "Time is the time after start of treatment" (Eq 1 definition),
    #    so the model clock `t` is used directly with t = 0 at the first
    #    dose. With gamma = 5 and IT50 = 808.8 h the term is negligible
    #    during the 10-28 day treatment period and rises steeply
    #    afterwards.
    # ------------------------------------------------------------------
    kimm <- imax * t^hill / (t50^hill + t^hill)

    # ------------------------------------------------------------------
    # 5. Blood parasite load. Net first-order rate is growth minus drug
    #    kill minus immune suppression (Fig 2 schematic).
    #
    #    Methods 2.4.3: "To allow for clinically meaningful parasite
    #    recrudescence after complete drug-induced parasite depletion,
    #    the parasite compartment was restricted to >= 1 parasite/mL."
    #
    #    The floor is enforced by splitting the net rate into its
    #    non-negative and non-positive parts (kgain = max(knet, 0),
    #    kloss = min(knet, 0), written with the abs() identities so the
    #    expression stays differentiable in the state):
    #
    #      * while the net rate is positive the state grows as
    #        kgain * parasites, exactly the paper's equation, so a
    #        patient whose immune response fades recrudesces normally
    #        from wherever the state sits -- including from the floor;
    #      * while the net rate is negative the loss acts on the
    #        killable excess above the floor, kloss * (parasites -
    #        pfloor), which decays the state asymptotically onto
    #        exactly 1 parasite/mL and never below it.
    #
    #    Above the floor the two branches reproduce knet * parasites to
    #    within the pfloor / parasites ratio, which is below 1e-3 for
    #    every state value the model reaches during treatment. The
    #    literal indicator form (multiplying the rate by a 0/1 step on
    #    `parasites <= pfloor`) is mathematically equivalent but
    #    introduces a state-dependent discontinuity that lsoda cannot
    #    step across without hand-tuned tolerances; this form solves
    #    with the rxode2 defaults, dop853, and tightened tolerances
    #    alike, all three landing on the same trajectory.
    # ------------------------------------------------------------------
    pfloor <- 1
    knet   <- kgrow - kdrug - kimm
    kgain  <- 0.5 * (knet + abs(knet))
    kloss  <- 0.5 * (knet - abs(knet))

    d/dt(parasites) <- kgain * parasites + kloss * (parasites - pfloor)
    parasites(0) <- rbase

    # ------------------------------------------------------------------
    # 6. Observation. The qPCR-quantified blood parasite load is the
    #    `parasites` state itself, with the combined proportional +
    #    additive residual error of Table 2.
    # ------------------------------------------------------------------
    parasites ~ add(addSd) + prop(propSd)
  })
}
