Larizza_2018_insulinMinimalModel <- function() {
  description <- paste(
    "Insulin (C-peptide) minimal model of beta-cell secretion after an intravenous glucose",
    "tolerance test (Toffolo 1995 / Magni 2004), re-estimated by Larizza 2018 in a single",
    "normal 25-year-old man. Two coupled subsystems: a linear two-compartment C-peptide",
    "disposition model whose micro rate constants k01, k12 and k21 are fixed from the",
    "companion population regression Larizza_2018_cpeptideKinetics_M0, and a two-state",
    "secretion model in which a first-phase beta-cell C-peptide store is released at rate m",
    "and a second-phase provisionary factor is driven with time constant 1/alpha towards a",
    "steady state proportional (via beta) to plasma glucose above a threshold. Plasma glucose",
    "enters as an error-free time-varying forcing function. Outputs the insulin secretion rate",
    "and the two beta-cell sensitivity indexes phi1 and phi2.",
    sep = " "
  )
  reference <- paste(
    "Larizza C, Borella E, Pasotti L, Tartaglione P, Smith M, Moodie S, Magni P. (2018).",
    "Complex Bayesian Modeling Workflows Encoding and Execution Made Easy With a Novel",
    "WinBUGS Plugin of the Drug Disease Model Resources Interoperability Framework.",
    "CPT Pharmacometrics Syst Pharmacol 7(5):298-308. doi:10.1002/psp4.12285.",
    "Underlying model: Magni P, Sparacino G, Bellazzi R, Toffolo GM, Cobelli C.",
    "Insulin minimal model indexes and secretion: proper handling of uncertainty by a",
    "Bayesian approach. Ann Biomed Eng 2004;32:1027-1037; Toffolo G, De Grandi F, Cobelli C.",
    "Diabetes 1995;44:845-854.",
    sep = " "
  )
  vignette <- "Larizza_2018_cpeptide_insulin_secretion"

  paper_specific_compartments <- c("betacell", "provision")

  units <- list(
    time = "min",
    dosing = "n/a (no exogenous C-peptide input; secretion is generated by the model)",
    concentration = "pmol/L (C-peptide)"
  )

  compartmentData <- list(
    central = list(
      analyte = "C-peptide",
      units = "pmol/L",
      specimen = "plasma",
      verified = TRUE
    ),
    peripheral1 = list(
      analyte = "C-peptide",
      units = "pmol/L",
      specimen = "plasma",
      verified = TRUE
    ),
    betacell = list(
      analyte = "C-peptide",
      units = "pmol/L",
      specimen = "plasma",
      verified = TRUE
    ),
    provision = list(
      analyte = "C-peptide",
      units = "pmol/L/min",
      specimen = "plasma",
      verified = TRUE
    )
  )

  covariateData <- list(
    GLU = list(
      description = "Plasma glucose concentration time course (forcing function)",
      units = "mg/dL",
      type = "continuous",
      reference_category = NULL,
      notes = paste(
        "Time-varying error-free regressor supplied at every row; declared as linear(GLU) so",
        "rxode2 interpolates linearly between rows, matching the source's own preprocessing",
        "(Supporting Information 2, MLE approach.R: approx(TIME, GLUC, ..., method = 'linear')).",
        "UNITS: the main text labels the glucose threshold h and G(t) as pmol/L, which is a",
        "label slip -- glucose is not reported in pmol/L anywhere and the estimated h of 89",
        "would be nonsensical there. The deposited analysis scripts settle it: the sensitivity",
        "index is computed as phi1 = (x0 * 10^3 / (391 - 87)) * 18.01, where 391 and 87 are the",
        "subject's peak and basal glucose in mg/dL and 18.01 g/mol converts to mmol/L. Basal",
        "glucose is therefore 87 mg/dL, consistent with the informative prior on h ('mean equal",
        "to the basal glucose level, CV 3%') and the estimated h of 89.0-89.9 mg/dL. Supply GLU",
        "in mg/dL.",
        sep = " "
      ),
      source_name = "GLUC"
    )
  )

  population <- list(
    species = "human",
    n_subjects = 1,
    n_studies = 1,
    age_range = "25 years",
    weight_range = "70.7 kg",
    sex_female_pct = 0,
    disease_state = "normal health status (non-diabetic, non-obese)",
    dose_range = "intravenous glucose tolerance test (IVGTT) glucose bolus; dose not reported",
    regions = "not reported",
    notes = paste(
      "A single subject, not included in the 207-subject C-peptide kinetics dataset:",
      "normal health status, male, 25 years old, 1.818 m, 70.7 kg (Larizza 2018 Datasets",
      "section, citing Magni 2000 and Shapiro 1988). Basal plasma glucose 87 mg/dL and peak",
      "391 mg/dL, from the deposited analysis scripts. The glucose bolus amount is not",
      "reported; users must supply the measured or assumed glucose profile through GLU.",
      sep = " "
    )
  )

  ini({
    # ================= C-peptide disposition micro rate constants =================
    # Fixed, not estimated: Larizza 2018 approaches 1 and 3 hold k01, k12 and k21 at the
    # values obtained by simulating Larizza_2018_cpeptideKinetics_M0 for this subject
    # (normal, male, 25 y, BSA 1.908 m^2). Larizza 2018 Table 1 'CP-kinetic parameters' block
    # rounds them to 0.061 / 0.049 / 0.050 min^-1; the four-significant-digit values below are
    # the same numbers as carried in Supporting Information 2 (full-bayesian approach.R, the
    # NONMEM reference values plotted against the BUGS posteriors) and are reproduced exactly
    # by the M0 forward conversion -- see the vignette.
    # Natural scale rather than log scale: these are mechanistic constants the source reports
    # as point values and fixes, not estimated positive-constrained parameters.
    # Held on the log scale per the canonical micro-constant convention; each is back-
    # transformed in model(). The log() sits inside fixed() so the marked-as-fixed quantity is
    # the linear-scale rate constant the paper reports.
    lk01 <- fixed(log(0.0607)) ; label("C-peptide irreversible loss rate constant from the central compartment (1/min)") # Table 1 M0 'k01' = 0.061; Supporting Information 2 value 0.0607
    lk12 <- fixed(log(0.0491)) ; label("C-peptide transfer rate constant from peripheral to central (1/min)") # Table 1 M0 'k12' = 0.049; Supporting Information 2 value 0.0491
    lk21 <- fixed(log(0.0503)) ; label("C-peptide transfer rate constant from central to peripheral (1/min)") # Table 1 M0 'k21' = 0.050; Supporting Information 2 value 0.0503

    # ================= Secretion subsystem =================
    # Larizza 2018 Table 2, MLE approach column. The MLE column is used for ini() because it is
    # the parameter set that is self-consistent with the fixed k01 / k12 / k21 above and with
    # Larizza_2018_cpeptideKinetics_M0, and because the paper reports it as identical to the
    # original publication. The other two approaches are one edit away:
    #
    #   parameter | MLE (here) | full-Bayesian | mixed
    #   m         |  0.817     |  0.820        | 0.907
    #   alpha     |  0.061     |  0.051        | 0.074
    #   beta      |  9.790     | 10.498        | 8.909
    #   x0        |  1.384     |  1.472        | 1.406
    #   h         | 89.002     | 89.097        | 89.859
    #
    # The full-Bayesian column additionally replaces the fixed k01 / k12 / k21 above with the
    # M4 posterior medians 0.062 / 0.049 / 0.049 min^-1 (Table 1, M4 column); the mixed column
    # keeps the fixed values above. No %RSE is reported for the MLE column because the NONMEM
    # covariance step did not complete (Table 2 footnote a).
    #
    # Paper symbols m and h are spelled msecr and gthresh here: single-character model
    # variables are collision-prone in rxode2 / R, and the longer names carry the role.
    msecr <- 0.817 ; label("Beta-cell C-peptide release rate constant, paper symbol m (1/min)") # Table 2 MLE: m = 0.817 min^-1
    alpha <- 0.061 ; label("Rate constant of the second-phase provisionary factor (1/min)") # Table 2 MLE: alpha = 0.061 min^-1
    beta <- 9.790 ; label("Second-phase beta-cell responsivity to glucose above threshold (pmol/L/min per mg/dL)") # Table 2 MLE: beta = 9.790
    x0 <- 1.384 ; label("First-phase beta-cell C-peptide store released at t = 0 (pmol/L)") # Table 2 MLE: x0 = 1.384 pmol/l
    gthresh <- 89.002 ; label("Plasma glucose threshold above which second-phase provision is stimulated, paper symbol h (mg/dL)") # Table 2 MLE: h = 89.002

    # ================= Residual error =================
    # Larizza 2018 Mathematical Models: 'The residual error model was supposed normally
    # distributed with mean 0 and constant coefficient of variation (CV) fixed to 6%.' A
    # constant CV on a normally distributed residual is a proportional error of magnitude 0.06.
    propSd <- fixed(0.06) ; label("Proportional residual SD on plasma C-peptide (fraction)") # Mathematical Models: CV fixed to 6%
  })

  model({
    # Plasma glucose is an exogenous, error-free forcing function; the minimal model does not
    # describe glucose kinetics. Supplied in mg/dL at every row and linearly interpolated
    # between rows, matching the source's own preprocessing.
    linear(GLU)

    k01 <- exp(lk01)
    k12 <- exp(lk12)
    k21 <- exp(lk21)

    # Insulin (and therefore C-peptide) secretion rate, Larizza 2018 Mathematical Models:
    # ISR(t) = m * X(t). Defined here because it is the input of the disposition subsystem
    # below; the state it reads, `betacell`, is declared in subsystem 2.
    ISR <- msecr * betacell

    # ---------------- Subsystem 1: C-peptide disposition ----------------
    # Larizza 2018 Mathematical Models, 'Glucose-insulin minimal model', first subsystem:
    #
    #   dCP1/dt = -(k01 + k21) * CP1 + k12 * CP2 + ISR(t)
    #   dCP2/dt = -k12 * CP2 + k21 * CP1
    #   CP1(0) = CP2(0) = 0
    #
    # Both states hold CONCENTRATIONS (pmol/L), not amounts, and both are expressed as
    # DEVIATIONS FROM THE BASAL C-peptide level: the source states that ISR(t) is 'the insulin
    # (and therefore CP) secretion rate expressed as deviation from the basal and normalized by
    # the volume of compartment 1 (V)'. Observations fed to this model must therefore be
    # baseline-subtracted plasma C-peptide, and the zero initial conditions are the basal
    # steady state. Because ISR is already volume-normalised, the central volume V predicted by
    # the companion regression models does not appear here.
    d/dt(central) <- -(k01 + k21) * central + k12 * peripheral1 + ISR
    d/dt(peripheral1) <- k21 * central - k12 * peripheral1
    central(0) <- 0
    peripheral1(0) <- 0

    # ---------------- Subsystem 2: beta-cell secretion ----------------
    # Larizza 2018 Mathematical Models, second subsystem:
    #
    #   ISR(t) = m * X(t)
    #   dX/dt  = -ISR(t) + Y(t)
    #   dY/dt  = -alpha * (Y(t) - beta * (G(t) - h))   if G(t) >  h
    #          = -alpha *  Y(t)                        otherwise
    #   X(0) = x0,  Y(0) = 0
    #
    # State `betacell` is X(t), the C-peptide concentration in beta cells (pmol/L); its initial
    # value x0 is the first-phase burst released in response to the glucose bolus. State
    # `provision` is Y(t), the second-phase provisionary factor (pmol/L/min), which relaxes
    # with time constant 1/alpha towards beta * (G - h) while glucose is above threshold and
    # towards zero once it falls back below. The IF-THEN-ELSE on the glucose threshold is
    # encoded as the multiplicative indicator (GLU > gthresh), which is 1 above threshold and
    # 0 at or below it -- identical to the paper's branch and differentiable-free for the
    # solver in the same way.
    d/dt(betacell) <- -ISR + provision
    d/dt(provision) <- -alpha * (provision - beta * (GLU - gthresh) * (GLU > gthresh))
    betacell(0) <- x0
    provision(0) <- 0

    # ---------------- Beta-cell sensitivity indexes ----------------
    # Larizza 2018 Mathematical Models: phi1 = x0 / deltaG and phi2 = beta, where deltaG is the
    # maximum measured increment of plasma glucose after the IVGTT. The deposited analysis
    # scripts give the exact computational form actually used, including the unit conversion:
    #
    #   phi1 = (x0 * 10^3 / deltaG_mgdL) * 18.01        [10^-9]
    #   phi2 = beta
    #
    # i.e. phi1 is x0 in pmol/L divided by deltaG expressed in mmol/L, the Toffolo / Cobelli
    # convention. deltaG is a property of the observed glucose profile rather than of the
    # model, so phi1 is reported per-subject in the vignette rather than as a model output;
    # phi2 needs no data and is emitted here.
    phi2 <- beta

    # ---------------- Observation ----------------
    # Baseline-subtracted plasma C-peptide concentration in pmol/L.
    Cc <- central
    Cc ~ prop(propSd)
  })
}
